ballerina-platform/ballerina-dev-website

- learn/how-to-test-ballerina-code.md
Below code snippets need to be updated in the Service Skeleton Start/Stop Utility example code in Ballerina Test documentation. https://ballerina.io/learn/how-to-test-ballerina-code/`
In line 1 import ballerina/config; should removed
In line 31 httpEndpoint should changed as clientEndpoint
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/151
> Update Code Snippets of the Service Skeleton Start/Stop Utility Example

- learn/how-to-generate-code-for-protocol-buffers.md
Update ballerina command in how-to-generate-code-for-protocol-buffers.md
> Fix ballerina command for generating Ballerina code from Protocol Buffer Definition

- learn/tools-ides/vscode-plugin.md
- learn/tools-ides/vscode-plugin/documentation-viewer.md
- learn/tools-ides/vscode-plugin/graphical-editor.md
- learn/tools-ides/vscode-plugin/language-intelligence.md
- learn/tools-ides/vscode-plugin/run-all-tests.md
- learn/tools-ides/vscode-plugin/run-and-debug.md
- v1-0/learn/tools-ides/vscode-plugin.md
- v1-0/learn/tools-ides/vscode-plugin/documentation-viewer.md
- v1-0/learn/tools-ides/vscode-plugin/graphical-editor.md
- v1-0/learn/tools-ides/vscode-plugin/language-intelligence.md
- v1-0/learn/tools-ides/vscode-plugin/run-all-tests.md
- v1-0/learn/tools-ides/vscode-plugin/run-and-debug.md
- v1-1/learn/tools-ides/vscode-plugin.md
- v1-1/learn/tools-ides/vscode-plugin/documentation-viewer.md
- v1-1/learn/tools-ides/vscode-plugin/graphical-editor.md
- v1-1/learn/tools-ides/vscode-plugin/language-intelligence.md
- v1-1/learn/tools-ides/vscode-plugin/run-all-tests.md
- v1-1/learn/tools-ides/vscode-plugin/run-and-debug.md
We need to change the word "plugin" to "extension" in all occurrences of VSCode docs in the below website versions.
no-version
v1-1
v1-0
v0-991
> Fixes #186
> Change "Plugin" to "Extension" in VSCode Docs

- learn.md
- v0-991/learn.md
- v1-0/learn.md
- v1-1/learn.md
This is to fix the broken links after the change that was done in https://github.com/ballerina-platform/ballerina-dev-website/pull/182/.
> Fixes #
> Fix the Broken Links After Removing Tools & IDEs Page

- learn/how-to-keep-ballerina-up-to-date.md
- v1-1/learn/how-to-keep-ballerina-up-to-date.md
This is to fix the ToC [1] in both `/learn/` and` /v1-1/learn` domains of the B.io.
[1] https://ballerina.io/v1-1/learn/how-to-keep-ballerina-up-to-date/#Pull-a-specific-distribution
> Fixes #
> Fix the ToC of the How to Keep Ballerina up to date Guide

- community.md
- security.md
This is to make some important text bold in the security policy.
> Fixes #
> Making Text Bold in the Security Policy

- code-of-conduct.md
- community.md
- contribution-guide.md
- learn/installing-ballerina.md
- v0-991/learn/getting-started.md
- v1-0/learn/installing-ballerina.md
- v1-1/learn/installing-ballerina.md
This is to add the "Install from source" section in [1] to [2].
[1] https://github.com/ballerina-platform/ballerina-lang
[2] https://ballerina.io/v1-1/learn/installing-ballerina/
> Fixes #214
> Add Installing from Source Instructions  to B.io

- _config.yml
- index.html
This will fix the home page link for the BBE to direct to the latest version's BBE location.
> Fix home page BBE link

- learn/installing-ballerina.md
- v0-991/learn/getting-started.md
- v1-0/learn/installing-ballerina.md
- v1-1/learn/installing-ballerina.md
We need to remove Docker from the "Setting up the prerequisites" in [1].
[1] https://ballerina.io/v1-1/learn/installing-ballerina/
> Fixes #
> Remove Docker from Prerequisites

- contribution-guide.md
Fix the "Installing from Source" Link in the Contribution Guide.
[2] 
> Fixes #
> Fix the Installing from Source Link in the Contribution Guide

- community.md
We need to link [1] from [2] to get more community involvement.
[1] https://medium.com/ballerina-techblog
[2] https://ballerina.io/community/
> Fixes #218
> Link the Ballerina Tech Blog from the Community Page

- community.md
We need to fix the Ballerina Tech Blog link in the Community Page in B.io.
> Fixes #236
> Fix the Ballerina Tech Blog Link in the Community Page in B.io

- learn/style-guide.md
In record definition in style guide section for line, spaces there is a missing a space after the ":" sign. This PR is fixing it.
```Ballerina
Person personRecord = {name:"marcus", id: 0};
```
```Ballerina
Person personRecord = {name: "marcus", id: 0};
```
> Add a space after record definition ":" sign

- v1-0/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
- v1-1/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
This fixes the 2 links in the "What's Next" section of https://ballerina.io/v1-1/learn/intellij-plugin/using-intellij-plugin-features.
> Fixes #252
> Fix Links in Using the Features of the IntelliJ Plugin Page

- learn.md
- v1-0/learn.md
- v1-1/learn.md
This adds the text "API Docs" so that it can be searched easily.
> Fixes #257
> Add the Text "API" to the Learn Page 

- v1-0/learn/api-docs/ballerina/transactions/annotations.html
- v1-0/learn/api-docs/ballerina/websub/functions.html
- v1-0/learn/api-docs/ballerina/websub/objects/Hub.html
- v1-0/learn/style-guide/definitions.md
- v1-0/learn/style-guide/expressions.md
We need to fix the below links, which were caused by #259.
http://localhost:4000/v1-0/learn/style-guide/definitions#function-definition
http://localhost:4000/learn/style-guide/expressions#record-literal
> Fixes #260
> Fix the V1.0 Links in the Style Guide

- terms-of-service.md
Currently, the [Terms of Service in B.io](https://ballerina.io/terms-of-service/) links to the WSO2 Privacy Policy.
However, since the [Terms of Service  in Ballerina Central](https://central.ballerina.io/terms-of-service) is more relevant to Ballerina better to add it in B.io.
> Fixes #264
> Update the Terms of Service of the B.io

- privacy-policy.md
Currently, the [Privacy Policy in B.io](https://ballerina.io/privacy-policy/) links to the WSO2 Privacy Policy.
However, since the [Privacy Policy in Ballerina Central](https://central.ballerina.io/privacy-policy) is more relevant to Ballerina better to add it in B.io.
> Fixes #263
> Update the Privacy Policy of the B.io

- terms-of-service.md
Need to fix the below two TOC links introduced by https://github.com/ballerina-platform/ballerina-dev-website/pull/268.
- Subscriptions and mail notifications: your choice
- Limitation of liability; disclaimer of warranties
> Fixes #270
> Fix the TOC Links in the Terms of Service

- v1-1/learn.md
- v1-1/learn/cli-commands.md
- v1-1/learn/installing-ballerina.md
- v1-1/learn/quick-tour.md
- v1-1/learn/set-up-ballerina-sdk.md
- v1-1/learn/style-guide.md
- v1-1/learn/tools-ides/intellij-plugin.md
- v1-1/learn/tools-ides/vscode-plugin.md
This will add redirection from to old /learn path to redirect old URLs to new path.
> Add redirection from to /learn

- license-of-site.md
- v1-2/learn/how-to-keep-ballerina-up-to-date.md
- v1-2/learn/how-to-write-secure-ballerina-code.md
- v1-2/learn/installing-ballerina.md
- v1-2/learn/set-up-ballerina-sdk.md
- v1-2/learn/tools-ides/intellij-plugin.md
- v1-2/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
- v1-2/learn/tools-ides/vscode-plugin.md
- v1-2/learn/tools-ides/vscode-plugin/graphical-editor.md
- v1-2/learn/tools-ides/vscode-plugin/language-intelligence.md
- v1-2/learn/tools-ides/vscode-plugin/run-all-tests.md
- v1-2/learn/tools-ides/vscode-plugin/run-and-debug.md
We need to fix the broken links identified while testing the staging website for the 1.2 release.
> Fixes #307
> Fix the Broken Links Identified in the 1.2.0 RC Stage

- v1-2/learn/tools-ides/vscode-plugin/run-all-tests.md
This will fix broken links in VSCode plugin docs.
> Fix broken links

- spec/lang/2020R1/index.html
Add perma link to the spec 2020R1 doc to resolve the issue in prod.
> Add permalink to spec 2020R1

- spec/lang/2020R1/index.html
We need to fix the "Appendix C" broken link in [1].
[1] https://ballerina.io/spec/lang/2020R1/
> Fixes #
> Fix the Appendix C link in the Spec

- v1-2/learn/api-docs/ballerina/observe/index.html
- v1-2/learn/api-docs/ballerina/websub/index.html
This is to fix the How To Guide links in Docerina HTMLs to fix them in the Bio site.
> Fixes #
> Fix the How To Guide Links in Docerina HTMLs

- _layouts/ballerina-example-page.html
This is to remove the "Edit on GitHub" option at the top in all BBE pages.
> Fixes #334
> Remove the "Edit on GitHub" Option at the Top of Each BBE Page

- learn/api-docs/ballerina/observe/index.html
- learn/api-docs/index.html
- learn/by-example/index.html
- learn/how-to-deploy-and-run-ballerina-programs.md
- learn/how-to-document-ballerina-code.md
- learn/how-to-keep-ballerina-up-to-date.md
- learn/how-to-observe-ballerina-code.md
- learn/how-to-write-secure-ballerina-code.md
- learn/installing-ballerina.md
- learn/quick-tour.md
- learn/style-guide.md
- learn/style-guide/definitions.md
- learn/style-guide/expressions.md
- learn/tools-ides/intellij-plugin.md
- learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
- learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md
- learn/tools-ides/vscode-plugin.md
- learn/tools-ides/vscode-plugin/documentation-viewer.md
- learn/tools-ides/vscode-plugin/graphical-editor.md
- learn/tools-ides/vscode-plugin/language-intelligence.md
- learn/tools-ides/vscode-plugin/run-all-tests.md
- learn/tools-ides/vscode-plugin/run-and-debug.md
> Updating the /learn URL structure
> Fixes #
> Removed v1-2 from the URLs

- _includes/nav.html
- js/api-doc-template.js
- js/ballerina-common.js
This will fix the issue where selecting latest version won't redirect to the correct URL.
> Fix version dropdown issues for latest versions

- 0.991/learn/api-docs/ballerina/auth.html
- learn/tools-ides/intellij-plugin.md
> Fixing the 0.991 API docs link issue

- license-of-site.md
- why/the-network-in-the-language.md
This is to fix the broken links identified after the 1.2.2 release.
> Fixes #
> Fix Broken Links After the 1.2.2 Release

- learn/how-to-use-java-interoperability.md
This is fix the diagram in the Interoperability How To Guide[1] after the /learn URl change.
[1] https://ballerina.io/learn/how-to-use-java-interoperability/
> Fixes #
> Fix the Diagram in the Interoperability How To Guide

- learn/how-to-use-java-interoperability.md
This is to fix the diagram in the interoperability how to guide[1].
[1] https://ballerina.io/learn/how-to-use-java-interoperability/
> Fixes #
> Fix the diagram in the interop how to guide

- .github/workflows/publish_script/publish_vscode_plugin.py
- .github/workflows/publish_vscode_plugin.yml
> Automated the publishing vscode plugin to vscode marketplace.
> Add GitHub workflow to publish vscode pulgin

- learn/api-docs/index.html
This is to fix the /learn redirections in Docerina V1-2 links.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/341
> Fix the /learn Redirections in Docerina V1-2 Links

- _includes/ballerina-example-head.html
- _includes/ballerina-head-landing-page.html
- _includes/ballerina-head.html
- _includes/ballerina-home-head.html
> Enabled page-specific meta descriptions in the layouts 
> Fixes #
> Updated meta description section

- _data/learnnav.yml
- _layouts/ballerina-learn-landing-page.html
- learn.md
This is to add more links to the new learn page structure.
> Fixes #
> Add More Links to the New Learn Structure

- _data/learnnav.yml
- learn.md
This is to fix the left navigation links in the new learn page.
> Fixes #
> Fix the Left Navigation Links in the New Learn Page

- _data/learnnav.yml
- learn.md
- learn/cli-commands.md
- learn/how-to-deploy-ballerina-programs-in-cloud.md
- learn/quick-tour.md
Make the Quick Tour a main page of Learn.
> Fixes #
> Make the Quick Tour a Main Page

- learn/how-to-keep-ballerina-up-to-date.md
- learn/installing-ballerina.md
- learn/tools-ides/intellij-plugin.md
Update IntelliJ Docs after the Learn page redesign.
> Fixes #
> Update IntelliJ Docs After the Learn Page Redesign

- _data/learnnav.yml
- learn.md
Add interoperability as a new section in the left navigation of the Learn page.
> Fixes #
> Add Interoperability to the Learn Left Nav

- 1.0/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
- 1.0/learn/tools-ides/vscode-plugin.md
- 1.0/learn/tools-ides/vscode-plugin/documentation-viewer.md
- 1.0/learn/tools-ides/vscode-plugin/graphical-editor.md
- 1.0/learn/tools-ides/vscode-plugin/run-all-tests.md
- 1.0/learn/tools-ides/vscode-plugin/run-and-debug.md
- 1.1/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
- 1.1/learn/tools-ides/vscode-plugin.md
- 1.1/learn/tools-ides/vscode-plugin/documentation-viewer.md
- 1.1/learn/tools-ides/vscode-plugin/graphical-editor.md
- 1.1/learn/tools-ides/vscode-plugin/run-all-tests.md
- 1.1/learn/tools-ides/vscode-plugin/run-and-debug.md
- learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
- learn/tools-ides/vscode-plugin.md
- learn/tools-ides/vscode-plugin/documentation-viewer.md
- learn/tools-ides/vscode-plugin/graphical-editor.md
- learn/tools-ides/vscode-plugin/run-all-tests.md
- learn/tools-ides/vscode-plugin/run-and-debug.md
Fix the inconsistencies in the Tooling Pages in Learn.
> Fixes #529
> Fix the Inconsistencies in the Tooling Pages in Learn

- hbs/archived_list.hbs
> Added data-pack attribute to download links to proper grouping in download stats
> Fixes #
> Added data-pack attribute to download links

- community.md
This is to fix the "Seek Help" title in the Community page.
> Fixes #
> Fix the "Seek Help" Title in the Community page

- .github/workflows/publish_github_release.yml
> Without the fix workflow doesn't fail if curl returns anything other than 200 OK.
> Fix error handling issue in github publish workflow

- learn/how-to-use-openapi-tools.md
Correct spelling of "serviceName"
> Fix typo in example code block

- 1.0/learn/vscode-plugin/index.html
- 1.1/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
- 1.1/learn/tools-ides/vscode-plugin.md
- 1.1/learn/tools-ides/vscode-plugin/language-intelligence.md
- 1.1/learn/tools-ides/vscode-plugin/run-all-tests.md
- 1.1/learn/tools-ides/vscode-plugin/run-and-debug.md
- learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md
- learn/tools-ides/vscode-plugin.md
- learn/tools-ides/vscode-plugin/language-intelligence.md
- learn/tools-ides/vscode-plugin/run-all-tests.md
- learn/tools-ides/vscode-plugin/run-and-debug.md
Fix the term "VS Code" and the breadcrumbs of the VS Code Plugin pages.
> Fixes #586
> Fix the Term "VS Code" and Breadcrumbs of the VS Code Plugin Pages

- _data/learnnav.yml
- learn/using-the-openapi-tools.md
Fix issues after renaming the OpenAPI How To Guide[1].
[1] https://ballerina.io/learn/using-the-openapi-tools
> Fixes #
> Fix Issues after Renaming the OpenAPI How To Guide

- _data/learnnav.yml
- learn/tools-ides/setting-up-intellij-idea.md
- learn/tools-ides/setting-up-intellij-idea/using-intellij-plugin-features.md
- learn/tools-ides/setting-up-intellij-idea/using-the-intellij-plugin.md
- learn/tools-ides/setting-up-visual-studio-code.md
- learn/tools-ides/setting-up-visual-studio-code/documentation-viewer.md
- learn/tools-ides/setting-up-visual-studio-code/graphical-editor.md
- learn/tools-ides/setting-up-visual-studio-code/language-intelligence.md
- learn/tools-ides/setting-up-visual-studio-code/run-all-tests.md
- learn/tools-ides/setting-up-visual-studio-code/run-and-debug.md
Add more front matter redirections in all the Tooling pages. This is related to [1].
[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/587
> Fixes #
> Add More Front Matter Redirections in Tooling Pages

- learn.md
- learn/calling-java-code-from-ballerina.md
- learn/coding-conventions.md
- learn/deploying-ballerina-programs-in-the-cloud.md
- learn/documenting-ballerina-code.md
- learn/extending-with-compiler-extensions.md
- learn/generating-ballerina-code-for-protocol-buffer-definitions.md
- learn/keeping-ballerina-up-to-date.md
- learn/observing-ballerina-code.md
- learn/publishing-modules-to-ballerina-central.md
- learn/running-ballerina-code.md
- learn/structuring-ballerina-code.md
- learn/testing-ballerina-code.md
- learn/tools-ides/setting-up-intellij-idea.md
- learn/tools-ides/setting-up-intellij-idea/using-the-intellij-plugin.md
- learn/tools-ides/setting-up-visual-studio-code.md
- learn/using-the-cli-tools.md
- learn/using-the-openapi-tools.md
- learn/writing-secure-ballerina-code.md
Add Trailing Slashes in the Permalinks of Tooling Pages
> Fixes #
> Add Trailing Slashes in the Permalinks of Tooling Pages

- learn/tools-ides/setting-up-intellij-idea.md
- learn/tools-ides/setting-up-visual-studio-code.md
Fix redirection issues in the setting up tooling pages
> Fixes #
> Fix Redirection Issues in the Setting up Tooling Pages

- learn/tools-ides/setting-up-visual-studio-code.md
Remove the VSIX download tip from the VSCode guide.
> Fixes #
> Remove the VSIX Download Tip from the VSCode Guide

- 1.1/learn/tools-ides/vscode-plugin/run-all-tests.md
- downloads.html
Add other installation options to the Downloads page[1].
[1] http://ballerina.io/downloads/
> Fixes #
> Add Other Installation Options to the Downloads Page

- downloads.html
Improve the new Downloads page layout in [1].
[1] http://ballerina.io/downloads/
> Fixes #
> Improve the New Downloads Page Layout

- downloads.html
Add the missing title in the Downloads Page.
> Fixes #
> Add the Missing Title in the Downloads Page

- downloads.html
Add the ZIP archive under the other installation options.
> Fixes #
> Add the ZIP Archive Under Other Installation Options

- spec.md
Address feedback on the Spec page[1].
> Fixes #
> Address Feedback on the Spec Page

- spec.md
Move proposals out from the spec types section in [1].
> Fixes #
> Move Proposals out from the Spec Types Section

- spec.md
Open Links in the Spec page[1] in new tabs.
> Fixes #
> Open Links in the Spec Page in New Tabs

- spec.md
Fix a typo in the Spec page[1].
> Fixes #
> Fix a Typo in the Spec Page

- learn/using-the-cli-tools.md
Add the bindgen tool command to CLI commands page under the `Use the supporting tools` section.
> Add the bindgen tool to CLI commands page

- css/bbe-page.css
Remove bullets in the BBE home page.
> Fixes #
> Remove Bullets in the BBE Home Page

- downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
Fix the capitalization in the topics of the Swan Lake release note.
> Fixes #
> Fix the Capitalization in Topics of the Swan Lake Release Note

- downloads.html
- downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
Fix the Update Tool info on the downloads page.
> Fixes #
> Fix the Update Tool info on the Downloads Page

- downloads.html
Resolve a conflict in the Downloads page.
> Fixes #
> Resolve a Conflict in the Downloads Page

- downloads.html
Fix the line break in the Downloads page.
> Fixes #
> Fix the Line Break in the Downloads Page

- downloads.html
Remove the What's Next section in the Downloads page.
> Fixes #
> Remove the What's Next Section in the Downloads Page

- downloads.html
Change the "Current version" title in Downloads page to "Stable release".
> Fixes #
> Change the "Current Version" Title in the Downloads Page

- downloads.html
Change the preview release title in the Downloads page.
> Fixes #
> Change the Preview Release Title in the Downloads Page

- downloads.html
Fix the hyperlink style in the downloads page.
> Fixes #
> Fix the Hyperlink Style in the Downloads Page

- .github/workflows/add_new_release_note.yml
- .github/workflows/index_search.yml
- .github/workflows/prod_sync.yml
- .github/workflows/sw_add_new_release_note.yml
- .github/workflows/sw_update_release__note_versions.yml
- .github/workflows/update_release_note_versions_json.yml
> $subject. 
Previously we created PRs for,
- Syncing changes with prod site even though it is been verified at the time changes are merged to prod-sync branch
- Index search which is generated by a tool and no pointing reviewing it
- Updating Archive/Release note pages. This is also automatically done no point in reviewing. Hence no need for PR
- Creating a new release note location is also auto created no point in reviewing 
Now with the new changes these will be directly committed to master by ballerina-bot.
> Directly push changes instead of creating redundant PRs

- js/redirections.js
Add the "Page not available" custom error to the 1.1 interop guide.
> Fixes #
> Add the "Page not available" Custom Error Page to the 1.1 Interop Guide

- .github/scripts/publish_homebrew.py
- .github/workflows/publish_homebrew.yml
> Add the OS-dependent [end-of-the-line character](https://github.com/Homebrew/homebrew-core/blob/629f078633500a0c5462276e66f4061192039dad/Formula/ballerina.rb#L32) which is required by the `ballerina.rb Formula`.
> Fix Homebrew publish new line char issue

- .github/scripts/publish_json.py
- .github/workflows/sw_update_release__note_versions.yml
> For a given release metadata.json file can be updated few times due to blockers in the pack. In such cases, we this script now remove the old entry and add the new one.
> Improve publish_json.py to remove and update

- _data/learnnavswanlake.yml
> Add missing testing guide navigations to swanlake yml
> Add missing navigations in SwanLake learn page

- 1.0/learn/by-example/index.html
- 1.1/learn/by-example/index.html
Fix the breadcrumbs of the BBE index page in 1.0 and 1.1 versions.
> Fixes #
> Fix the Breadcrumbs of the BBE Index Page in 1.0 and 1.1 versions

- _data/learnnav.yml
- _data/learnnavswanlake.yml
- swan-lake/learn/deployment/awslambda.md
Add the AWS Lambda guide to the learn nav structure.
> Fixes #
> Add the AWS Lambda Guide to the Learn Navigation Structure

- 1.0/learn/by-example/index.html
Fix the breadcrumbs of the BBE index page in 1.0.
> Fixes #
> Fix the Breadcrumbs of the BBE Index Page  in 1.0

- _data/learnnav.yml
- _data/learnnavswanlake.yml
- js/redirections.js
- learn/deployment/aws-lambda.md
- learn/deployment/azure-functions.md
- swan-lake/learn/deployment/aws-lambda.md
Add redirections for AWS Lambda and Azure in 1.0 & 1.1.
> Fixes #
> Add Redirections for AWS Lambda and Azure in 1.0 & 1.1

- 1.0/learn/how-to-use-openapi-tools/index.html
- 1.1/learn/how-to-use-openapi-tools.md
- learn/using-the-openapi-tools.md
- swan-lake/learn/using-the-openapi-tools.md
Add formatting for code snippets in the OpenAPI guide[1] in all versions.
[1] https://ballerina.io/learn/using-the-openapi-tools/
> Fixes #
> Add Formatting for Code Snippets in the OpenAPI Guide

- swan-lake/learn.md
Fix the Swan Lake testing guide link.
> Fixes #
> Fix the Swan Lake Testing Guide Link

- downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
Fix the update guide links in the Swan Lake release notes.
> Fixes #
> Fix the Update Guide Links in the Swan Lake Release Notes

- 1.0/page-not-available.html
- 1.1/page-not-available.html
- page-not-available.html
- swan-lake/page-not-available.html
Add a Link to the "Learn" section in the "page not available" error page.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/733
> Add a Link to the Learn Section in the "Page Not Available" Error Page

- learn/installing-ballerina.md
- swan-lake/learn/installing-ballerina.md
Update the supported Node.js version as "8.9.x" in the installation page.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1093
> Update the Supported "Node.js" Version in the Installation Page

- downloads/RELEASE_NOTE.md
- downloads/release-notes/1.2.7/RELEASE_NOTE.md
Change the heading levels in the 1.2.7 release note.
> Fixes #
> Change the Heading Levels in the 1.2.7 Release Note

- swan-lake/learn/tools-ides/setting-up-intellij-idea/using-intellij-plugin-features.md
Fix the IntelliJ Guide broken link.
> Fixes #
> Fix the IntelliJ Guide Broken Link

- spec/lang/draft/v2020-06-18/index.html
Fix the "Appendix C" broken link in a released spec version.
> Fixes #
> Fix the "Appendix C" Broken Link in a Released Spec Version

- swan-lake/learn/deployment/azure-functions.md
Fix a link in the Azure Deployment Guide.
> Fixes #
> Fix a Link in the Azure Deployment Guide

- downloads.html
Fix the Linux md5 links in the Downloads page.
> Fixes #
> Fix the Linux MD5 Links in Downloads

- spec/lang/2019R1/index.html
- spec/lang/2019R2/index.html
- spec/lang/2019R3/index.html
- spec/lang/2020R1/index.html
- spec/lang/draft/v2020-06-18/index.html
- spec/lang/master/index.html
- spec/lang/master/spec.xml
Fix the Google Group link in spec versions.
> Fixes #
> Fix the Google Group Link in Spec Versions

- 1.0/learn/by-example/docker-deployment.html
- 1.0/learn/by-example/kubernetes-deployment.html
- 1.0/learn/by-example/openshift-deployment.html
- 1.1/learn/by-example/docker-deployment.html
- 1.1/learn/by-example/kubernetes-deployment.html
- 1.1/learn/by-example/openshift-deployment.html
- js/redirections.js
Fix the "Edit on GitHub" Option of the Deployment Modules for 1.1.x & 1.0.x.
> Fixes #
> Fix the "Edit on GitHub" Option of the Deployment Modules for 1.1.x & 1.0.x

- learn/api-docs/ballerina/java.jdbc/types.html
Fix the new lines formatting in the java.jdbc module API Docs in 1.2.x.
> Fixes #
> Fix the New Lines Formatting in Java JDBC API Docs

- learn/api-docs/ballerina/index.html
Update the API Docs home page for 1.2.x.
> Fixes #
> Update the API Docs Home Page for 1.2.x

- 1.0/learn/by-example/awslambda-deployment.html
- 1.1/learn/by-example/awslambda-deployment.html
- js/redirections.js
Fix the "Edit on GitHub" links of AWS Lambda.
> Fixes #
> Fix the "Edit on GitHub" Links of AWS Lambda

- learn/testing-ballerina-code/mocking.md
Fix Object Mocking examples in Testing Ballerina code.
> Fixes #25343
> Fix Object Mocking examples

- learn/api-docs/ballerina/istio/index.html
- swan-lake/learn/api-docs/ballerina/istio/index.html
Add a Missing Hyphen in the Istio Module.md file.
> Fixes #
> Add a Missing Hyphen in the Istio Module.md File

- 1.0/learn/api-docs/ballerina/awslambda/annotations.html
- 1.0/learn/api-docs/ballerina/awslambda/functions.html
- 1.0/learn/api-docs/ballerina/awslambda/index.html
- 1.0/learn/api-docs/ballerina/awslambda/objects/Context.html
- 1.1/learn/api-docs/ballerina/awslambda/annotations.html
- 1.1/learn/api-docs/ballerina/awslambda/functions.html
- 1.1/learn/api-docs/ballerina/awslambda/index.html
- 1.1/learn/api-docs/ballerina/awslambda/objects/Context.html
Add API Docs of AWS Lambda to 1.1 & 1.0.
> Fixes #
> Add API Docs of AWS Lambda to 1.1 & 1.0

- learn/api-docs/ballerina/docker/records/FileConfigs.html
- learn/api-docs/ballerina/knative/records/ConfigMapMount.html
- learn/api-docs/ballerina/knative/records/SecretMount.html
- learn/api-docs/ballerina/knative/records/ServiceConfiguration.html
- learn/api-docs/ballerina/kubernetes/records/ConfigMapMount.html
- learn/api-docs/ballerina/kubernetes/records/DeploymentConfiguration.html
- swan-lake/learn/api-docs/ballerina/docker/records/FileConfigs.html
- swan-lake/learn/api-docs/ballerina/knative/records/ConfigMapMount.html
- swan-lake/learn/api-docs/ballerina/knative/records/SecretMount.html
- swan-lake/learn/api-docs/ballerina/knative/records/ServiceConfiguration.html
- swan-lake/learn/api-docs/ballerina/kubernetes/records/ConfigMapMount.html
- swan-lake/learn/api-docs/ballerina/kubernetes/records/DeploymentConfiguration.html
Fix broken links of the deployment modules in both 1.2.x and Swan Lake API Docs.
> Fixes #
> Fix Broken Links of the Deployment Modules

- learn/api-docs/ballerina/kubernetes/records/JobConfig.html
- learn/api-docs/ballerina/kubernetes/records/PersistentVolumeClaims.html
- swan-lake/learn/api-docs/ballerina/kubernetes/records/JobConfig.html
- swan-lake/learn/api-docs/ballerina/kubernetes/records/PersistentVolumeClaims.html
Fix more broken links in the K8S API Docs.
> Fixes #
> Fix More Broken Links in the K8S API Docs

- 1.1/learn/api-docs/ballerina/kubernetes/records/SecretMount.html
- learn/api-docs/ballerina/kubernetes/records/ResourceQuotas.html
- learn/api-docs/ballerina/kubernetes/records/SecretMount.html
- swan-lake/learn/api-docs/ballerina/kubernetes/records/ResourceQuotas.html
- swan-lake/learn/api-docs/ballerina/kubernetes/records/SecretMount.html
Fix more K8S API Docs broken links.
> Fixes #
> Fix More K8S API Docs Broken Links

- learn/api-docs/ballerina/index.html
Update the index page of API Docs for 1.2.8.
> Fixes #
> Update the Index Page of API Docs for 1.2.8

- 1.0/learn/api-docs/ballerina/observe/index.html
- 1.1/learn/api-docs/ballerina/observe/index.html
- 1.1/learn/by-example/websocket-client.html
- learn/api-docs/ballerina/observe/index.html
- learn/by-example/testerina-before-and-after-test.html
- learn/by-example/testerina-function-mocks.html
- learn/by-example/testerina-object-mocks.html
- swan-lake/learn/api-docs/ballerina/observe/index.html
Fix broken links in live site after 1.2.8.
> Fixes #
> Fix Broken Links in the Live Site After the 1.2.8 Release

- 1.0/learn/by-example/websocket-client.html
- learn/by-example/testerina-before-each-test.html
Fix the "previous" link of the Web Socket Client BBE.
> Fixes #
> Fix the "Previous" Link of the Web Socket Client BBE

- .github/scripts/search_index_generator.js
> removed temporary api docs pages from the search
> Fixes #
> removed temporary api docs from the search

- 1.0/learn/how-to-document-ballerina-code/index.html
- 1.1/learn/how-to-document-ballerina-code.md
- learn/documenting-ballerina-code.md
- swan-lake/learn/documenting-ballerina-code.md
Add guidelines on documenting comments.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1208
> Add Guidelines on Documenting Comments

- CODEOWNERS.md
Add code owners to the Dev Website repo as per [1].
[1] https://github.blog/2017-07-06-introducing-code-owners/
> Fixes #
> Add Code Owners to the Dev Website Repo

- 1.0/learn/by-example/index.html
- 1.1/learn/by-example/index.html
- swan-lake/learn/by-example/index.html
Fix the broken edit links in the BBE index pages.
> Fixes #
> Fix the Broken Edit Links in the BBE Index Pages

- downloads.html
- downloads/RELEASE_NOTE.md
- downloads/release-notes/1.2.1/RELEASE_NOTE.md
- downloads/release-notes/1.2.2/RELEASE_NOTE.md
- downloads/release-notes/1.2.3/RELEASE_NOTE.md
- downloads/release-notes/1.2.4/RELEASE_NOTE.md
- downloads/release-notes/1.2.5/RELEASE_NOTE.md
- downloads/release-notes/1.2.6/RELEASE_NOTE.md
- downloads/release-notes/1.2.7/RELEASE_NOTE.md
- downloads/release-notes/1.2.8/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
Change the layout of the release notes pages.
> Fixes #
> Change the Layout of the Release Notes Pages

- downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
Make H7 titles bold.
> Fixes #
> Make H7 Titles Bold

- swan-lake/learn/api-docs/ballerina/kafka/index.html
Fix broken links after SLP4.
> Fixes #
> Fix Broken Links After SLP4

- downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
- swan-lake/learn/api-docs/ballerina/io/index.html
Fix a link in the SLP4 release note.
> Fixes #
> Fix a Link in the SLP4 Release Note

- swan-lake/learn/api-docs/ballerina/awslambda/index.html
- swan-lake/learn/api-docs/ballerina/azure.functions/index.html
- swan-lake/learn/api-docs/ballerina/istio/index.html
- swan-lake/learn/api-docs/ballerina/knative/index.html
- swan-lake/learn/api-docs/ballerina/kubernetes/index.html
- swan-lake/learn/api-docs/ballerina/openshift/index.html
Fix deployment API Docs Object links.
> Fixes #
> Fix Deployment API Docs Object Links

- downloads/release-notes/0.970.0/RELEASE_NOTE.html
- downloads/release-notes/0.975.0/RELEASE_NOTE.html
- downloads/release-notes/0.980.0/RELEASE_NOTE.html
- downloads/release-notes/0.981.0/RELEASE_NOTE.html
- downloads/release-notes/0.982.0/RELEASE_NOTE.html
- downloads/release-notes/0.983.0/RELEASE_NOTE.html
- downloads/release-notes/0.990.0/RELEASE_NOTE.html
- downloads/release-notes/0.990.1/RELEASE_NOTE.html
- downloads/release-notes/0.990.3/RELEASE_NOTE.html
- downloads/release-notes/0.991.0/RELEASE_NOTE.html
- downloads/release-notes/1.0.0/RELEASE_NOTE.html
- downloads/release-notes/1.1.0/RELEASE_NOTE.html
- downloads/release-notes/1.1.1/RELEASE_NOTE.html
- downloads/release-notes/1.2.0/RELEASE_NOTE.html
- downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
Add the syntax highlighter class to old versions of the release notes.
> Fixes #
> Add the Syntax Highlighter Class to Old Versions of the Release Notes

- swan-lake/learn/by-example/http-filters.html
- swan-lake/learn/by-example/http-to-websocket-upgrade.html
- swan-lake/learn/by-example/request-with-multiparts.html
- swan-lake/learn/by-example/websocket-cookie.html
- swan-lake/learn/by-example/websub-hub-client-sample.html
Fix more object API Docs links in BBEs.
> Fixes #
> Fix More Object API Docs Links in BBEs

- swan-lake/learn/by-example/http-filters.html
- swan-lake/learn/by-example/websocket-cookie.html
Fix more API Docs links in BBEs.
> Fixes #
> Fix More API Docs Links in BBEs

- why-ballerina/network-aware-type-system.md
Add quotes in the "Network-Aware Type System"[1] "Why Ballerina" Page Samples.
This is for the fix done in [2].
[1] https://ballerina.io/why-ballerina/network-aware-type-system/
[2] https://github.com/ballerina-platform/ballerina-platform.github.io/pull/189
> Fixes #
> Add Quotes in the "Why Ballerina" Page Samples

- 1.0/learn/api-docs/ballerina/java.jdbc/index.html
- 1.0/learn/by-example/jdbc-client-batch-update.html
- 1.0/learn/by-example/jdbc-client-call-procedures.html
- 1.0/learn/by-example/jdbc-client-crud-operations.html
- 1.1/learn/api-docs/ballerina/java.jdbc/index.html
- 1.1/learn/by-example/jdbc-client-batch-update.html
- 1.1/learn/by-example/jdbc-client-call-procedures.html
- 1.1/learn/by-example/jdbc-client-crud-operations.html
Fix the JDBC Driver Path in 1.1.x & 1.0.x docs.
> Fixes #
> Fix the JDBC Driver Path in 1.1.x & 1.0.x Docs

- learn/deployment/docker.md
- swan-lake/learn/deployment/docker.md
Add info on how to copy JDBC driver files to Docker images.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/112
> Add info on How to Copy JDBC Driver Files to Docker Images

- _config.yml
Update the "Edit on GitHub" option to link to the dev site. Currently, it is linked to the live site.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1303
> Update the "Edit on GitHub" Option to Link to the Dev Site

- learn/coding-conventions.md
- learn/deployment/kubernetes.md
- learn/generating-ballerina-code-for-protocol-buffer-definitions.md
- learn/keeping-ballerina-up-to-date.md
- learn/observing-ballerina-code.md
- learn/running-ballerina-code.md
- learn/structuring-ballerina-code.md
- learn/using-the-openapi-tools.md
Fix TOC issues in the 1.2 Learn pages.
> Fixes #
> Fix TOC Issues in the 1.2 Learn Pages

- learn/running-ballerina-code.md
- swan-lake/learn/running-ballerina-code.md
Add info about the `--b7a.config.secret` flag.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/66
> Add Info About the `--b7a.config.secret` Flag

- swan-lake/learn/documenting-ballerina-code.md
> Since Docerina doesn't support services, the current learn page has wrong information at the end. This PR fixes the issue with a custom function and a class definition.
> Fix docerina learn page

- js/redirections.js
- learn/using-the-openapi-tools.md
- swan-lake/learn/using-the-openapi-tools.md
Fix the Open API page redirections for Swan Lake.
> Fixes #
> Fix the Open API Page Redirections for Swan Lake

- swan-lake/learn/deployment/azure-functions.md
Add Java 11 changes in Azure Docs for SLP5.
> Fixes #
> Add Java 11 Changes in Azure Docs for SLP5

- swan-lake/learn/by-example/aws-lambda-deployment.html
- swan-lake/learn/deployment/aws-lambda.md
- swan-lake/learn/deployment/docker.md
- swan-lake/learn/deployment/kubernetes.md
Lambda - Changes ballerina:2 to ballerina-jre11:1 in AWS learn page and BBE.
Docker - Changes ballerina/jre8:v1 of the Dockerfile to ballerina/jre11:v1.
Custom docker image in learn page.    baseImage: "openjdk:8-jre-alpine" -> baseImage: "openjdk:11-jre-slim".
Kubernetes - Changes ballerina/jre8:v1 of the Dockerfile to ballerina/jre11:v1.
~~Note - In the New Dockerfile it uses separate jars instead of one fat jar. Learn pages contains sample output of the generated dockerfile. In this PR, I didn't update it to the latest because inline jars takes lot of unnecessary space in the page. This should be discussed before merging this PR.~~
Edit -: Updated the PR with Several Copy commands.
@anuruddhal  @hemikak @praneesha
> Fix JRE 11 changes in c2c learn and Lambda BBE  

- js/redirections.js
- swan-lake/learn/api-docs/ballerina/ftp/index.html
- swan-lake/learn/by-example/websocket-cookie.html
Fix Broken Links in the Dev Site for SLP5.
> Fixes #
> Fix Broken Links in the Dev Site for SLP5

- js/redirections.js
The FTP module is added in the SLP5 release. 
Therefore, we need to add "Page not available" error message pages for previous releases to avoid broken links in the version navigation.
> Fixes #
> Add Redirections to the FTP Module

- swan-lake/learn/api-docs/ballerina/java.jdbc/clients/Client.html
Fix the SQL Module link in the Java JDBC module.
> Fixes #
> Fix the SQL Module Link in the Java JDBC Module

- downloads.html
Change camel case back to all caps in titles of the "Downloads" page.
> Fixes #
> Change Camel Case Back to All Caps in Titles of the "Downloads" Page

- swan-lake/learn/by-example/aws-lambda-deployment.html
- swan-lake/learn/deployment/aws-lambda.md
$Subject. 
Fixes the overriding issue occurred from #1419
AWS Repo PR - ballerina-platform/module-ballerinax-aws.lambda#220
> Update AWS BBE/Learn layer to JDK 11

- _config.yml
- downloads.html
Update vscode extension download links on website for preview releases.
> Update vscode extension download links

- swan-lake/learn/by-example/index.html
Change the layout of the Swan Lake BBE Landing Page. This is to fix the broken "Edit on GitHub" link that apperas in the link checker search results[1].
[1] https://github.com/ballerina-platform/ballerina-dev-website/issues/1110
> Fixes
> Change the Layout of the Swan Lake BBE Landing Page

- downloads/release-notes/1.2.7/RELEASE_NOTE.md
- downloads/release-notes/1.2.8/RELEASE_NOTE.md
- downloads/release-notes/1.2.9/RELEASE_NOTE.md
Fix the liquid syntax links (i.e., `{{ site.data.stable-latest.metadata.version }}`) manually in 1.2.x release notes.
> Fixes #
> Fix the Liquid Syntax Links Manually in 1.2.x Release Notes

- learn/api-docs/ballerina/docker/records/FileConfigs.html
- swan-lake/learn/api-docs/ballerina/observe/index.html
Fix Swan Lake broken links.
> Fixes #
> Fix Swan Lake Broken Links

- learn-2.md
Change "User Guides" to "User Guide".
> Fixes #
> Change "User Guides" to "User Guide"

- spec/spec.md
Fix the TOC of the Spec page.
> Fixes #
> Fix the TOC of the Spec Page

- swan-lake/learn/deployment/code-to-cloud/code-to-cloud-samples.md
Fix the syntax highlighting of the TOML file in the C2C Learn page.
> Fixes #
> Fix the syntax highlighting of the TOML file in the C2C Learn Page

- privacy-policy.md
Fix a typo in the Privacy Policy.
> Fixes #
> Fix a Typo in the Privacy Policy

- js/ballerina-common.js
> Added cookie-based validation for the privacy popup. Hiding the popup if the policy is already accepted.
> Fixes #
> Added cookie based validation for the privacy popup

- swan-lake/learn/api-docs/ballerina/kubernetes/index.html
- swan-lake/learn/api-docs/ballerina/observe/index.html
- swan-lake/learn/quick-tour.md
Fix broken links for the 1.2.11 release.
> Fixes #
> Fix Broken Links for the 1.2.11 Release

- swan-lake/learn/deployment/aws-lambda.md
- swan-lake/learn/deployment/azure-functions.md
Fix broken links after SLP7.
> Fixes #
> Fix Broken Links After SLP7

- 1.0/learn/cli-commands/index.html
- 1.0/learn/how-to-generate-code-for-protocol-buffers/index.html
- 1.1/learn/cli-commands/index.html
- 1.1/learn/how-to-generate-code-for-protocol-buffers/index.html
- 1.1/learn/how-to-keep-ballerina-up-to-date/index.html
- learn/generating-ballerina-code-for-protocol-buffer-definitions.md
- learn/keeping-ballerina-up-to-date.md
- learn/using-the-cli-tools.md
- swan-lake/learn/generating-ballerina-code-for-protocol-buffer-definitions.md
- swan-lake/learn/keeping-ballerina-up-to-date.md
- swan-lake/learn/using-the-cli-tools.md
Make the "Ballerina Tool" wording consistent in Docs.
> Fixes #1563
> Make the "Ballerina Tool" Wording Consistent in Docs

- swan-lake/learn/tools-ides/setting-up-intellij-idea.md
Redirect the IntelliJ Learn pages of Swan Lake.
> Fixes #1606
> Redirect the IntelliJ Learn Pages of Swan Lake

- 1.0/page-not-available.html
- 1.1/page-not-available.html
- page-not-available.html
- swan-lake/learn/installing-ballerina.md
- swan-lake/learn/structuring-ballerina-code/structuring-ballerina-code.md
- swan-lake/page-not-available.html
Fix broken links after slp8.
> Fixes #
> Fix Broken Links After SLP8

- download.html
Redirect "/download" to the Bio "Download" page.
> Fixes #
> Redirect "/download" to the Bio "Download" Page

- learn/calling-java-code-from-ballerina.md
- learn/documenting-ballerina-code.md
- swan-lake/learn/calling-java-code-from-ballerina.md
- swan-lake/learn/coding-conventions.md
- swan-lake/learn/coding-conventions/annotations_documentation_and_comments.md
- swan-lake/learn/deployment/aws-lambda.md
- swan-lake/learn/deployment/code-to-cloud/code-to-cloud.md
- swan-lake/learn/deployment/docker.md
- swan-lake/learn/documenting-ballerina-code.md
- swan-lake/learn/structuring-ballerina-code/structuring-ballerina-code.md
- swan-lake/learn/testing-ballerina-code/mocking.md
- swan-lake/learn/testing-ballerina-code/writing-tests.md
- swan-lake/learn/writing-secure-ballerina-code.md
> Fix typos and few minor issues in learn pages

- learn/by-example/secured-service-with-oauth2.html
The example https://ballerina.io/learn/by-example/secured-service-with-oauth2.html is not working. 
When trying to connect to server with command: 
curl -k -H "Authorization: Bearer YWRtaW46MTIz" https://localhost:9090/hello/sayHello
The request fails with ssl error.
After checking at example https://ballerina.io/learn/by-example/https-listener.html that explains how to configure https it appears that the wrong p12 is used in the example. 
By making this change the example is working and it's possible to connect to server
> Fix oauth2 service example

- swan-lake/learn/by-example/index.html
Remove the "Back To Top" button from the Swan Lake BBE landing page.
> Fixes #
> Remove the "Back To Top" button from the Swan Lake BBE Landing Page

- learn/coding-conventions.md
Remove the "Expand/Collapse All" option.
> Fixes #
> Remove the "Expand/Collapse All" Option

- _data/learnnavswanlake.yml
- js/redirections.js
- swan-lake/learn/observing-ballerina-code.md
Add the Observability Docs removed via [1] back to Swan Lake.
[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/1403/files
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1406
> Add the Observability Docs Back to Swan Lake

- community.md
Add a section on the "Community Call" on the "Community" page.
> Fixes #
> Add a Section on the "Community Call" on the "Community" Page

- learn/coding-conventions/annotations_documentation_and_comments.md
- learn/coding-conventions/expressions.md
- learn/coding-conventions/operators_keywords_and_types.md
- learn/coding-conventions/top-level-definitions.md
- swan-lake/learn/coding-conventions/annotations_documentation_and_comments.md
- swan-lake/learn/coding-conventions/expressions.md
- swan-lake/learn/coding-conventions/operators_keywords_and_types.md
- swan-lake/learn/coding-conventions/top-level-definitions.md
Remove the "Expand/Collapse All" option in Learn page TOCs that do not have any sub headings.
> Fixes #
> Remove the "Expand/Collapse All" Option in Learn Page TOCs

- swan-lake/learn/deployment/code-to-cloud/code-to-cloud-samples.md
- Change module name from c2c -> cloud
> Fixes https://github.com/ballerina-platform/module-ballerina-c2c/issues/50
> Change c2c module name

- _data/learnnavswanlake.yml
- learn/coding-conventions/top-level-definitions.md
- swan-lake/learn/deployment/azure-functions.md
- swan-lake/learn/security/authentication-and-authorization.md
- swan-lake/learn/security/writing-secure-ballerina-code.md
- swan-lake/learn/testing-ballerina-code/writing-tests.md
Fix broken links for the Swan Lake Alpha release.
> Fixes #
> Fix Broken Links for the Swan Lake Alpha Release

- swan-lake/learn/calling-java-code-from-ballerina.md
* Add the `-m|--modules` flag support as per the latest changes in Project API and Bindgen Tool.
* Add the custom maven repository support.
> Update the calling java code learn page

- downloads/swan-lake-archived.md
Remove SLP6 from the "Archived Versions" page for SLAlpha1.
> Fixes #
> Remove SLP6 from the "Archived Versions" Page for SLAlpha1

- _data/learnnavswanlake.yml
Remove gRPC from Swan Lake Learn.
> Fixes #
> Remove gRPC from Swan Lake Learn

- swan-lake/learn/by-example/anydata-type.html
Fix the "next/previous" links in the "Anydata" BBE in Swan Lake.
> Fixes #
> Fix the "Next/Previous" Links in the "Anydata" BBE

- 1.2/learn/api-docs/ballerina/auth/index.html
- 1.2/learn/api-docs/ballerina/cache/index.html
- 1.2/learn/api-docs/ballerina/crypto/index.html
- 1.2/learn/api-docs/ballerina/email/index.html
- 1.2/learn/api-docs/ballerina/file/index.html
- 1.2/learn/api-docs/ballerina/filepath/index.html
- 1.2/learn/api-docs/ballerina/grpc/index.html
- 1.2/learn/api-docs/ballerina/http/index.html
- 1.2/learn/api-docs/ballerina/io/index.html
- 1.2/learn/api-docs/ballerina/java.arrays/index.html
- 1.2/learn/api-docs/ballerina/java/index.html
- 1.2/learn/api-docs/ballerina/jwt/index.html
- 1.2/learn/api-docs/ballerina/kafka/index.html
- 1.2/learn/api-docs/ballerina/ldap/index.html
- 1.2/learn/api-docs/ballerina/log/index.html
- 1.2/learn/api-docs/ballerina/math/index.html
- 1.2/learn/api-docs/ballerina/mime/index.html
- 1.2/learn/api-docs/ballerina/nats/index.html
- 1.2/learn/api-docs/ballerina/oauth2/index.html
- 1.2/learn/api-docs/ballerina/rabbitmq/index.html
- 1.2/learn/api-docs/ballerina/socket/index.html
- 1.2/learn/api-docs/ballerina/task/index.html
- 1.2/learn/api-docs/ballerina/time/index.html
- 1.2/learn/api-docs/ballerina/websub/index.html
- 1.2/learn/api-docs/ballerina/xslt/index.html
> Fixes links from api docs v1.2 to BBEs.
> Fix links to bbes from API Docs v1.2

- download.html
Fix the VSCode plugin links on the Downloads page.
> Fixes #
> Fix the VSCode Plugin Links on the Downloads Page

- learn.md
- learn/tools-ides/setting-up-visual-studio-code/run-and-debug.md
Remove the "Graphical View" link in the "What's Next?" section.
> Fixes #1814
> Remove the "Graphical View" Link in the "What's Next?" Section

- 1.2/learn/calling-java-code-from-ballerina.md
- learn/calling-java-code-from-ballerina.md
Fixes some backporting mistakes in the `1.2` learn page and a few bugs in the `swan-lake` version as well.
> Fix some issues in the Calling Java Code from Ballerina guide

- learn/deployment/aws-lambda.md
Updates the Learn documents with the AWS CLI payload update and ARN bump with recent changes. 
Related to ballerina-platform/module-ballerinax-aws.lambda#256
> Fix payload issue and update ARN in AWS Lambda Page

- 1.2/learn/tools-ides/setting-up-visual-studio-code/documentation-viewer.md
- 1.2/learn/tools-ides/setting-up-visual-studio-code/graphical-editor.md
- 1.2/learn/tools-ides/setting-up-visual-studio-code/language-intelligence.md
- 1.2/learn/tools-ides/setting-up-visual-studio-code/run-all-tests.md
- 1.2/learn/tools-ides/setting-up-visual-studio-code/run-and-debug.md
Fix redirections in VSCode sub pages.
> Fixes #1854
> Fix Redirections in VSCode Sub Pages

- learn/by-example/kafka-authentication-sasl-plain-consumer.html
- learn/by-example/kafka-authentication-sasl-plain-producer.html
- learn/by-example/kafka-consumer-client.html
- learn/by-example/kafka-consumer-group-service.html
- learn/by-example/kafka-consumer-service.html
- learn/by-example/kafka-producer-transactional.html
- learn/by-example/kafka-producer.html
- learn/by-example/nats-basic-client.html
- learn/by-example/nats-streaming-client.html
- learn/by-example/nats-streaming-durable-subscriptions.html
- learn/by-example/nats-streaming-queue-group.html
- learn/by-example/nats-streaming-start-position.html
- learn/by-example/rabbitmq-consumer-with-client-acknowledgement.html
- learn/by-example/rabbitmq-consumer.html
- learn/by-example/rabbitmq-producer.html
- learn/by-example/rabbitmq-transaction-consumer.html
- learn/by-example/rabbitmq-transaction-producer.html
Changes (kafka, rabbitmq, nats) api docs links to central.
> Change messaging package links to central 

- download.html
Fix the VSCode Download icon for Swan Lake.
> Fixes #1861
> Fix the VSCode Download Icon for Swan Lake

- .github/workflows/sw_update_api_docs.yml
- .github/workflows/sw_update_ballerina_by_example.yml
> Fixes an issue in the Swan Lake API docs generating workflow.
> Fix command for retrieving short version

- download.html
- page-not-available.html
Remove the Homebrew option from the "Downloads" page.
> Fixes #
> Remove the Homebrew Option from the "Downloads" Page

- community.md
Fix the link of the logos in the "Community" page.
> Fixes #
> Fix the Link of the Logos in the "Community" Page

- downloads/swan-lake-release-notes/swan-lake-alpha1/RELEASE_NOTE.md
Fix a typo in the SLAlpha1 release note.
> Fixes #
> Fix a Typo in the SLAlpha1 Release Note

- index.html
Update the getting started link on the Home page.
> Fixes #
> Update the Getting Started Link on the Home Page

- learn/tooling-guide/cli-tools/cli-commands.md
- learn/tooling-guide/cli-tools/update-tool.md
- learn/tooling-guide/vs-code-extension/installing-the-vs-code-extesnion.md
- learn/user-guide/data-and-events-processing/using-language-integrated-queries.md
- learn/user-guide/deployment/code-to-cloud/code-to-cloud.md
- learn/user-guide/getting-started/Installation-options.md
- learn/user-guide/network-communication/HTTP/http-clients/communication-resiliency.md
- learn/user-guide/network-communication/HTTP/http-clients/data-binding.md
- learn/user-guide/network-communication/HTTP/http-clients/data-streaming.md
- learn/user-guide/network-communication/HTTP/http-clients/multipart-message-handling.md
- learn/user-guide/network-communication/HTTP/http-clients/secure-communication.md
- learn/user-guide/network-communication/HTTP/http-services/http-services.md
- learn/user-guide/network-communication/HTTP/http-services/secure-communication.md
- learn/user-guide/network-communication/HTTP/http.md
- learn/user-guide/network-communication/WebSocket/websocket.md
- learn/user-guide/security/authentication-and-authorization.md
- learn/user-guide/security/writing-secure-ballerina-code.md
- learn/user-guide/testing-ballerina-code/testing-quick-start.md
- why-ballerina/sequence-diagrams-for-programming.md
Fix broken links after user guide changes.
> Fixes #
> Fix Broken Links After User Guide Changes

- download.html
Fix the macOS pkg installer pack size.
> Fixes #
> Fix the macOS pkg Installer Pack Size

- _data/toolingguidenavswanlake.yml
- learn/tooling-guide/visual-studio-code-extension/configurations.md
- learn/tooling-guide/visual-studio-code-extension/installing-the-vs-code-extesnion.md
- learn/tooling-guide/visual-studio-code-extension/language-support/documentation-viewer.md
- learn/tooling-guide/visual-studio-code-extension/language-support/graphical-editor.md
- learn/tooling-guide/visual-studio-code-extension/language-support/language-intelligence.md
- learn/tooling-guide/visual-studio-code-extension/language-support/language-support.md
- learn/tooling-guide/visual-studio-code-extension/language-support/run-all-tests.md
- learn/tooling-guide/visual-studio-code-extension/low-code.md
- learn/tooling-guide/visual-studio-code-extension/run-and-debug.md
- learn/tooling-guide/visual-studio-code-extension/vs-code-commands.md
- security.md
Fix the Security page email link and change VSCode to Visual Studio Code in the left navigation and breadcrumbs.
> Fixes #1960
> Fix the Security Page Email Link and Change VSCode to Visual Studio Code

- index.html
Remove the Sequence Diagrams Why Ballerina section from the Home page of Bio.
> Fixes #
> Remove the Sequence Diagrams Why Ballerina Section

- learn/user-guide/coding-conventions/expressions.md
$title and add missing indentation to second line.
> Fixes #
> Fix tuple syntax in sample

- learn/user-guide/deployment/azure-functions.md
Adds cosmos database connection related steps to learn page to make the development process easier for users.
> Fixes #
> Add cosmos db steps to Azure learn page

- index.html
- learn.md
Add links to API Docs in Ballerina Central.
> Fixes #
> Add Links to API Docs in Ballerina Central

- learn/tooling-guide/visual-studio-code-extension/installing-the-vs-code-extesnion.md
Fix vscode extension download links for alpha3 release.
> Fix alpha3 vscode links

- index.html
Fix the "Network in the Language" "Why Ballerina" section on the Home Page.
> Fixes #
> Fix the "Network in the Language" "Why Ballerina" Section on the Home Page

- downloads/swan-lake-archived.md
- spec/spec.md
Remove the edit option on the "Archived Versions" page.
> Fixes #
> Remove the Edit Option on the "Archived Versions" Page

- _data/swanlake_release_notes_versions.json
- download.html
- downloads/swan-lake-release-notes/swan-lake-alpha3/RELEASE_NOTE.md
- js/download/swan_lake_archived_download.js
- learn/tooling-guide/visual-studio-code-extension/installing-the-vs-code-extesnion.md
Add the VSCode extension to the Swan Lake "Archived Versions" page.
> Fixes #2046
> Add VSCode Extension to the Swan Lake "Archived Versions" Page

- learn/user-guide/deployment/azure-functions.md
Azure module name was changed from azure.functions -> azure_functions. This PR does the necessary changes for Learn deployment documentation of this change.
Resolves #2022
> Fix Azure import in Azure deployments

- download.html
Fix the ZIP link in the Downloads page.
> Fixes #1602
> Fix the ZIP Link in the Downloads Page

- learn/tooling-guide/visual-studio-code-extension/run-and-debug.md
Remove the "What's Next" section from the "Run & Debug" Learn page.
> Fixes #2063
> Remove the "What's Next" Section from the "Run & Debug" Learn Page

- learn/user-guide/testing-ballerina-code/mocking.md
- learn/user-guide/testing-ballerina-code/testing-quick-start.md
> Fix usage of `stringutils` package in code samples of testing guide.
> Fixes #2056
> Fix usage of stringutils in test guide

- _data/learnnavswanlake.yml
- index.html
- learn/user-guide/deployment/code-to-cloud/code-to-cloud.md
Remove the Docker Learn page from Swan Lake User Guide.
> Fixes #
> Remove the Docker Learn Page from Swan Lake User Guide

- learn/user-guide/deployment/aws-lambda.md
Adds memory, timeout and invoking instructions to aws lambda guide
Resolves #2047
> Add memory, timeout and invoking instructions to aws  lambda guide

- home.html
Add the iframe to the Home page for the Playground widget.
> Fixes #
> Add the iFrame to the Home page for the Playground Widget

- index.html
- learn.md
- learn/language-guide/language-guide.md
Rename the "Language Guide" to "Language Concepts".
> Fixes #
> Rename the "Language Guide" to "Language Concepts"

- index.html
Fix the "More Info" links in the "Why Ballerina" section
> Fixes #
> Fix the "More Info" Links in the "Why Ballerina" Section

- learn/user-guide/observing-ballerina-code.md
With the pr -> ballerina-platform/ballerina-lang/pull/30543, we have updated the default metrics and tracing provider as choreo.  These doc changes are the related configuration changes to support prometheus and jaeger
> Update the configurations related to the change in default observability extensions

- index.html
Upgrade the playground widget from playground staging to prod.
> Fixes #
> Upgrade the Playground Widget from Playground Staging to Prod

- _data/toolingguidenavswanlake.yml
- learn/tooling-guide/visual-studio-code-extension/language-support/intellisense.md
Rename "language intelligence" to "IntelliSense" in VSCode Docs.
> Fixes #2194
> Rename "Language Intelligence" to "IntelliSense" in VSCode Docs

- learn/tooling-guide/visual-studio-code-extension/installing-the-vs-code-extesnion.md
Remove the bullet points on the VSCode installation page.
> Fixes #2204
> Remove the Bullet Points on the VSCode Installation Page

- community.md
Fix the titles on the "Community" page.
> Fixes #2239
> Fix the Titles on the "Community" Page

- _layouts/ballerina-learn-landing-page.html
- learn-old.md
- learn.md
Improve the Learn page descriptions.
> Fixes #2238
> Improve the Learn Page Descriptions

- learn/user-guide/calling-java-code-from-ballerina.md
- learn/user-guide/coding-conventions.md
- learn/user-guide/deployment/aws-lambda.md
- learn/user-guide/deployment/azure-functions.md
- learn/user-guide/publishing-packages-to-ballerina-central.md
- learn/user-guide/testing-ballerina-code/executing-tests.md
- learn/user-guide/testing-ballerina-code/testing-quick-start.md
- learn/user-guide/why-ballerina/graphical.md
Remove the Expand/Collapse All Option from the TOCs in pages that do not have sub-sections.
> Fixes #
> Remove the Expand/Collapse All Option from the TOCs

- download.html
- downloads/1.2.x-release-notes/1.2.10.md
- downloads/1.2.x-release-notes/1.2.11.md
- downloads/1.2.x-release-notes/1.2.6.md
- downloads/swan-lake-release-notes/swan-lake-preview6/RELEASE_NOTE.md
Fix the 1.2.11 release note and VSCode Marketplace Link.
> Fixes #
> Fix the 1.2.11 Release Note and VSCode Marketplace Link

- learn/user-guide/deployment/aws-lambda.md
Fixes auto generated compiler outputs according to the correct bal file name. `function` -> `functions`
> Fix aws learn page function name

- learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
- learn/user-guide/ballerina-packages/package-layout.md
- learn/user-guide/ballerina-packages/sharing-a-library-package.md
> Remove ToC from Package Layout page and fix formatting issues
> Remove ToC from Package Layout page and fix formatting issues

- 1.2/learn/by-example/testerina-mocking-functions.html
- learn/tooling-guide/cli-tools/cli-commands.md
- learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
- learn/user-guide/ballerina-packages/dependencies.md
- learn/user-guide/ballerina-packages/modules.md
- learn/user-guide/ballerina-packages/package-layout.md
- learn/user-guide/ballerina-packages/sharing-a-library-package.md
- learn/user-guide/getting-started/writing-your-first-ballerina-program.md
> Fix capitalization of titles in Ballerina Packages guides
> Fixes part of #2288
> Fix capitalization of titles in Ballerina Packages guides

- _includes/nav.html
Fix the "Download" top menu link.
> Fixes #
> Fix the "Download" Top Menu Link

- css/home-page-2020.css
Increase the height of the playground widget on the Home page.
> Fixes #
> Increase the Height of the Playground Widget

- 1.2/learn/by-example/kubernetes-deployment.html
- 1.2/learn/deployment/aws-lambda.md
- community.md
- learn/user-guide/code-organization/coding-conventions.md
- learn/user-guide/network-communication/gRPC/implementing-grpc-services-and-clients/implementing-grpc-clients.md
- learn/user-guide/why-ballerina/cloud-native.md
- learn/user-guide/why-ballerina/concurrent.md
Fix concurrency page intro and broken links.
> Fixes #
> Fix Concurrency Page Intro and Broken Links

- downloads/swan-lake-release-notes/swan-lake-beta2/RELEASE_NOTE.md
Include a bit about allowing unary operator in constant expressions.
> Add unary op in const expr

- 1.2/learn/api-docs/ballerina/grpc/index.html
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/664
> Remove unnecessary equal operator from gRPC doc

- learn/user-guide/ballerina-packages/package-layout.md
- learn/user-guide/deployment/code-to-cloud/code-to-cloud-samples.md
Fix a typo and update backticks on the TOC.
> Fixes #
> Fix Typo and Update Backticks on the TOC

- .github/workflows/update_ballerina_by_example.yml
Enable the 1.2 BBEs gen workflow to run manually.
> Fixes #
> Enable the 1.2 BBEs Gen Workflow to Run Manually

- .github/workflows/update_ballerina_by_example.yml
Update 1.2.x BBE gen workflow to use the 1.2.x branch of the `ballerina-release` repo.
> Fixes #
> Update 1.2.x BBE Gen Workflow to Use the 1.2.x Branch

- learn/by-example/index.html
Add keywords to the BBE index page for the Algolia search.
> Fixes #
> Add Keywords to the BBE Index Page for the Algolia Search

- download.html
Fix the ZIP and source download links.
> Fixes #2563
> Fix the ZIP and Source Download Links

- learn.md
Change the API Docs URL.
> Fixes #2634
> Change the API Docs URL

- learn.md
Fix the breadcrumbs of the learn page.
> Fixes #
> Fix the Breadcrumbs of the Learn Page

- learn/tooling-guide/cli-tools/openapi.md
$Subject
Add new command-line options details to the learn page
> Update OpenAPI learn page

- js/redirections.js
Add redirections for the removed Learn pages.
> Fixes #
> Add Redirections for the Removed Learn Pages

- community-old.md
Fix the report issues links on the Community page in the `master` branch.
> Fixes #
> Fix the Report Issues Links on the Community Page in the Master Branch

- learn/guides/running-ballerina-programs-in-the-cloud/function-as-a-service-with-ballerina/aws-lambda.md
Fix the breadcrumbs of the FaaS Learn page.
> Fixes #2855
> Fix the Breadcrumbs of the FaaS Learn page

- _data/clidocumentationnavswanlake.yml
Fix the OpenAPI text in left nav.
> Fixes #2873
> Fix the OpenAPI Text in Learn Left Nav

- learn/references/style-guide/coding-conventions/expressions.md
Fix the line breaks link on the Expressions page.
> Fixes #
> Fix the Line Breaks Link on the Expressions Page

- learn/references/style-guide/coding-conventions/top-level-definitions.md
Remove the duplicated TOC in the "Top-level Definitions" page.
> Fixes #2871
> Remove the duplicated TOC in the "Top-level Definitions" page

- learn/guides/calling-java-code-from-ballerina-and-vice-versa.md
- learn/guides/organizing-ballerina-code/package-layout.md
Fix the package layout link in the Interop page.
> Fixes #2870
> Fix the Package Layout Link in the Interop Page

- learn/guides/calling-java-code-from-ballerina-and-vice-versa.md
Fix the title formatting in the Interop page.
> Fixes #2869
> Fix the Title Formatting in the Interop Page

- learn/guides/publishing-packages-to-ballerina-central.md
Fix the links in the Ballerina Central Learn page.
> Fixes #2866
> Fix the Links in the Ballerina Central Learn Page

- learn/guides/managing-dependencies.md
Fix incorrect links in the "Managing Dependencies" pagec.
> Fixes #2865
> Fix Incorrect Links in the "Managing Dependencies" Page

- learn/guides/running-ballerina-programs-in-the-cloud/function-as-a-service-with-ballerina/aws-lambda.md
Fix the incorrect link in the AWS Lambda Learn page.
> Fixes #2864
> Fix the Incorrect Link in the AWS Lambda Learn Page

- learn/guides/managing-dependencies.md
> Fix a typo in Overriding Dependencies

- _includes/left-nav-cli-documentation-swan-lake.html
- _layouts/ballerina-cli-documentation-left-nav-pages-swanlake.html
- learn/references/cli-documentation/openapi.md
Fix the TOCs of the CLI docs pages.
> Fixes #
> Fix the TOCs of the CLI Docs Pages

- download.html
Fix the links to the "Installing Ballerina" page on the "Downloads" page.
> Fixes #2958
> Fix the Links to the "Installing Ballerina" Page on the "Downloads" Page

- learn/by-example/websocket-text-client.html
Fix the API Docs links on the WebSocket text client BBE.
> Fixes #
> Fix the API Docs Links on the WebSocket Text Client BBE

- Gemfile
- Gemfile.lock
- _config.yml
Integrate the Jekyll sitemap generation plugin[1].
[1] https://github.com/jekyll/jekyll-sitemap
> Fixes
> Integrate the Jekyll Sitemap Generation Plugin

- download.html
Update the VSIX GitHub link for the 1.2.21 release.
> Fixes #
> Update the VSIX GitHub Link for the 1.2.21 Release

- _data/clidocumentationnavswanlake.yml
- _data/helloworldnavswanlake.yml
- _data/installingballerinanavswanlake.yml
- _data/observingprogramsswanlake.yml
- _data/styleguidenavswanlake.yml
- _data/visualstudiocodeextensionnavswanlake.yml
- learn.md
- learn/guides/observing-ballerina-programs/observing-your-application-with-choreo.md
- learn/references/cli-documentation/grpc.md
Add the missing page TOCs to the left nav.
> Fixes #
> Add the Missing Page TOCs to the Left Nav

- _includes/left-nav-cli-documentation-swan-lake.html
Fix the left nav of the "CLI Documentation" section.
> Fixes #
> Fix the Left Nav of the "CLI Documentation" Section

- community.md
Remove broken event links on the Community page.
> Fixes #
> Remove Broken Event Links on the Community Page

- learn/guides/why-ballerina/cloud-native.md
The link is shown incorrectly right now.
> Update markdown around github action link

- _includes/ballerina-footer.html
- security-policy.md
Add the "Security Policy" footer link.
> Fixes #3167
> Add the "Security Policy" footer link

- css/ballerina-io.css
> Fix  broken title h6 tag issue when scrolling
> Fixes #3086
> Fix the h6 broken title

- learn/getting-started/visual-studio-code-extension/debugging.md
This PR will remove the `--debug` option from the `build` command.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/34169 | https://github.com/ballerina-platform/ballerina-lang/issues/33748
> Remove  `--debug` option from `build` command

- learn/guides/why-ballerina/reliable-maintainable.md
Fix the Breadcrumbs of the "Reliable, Maintainable" "Why Ballerina" page.
> Fixes #3196
> Fix the Breadcrumbs of the "Reliable, Maintainable" "Why Ballerina" Page

- _data/whyballerinanavswanlake.yml
- index.html
- learn.md
- learn/why-ballerina/cloud-native.md
- learn/why-ballerina/concurrent.md
- learn/why-ballerina/data-oriented.md
- learn/why-ballerina/flexibly-typed.md
- learn/why-ballerina/graphical.md
- learn/why-ballerina/reliable-maintainable.md
Need to remove the Why Ballerina pages from the Learn section. They will just be linked from the Home page.
Also, updated a few sections on the Learn landing page as follows.
> Fixes #3213
> Remove the "Why Ballerina" Pages and Update Learn Sections

- index.html
- js/philosophy.js
- learn.md
- learn/by-example/index.html
- learn/by-example/table-syntax.html
Remove the "Language By Examples" view.
> Fixes #3084
> Remove the "Language By Examples" View

- security-policy.md
Add the "Security Advisories" section to the "Security Policy" page.
> Fixes #
> Add the "Security Advisories" Section to the "Security Policy" Page

- community/newsletter.md
Update the date of 2021-6 on the past newsletters section.
> Fixes #
> Update the Date of 2021-6 on the Past Newsletters Section

- learn/why-ballerina/concurrent.md
- learn/why-ballerina/reliable-maintainable.md
Fix the typos on the Why Ballerina pages.
> Fixes #
> Fix the typos on the "Why Ballerina" Pages

- robots.txt
Block content of old doc versions in Google search results.
> Fixes #
> Block Content of Old Doc Versions in Google Search Results

- _includes/nav.html
- css/ballerina-io.css
> Add styles for old learn page top banners
> Fixes #
> Add styles for old learn page top banners

- learn/guides/running-ballerina-programs-in-the-cloud/function-as-a-service-with-ballerina/aws-lambda.md
- learn/guides/running-ballerina-programs-in-the-cloud/function-as-a-service-with-ballerina/azure-functions.md
$Subject. As single file projects won't be supported in the long run.
> Fixes #
> Make FaaS learn pages use Projects instead single files

- learn.md
- learn/guides/distinctive-language-features/network-interaction.md
Fix the links of the learn landing page.
> Fixes #
> Fix the Links of the Learn Landing Page

- learn/guides/visual-studio-code-extension/vs-code-quick-start.md
Remove the 1.2.x support reference from VS Code docs.
> Fixes #3419
> Remove the 1.2.x Support Reference from VS Code Docs

- learn.md
Remove the language intro slides from Learn.
> Fixes #3421
> Remove the Language Intro Slides from Learn

- _data/configurableswanlake.yml
- _data/guidesnavswanlake.yml
- learn/guides/configuring-ballerina-programs/configure-values-in-kubernetes-environment.md
- learn/guides/configuring-ballerina-programs/configuring-a-sample-ballerina-service.md
- learn/guides/configuring-ballerina-programs/providing-values-to-configurable-variables.md
$subject
- fixed upper case, lower case inconsistency in titles
- fixed title format inconsistency (`ing` format)
- Removed `Additional Information` section
- Improved Page structure
The improved structure will be as follows, 
When enhanced -
> Improve configurable learn page as per the suggestions

- learn/references/cli-documentation/grpc.md
This is to update the gRPC tooling guide in learn pages
> Fixes #
> Update gRPC tooling guide in learn pages

- _data/installingballerinanavswanlake.yml
Add the missing title in the "Installation Options" page to the left nav.
> Fixes #3443
> Add the Missing Title in the Installation Options Page to the Left Nav

- learn/guides/generating-code-documentation.md
> Convert unnecessary heading to bold text
> Remove sub heading from documentation guide

- learn.md
- learn/getting-started/installing-ballerina/setting-up-ballerina.md
Fix the VSCode links.
> Fixes #
> Fix the VSCode Links

- learn/getting-started/writing-a-grpc-service-with-ballerina.md
Correct the output message of CLI tooling. This is corrected recently
> Fixes #
> Correct the output message of cli tooling

- learn.md
- learn/guides/managing-dependencies.md
- learn/guides/organizing-ballerina-code.md
- learn/guides/publishing-packages-to-ballerina-central.md
- learn/references/package-references/package-layout.md
> Fix more broken links in ballerina packages guides
> Fix more broken links in ballerina packages guides

- .gitignore
Add macOS-related files and IDE-related files to the .gitignore file. This is to avoid these unnecessary files being committed to the repo via PRs.
> Fixes #
> Add macOS and IDE Related Files to the .gitignore File

- learn/guides/managing-dependencies.md
- learn/references/package-references.md
> Temporarily remove sticky option example in ballerina.toml
> Temporarily remove sticky option example in ballerina.toml

- learn/guides/managing-dependencies.md
- learn/guides/testing-ballerina-code/code-coverage-and-reporting.md
- learn/guides/testing-ballerina-code/configuring-tests.md
- learn/guides/testing-ballerina-code/defining-data-driven-tests.md
- learn/guides/testing-ballerina-code/defining-test-groups.md
- learn/guides/testing-ballerina-code/executing-tests.md
- learn/guides/testing-ballerina-code/mocking.md
- learn/guides/testing-ballerina-code/testing-a-simple-function.md
- learn/guides/testing-ballerina-code/testing-services-and-clients.md
- learn/references/package-references.md
Improve descriptions in guides
> Improve descriptions in guides

- learn/guides/testing-ballerina-code/writing-tests.md
> Add assertion functions as code in using assertions table at `/learn/testing-ballerina-code/writing-tests/#using-assertions`.
> Fixes #
> Add assertion functions as code in using assertions table

- spec/lang/draft/latest/index.md
Remove the 2021R1 spec draft entry from the `index.md` file.
> Fixes #
> Remove the 2021R1 Spec Draft Entry from the `index.md` File

- download.html
- downloads/swan-lake-release-notes/swan-lake-2201.0.0/RELEASE_NOTE.md
Update the update commands post SL GA release.
Download page
Release Note
> Fixes #
> Update the Update Commands Post SL GA Release

- downloads/swan-lake-release-notes/swan-lake-2201.0.0/RELEASE_NOTE.md
This is a required step if someone is migrating from Swan Lake Beta releases.
> Add instructions to delete `Dependencies.toml` to avoid compilation errors

- learn/guides/distinctive-language-features/network-interaction.md
Under the _Resources_ section, It was written as
> **``name``** is the resource name
But to my understanding resource name is **``hello``** as per the shown code snippet.
> Fixed a typo (?)

- _includes/ballerina-footer.html
Fix the `Subscribe to Our Newsletter` footer link.
> Fixes #3856
> Fix the `Subscribe to Our Newsletter` Footer Link

- events.html
Redirect the Old `Events` page to the new one.
> Fixes #3822
> Redirect the Old `Events` Page to the New One

- community-new.html
- resources.html
- tech-talk.html
> Removed "subscribe to Tech Talk" from the community page
> Removed "subscribe to Tech Talk" from the Tech Talk page
> Removed submit content from the 'Contribute to the Resource Library' -- Removed entire item comes under "Get Involved"
> Fixes #
> Update community page sections

- learn/getting-started/language-basics.md
Edited an invalid statement from [language-basics#binary-data](https://ballerina.io/learn/language-basics/#binary-data)
> ``byte`` is not the same as a character in C. It is a subtype of the integer type.
This statement is contradictory. A ``char`` is an integral type in C. But these two statements suggest otherwise.
> Edited an invalid statement

- _data/all-bbes.json
- learn/by-example/all-bbes.json
- learn/by-example/floating-point-numbers.html
Fix the typos in the Floating Point Numbers BBE.
> Fixes #
> Fix the Typos in the Floating Point Numbers BBE

- downloads/swan-lake-release-notes/swan-lake-2201.0.2/RELEASE_NOTE.md
Remove empty links in the 2201.0.2 release note.
> Fixes #
> Remove Empty Links in the 2201.0.2 Release Note

- learn/get-started/write-a-restful-api-with-ballerina.md
Fix the permalink of the RESful get started guide.
> Fixes #
> Fix the permalink of the RESful Get Started Guide

- learn/get-started/install-ballerina/Installation-options.md
Fix the installation page links.
> Fixes #
> Fix the Installation Page Links

- learn/references/package-references.md
> Fix link in package references
> Fix link in package references

- learn/guides/observe-ballerina-programs.md
Remove committed conflicts on the Observability page.
> Fixes #
> Remove Committed Conflicts on the Observability Page

- learn/guides/configure-ballerina-programs/provide-values-to-configurable-variables.md
- learn/guides/observe-ballerina-programs.md
- learn/guides/test-ballerina-code/write-tests.md
- learn/references/java-interoperability/ballerina-ffi.md
- learn/references/java-interoperability/the-bindgen-tool.md
- spec/spec.md
Fix sentence case in table headings.
> Fixes #
> Fix sentence Case in Table Headings

- _data/callingjavacodeswanlake.yml
Add the level3 headings to Interoperability page left nav.
> Fixes #4141
> Add the Level3 Headings to the Interoperability Page Left Nav

- learn/guides/configure-ballerina-programs/provide-values-to-configurable-variables.md
Do quick fixes of the Configurable Learn page.
> Fixes #
> Do Quick Fixes of the Configurable Learn Page

- learn/references/cli-documentation/openapi.md
Add the Ballerina to OpenAPI command reference.
> Fixes #
> Add the Ballerina to OpenAPI Command Reference

- _data/installingballerinanavswanlake.yml
Add the Learn more section to the installation page left nav.
> Fixes #
> Add the `Learn more` Section to the Installation Page Left Nav

- .github/ISSUE_TEMPLATE/type_bug.md
- .github/ISSUE_TEMPLATE/type_improvement.md
- .github/ISSUE_TEMPLATE/type_new_feature.md
- .github/ISSUE_TEMPLATE/type_task.md
- learn.md
Add area labels as comments in issue templates.
> Fixes #
> Add Area Labels as Comments in Issue Templates

- .github/workflows/add_link_checker.yml
Change the base URL of the Lychee link checker to `pre-prod.ballerina.io`.
> Fixes #
> Change the Base of Link Checker to Pre-Prod

- .github/workflows/add_link_checker.yml
- home.html
- learn/why-ballerina/cloud-native.md
- learn/why-ballerina/flexibly-typed.md
- learn/why-ballerina/graphical.md
Fix URLs to mandate the link checker.
> Fixes #
> Fix URLs to Mandate the Link Checker

- downloads/archived.md
- downloads/swan-lake-archived.md
Fix sentence case in `Archived Versions` pages of both 1.2.x and Swan Lake.
> Fixes #
> Fix Sentence Case in `Archived Versions` Pages

- .github/workflows/sw_publish_github_release.yml
Fix the prod sync release note generation issue.
> Fixes #
> Fix the Prod Sync Release Note Generation Issue

- _config.yml
Change 2201.0.3 Release Note Folder Name
Exclude 1.0 from the build.
> Fixes #
> Exclude 1.0 From the Build

- downloads/swan-lake-release-notes/swan-lake-2201.0.2/RELEASE_NOTE.md
Add the 2201.0.2 release note back.
> Fixes #
> Add the 2201.0.2 release note back

- _includes/ballerina-footer.html
Change the order of the footer icons. Going with the order below based on how active user interactions are on each of these channels.
1. GitHub
2. Twitter
3. Slack
4. Stack Overflow
5. YouTube
**Current order:**
**Proposed order:**
> Fixes #4005
> Change the Order of the Footer Icons

- _includes/nav.html
- js/redirections.js
Remove 1.0 from the version drop-down.
> Fixes #4329
> Remove 1.0 from the Version Drop-Down

- community/newsletter/2020-1.md
- community/newsletter/2020-2.md
- community/newsletter/2020-3.md
- community/newsletter/2020-4.md
- community/newsletter/2020-5.md
- community/newsletter/2021-1.md
- community/newsletter/2021-2.md
- community/newsletter/2021-3.md
- community/newsletter/2021-4.md
- community/newsletter/2021-5.md
- community/newsletter/2021-6.md
- community/newsletter/2021-7.md
- community/newsletter/2022-1.md
- community/newsletter/2022-2.md
Fix the page title of newsletters as follows.
> Fixes #4326
> Fix the Page Title of Newsletters

- _data/releasenotes.yml
- downloads/1.2.x-release-notes/1.2.28.md
- downloads/1.2.x-release-notes/1.2.29.md
Add the 1.2.29 release note.
> Fixes #
> Add the 1.2.29 Release Note

- downloads/1.2.x-release-notes/1.2.1.md
- downloads/1.2.x-release-notes/1.2.11.md
- downloads/1.2.x-release-notes/1.2.15.md
- downloads/1.2.x-release-notes/1.2.16.md
- downloads/1.2.x-release-notes/1.2.17.md
- downloads/1.2.x-release-notes/1.2.18.md
- downloads/1.2.x-release-notes/1.2.19.md
- downloads/1.2.x-release-notes/1.2.2.md
- downloads/1.2.x-release-notes/1.2.20.md
- downloads/1.2.x-release-notes/1.2.21.md
- downloads/1.2.x-release-notes/1.2.22.md
- downloads/1.2.x-release-notes/1.2.23.md
- downloads/1.2.x-release-notes/1.2.24.md
- downloads/1.2.x-release-notes/1.2.25.md
- downloads/1.2.x-release-notes/1.2.26.md
- downloads/1.2.x-release-notes/1.2.27.md
- downloads/1.2.x-release-notes/1.2.28.md
- downloads/1.2.x-release-notes/1.2.29.md
- downloads/1.2.x-release-notes/1.2.4.md
- downloads/1.2.x-release-notes/1.2.5.md
- downloads/1.2.x-release-notes/1.2.7.md
- downloads/1.2.x-release-notes/1.2.9.md
Fix fullstop inconsistencies in 1.2.x release notes.
> Fixes #4356
> Fix Fullstop Inconsistencies in 1.2.x Release Notes

- learn/by-example/http-request-error-interceptor.html
- learn/by-example/http-request-interceptor-at-listener.html
- learn/by-example/http-request-interceptor-at-service.html
Fix the edit option of removed HTTP BBEs. These were removed to go with Update1.
> Fixes #
> Fix the Edit Option of Removed HTTP BBEs

- learn/guides/distinctive-language-features/network-interaction.md
> Fixes the sendMessage method call in the explanation of the Consume Services example on https://ballerina.io/learn/distinctive-language-features/network-interaction/#consume-services---client-objects
> Fixes #4369
> Fix sendMessage method call on Consume Services example : Distinctive Features page

- _data/learnleftnav.yml
- css/ballerina-io-docs.css
- css/ballerina-io.css
- learn.md
Remove the detailed learn left nav.
> Fixes #
> Remove the Detailed Learn Left Nav

- community-new.html
> Regarding the request made by Ashweni via [1] I added Join the Dev Google Group under get started section in community page
[1] - Thread <Website update | Ballerina Dev Google group>
> Fixes #
> Add Ballerina Dev Google group to Community page

- learn/get-started/write-a-grpc-service-with-ballerina.md
Update the left nav mismatch in gRPC `Get started` guide.
> Fixes #4387
> Update the Left Nav Mismatch in the gRPC Guide

- learn.md
Fix new learn page sections.
> Fixes #
> Fix New Learn Page Sections

- _data/ballerinaasyncapisupportswanlake.yml
- _data/ballerinagraphqlsupportswanlake.yml
- _data/ballerinaopenapisupportswanlake.yml
- css/ballerina-io-docs.css
- css/ballerina-io.css
- learn.md
- learn/guides/asyncapi-tool.md
- learn/guides/graphql-tool.md
- learn/guides/openapi-tool.md
Revert the new learn page design and title style changes from 2201.1.0.
> Fixes #
> Revert New Learn Design and Title Styles from 2201.1.0

- _data/ballerinagraphqlsupportswanlake.yml
- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
- learn.md
- learn/guides/graphql-client-tool.md
Rename the GraphQL guide.
> Fixes #
> Rename the GraphQL Guide

- learn/references/cli-documentation/cli-commands.md
> Add missing `bal graphql` cmd to cli documentation
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/36251
> Add missing `bal graphql` cmd to cli documentation

- community-new.html
- community/event-date.js
- community/events.html
- index.html
> This will automate hide the expired event once event start at given time zone.
> Fixes #3976
> Fix automatically hide expired events

- learn/references/style-guide/coding-conventions/statements.md
Removing the incorrect bullet point regarding the pattern clauses with one statement in match command style guide.
Fixes #4453
> Remove Inconsistent Match Command Description for Single Statements in Style Guide

- _data/releasenotes.yml
- downloads/swan-lake-release-notes/swan-lake-2201.0.0/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.0.1/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.0.2/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.0.3/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.0.4/RELEASE_NOTE.md
- hbs/archived_list.hbs
> Links were not worked, So I fixed that as follows
> Fixes #4086
https://user-images.githubusercontent.com/73055030/171575406-896eb770-0108-4558-a36d-7f10f69c22d0.mov
> Fix archived release notes link issue

- download.html
Update the `Downloads` page for 2201.1.0.
> Fixes #
> Update the `Downloads` Page for 2201.1.0

- _layouts/ballerina-left-nav-release-notes.html
Remove the version picker in the release notes layout.
> Fixes #4513
> Remove the Version Picker in Release Notes Layout

- community-new.html
- community/events.html
- index.html
> Update the no event banner on events section since there is no event available at the moment. It's just uncomment code part in that section
> Fixes #
> Add no event banner

- _data/releasenotes.yml
- downloads/1.2.x-release-notes/1.2.29.md
- downloads/1.2.x-release-notes/1.2.30.md
Add the 1.2.30 release note.
> Fixes #
> Add the 1.2.30 Release Note

- community-new.html
Remove the Google dev group section from the `Get involved` topic.
> Fixes #
> Remove Google Dev Group from `Get involved`

- .github/workflows/prod_sync_artifacts_on_demand.yml
Currently there is a workflow to sync artifacts from dev to prod when there is a release. But it will only trigger when download page has been updated. There might be scenarios that there will be releases which won't be the latest version (eg: current lastest version is `2201.2.0` and we have a release `2201.1.2`.). 
This workflow will sync artifacts from dev to prod on demand for a given version. 
> Fixes #4658
> Add workflow to sync artifacts from dev to prod

- downloads/swan-lake-release-notes/swan-lake-2201.1.1/RELEASE_NOTE.md
Fix the build error in the 2201.1.1 release branch.
> Fixes #
> Fix the build error in the 2201.1.1 release branch

- _data/releasenotes.yml
- downloads/1.2.x-release-notes/1.2.31.md
Add the 1.2.31 release note.
> Fixes #
> Add the 1.2.31 release note

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
Fix the release notes link on the `Downloads` page.
> Fixes #
> Fix the release notes link on the `Downloads` page

- spec/spec.md
Restructure the spec Learn page.
> Fixes #4403
> Restructure the Spec Learn Page

- spec/spec.md
Fix uppercase letter on spec learn page
> Fixes #
> Fix uppercase letter on spec learn page

- 0.990/learn/api-docs/ballerina/index.html
Remove 0.990 dummy text.
> Fixes #490
> Remove 0.990 dummy text

- .github/scripts/bal_proposals_bot/main.bal
Fix a minor typo on the `Get involved` section.
> Fixes #
> Fix a minor typo on the `Get involved` section

- swan-lake/learn-the-platform/source-code-dependencies/organize-ballerina-code.md
Fix the import syntax on `Organize Ballerina code` page.
> Fixes #4877
> Fix the import syntax on `Organize Ballerina code` page

- spec/spec.md
- swan-lake/learn-the-platform/source-code-dependencies/manage-dependencies.md
Update `that` vs. `which` on the spec learn page.
> Fixes #
> Update `that` vs. `which` on the spec learn page

- spec/spec.md
- swan-lake/learn-the-platform/source-code-dependencies/manage-dependencies.md
Fix code highlighting on the dependencies page.
> Fixes #4884
> Fix code highlighting on the dependencies page

- .github/scripts/bbe/generateBBEs.js
- .github/scripts/bbe/generateNav.js
- .github/scripts/bbe/markdownConverter.js
- pages/learn/by-example/[bbe].js
- pages/learn/by-example/index.js
Add WSO2 license header for the following.
- BBE generation scripts.
- BBE javascript pages.
> Add WSO2 license header

- public/0.990/learn/api-docs/ballerina/index.html
Remove the dummy text on 0.990 API docs.
> Fixes #
> Remove the dummy text on 0.990 API docs

- spec/spec.md
Update the active proposals link on the spec page.
> Fixes #
> Update the active proposals link on the spec page

- policy/license-of-site.md
Remove the BBE attribution section as we do not use the Go Tool for BBE generation now.
> Fixes #
> Remove the BBE attribution section

- swan-lake/learn-the-platform/ballerina-tooling/graphql-client-tool.md
Replace the GraphQL config doc link.
> Fixes #5139
> Replace the GraphQL config doc link

- swan-lake/get-started/get-started-with-ballerina.md
Fix the hyperlink rendering of the tip.
> Fixes #
> Fix the hyperlink rendering of the tip

- pages/learn/by-example/index.js
Add `prefix` to BBE landing page URLs.
> Add `prefix` to BBE landing page URLs

- swan-lake/learn-the-platform/source-code-dependencies/organize-ballerina-code.md
Fix the `Package references` broken link.
> Fixes #
> Fix the `Package references` broken link

- swan-lake/learn-the-language/language-basics.md
While importing ballerina/lang.string it should be corrected as ballerina/lang.'string else import will throw an error.
> Fixes # Corrected Docs for language basics in import where given statement will throw import error. Corrected import syntax is import ballerina/'string
> Updated language-basics import for lang library

- swan-lake/learn-the-platform/configure-observe/configure-ballerina-programs/configure-a-sample-ballerina-service.md
- swan-lake/learn-the-platform/configure-observe/configure-ballerina-programs/provide-values-to-configurable-variables.md
Improve the `Configurable` learn pages.
> Fixes #5425
> Improve the `Configurable` learn pages

- downloads/1.2.x-release-notes/1.2.32.md
- utils/rl.json
Add the 1.2.32 release note.
> Fixes #
> Add the 1.2.32 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.0/RELEASE_NOTE.md
Remove the troubleshooting instructions from the 2201.2.0 release note.
> Fixes #
> Remove troubleshooting instructions from the 2201.2.0 release note

- utils/archived-lm.json
Update 1.2.32 in archived versions left nav.
> Fixes #
> Update 1.2.32 in archived versions left nav

- components/common/top-nav/TopNav.js
> Automatically hide the hackathon banner after the hackathon

- downloads/1.2.x-release-notes/1.2.33.md
- utils/archived-lm.json
- utils/rl.json
Add the 1.2.33 release note to master.
> Fixes #
> Add the 1.2.33 release note to master

- downloads/swan-lake-release-notes/swan-lake-2201.2.1/RELEASE_NOTE.md
- utils/rl.json
Add the 2201.2.1 release note to master.
> Fixes #
> Add the 2201.2.1 release note to master

- pages/downloads/index.js
- styles/globals.css
Update the `Download` page on VS Code content as shown below.
> Fixes #5597
> Update the `Download` page on VS Code content

- downloads/swan-lake-release-notes/swan-lake-2201.2.2/RELEASE_NOTE.md
> Remove CLI & Project API Links from the 2201.2.2 Release note

- swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md
> Update Azure function learn pages according to 3.0.0 release

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
Update the 2201.2.3 release note content.
> Fixes #
> Update the 2201.2.3 release note content

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
Remove fullstops in the 2201.2.3 release note.
> Fixes #
> Remove fullstops in the 2201.2.3 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
Fix the links in the 2201.2.3 release note.
> Fixes #
> Fix the links in the 2201.2.3 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
Update the Project API link in 2201.2.3 release note.
> Fixes #
> Update the Project API link in 2201.2.3 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
Update the Lang bug fixes link in 2201.2.3 release note.
> Fixes #
> Update the Lang bug fixes link in 2201.2.3 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
Update the OpenAPI note in 2201.2.3 release note.
> Fixes #
> Update the OpenAPI note in 2201.2.3 release note

- downloads/vs-code-release-notes/3.3.0.md
Add the VS Code 3.3.0 release note.
> Fixes #
> Add the VS Code 3.3.0 release note

- components/learn/platform/Platform.js
- utils/learn-lm.json
> Add Native support section to Learn landing page

- .github/scripts/bbe/convertMarkdown.js
- styles/globals.css
> Remove extra space between Related Links in BBE

- components/common/redirect-message/RedirectMessage.js
Update the Slack link to Discord.
> Fixes #
> Update the Slack link to Discord

- spec/spec.md
Update 2022R3 spec release date.
> Fixes #
> Update 2022R3 spec release date

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.2.4 /RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.3.0/RELEASE_NOTE.md
Add the 2201.2.4 release note.
> Fixes #
> Add the 2201.2.4 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.4/RELEASE_NOTE.md
Fix milestone links in the 2201.2.4 release note.
> Fixes #
> Fix milestone links in the 2201.2.4 release note

- _data/configurableswanlake.yml
- _data/guidesnavswanlake.yml
- swan-lake/learn-the-platform/configure-observe/configure-ballerina-programs/configure-values.md
- swan-lake/learn-the-platform/configure-observe/configure-ballerina-programs/provide-values-to-configurable-variables.md
> Change `command line` to `command-line` in the config learn page 

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
> Fix 2201.3.2 release notes to use the term `project design tool` 

- swan-lake/learn-the-platform/source-code-dependencies/package-references.md
- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/test-services-and-clients.md
> Update build tools documentation for 2201.4.0 release
> Update documentation for 2201.4.0 release

- downloads/1.2.x-release-notes/1.2.35.md
- utils/archived-lm.json
- utils/rl.json
Update the 1.2.35 release in B.io.
> Fixes #
> Update 1.2.35 release in B.io

- components/learn/language/Language.js
- components/learn/language/Language.module.css
- components/learn/platform/Platform.js
- components/learn/platform/Platform.module.css
>Redesign the Learn the language section
and rearreange and increase padding spacing in Learn the platform
> Fixes #6268
> Redesign learn the language section

- components/learn/intro/Intro.js
- components/learn/intro/Intro.module.css
- styles/globals.css
> Increase spacing in learn landing page
> Fixes #
> Update spacing in learn page

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
- utils/archived-lm.json
Update the 2201.4.0 release note.
> Fixes #
> Update 2201.4.0 release note

- styles/globals.css
Remove the horizontal bar on Learn page as shown below to be consistent with the other Community and Home page designs.
> Fixes #
> Remove the horizontal bar on Learn page

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
Fix the broken links on the native executable page.
> Fixes #
> Fix the broken links on the native executable page

- components/learn/platform/Platform.js
- next.config.js
- utils/learn-lm.json
Fix the broken links of the GraphQL tool page.
> Fixes #
> Fix the broken links of the GraphQL tool page

- _data/release_notes_versions.json
- pages/downloads/archived.js
- styles/globals.css
Remove .`vsix` file from 1.2.x versions (from 1.2.20 upwards, in which it last worked) and add a common link to the deprecated marketplace download link as shown below.
> Fixes #6346
> Remove .`vsix` file from 1.2.x versions

- pages/downloads/index.js
- swan-lake/get-started/install-ballerina/installation-options.md
Add separate section for Homebrew as follows.
> Fixes #6511
> Add separate section for Homebrew

- downloads/swan-lake-release-notes/swan-lake-2201.3.4/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
Add breaking changes section in 2201.4.0 release note.
> Fixes #6505
> Add breaking changes section in 2201.4.0 release note

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Add the 2201.5.0 (Swan Lake Update 5) release note.
> Fixes #
> Add the 2201.5.0 (Swan Lake Update 5) release note

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
Add indentation to info.
> Fixes #
> Update `Backward-incompatible changes` in Update 4 release note

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Fix github issue link in the release note
> Fix github issue link in the release note

- downloads/1.2.x-release-notes/1.2.36.md
Fix typo in 1.2.36.md.
> Fixes #
> Fix typo in 1.2.36.md

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
Fix heading levels of update tool page.
> Fixes #
> Fix heading levels of update tool page

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
Add runtime release notes for the `2201.5.0` release.
> Fixes #
> Add runtime changes to `2201.5.0` release note

- swan-lake/learn-the-language/distinctive-language-features/advanced-general-purpose-language-features.md
$subject
> Fixes [issue](https://github.com/ballerina-platform/ballerina-lang/issues/39632)
Master PR #6547
> [Release-2201.5.0] Add regexp type under advance general purpose language features section

- components/community/get-involved/GetInvolved.js
- components/community/tech-talk/TechTalk.js
Remove user forms from the Community page.
> Fixes #6785
> Remove user forms from the Community page

- utils/learn-lm.json
> Fix the order in learn left nav

- swan-lake/featured-scenarios/write-a-restful-api-with-ballerina.md
Fix a minor typo in the RESTful get started guide.
> Fixes #6838
> Fix a minor typo in the RESTful get started guide

- pages/downloads/index.js
- swan-lake/featured-scenarios/build-a-data-service-in-ballerina.md
- swan-lake/featured-scenarios/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-scenarios/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-scenarios/write-a-graphql-api-with-ballerina.md
- swan-lake/featured-scenarios/write-a-grpc-service-with-ballerina.md
- swan-lake/featured-scenarios/write-a-restful-api-with-ballerina.md
- swan-lake/get-started/get-started.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
Fix the `Get started` section broken links.
> Fixes #6837
> Fix the `Get started` section broken links 

- public/1.2/learn/deployment/aws-lambda/index.html
- swan-lake/api-docs/ballerina/index.html
- swan-lake/by-example/xslt-transformation/content.jsx
- swan-lake/other/network-communication/HTTP/http-clients/communication-resiliency.md
- swan-lake/other/network-communication/HTTP/http-clients/data-binding.md
- swan-lake/other/network-communication/HTTP/http-clients/data-streaming.md
- swan-lake/other/network-communication/HTTP/http-clients/http-clients.md
- swan-lake/other/network-communication/HTTP/http-clients/multipart-message-handling.md
- swan-lake/other/network-communication/HTTP/http-clients/secure-communication.md
- swan-lake/other/network-communication/HTTP/http-services/extended-request-response-access.md
- swan-lake/other/network-communication/HTTP/http-services/http-services.md
- swan-lake/other/network-communication/HTTP/http-services/multipart-message-handling.md
- swan-lake/other/network-communication/HTTP/http-services/payload-data-binding.md
- swan-lake/other/network-communication/HTTP/http-services/secure-communication.md
- swan-lake/other/network-communication/WebSocket/secure-websocket-communication.md
- swan-lake/other/network-communication/WebSocket/websocket.md
Fix more `docs.central.ballerina.io` redirections.
> Fixes #
> Fix more `docs.central.ballerina.io` redirections

- swan-lake/featured-scenarios/work-with-data-using-queries-in-ballerina.md
Fix title levels in the queries guide.
> Fixes #
> Fix title levels in the queries guide

- components/learn/intro/Intro.js
Make the button labels on learn and home pages consistent.
> Fixes #6887
> Make the button labels on learn and home pages consistent 

- components/common/footer/Footer.js
> Remove Google Groups icon from footer

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
Add LS release note for the 2201.6.0 release.
> Fixes #
> Add ls changes to 2201.6.0 release note

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
Fix ls release note of update 6.
> Fixes #
> Fix ls changes in 2201.6.0 release note

- pages/downloads/index.js
- swan-lake/get-started/get-started.md
Add VS Code ext docs in B.io.
> Fixes #
> Add VS Code ext docs in B.io

- components/learn/intro/Intro.js
Add Vs Code ext to the Learn block as shown below.
> Fixes #
> Add Vs Code ext to the Learn block

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
Add the 2201.6.0 release note.
> Fixes #
> Add the 2201.6.0 release note

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/configure-tests.md
Update missing Up6 changes.
> Fixes #
> Update missing Up6 changes

- components/downloads/packs/Packs.js
> Add GTM class to download links

- components/vs-code-home-page/intro/Intro.js
Add the `noreferrer` class to fix Zapier demo build errors.
> Fixes #
> Add the `noreferrer` class to fix Zapier demo build errors

- components/vs-code-home-page/code/Code.module.css
- components/vs-code-home-page/intro/Intro.module.css
Fix mobile view intro button displaying.
> Fixes #
> Fix mobile view intro button displaying

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
- downloads/vs-code-release-notes/3.3.0.md
- swan-lake/get-started/get-started.md
- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
- swan-lake/learn-the-platform/test-document-the-code/debug-ballerina-programs.md
- swan-lake/why-ballerina/graphical.md
Fix VS Code links after revamp.
> Fixes #
> Fix VS Code links after revamp

- components/learn/intro/Intro.js
Update the VS Code home page in Learn.
> Fixes #
> Update the VS Code home page in Learn

- components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/designer-tool.md
- downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
- swan-lake/featured-scenarios/build-a-data-service-in-ballerina.md
- swan-lake/featured-scenarios/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-scenarios/manage-data-persistence-with-bal-persist.md
- swan-lake/featured-scenarios/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-scenarios/write-a-graphql-api-with-ballerina.md
- swan-lake/featured-scenarios/write-a-grpc-service-with-ballerina.md
- swan-lake/featured-scenarios/write-a-restful-api-with-ballerina.md
- swan-lake/learn-the-platform/ballerina-tooling/asyncapi-tool.md
- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
Fix VS Code links in more pages.
> Fixes #
> Fix VS Code links in more pages

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
Add installer verification section to Update 7 release note.
> Fixes #
> [2201.7.0] - Add installer verification section to Update 7 release note

- downloads/swan-lake-release-notes/swan-lake-2201.5.1/RELEASE_NOTE.md
Remove standard library bug fixes from the 2201.5.1 release note as we do not have any.
> Fixes #
> Remove standard library bug fixes from 2201.5.1

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/graphql.md
- swan-lake/learn-the-platform/ballerina-tooling/graphql-tool.md
The functionality to generate Ballerina GraphQL service sources for a given GraphQL schema is introduced to the GraphQL tool. The GraphQL tool guide is updated with the details of this functionality.
> Fixes [#4433](https://github.com/ballerina-platform/ballerina-standard-library/issues/4433)
> Update the GraphQL Tool Guide with Ballerina GraphQL service generation

- downloads/swan-lake-release-notes/swan-lake-2201.6.1/RELEASE_NOTE.md
Update 2201.6.1 release note tooling bug fixes link.
> Fixes #
> Update 2201.6.1 release note tooling bug fixes link

- components/learn/boxes/Boxes.js
Revert the Learn page.
> Fixes #
> Revert the Learn page

- components/learn/boxes/Boxes.js
- components/learn/platform/Platform.js
- downloads/1.2.x-release-notes/1.2.8.md
- downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
- next.config.js
- swan-lake/by-example/aws-lambda-deployment/content.jsx
- swan-lake/by-example/azure-functions-deployment/content.jsx
- swan-lake/by-example/c2c-docker-deployment/content.jsx
- swan-lake/by-example/c2c-k8s-deployment/content.jsx
- swan-lake/resources/featured-scenarios/deploy-ballerina-on-kubernetes.md
- utils/learn-lm.json
> Fix learn run in cloud pages

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
- swan-lake/development-tutorials/build-and-run/cli-commands.md
- swan-lake/integration-tools/graphql-tool.md
- swan-lake/integration-tools/openapi-tool.md
- swan-lake/resources/featured-scenarios/write-a-grpc-service-with-ballerina.md
Fix more tool page links after learn revamp.
> Fixes #
> Fix more tool page links after learn revamp

- policy/cookie-policy.md
- policy/privacy-policy.md
Improve the privacy and cookie policy pages.
> Fixes #
> Improve the privacy and cookie policy pages

- downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
> [Update 8] - Remove `soap` package from the release note

- downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
Fix formatting of the 2201.8.0 release note.
> Fixes #
> Fix formatting of the 2201.8.0 release note

- swan-lake/development-tutorials/build-a-graalvm-executable/build-the-executable-locally.md
Fix a typo in the GraalVM section.
> Fixes #
> Fix a typo in the GraalVM section

- swan-lake/development-tutorials/build-and-run/cli-commands.md
Fix code snippets in CLI commands page.
> Fixes #
> Fix code snippets in CLI commands page

- swan-lake/development-tutorials/run-in-the-cloud/aws-lambda.md
- swan-lake/resources/featured-scenarios/write-a-graphql-api-with-ballerina.md
Fix GraphQL broken link.
> Fixes #
> Fix GraphQL broken link

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
Fix the broken links of 2201.1.0 release note.
> Fixes #
> Fix the broken links of 2201.1.0 release note

- downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
Fix GraphiQL word in Update 8 release note.
> Fixes #
> Fix GraphiQL word in Update 8 release note

- components/common/left-nav/LeftNavYaml.js
Navigating to a new example will reload the page and scroll to the top. However, by adding a Next.js Link, the page will not reload, and the scroll position will be preserved.
> Fixes #5586
> Improve UX in ballerina by example website

- _data/swanlake_release_notes_versions.json
- downloads/swan-lake-release-notes/swan-lake-2201.8.1/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Add dev-tools changes to the 2201.8.1 release note.
> Fixes #
> Add dev-tools changes to the 2201.8.1 release note

- pages/spec/[slug].js
> fix: for missing page titles in library spec pages

- components/home-page/bal-action/BalAction.js
- pages/index.js
> Fixes #8001 
This is how it looks
> copy code button added in Ballerina Action sample

- swan-lake/development-tutorials/test-document-the-code/generate-code-documentation.md
- utils/highlighter.js
> Code blocks with nested syntax was not being highlighted
> Fixes #6656
> Add syntax highlighting to nested code blocks #6656

- pages/downloads/index.js
> Layout not managed properly on viewports `lg` and `xl`.
> Fixes #8126
> Layout shift fixed on /downloads - Update index.js

- swan-lake/resources/featured-scenarios/manage-data-persistence-with-bal-persist.md
Remove the UUID generation in the persist get started guide.
> Fixes #8141
> Remove the UUID generation in the persist get started guide

- swan-lake/integration-tools/health-tool.md
Improve the health tool page content.
> Fixes #
> Improve the health tool page content

- swan-lake/vs-code-extension/configure-the-extension.md
Fix the VS Code ext docs intra links.
> Fixes #
> Fix the VS Code ext docs intra links

- components/learn/pattern/CodeView.js
- components/learn/pattern/CodeView.module.css
- components/learn/pattern/readPattern.js
- pages/learn/enterprise-integration-patterns/[pattern].js
Add code collapse feature to EIP and reactor code view into a component.
> Add code collapse feature to EIPs

- swan-lake/integration-tutorials/sending-emails-from-a-service.md
Fix the project name in the `Build and run the service` section of the `sending-emails-from-a-service` tutorial
> Fix `sending-emails-from-a-service` tutorial

- swan-lake/resources/featured-scenarios/manage-data-persistence-with-bal-persist.md
Remove UUID values from the persist guide.
> Fixes #
> Remove UUID values from persist guide

- swan-lake/integration-tutorials/service-orchestration.md
> Address review comments in `Service Orchestration` tutorial

- swan-lake/resources/featured-scenarios/build-a-data-service-in-ballerina.md
- swan-lake/resources/featured-scenarios/manage-data-persistence-with-bal-persist.md
- swan-lake/resources/featured-scenarios/write-a-graphql-api-with-ballerina.md
- swan-lake/resources/featured-scenarios/write-a-restful-api-with-ballerina.md
Add dollar signs to new cURL commands.
> Fixes #
> Add dollar signs to new cURL commands

- styles/globals.css
> Fix sticky footer

- downloads/swan-lake-release-notes/swan-lake-2201.8.3/RELEASE_NOTE.md
Improve the 2201.8.3 release note.
> Fixes #
> Improve the 2201.8.3 release note

- swan-lake/integration-tools/edi-tool.md
Fix the EDI Tool TOML file link.
> Fixes #
> Fix the EDI Tool TOML file link

- swan-lake/integration-tools/edi-tool.md
Change `arguments` to `command options` in EDI tool  page.
> Fixes #
> Change `arguments` to `command options` in EDI tool page

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
- swan-lake/vs-code-extension/implement-the-code/data-mapper.md
- swan-lake/vs-code-extension/references/statement-editor/call-a-ballerina-package-function.md
Fix a few lib broken links.
> Fixes #
> Fix a few lib broken links 

- swan-lake/why-ballerina/graphical.md
Fix the data mapper link in the Graphical Why Ballerina page.
> Fixes #
> Fix the data mapper link in Graphical page

- swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/mocking.md
> Update regex usage in mocking learn page

- downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Add the 2201.9.0 release note.
> Fixes #
> Add the 2201.9.0 release note

- swan-lake/development-tutorials/source-code-dependencies/package-references.md
Remove the `-c` command option from the `bal build` command.
> Fixes #8543
> Remove the `-c` command option from `bal build` command

- swan-lake/development-tutorials/source-code-dependencies/style-guide/expressions.md
> Fix formatting issue in expressions page[1].
[1] https://ballerina.io/learn/style-guide/expressions/#type-casting
> Fixes #8551
> Fix formatting issue in expressions page

- swan-lake/development-tutorials/source-code-dependencies/package-references.md
Remove the incomplete sentence in the `Package references` page.
> Fixes #8549
> Remove the incomplete sentence in `Package references` page

- swan-lake/integration-tools/edi-tool.md
Remove extra space in the EDI page cURL command.
> Fixes #
> Remove extra space in the EDI page cURL command

- swan-lake/development-tutorials/source-code-dependencies/package-references.md
Change the `bal build` command to `bal pack` in the `Package references` page.
> Fixes #
> Change the `bal build` command in Package references page

- swan-lake/development-tutorials/ballerina-persist/bal-persist-overview.md
- utils/learn-lm.json
Change the `bal persist overview` page title.
> Fixes #8586
> Change the `bal persist overview` page title

- swan-lake/development-tutorials/test-document-the-code/generate-code-documentation.md
Remove the word `Docerina` from docs.
> Fixes #8585
> Remove the word `Docerina` from docs

- swan-lake/development-tutorials/ballerina-central/publish-packages-to-ballerina-central.md
Change the usage of the `library` word.
> Fixes #8600
> Change the usage of the `library` word

- pages/downloads/index.js
> Remove backticks from Downloads page

- _data/swanlake-latest/metadata.json
- _data/swanlake_release_notes_versions.json
- downloads/swan-lake-release-notes/swan-lake-2201.8.6/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
> Add Release 2201.8.6 meta data and Release Note

- swan-lake/development-tutorials/source-code-dependencies/manage-dependencies.md
> Modify offline flag

- components/learn/boxes/Boxes.js
- swan-lake/development-tutorials/ballerina-central/configure-a-network-proxy.md
- swan-lake/development-tutorials/ballerina-central/publish-packages-to-ballerina-central.md
- swan-lake/development-tutorials/source-code-dependencies/manage-dependencies.md
- utils/learn-lm.json
> Move proxy configuration to a separate page

- swan-lake/development-tutorials/ballerina-central/configure-a-network-proxy.md
- swan-lake/development-tutorials/ballerina-central/publish-packages-to-ballerina-central.md
> Reorganize titles in proxy doc

- downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md
Update the release note 2201.9.0 with the following connector updates.
> Google Calendar
> Docusign eSignature
> Docusign Admin
> Docusign Click
> Confluent Schema Registry
> Confluent Avro Serialization/Deserialization
> Add connector updates to the 2201.9.0 release note

- downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md
> Add EDI Tool changes

- swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/execute-tests-in-parallel.md
- swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/execute-tests.md
- utils/learn-lm.json
Related to https://github.com/ballerina-platform/ballerina-lang/issues/24643
> [2201.9.0] Add test parallelisation  document

- downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md
> Add build tools features to release note
> Add build tools features to release note

- swan-lake/development-tutorials/source-code-dependencies/style-guide/top-level-definitions.md
> Add style guideline for `const-decl` best practices

- swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/mocking.md
- swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/test-services-and-clients.md
> Related to https://github.com/ballerina-platform/ballerina-lang/issues/40059
> [2201.9.0] Add resource mocking content

- swan-lake/integration-tools/edi-tool.md
> Minor improvements on the grammar/paragraphs and changed the incorrect `library` terminology to `package`.
> Resolves https://github.com/ballerina-platform/ballerina-dev-website/issues/8977, https://github.com/ballerina-platform/ballerina-dev-website/issues/8974
> Revise the EDI Tools Documentation

- swan-lake/development-tutorials/ballerina-persist/persist-client-api.md
- swan-lake/development-tutorials/ballerina-persist/persist-introspection.md
This PR is to fix broken hyperlinks in some of the persist documentation.
> Fix broken hyperlinks in `persist` docs

- downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md
> Add compile time errors on interop calls of constructors of abstract classes as breaking changes

- downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
> Template to update release note for Update 10
> Add update10 release note

- public/spec/lang/2019R1/index.html
- public/spec/lang/2019R2/index.html
- public/spec/lang/2019R3/experimental.html
- public/spec/lang/2019R3/index.html
- public/spec/lang/2020R1/index.html
- public/spec/lang/2021R1/index.html
- public/spec/lang/2022R1/index.html
- public/spec/lang/2022R2/index.html
- public/spec/lang/2022R3/index.html
- public/spec/lang/2022R4/index.html
- public/spec/lang/2023R1/index.html
- public/spec/lang/2024R1/index.html
- public/spec/lang/draft/index.html
- public/spec/lang/draft/v2020-06-18/index.html
- public/spec/lang/draft/v2020-09-16/index.html
- public/spec/lang/draft/v2020-09-22/index.html
- public/spec/lang/draft/v2020-12-07/spec.html
- public/spec/lang/draft/v2020-12-17/index.html
- public/spec/lang/draft/v2022-01-07/index.html
- public/spec/lang/draft/v2022R1/build/index.html
- public/spec/lang/master/index.html
> Add viewport tags to spec pages

- downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md
> Add deprecated xmldata module to the release notes

- swan-lake/vs-code-extension/run-a-program.md
- Remove invalid options from VSCode guide
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8975
> Remove invalid options from VSCode guide

- _data/swanlake-latest/metadata.json
- _data/swanlake_release_notes_versions.json
- downloads/swan-lake-release-notes/swan-lake-2201.10.1/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
> Update release notes and versions for Release 2201.10.1

- swan-lake/development-tutorials/run-in-the-cloud/code-to-cloud-deployment.md
- Document the required command for c2c build in MacOS
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9431
> Document the required command for c2c build in MacOS

- components/common/left-nav/LeftNav.js
- pages/downloads/swan-lake-release-notes/[...slug].js
- utils/rl.json
Redesign the release notes page to have a nested view with the patch releases listed under the main update releases as follows. The below pattern will be ordered based on latest releases unlike presented below.
- 2201.0.0 (Swan Lake)
- 2201.0.1
- 2201.0.2
- 2201.0.3
- 2201.0.4
- 2201.0.5
- 2201.1.0 (Swan Lake Update 1)
- 2201.1.1
- 2201.1.2
- 2201.2.0 (Swan Lake Update 2)
- 2201.2.1
> Fixes #5627 
https://github.com/user-attachments/assets/af712f0f-01b9-4a9e-bd03-f3b4e1738de1
> Add accordions to list release versions 

- downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md
> $Subject
Fixes # partial https://github.com/ballerina-platform/ballerina-library/issues/7420
> [2201.11.0] Update OpenAPI changes for U11

- downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md
- This PR includes the changes to Ballerina U11 release notes by including the sub-command name change from `sanitize` to `align` in Ballerina OpenAPI tool.
> Modify 2201.11.0 release notes with changes of the openapi-tools

- swan-lake/development-tutorials/build-a-graalvm-executable/build-the-executable-in-a-container.md
> $Subject
> Fixes # https://github.com/ballerina-platform/ballerina-dev-website/issues/9629
GraalVM local build learn page is also changed with Java 21 changes - https://github.com/ballerina-platform/ballerina-dev-website/pull/9687
> Update the GraalVM cloud learn page with Java 21 changes

- components/vs-code-extension/code/Code.js
- components/vs-code-extension/code/vs-code-extension-bbe/try-the-services.md
> Fix styling issues in VSCode doc landing page

- swan-lake/development-tutorials/source-code-dependencies/style-guide/coding-conventions.md
Extra whitespaces at the end of line in code snippets leads to first few missing characters.
> Fixes #10078 
Localhost after the fix:
> Fix Character Display by Removing Unwanted Spaces

- swan-lake/development-tutorials/ballerina-persist/persist-client-api.md
> Resolves [#10096](https://github.com/ballerina-platform/ballerina-dev-website/issues/10096)  
> This change provides guidance on how to adjust the connection pool size within the `init()` method of `persist_client.bal` to mitigate or resolve 
Hikari Connection Pool errors that users might encounter when integrating Ballerina Persist with their projects.
> Add guidance for configuring Hikari Connection Pool in Ballerina Persist

- downloads/installation-options/installation-options.md
- pages/downloads/installation-options/index.js
- "Edit in Github" button in [Installation options](https://ballerina.io/downloads/installation-options/) page landing into [404 - page not found](https://github.com/ballerina-platform/ballerina-dev-website/blob/master/downloads/installation-options.md) on github.
- Changed `const id = "installation-options";` into `const id = "installation-options/installation-options"; ` in [pages/downloads/installation-options/index.js](https://github.com/ballerina-platform/ballerina-dev-website/blob/master/pages/downloads/installation-options/index.js) file.
Fixes issue in #10091 
- Added macOS Homebrew uninstallation instructions to installation-options.md file.
Added this Improvements in #10092
> Fix "Edit in GitHub" button and update uninstallation instructions
