ballerina-platform/ballerina-dev-website

_data/learnnavswanlake.yml
_data/toolingguidenavswanlake.yml
community.md
learn.md
learn/tooling-guide/vs-code-extension/installing-the-vs-code-extesnion.md
learn/user-guide/getting-started.md
learn/user-guide/getting-started/Installation-options.md
learn/user-guide/getting-started/setting-up-ballerina.md
learn/user-guide/getting-started/writing-your-first-ballerina-program.md
learn/user-guide/structuring-ballerina-code/structuring-ballerina-code.md

Update the Getting Started guide.
> Fixes #

Update the Getting Started Guide

---

download.html
learn.md

Fix the Learn links.
> Fixes #

Fix the Learn Links

---

learn/user-guide/coding-conventions/expressions.md

Update Syntax for Tables

---

learn/user-guide/coding-conventions/annotations_documentation_and_comments.md

Update Annotations Usage

---

learn/user-guide/coding-conventions/README.md

Update Coding Conventions Landing Page Syntax

---

learn-old.md
learn.md

Update the Language Guide PDF link.
> Fixes #

Update the Language Guide PDF Link

---

learn/user-guide/security/authentication-and-authorization.md
why-ballerina/the-network-in-the-language.md

$subject related to https://github.com/ballerina-platform/ballerina-dev-website/pull/1965

Fix bugs in security docs

---

_includes/nav.html
learn-old.md
learn.md
learn/language-guide/language-guide.md

Update the Lang Guide and Play option.
> Fixes #

Update the Lang Guide and Play Option

---

why-ballerina/from-code-to-cloud.md

Update c2c guides

---

learn/user-guide/network-communication/HTTP/http-clients/communication-resiliency.md
learn/user-guide/network-communication/HTTP/http-clients/data-binding.md
learn/user-guide/network-communication/HTTP/http-clients/data-streaming.md
learn/user-guide/network-communication/HTTP/http-clients/http-clients.md
learn/user-guide/network-communication/HTTP/http-clients/multipart-message-handling.md
learn/user-guide/network-communication/HTTP/http-clients/secure-communication.md

Update sample to new client changes

---

_includes/nav.html
learn/user-guide/getting-started/setting-up-ballerina.md

Fix the Ballerina logo and Play option.
> Fixes #

Fix the Ballerina Logo and Play Option

---

_data/toolingguidenavswanlake.yml
learn/tooling-guide/visual-studio-code-extension/language-intelligence.md

Fix URLs of Learn pages.
> Fixes #

Fix URLs of Learn Pages

---

learn/user-guide/getting-started/writing-your-first-ballerina-program.md

Update quick tour to new client changes

---

_data/swanlake-latest/metadata.json

Update metadata.json for alpha3 release

---

download.html

Update vsix link for alpha3

---

downloads/swan-lake-release-notes/swan-lake-alpha3/RELEASE_NOTE.md

This PR will add the release note for `swan-lake-alpha3`

Add release note for swan-lake-alpha3

---

downloads/swan-lake-release-notes/swan-lake-alpha3/RELEASE_NOTE.md

Format alpha3 release note

---

downloads/swan-lake-release-notes/swan-lake-alpha3/RELEASE_NOTE.md
learn/by-example/tcp-listener.html
learn/by-example/udp-listener.html
learn/user-guide/network-communication/HTTP/http-services/http-services.md

Fix the SLAlpha3 release note issues.
> Fixes #

Fix the SLAlpha3 Release Note Issues

---

downloads/swan-lake-release-notes/swan-lake-alpha3/RELEASE_NOTE.md

Fix alpha3 release note formating issues

---

learn/by-example/tcp-listener.html
learn/by-example/udp-listener.html
learn/tooling-guide/visual-studio-code-extension/installing-the-vs-code-extesnion.md
learn/user-guide/network-communication/HTTP/http-services/http-services.md

Fix more broken links post SLAlpha3.
> Fixes #

Fix More Broken Links Post SLAlpha3

---

learn/by-example/response-with-multiparts.html

Fix the comments of the multipart response BBE.
> Fixes #2066

Fix the Comments of the Multipart Response BBE

---

learn/tooling-guide/visual-studio-code-extension/run-and-debug/run-and-debug.md

Improve the "Run and Debug" Learn page.
> Fixes #

Improve the "Run and Debug" Learn Page

---

learn/user-guide/security/authentication-and-authorization.md

This PR updates authn/authz guide for SwanLake Alpha4

Update authn/authz guide for SwanLake Alpha4

---

_config.yml
robots.txt

Fix server artiacts

---

learn.md

Fix Learn sections being opened in new tabs.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/2007

Fix Learn Sections Being Opened in New Tabs

---

_data/swanlake-latest/metadata.json

Fix release title

---

learn/user-guide/observing-ballerina-code.md

Update observing ballerina code doc after opentelemetry migration

---

js/prism-ballerina.js

Update the "prism.js" file to highlight string templates.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/2038

Update the "prism.js" File to Highlight String Templates

---

downloads/swan-lake-release-notes/swan-lake-alpha4/RELEASE_NOTE.md

Fix the inconsistency issues in the SLAlpha4 Release Note.
> Fixes #

Fix the Inconsistency Issues in the SLAlpha4 Release Note

---

downloads/swan-lake-release-notes/swan-lake-alpha4/RELEASE_NOTE.md
learn/tooling-guide/visual-studio-code-extension/installing-the-vs-code-extesnion.md
learn/user-guide/documenting-ballerina-code.md

Fix broken links post SLAlpha4.
> Fixes #

Fix Broken Links Post SLAlpha4

---

learn/by-example/configurable.html

Update the Configurable BBE for SLAlpha4.
> Fixes #

Update the Configurable BBE for SLAlpha4

---

learn/by-example/testerina-mocking-objects.html

Update the Testerina Mocking Objects BBE.
> Fixes #

Update the Testerina Mocking Objects BBE

---

learn/user-guide/security/authentication-and-authorization.md

$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/584

Update authn/authz guide for Swan Lake Alpha5

---

_data/swanlake-latest/metadata.json

> Update swan lake alpha5 release

Update swan lake alpha5 release

---

learn/user-guide/publishing-modules-to-ballerina-central.md

> Address https://github.com/ballerina-platform/ballerina-dev-website/pull/2116#r619676826

Revert central url change

---

1.0/learn/by-example/awslambda-deployment.html

Fix the recursive redirection in the 1.0 AWS Lambda BBE.
> Fixes #

Fix the Recursive Redirection in the 1.0 AWS Lambda BBE

---

downloads/swan-lake-release-notes/swan-lake-alpha5/RELEASE_NOTE.md

Fix the SLAlpha5 release note issues.
> Fixes #

Fix the SLAlpha5 Release Note Issues

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-alpha5/RELEASE_NOTE.md

Update the SLAlpha5 Release Note

---

downloads/swan-lake-release-notes/swan-lake-alpha5/RELEASE_NOTE.md

Fix minor issues Post SLalpha5.
> Fixes #

Fix Minor Issues Post SLalpha5

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
why-ballerina/the-network-in-the-language.md

Update the VSIX artifact and sequence diagram.
> Fixes #

Update the VSIX Artifact and Sequence Diagram

---

learn/user-guide/deployment/aws-lambda.md

Review and improve the AWS Lambda Learn page.
> Fixes #

Review and Improve the AWS Lambda Learn Page

---

community.md

Mention the Ballerina GitHub Action on the "Community" page.
> Fixes #2060

Mention the Ballerina GitHub Action on the "Community" Page

---

learn/user-guide/observing-ballerina-code.md

Update BAL_CONFIG_FILES env variable
> Fixes #

Update BAL_CONFIG_FILES env variable

---

learn/user-guide/network-communication/gRPC/implementing-grpc-services-and-clients.md
learn/user-guide/network-communication/gRPC/performing-grpc-streaming.md

Fix formatting issues in the GRPC docs.
> Fixes #

Fix Formatting Issues in the GRPC Docs

---

learn/tooling-guide/visual-studio-code-extension/run-and-debug/run-and-debug.md

This PR will add working directory related information to debugger guide.
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/29480

Add working directory related information to debugger guide

---

learn/user-guide/network-communication/GraphQL/graphql.md
learn/user-guide/network-communication/GraphQL/implementing-graphql-services.md

Improve the GraphQL Learn pages.
> Fixes #

Improve the GraphQL Learn Pages

---

css/home-page-2020.css
css/home-page.css

Fix the alignment of Home page links.
> Fixes #

Fix the Alignment of Home Page Links

---

_includes/nav.html
community.md
events.md

Add Events to the Community Page.
> Fixes #189

Add Events to the Community Page

---

learn/user-guide/observing-ballerina-code.md

> Update the jaeger agent port to 55680

Update the jaeger agent port

---

_includes/nav.html

Add "Download" to the top menu.
> Fixes #

Add "Download" to the Top Menu

---

_includes/nav.html
index.html

Redesign the Home page for the SL Beta release.
> Fixes #

Redesign the Home Page for the SL Beta Release

---

_data/swanlake-latest/metadata.json

Update metadata for beta1 release

---

learn/user-guide/testing-ballerina-code/mocking.md

Update Testerina mocking guide
> Fixes #2053

Update testing-ballerina-code mocking guide

---

why-ballerina/from-code-to-cloud.md

- Update why ballerina code to cloud section 
- Add azure function description

Update why ballerina code to cloud section

---

index.html

Change the tagline on the Home page.
> Fixes #

Change the Tagline on the Home Page

---

_data/learnnavswanlake.yml
_data/toolingguidenavswanlake.yml
downloads/1.2.x-release-notes/release-note-1-2-13.md
downloads/archived.md
downloads/release-notes.md
learn/language-concepts/language-concepts.md

Fix a few issues with the breadcrumbs.
> Fixes #

Fix a Few Issues with the Breadcrumbs

---

learn/user-guide/getting-started/Installation-options.md

Update the "Building from Source" section of "Installation Options".
> Fixes #2198

Update the "Building from Source" Section of "Installation Options"

---

downloads/swan-lake-release-notes/swan-lake-beta1/RELEASE_NOTE.md

This PR will add debugger related release note for swan-lake-beta1.

Add debugger release note for swan-lake-beta1

---

css/home-page-2020.css
index.html

Fix the CSS issues on the Home page.
> Fixes #

Fix the CSS issues on the Home Page

---

index.html

Update the description of the "Graphical" "Why Ballerina" section.
> Fixes #

Update the description of the "Graphical" "Why Ballerina" Section

---

hbs/archived_list.hbs
js/download/archived_download.js
js/download/swan_lake_archived_download.js

Updated release notes link in the archived releases page

---

index.html

Fix language issues on the home page.
> Fixes #

Fix Language Issues on the Home Page

---

index.html
learn/user-guide/why-ballerina/reliable-and-maintainable.md

Add the "Reliable and Maintainable" "Why Ballerina" page.
> Fixes #

Add the "Reliable and Maintainable" "Why Ballerina" Page

---

_layouts/ballerina-example-page.html

Fix left menu

---

_data/bbenavswanlake.yml
_includes/bbe-nav-swanlake.html
_layouts/ballerina-left-nav-bbes-swanlake.html
learn/by-example/documentation.html
learn/by-example/hello-world-service.html

Add the new layout for the BBEs.
> Fixes #

Add the New Layout for the BBEs

---

index.html

Improve the alignment of the videos.
> Fixes #2236

Improve the Alignment of the Videos

---

css/home-page-2020.css
index.html

Fix the videos section on the Home page.
> Fixes #

Fix the Videos Section on the Home Page

---

_includes/ballerina-head.html
js/download/archived_download.js

Added release note links to 1.2.x archived list

---

learn/user-guide/structuring-ballerina-code/structuring-ballerina-code.md

Fix the command highlighting issue.
> Fixes #2174

Fix the Command Highlighting Issue

---

_data/bbenavswanlake.yml
learn/by-example/hello-world.html

Fix the links of the "Hello World" BBE.
> Fixes #

Fix the Links of the "Hello World" BBE

---

learn/user-guide/security/http-client-authentication.md
learn/user-guide/security/http-listener-authentication-and-authorization.md

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/584

Split authn/authz learn page into 2 pages

---

_data/learnnavswanlake.yml
learn/user-guide/why-ballerina/reliable-maintainable.md

Rename the "Reliable, Maintainable" "Why Ballerina" Page.
> Fixes #

Rename the "Reliable, Maintainable" "Why Ballerina" Page

---

learn/user-guide/network-communication/HTTP/http-clients/data-binding.md

Remove unwanted usage of targetType

---

_data/bbenavswanlake.yml
_data/learnnavswanlake.yml
index.html
learn.md
learn/language-concepts/language-concepts.md
learn/user-guide/getting-started/setting-up-ballerina.md
learn/user-guide/why-ballerina/cloud-native.md
learn/user-guide/why-ballerina/concurrent.md
learn/user-guide/why-ballerina/graphical.md

Update the language concepts video link.
> Fixes #

Update the Language Concepts Video Link

---

learn/user-guide/configurability/defining-configurable-variables.md
learn/user-guide/configurability/supplying-values-to-configurable-variables.md
learn/user-guide/configurability/trying-it-out.md

Fix configurability page issues

---

_data/bbenavswanlake.yml
learn/by-example/hello-world.html

Fix the Hello World BBE.
> Fixes #

Fix the Hello World BBE

---

index.html

Fix Website Issues

---

_data/learnnavswanlake.yml
learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
learn/user-guide/ballerina-packages/dependencies.md
learn/user-guide/ballerina-packages/modules.md
learn/user-guide/ballerina-packages/package-layout.md
learn/user-guide/ballerina-packages/sharing-a-library-package.md

> Fix issues in Ballerina Packages guide
> Fixes #2283

Fix issues in Ballerina Packages guide

---

_data/learnnavswanlake.yml
learn/user-guide/ballerina-packages/dependencies.md
learn/user-guide/ballerina-packages/package-layout.md
learn/user-guide/ballerina-packages/sharing-a-library-package.md
learn/user-guide/getting-started/writing-your-first-ballerina-program.md

> Remove "Running Ballerina Code" with refactoring and link fixes

Remove "Running Ballerina Code" with refactoring and link fixes

---

learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
learn/user-guide/getting-started/writing-your-first-ballerina-program.md

> Refactor Ballerina Packages guides

Refactor Ballerina Packages guides

---

community.md
index.html
learn/language-concepts/language-concepts.md

Fix the video links.
> Fixes #

Fix the Video Links

---

learn/tooling-guide/visual-studio-code-extension/run-and-debug/run-and-debug.md

This PR will fix the formatting issues in `Debugging` guide.

Fix formatting issues in `Debugging` guide 

---

learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
learn/user-guide/ballerina-packages/dependencies.md
learn/user-guide/ballerina-packages/modules.md
learn/user-guide/ballerina-packages/package-layout.md
learn/user-guide/ballerina-packages/sharing-a-library-package.md
learn/user-guide/getting-started/writing-your-first-ballerina-program.md

> Revert link changes
> Also
Fixes #2286
Fixes #2280
Fixes #2281

Revert link changes

---

_data/learnnavswanlake.yml

$subject related to https://github.com/ballerina-platform/ballerina-dev-website/pull/2272

Update left nave for security pages

---

_includes/nav.html
css/ballerina-io.css

Add Swanlake banner

---

1.2/learn/by-example/testerina-assertions.html
1.2/learn/by-example/testerina-before-and-after-each.html
1.2/learn/by-example/testerina-before-and-after-suite.html
1.2/learn/by-example/testerina-before-and-after-test.html
1.2/learn/by-example/testerina-data-driven-tests.html
1.2/learn/by-example/testerina-guarantee-test-execution-order.html
1.2/learn/by-example/testerina-mocking-functions.html
learn/user-guide/testing-ballerina-code/writing-tests.md

Update Mock BBE 1.2 broken links

---

learn/by-example/hello-world.html

Fix BBE Links

---

_data/learnnavswanlake.yml

> Fix cases of titles in left nav
> Fixes part of #2288

Fix cases of titles in left nav

---

_includes/nav.html

Fix the new tab opening of the top menu.
> Fixes #

Fix the New Tab Opening of the Top Menu

---

learn/user-guide/running-ballerina-code.md
learn/user-guide/why-ballerina/cloud-native.md
learn/user-guide/why-ballerina/graphical.md

Fix broken links and breadcrumbs.
> Fixes #

Fix Broken Links and Breadcrumbs

---

learn/tooling-guide/visual-studio-code-extension/configurations.md
learn/tooling-guide/visual-studio-code-extension/language-support.md
learn/tooling-guide/visual-studio-code-extension/quick-start.md
learn/tooling-guide/visual-studio-code-extension/run-and-debug/run-and-debug.md
learn/tooling-guide/visual-studio-code-extension/vs-code-commands.md

Fix tooling guide pages

---

css/bbe-page.css

Fix the scroll bar of the BBE layout to stop the disappearance of it and keep it fixed.
> Fixes #

Fix the Scroll Bar of the BBE Layout

---

learn/user-guide/getting-started/setting-up-ballerina.md
spec/lang/2021R1/index.html
spec/lang/2021R1/style/ballerina-language-specification.css
spec/lang/2021R1/style/ballerina-language-specification.js

Add the v2021R1 spec.
> Fixes #

Add the v2021R1 Spec

---

learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md

> Changed `bal new` project name and the `tree .` output.
> Fixes #

Change `bal new` project name and the `tree .` output

---

_data/bbenavswanlake.yml
download.html
learn/tooling-guide/visual-studio-code-extension/quick-start.md

Fix Broken BBEs

---

learn/user-guide/ballerina-packages/creating-your-first-ballerina-package.md
learn/user-guide/interoperability/calling-java-code-from-ballerina.md

Fix more formatting issues in Learn pages.
> Fixes #

Fix More Formatting Issues in Learn Pages

---

learn/user-guide/ballerina-packages/modules.md
learn/user-guide/ballerina-packages/sharing-a-library-package.md

> Fix formatting in Ballerina Packages pages

Fix formatting in Ballerina Packages pages

---

.github/workflows/publish_vscode_plugin.yml

> Remove publishing vscode plugin during prod sync

Remove publishing vscode plugin during prod sync

---

learn/user-guide/testing-ballerina-code/writing-tests.md

Move assertion functions to a table.

Add assertion functions to a table

---

_data/bbenavswanlake.yml
_data/toolingguidenavswanlake.yml
_includes/bbe-nav-swanlake.html

Revert the BBE YAML and HTML files.
> Fixes #

Revert the BBE YAML and HTML Files

---

_includes/left-nav-release-notes.html
_includes/left-nav-swanlake.html
_includes/left-nav-tooling-guide-swan-lake.html
_layouts/ballerina-example-page.html
_layouts/ballerina-left-nav-pages-swanlake.html
_layouts/ballerina-left-nav-release-notes.html
_layouts/ballerina-tooling-guide-left-nav-pages-swanlake.html
css/ballerina-io-learn-v2.css
css/ballerina-io.css

> Add style for Left Nav Bar and Main Top Nav Bar for sticky when it scroll for Ballerina By Example, User Guide, Tooling Guide , Release Notes Pages
> Add styles for Left Nav Bar scroll.

Fix left navbar and main navbar when scrolling.

---

_data/learnnavswanlake.yml
_includes/left-nav-swanlake.html
_includes/left-nav-tooling-guide-swan-lake.html
css/ballerina-io-learn-v2.css
js/ballerina-leftnav.js

>  Add second level navigation and collapsing ability for left navigation to User Guide page and Tooling guide page

Add second level navigation and collapsing ability for left navigation

---

_includes/nav.html

> Report issue button added and styled.

Add "Report Issue" button

---

.github/workflows/update_ballerina_by_example_on_demand.yml

Fix distribution path

---

.github/workflows/update_ballerina_by_example_on_demand.yml

Fix repo path

---

.github/workflows/update_ballerina_by_example_on_demand.yml

> Include all-bbes json to commit

Include all-bbes json to commit

---

_data/learnnavswanlake.yml
learn/user-guide/network-communication/gRPC/defining-the-service-interface.md
learn/user-guide/network-communication/gRPC/implementing-grpc-services-and-clients/implementing-grpc-clients.md
learn/user-guide/network-communication/gRPC/implementing-grpc-services-and-clients/implementing-grpc-services.md

Change the structure of the gRPC Learn section.
> Fixes #

Change the Structure of the gRPC Learn Section

---

.github/workflows/update_ballerina_by_example_master.yml
.github/workflows/update_ballerina_by_example_on_demand.yml

> Include a workflow for master bbe generation

Include a workflow for master bbe generation

---

.github/workflows/update_ballerina_by_example_master.yml

> Remove distribution downloading steps

Remove distribution downloading steps

---

.github/workflows/update_ballerina_by_example_master.yml

 Fix _data directory path 

---

_includes/left-nav-swanlake.html
css/ballerina-io-learn-v2.css
js/ballerina-leftnav.js

> Add third level dropdown menu and fourth level navigation

Add Fourth Level Navigation to Left Navigation Bar

---

learn/user-guide/getting-started/building-from-source.md

Improve the "Building From Source" page content.
> Fixes #2405

Improve the "Building From Source" Page Content

---

css/ballerina-io-docs.css
css/download-page.css
learn/user-guide/getting-started/setting-up-ballerina.md

> Fix hyperlink highlight issue and download button styles
> Fixes #1760
> Fixes #2387

Fix Hyperlinks and Download Button styles

---

1.2/learn/by-example/index.html
learn.md
learn/user-guide/getting-started/setting-up-ballerina.md
learn/user-guide/why-ballerina/cloud-native.md

Update the User Guide link and add BBE Intro Page redirections
> Fixes #

Update the User Guide Link and Add the BBE Intro Page Redirections

---

css/ballerina-io-learn-v2.css
img/down-arrow-learn.svg
img/up-arrow-learn.svg

> Fix left navbar icon had difference size and TOC text has different margin in between icon and text
> Fixes #2388
> Fixes #2426

Fix Left Navbar Dropdown Icon Size and TOC margin issue

---

_layouts/ballerina-inner-page.html
css/events-page.css

> Fix following issues
> Fixes #2456
> Fixes #2458

Fix More Info Buttons Styles GitHub Icon Alignment

---

_includes/nav.html
_layouts/ballerina-learn-landing-page.html
documentation.md

Redesign the Learn landing page.
> Fixes #

Redesign the Learn Landing Page

---

community.md
css/ballerina-io-docs.css
learn/tooling-guide/visual-studio-code-extension/vs-code-commands.md

Improve the description of the Paste JSON VS Code command and fix some style issues on the Community page.
> Fixes #

Improve the Description of the Paste JSON VS Code Command

---

_data/stable-latest/metadata.json
downloads/1.2.x-release-notes/1.2.14.md

> Include 1.2.14 release contents

Include 1.2.14 release contents

---

_data/swanlake-latest/metadata.json

Update SL metadata json to beta2

---

_data/releasenotes.yml
download.html
downloads/1.2.x-release-notes/1.2.10.md
downloads/1.2.x-release-notes/1.2.13.md
downloads/1.2.x-release-notes/1.2.14.md
downloads/1.2.x-release-notes/1.2.6.md

Add the 1.2.14 release note.
> Fixes #

Add the 1.2.14 Release Note

---

downloads/1.2.x-release-notes/1.2.14.md
downloads/stable-release-notes/1.2.14/RELEASE_NOTE.md

Include CVE

---

learn/tooling-guide/visual-studio-code-extension/diagram-editor.md
learn/tooling-guide/visual-studio-code-extension/quick-start.md
learn/tooling-guide/visual-studio-code-extension/vs-code-commands.md

Related issue: https://github.com/wso2/ballerina-plugin-vscode/issues/49

Update VS Code document command's label

---

_data/learnnavswanlake.yml
_data/whyballerinanavswanlake.yml
_includes/left-nav-why-ballerina-swan-lake.html
_layouts/ballerina-why-ballerina-left-nav-pages-swanlake.html
index.html
learn/user-guide/why-ballerina/cloud-native.md
learn/user-guide/why-ballerina/concurrent.md
learn/user-guide/why-ballerina/data-oriented.md
learn/user-guide/why-ballerina/flexibly-typed.md
learn/user-guide/why-ballerina/graphical.md
learn/user-guide/why-ballerina/reliable-maintainable.md

Restructure the "Why Ballerina" section.
> Fixes #

Restructure the "Why Ballerina" Section

---

learn/user-guide/interoperability/calling-java-code-from-ballerina.md

Update the Java interoperability learn guide with the default bindings mapping approach in the bindgen tool.
Related Issue: https://github.com/ballerina-platform/ballerina-lang/issues/30882

Update the Java interoperability learn guide

---

_config.yml
_includes/bbe-nav-swanlake.html
_layouts/ballerina-example-page.html
css/ballerina-io-docs.css
js/philosophy.js

> Filter Only the Required BBEs on the Learn By Example View by adding parameter for the URL
> Fixes #2516

Filter Only the Required BBEs on the Learn By Example View

---

_includes/bbe-nav-swanlake.html
home.html
index.html
learn-old.md
learn.md
learn/bbe-introduction.md
learn/by-example/index.html
license-of-site.md

Add Reference By Examples.
> Fixes #

Add Reference By Examples

---

_config.yml

Revert the config YML file change.
> Fixes #

Revert the Config YML File Change

---

download.html

> Fix Layout by Adding Closing Tags
> Fixes #2483

Fix Layout by Adding Closing Tags

---

css/ballerina-io.css

> Fix Tabbed Line Numbers Issue
> Fixes #1745

Fix Tabbed Line Numbers Issue

---

css/ballerina-io.css

>Fix for Line Numbers for Nested list tags
> Fixes #1745

Fix for Line Numbers for Nested list tags

---

_includes/toc.html
css/ballerina-io-bbe.css
css/ballerina-io-learn-v2.css

> Fix TOC back-tic issue
> Fixes #2429

Fix TOC back-tic issue

---

css/ballerina-central-api.css
css/ballerina-io-apidocs-2020.css
css/ballerina-io-docs.css
css/ballerina-io.css
css/download-page.css
css/home-page.css

> Change Font Size for Tags
H1 -> 38px
H2 -> 32 px
H3 -> 28px
H4 -> 22 px
H5 -> 20px
H6 -> 18px
P -> 16px

Change Font Size for Tags

---

css/ballerina-io.css

> Add Styles ffor Remove Unwanted Numbers
> Fixes #1745

Add Styles for Remove Unwanted Numbers

---

1.0/learn/by-example/index.html
1.1/learn/by-example/index.html
1.2/learn/by-example/index.html
_includes/bbe-nav-swanlake.html
learn-beta2-column.md
learn/bbe-introduction.md

Update the new Learn column layout.
> Fixes #

Update the New Learn Column Layout

---

_layouts/ballerina-example-page.html

> Hide Next Prev Buttons
> Fixes #2548

Hide Next Prev Buttons

---

learn-beta2-column.md

Recreate Learn Page Layout

---

_layouts/ballerina-example-page-old.html
_layouts/ballerina-example-page.html

>Hide Version Selector from V1.2

Hide Version Selector from V1.2

---

.github/workflows/update_ballerina_by_example.yml
community/branding.md

Update 1.2 BBE workflow and improve branding page.
> Fixes #

Update 1.2 BBE workflow and improve branding page

---

_includes/ballerina-footer.html
community.md
trademark-usage-policy.md

Add the trademark policy links.
> Fixes #

Add the trademark policy links

---

js/redirections.js

Add the redirection for 1.2 BBEs.
> Fixes #

Add the Redirection for 1.2 BBEs

---

learn/user-guide/deployment/code-to-cloud/code-to-cloud.md

- Add c2c settings description. 
- Resolves https://github.com/ballerina-platform/module-ballerina-c2c/issues/276

Add c2c settings description

---

trademark-usage-policy.md

Update content of trademark policy
Fixes #

Update content of trademark policy

---

learn.md

Fix the API Docs URL

---

.github/workflows/prod_sync_artifacts.yml

Add workflow dispatch to 1.2.x artifact sync workflow

---

index.html

> Revert Image to previous one

Revert Image to previous one

---

trademark-usage-policy.md

Made small change on paragraph

Update content of trademark policy paragraph space

---

learn/user-guide/deployment/code-to-cloud/code-to-cloud.md

> Add config file support details
> https://github.com/ballerina-platform/module-ballerina-c2c/issues/209

Add config file support details

---

_includes/ballerina-head.html
_includes/ballerina-home-head.html

> Fix twitter Meta Tags Inner Pages

Fix twitter Meta Tags Inner Pages

---

_includes/ballerina-head.html
_includes/ballerina-home-head.html
community.md

> Add Meta Tags and Description

Add Meta Tags and Description

---

_includes/ballerina-head.html

>  Add Meta Description
> Fixes #2381

Add Meta Description

---

css/abixTreeList.css
css/ballerina-io-learn-v2.css

> Add TOC Styles
> Fixes #2388

Add TOC Styles

---

learn/by-example/index.html

> Add p tag to Fix UI issue
> Fixes #2608

Add p tag to Fix UI issue

---

_includes/algolia.html

> Remove search fields that doesn't have title
> Fixes #2633

Remove Search Fields That Doesn't Have Title

---

css/abixTreeList.css

> Fix Collapse Icons Styles
> Fixes #2631

Fix Collapse Icons Styles

---

community.md
community/newsletter.md
community/newsletter/2021-2.md

> Add Ballerina Newsletter 2021 Issue #2
> Fixes #2637

Add Ballerina Newsletter 2021 Issue #2

---

_layouts/ballerina-left-nav-release-notes.html

> Add the Pilcrow Sign to the Page Titles of the Release Notes
> Fixes #2632

Add the Pilcrow Sign to the Page Titles of the Release Notes

---

community/newsletter/2021-2.md

Remove Unwanted Content

---

community/newsletter/2021-2.md
css/ballerina-io-docs.css

> Fix Spaces and Style Issues Links
> Fixes #2642

Fix Spaces and Style Issues Links

---

community/newsletter/2021-2.md
css/ballerina-io-docs.css

Fix Styles Colors

---

community/newsletter.md

> Remove Latest Newsletter Link On Past Issues

Remove Latest Newsletter Link On Past Issues

---

_config.yml
_includes/algolia.html

Update Algolia Search

---

downloads/1.2.x-release-notes/1.2.15.md
downloads/1.2.x-release-notes/1.2.16.md

Add release note for 1.2.16

---

_data/stable-latest/metadata.json

Update metata.json for 1.2.16 release

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.16.md

Add the 1.2.16 release note.
> Fixes #

Add the 1.2.16 Release Note

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.16.md
downloads/1.2.x-release-notes/1.2.17.md

Update the Release Notes for 1.2.17 Release

---

_config.yml

Add new config

---

.github/workflows/sw_update_ballerina_by_example.yml
.github/workflows/sw_update_release__note_versions.yml
.github/workflows/update_ballerina_by_example_master.yml
.github/workflows/update_ballerina_by_example_on_demand.yml

> Switch generations from master to dev

Switch generations from master to dev

---

_includes/nav.html

> Add banner massage when javascript is turn off
> Fixes #84

Add Banner Massage When Javascript is Turn Off

---

_includes/nav.html
css/abixTreeList.css
css/ballerina-io-learn-v2.css

> Fix learn page alignment and TOC issue
> Fixes #2702
> Fixes #2704

Fix Learn Page Alignment and TOC Issue

---

_data/stable-latest/metadata.json

Update metata.json for 1.2.18 release

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.17.md
downloads/1.2.x-release-notes/1.2.18.md

Add the 1.2.18 release note.
> Fixes #

Add the 1.2.18 Release Note

---

_includes/algolia-open-source.html
_includes/nav.html

> Add Algolia Open-source
> Fixes #2698

Add Algolia Open-source

---

community-old.md
community.html

Add the new community page.
> Fixes #

Add the New Community Page

---

community-old-1.html

> Change the permalink community old
> Fixes #

change permalink of community old

---

community.html
learn.md

Fix typos in the new Learn page.
> Fixes #

Fix Typos in the New Learn Page

---

community.html
css/community-page-new.css

Improve the new Community page.
> Fixes #

Improve the New Community Page

---

community.html
css/community-page-new.css

> Hover effect fixing
> Fixes #

Hover effect fix

---

community-old.md
community.html

> Change the community page URL
> Fixes #

Change community page URL

---

learn/other/security/http-client-authentication.md
learn/other/security/http-listener-authentication-and-authorization.md

$subject related to https://github.com/ballerina-platform/ballerina-dev-website/pull/2771

Remove Swan Lake Beta3 specific updates

---

learn/getting-started/installing-ballerina/setting-up-ballerina.md
learn/guides/testing-ballerina-code/testing-services-and-clients.md

Update the hypertext on the "Setting up Ballerina" page.
> Fixes #2733

Update the Hypertext on the "Setting up Ballerina" page

---

learn/other/security/http-client-authentication.md

$subject related to https://github.com/ballerina-platform/ballerina-dev-website/pull/2782

Fix a documentation issue

---

community.html

Update the "Publish to Central" section of the Community page.
> Fixes #2739

Update the "Publish to Central" Section of the Community Page

---

_includes/ballerina-footer.html
community.html

Fix the report issues links on the Community page in the `dev` branch.
> Fixes #

Fix the Report Issues Links on the Community Page in the Dev Branch

---

community.html

Community page final revamp

---

community.html

Change on map

---

community.html

New Changes on Map

---

community.html
js/ballerina-common.js

> URL validations
>Hiding the forms after submitting
>Adding a text area 
> Fixes #

Validation and form improvements

---

.github/workflows/add_link_checker.yml

Change the base URL property of the link checker.
> Fixes #

Change the Base URL Property of the Link Checker

---

_layouts/ballerina-learn-landing-page.html
community.html

Block the Google indexing of the new community page.
> Fixes #2810

Block the Google Indexing of the New Community Page

---

community.html

Add dummy upcoming events data to the new Community page for review purposes.
> Fixes #

Add Dummy Upcoming Events to the New Community Page

---

community.html

Add community page new version

---

community.html
css/community-page-new.css

Activate tabs function in events

---

_includes/bbe-nav-swanlake.html
_layouts/ballerina-example-page.html
learn/getting-started/learn-by-examples/bbe-introduction.md

Remove testing-related BBEs from the LBE view.
> Fixes #2813 #2715 #2829 #2814

Remove Testing-Related BBEs from the LBE View

---

.github/workflows/update_ballerina_by_example_master.yml

Fix switching branch to dev

---

_data/guidesnavswanlake.yml
_includes/left-nav-guides-swan-lake.html

Fix the Lear left nav issue.
> Fixes #2845

Fix the Learn Left Nav Issue

---

_data/guidesnavswanlake.yml
_data/visualstudiocodeextensionnavswanlake.yml
learn/getting-started/visual-studio-code-extension/vs-code-quick-start.md
learn/guides/making-ballerina-programs-configurable/trying-out-configurability.md
learn/guides/running-ballerina-programs-in-the-cloud/code-to-cloud/code-to-cloud-deployment.md
learn/guides/running-ballerina-programs-in-the-cloud/code-to-cloud/code-to-cloud-samples.md
learn/guides/testing-ballerina-code/executing-tests.md
learn/guides/testing-ballerina-code/mocking.md
learn/guides/testing-ballerina-code/quick-start-on-testing.md
learn/guides/testing-ballerina-code/writing-tests.md

Check and fix all learn page redirections.
> Fixes #

Check and Fix all Learn Page Redirections

---

_layouts/ballerina-hello-world-left-nav-pages-swanlake.html
_layouts/ballerina-inner-page.html
_layouts/ballerina-installing-ballerina-left-nav-pages-swanlake.html
_layouts/ballerina-left-nav-pages-swanlake.html
_layouts/ballerina-style-guide-left-nav-pages-swanlake.html
_layouts/ballerina-tooling-guide-left-nav-pages-swanlake.html
_layouts/ballerina-visual-studio-code-extension-left-nav-pages-swanlake.html
_layouts/ballerina-why-ballerina-left-nav-pages-swanlake.html

Fix the pilcrow sign and the title highlighting issue of the page TOC.
> Fixes #2859

Fix the Pilcrow Sign and Page TOC Title Highlighting Issue

---

learn/guides/organizing-ballerina-code/package-layout.md

Fix an incorrect link in the "Organizing Ballerina Code" page.
> Fixes #2867

Fix an Incorrect Link in the "Organizing Ballerina Code" Page

---

css/ballerina-io-docs.css

> Update ballerina-io-docs.css for release notes 
> Fixes #

Update css for release note

---

css/ballerina-io-docs.css
downloads/swan-lake-release-notes/swan-lake-beta1/RELEASE_NOTE.md

update css for li items

---

.github/workflows/update_ballerina_by_example_master.yml

Remove extra checkout

---

_includes/nav.html

Update the website top banner for SLBeta3.
> Fixes #

Update the Website Top Banner for SLBeta3

---

learn-new.md

Ädd new learn page design -tab version

---

learn/getting-started/installing-ballerina/setting-up-ballerina.md

Update the `bal` commands on the installing page.
> Fixes #

Update the `bal` Commands on the Installing Page

---

learn.md

> I added new learn page design
> Fixes #

Add new learn single page layout

---

_layouts/ballerina-example-page.html

Remove the breadcrumbs from the LBE view.
> Fixes #2939

Remove the Breadcrumbs from the LBE View

---

css/ballerina-io-learn-v2.css
js/ballerina-leftnav.js

> Highlight Anchored Links in the Left Nav TOCs of the Learn Pages

Highlight selected topic in left nav

---

_layouts/ballerina-left-nav-release-notes.html
css/ballerina-io-learn-v2.css
css/ballerina-io-release-note.css

> Removed TOC from Learn page layout by adding code to the ballerina-io-learn-v2.css file.
> Fixes #2811

Remove toc from the learn pages

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.19.md
downloads/1.2.x-release-notes/1.2.20.md

Create the 1.2.20 release note.
> Fixes #

Create the 1.2.20 Release Note

---

README.md

Update the Jekyll build instructions with troubleshooting tips.
> Fixes #

Update the Jekyll Build Instructions with Troubleshooting Tips

---

learn/guides/calling-java-code-from-ballerina-and-vice-versa.md

Test the prod sync build.
> Fixes #

Test the Prod Sync Build

---

CNAME
_config.yml
robots.txt

Revert changes to cname, robots.txt and _config.yml in prod-sync

---

community/newsletter/2021-5.md

Update newsletter page

---

community/newsletter.md

Update past issues on the newsletter.md 

---

community/newsletter.md

Past Issue page - Update

---

.github/workflows/prod_sync.yml

Add --no-rebase to prod sync workflow

---

learn/guides/calling-java-code-from-ballerina-and-vice-versa.md

Test prod sync post workflow update.
> Fixes #

Test Prod Sync Post Workflow Update

---

learn/guides/calling-java-code-from-ballerina-and-vice-versa.md

Fix a Minor Typo

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.20.md
downloads/1.2.x-release-notes/1.2.21.md

Add the 1.2.21 release note.
> Fixes #

Add the 1.2.21 Release Note

---

_config.yml

Exclude old versions from the sitemap.
> Fixes #

Exclude Old Versions From the Sitemap

---

learn.md

> Add new learn two column layout
> Fixes #

Add new two column learn  layout

---

community/newsletter/2021-4.md

Edited formatting error

---

_config.yml
learn/by-example/azure-functions-deployment.html

Test if a time-out occurs in the pre-prod build.
> Fixes #

Test if a Time Out Occurs in the Pre Prod Build

---

_config.yml
learn/by-example/azure-functions-deployment.html

Revert pre-prod build test.
> Fixes #

Revert the Pre Prod Build Test

---

_data/ballerinashellswanlake.yml
_data/callingjavacodeswanlake.yml
_data/generatingcodedocswanlake.yml
_data/managingdependenciesswanlake.yml
_data/platformspecificationsswanlake.yml
_data/publishingtocentralswanlake.yml
_includes/left-nav-ballerina-shell-swan-lake.html
_includes/left-nav-calling-java-code-swan-lake.html
_includes/left-nav-generating-doc-swan-lake.html
_includes/left-nav-managing-dependencies-swan-lake.html
_includes/left-nav-platform-specifications-swan-lake.html
_includes/left-nav-publishing-to-central-swan-lake.html
_layouts/ballerina-ballerina-shell-left-nav-pages-swanlake.html
_layouts/ballerina-calling-java-code-left-nav-pages-swanlake.html
_layouts/ballerina-generating-doc-left-nav-pages-swanlake.html
_layouts/ballerina-managing-dependencies-left-nav-pages-swanlake.html
_layouts/ballerina-platform-specifications-left-nav-pages-swanlake.html
_layouts/ballerina-publishing-to-central-left-nav-pages-swanlake.html
learn/getting-started/ballerina-shell.md
learn/guides/calling-java-code-from-ballerina-and-vice-versa.md
learn/guides/generating-code-documentation/generating-code-documentation.md
learn/guides/managing-dependencies.md
learn/guides/publishing-packages-to-ballerina-central.md
spec/spec.md

Create left navigations for guides without sub pages.
> Fixes #3010

Create Left Navs for Guides Without Sub Pages

---

download.html
learn/getting-started/installing-ballerina/Installation-options.md

Add installation verification instructions.
> Fixes #3085

Add Installation Verification Instructions

---

_includes/nav.html

Update the B.io banner for SLBeta4.
> Fixes #

Update the B.io Banner for SLBeta4

---

downloads/swan-lake-release-notes/swan-lake-beta4/RELEASE_NOTE.md

Update the SLBeta4 release note.
> Fixes #

Update the SLBeta4 Release Note

---

downloads/swan-lake-release-notes/swan-lake-beta4/RELEASE_NOTE.md

Add `Changes` section

---

learn/getting-started/visual-studio-code-extension/vs-code-quick-start.md

Add the tools and IDEs redirection.
> Fixes #3121

Add the Tools and IDEs Redirection

---

_includes/ballerina-footer.html

> Fix report issues pop up styling
> Fixes #3115

Fix report issues

---

js/ballerina-common.js

Updated the subscription form validation

---

_data/languageguidenavswanlake.yml
_includes/left-nav-language-guide-swan-lake.html
_layouts/ballerina-language-guid-left-nav-pages-swanlake.html
learn.md
learn/getting-started/language-walkthrough/language-walkthrough.md
learn/guides/language-guide/completing-the-picture
learn/guides/language-guide/concurrency-and-transactions
learn/guides/language-guide/how-ballerina-does-what-all-programming-languages-do
learn/guides/language-guide/query-tables-and-xml
learn/guides/language-guide/what-makes-ballerina-distinctive

Create the Language Guide.
> Fixes #

Create the Language Guide

---

_data/languageguidenavswanlake.yml
learn.md
learn/guides/language-guide/advanced-general-purpose-language-features.md
learn/guides/language-guide/concurrency.md
learn/guides/language-guide/data.md
learn/guides/language-guide/network-interaction.md

Update the "Language Guide" pages.
> Fixes #

Update the "Language Guide" Pages

---

_includes/ballerina-footer.html
community.md

Add the VS Code "REPORT ISSUES" link.
> Fixes #3145

Add the VS Code "REPORT ISSUES" link

---

404.html

Bulk redirection for 1.1 and 1.0 broken learn pages

---

_data/swanlake-latest/metadata.json

Update metadata for SLBeta5 release

---

_includes/nav.html

Update the B.io banner for SLBeta5c.
> Fixes #

Update the B.io Banner for SLBeta5

---

_layouts/ballerina-installing-ballerina-left-nav-pages-swanlake.html
_layouts/ballerina-observing-programs-left-nav-pages-swanlake.html
_layouts/ballerina-organizing-code-left-nav-pages-swanlake.html
css/ballerina-io-learn-v2.css
js/right-toc.js
learn/getting-started/installing-ballerina/Installation-options.md
learn/guides/observing-ballerina-programs/observing-your-application-with-choreo.md
learn/guides/observing-ballerina-programs/observing-your-application-with-prometheus-grafana-and-jaeger.md
learn/guides/organizing-ballerina-code/modules.md

Add right side toc for learn pages

---

_data/stable-latest/metadata.json

Update metadata.json with 1.2.22

---

1.2/learn/api-docs/ballerina/observe/index.html
downloads/1.2.x-release-notes/1.2.0.md

Fix broken links post SLBeta5.
> Fixes #

Fix Broken Links Post SLBeta5

---

_layouts/ballerina-language-guide-left-nav-pages-swanlake.html
learn/guides/distinctive-language-features/advanced-general-purpose-language-features.md

Fix the table and pilcrow signs.
> Fixes #

Fix the Table and Pilcrow Signs

---

learn/getting-started/installing-ballerina/setting-up-ballerina.md

Add the version drop down on the "Setting up Ballerina" page.
> Fixes #3151

Add the Version Drop Down on the "Setting up Ballerina" Page

---

_includes/ballerina-footer.html
community.md

Update the "Report Issues" links.
> Fixes #3148

Update the "Report Issues" Links

---

learn/why-ballerina/cloud-native.md
learn/why-ballerina/concurrent.md
learn/why-ballerina/data-oriented.md
learn/why-ballerina/flexibly-typed.md
learn/why-ballerina/graphical.md
learn/why-ballerina/reliable-maintainable.md

Update the layout of the "Why Ballerina" pages.
> Fixes #

Update the Layout of the "Why Ballerina" Pages

---

learn.md

Update the Learn page with the Lang Guide links.
> Fixes #

Update the Learn Page with the Lang Guide Links

---

learn.md

Update the Learn page.
> Fixes #

Update the Learn Page

---

learn.md

Update the BBE link on the Learn page.
> Fixes #

Update the BBE Link on the Learn Page

---

_data/releasenotes.yml
downloads/swan-lake-release-notes/swan-lake-beta5/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-beta6/RELEASE_NOTE.md

Add the SLBeta6 release note.
> Fixes #

Add the SLBeta6 Release Note

---

downloads/swan-lake-release-notes/swan-lake-beta6/RELEASE_NOTE.md

Add GraphQL context.set function to release note

---

_includes/nav.html

Update the banner for SLBeta6.
> Fixes #

Update the banner for SLBeta6

---

css/ballerina-io-learn-v2.css
js/ballerina-leftnav.js

> Fix scroll left nav not working issue and alignment issue
> Fixes #3246

Fix scroll issue in chrome browser

---

downloads/1.2.x-release-notes/1.2.0.md
learn/slides/language-walkthrough/language-walkthrough.md

Fix broken links post SLBeta6.
> Fixes #

Fix Broken Links Post SLBeta6

---

community-new.html
tech-talk.html

> Added checkbox for pop up forms for declaration
> Fixes #

Form fixes

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.22.md
downloads/1.2.x-release-notes/1.2.23.md

Create the 1.2.23 release note.
> Fixes #

Create the 1.2.23 Release Note

---

_data/stable-latest/metadata.json

Update metadata.json with 1.2.23

---

learn/references/cli-documentation/openapi.md

Fix the committed conflict on the OpenAPI page.
> Fixes #

Fix the Committed Conflict on the OpenAPI Page

---

css/home-page-2020.css
img/play-button-hover.svg
img/play=button.svg
index.html

> Added tab design to try ballerina section
> Fixes #3088

Add tab view of try ballerina

---

_data/stable-latest/metadata.json
_data/swanlake-latest/metadata.json

Update the 1.2.23 release date.
> Fixes #

Update the 1.2.23 Release Date

---

community-new.html
events.html
js/ballerina-common.js
resources.html
tech-talk.html

Add updates to the new community page

---

learn/getting-started/language-basics.md

Fix issue in code syntax of language guide

---

security-policy.md

Update the "Security Advisories" Section in the master branch.
> Fixes #

Update the "Security Advisories" Section in the Master Branch

---

_includes/ballerina-footer.html
community-new.html
events.html
resources.html
tech-talk.html

> Did the changes mentioned in the bugs doc related to the new community page
> Fixes #

Add UI changes to the community page

---

community-new.html
events.html
resources.html
tech-talk.html

Add changes to community page

---

community-new.html
js/ballerina-common.js

> Fixed the slack form issues and updated the status messages
> Fixes #

Updated the slack form

---

index.html

> Add events section for home page
> Fixes #

Add events section for home page

---

_includes/nav.html
css/ballerina-io.css

Add styles for old learn page version banner

---

learn/why-ballerina/cloud-native.md

Update cloud-native.md for Swan Lake GA

---

learn/why-ballerina/concurrent.md
learn/why-ballerina/reliable-maintainable.md
security-policy.md

Master to Dev Sync

---

_data/observingprogramsswanlake.yml
learn/guides/observing-ballerina-programs/observing-your-application-with-prometheus-grafana-and-jaeger.md
learn/guides/observing-ballerina-programs/observing-your-application-with-prometheus-grafana-jaeger-and-elastic-the-stack.md

Improve doc on Observing Your Application with Prometheus, Grafana, and Jaeger

---

learn/getting-started/hello-world/writing-your-first-ballerina-program.md

Update the bash output when the Hello World service is run.
> Fixes #3270

Update the Bash Output when the Hello World Service is Run

---

learn/guides/observing-ballerina-programs/observing-your-application-with-choreo.md

Improve 'Observing Your Application with Choreo'

---

learn/why-ballerina/reliable-maintainable.md

Update reliable-maintainable.md for Swan Lake GA

---

learn/why-ballerina/data-oriented.md

Update data-oriented.md for Swan Lake GA

---

community-new.html
js/ballerina-common.js
resources.html
tech-talk.html

> Add community page corrections
> Fixes #

Add community page corrections

---

learn/why-ballerina/concurrent.md

Update concurrent.md for Swan Lake GA

---

events.html
resources.html

> Fix issues on events and resources pages
> Fixes #

Bug fix on events resources

---

community-new.html
events.html
index.html
resources.html
tech-talk.html

Add fixes for test round 2

---

community-new.html
index.html
tech-talk.html

Add changes for test round 2 -2

---

_data/ballerinashellswanlake.yml
learn/guides/ballerina-shell.md

Refactor Ballerina Shell learn page

Refactor Ballerina Shell learn page

---

community-new.html
events.html
index.html
resources.html
tech-talk.html

> Fixes #3387
> Fixes #3386 
> Fixes #3384

Bug fix in community page

---

community-new.html
js/ballerina-common.js
resources.html

Add upcoming event banner

---

_data/ballerinaopenapisupportswanlake.yml
_data/clidocumentationnavswanlake.yml
_includes/left-nav-openapi-support-swan-lake.html
_layouts/ballerina-openapi-support-left-nav-pages-swanlake.html
learn.md
learn/guides/ballerina-openapi-support.md
learn/references/cli-documentation/openapi.md

> $subject
> Fixes #https://github.com/ballerina-platform/openapi-tools/issues/804
https://docs.google.com/document/d/1kD5Z7QcwsEObZCL9FBugYByfMh0lgl6EeuryNq7gkjs/edit#
https://docs.google.com/document/d/1-oaKxC0qcDE4_klIiYlLHs24E_pmoVsnQseQIKlM_T0/edit#

Refactor OpenAPI learn page

---

_data/stable-latest/metadata.json

Update metadata.json for 1.2.24 release

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.24.md

Add the 1.2.24 release note.
> Fixes #

Add the 1.2.24 Release Note

---

learn/getting-started/installing-ballerina/Installation-options.md

Update installation guide

---

downloads/1.2.x-release-notes/1.2.23.md

Update the 1.2.24 release note link.
> Fixes #

Update the 1.2.24 Release Note Link

---

learn/getting-started/installing-ballerina/Installation-options.md

Update the language specification

---

_data/stable-latest/metadata.json

Update metadata.json for 1.2.25 release

---

learn/guides/generating-code-documentation.md

> Update the `Generating Code Documentation` guide for GA

Update documentation guide

---

learn/getting-started/installing-ballerina/Installation-options.md
learn/getting-started/installing-ballerina/setting-up-ballerina.md

Remove 'what is next?' section

---

learn/references/style-guide/coding-conventions.md
learn/references/style-guide/coding-conventions/top-level-definitions.md

Update the coding conventions style guide

---

js/redirections.js

Add redirection for building from source

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.24.md
downloads/1.2.x-release-notes/1.2.25.md

Add the 1.2.25 release note.
> Fixes #

Add the 1.2.25 Release Note

---

_data/deployingballerinaonkubernetesnavswanlake.yml
_includes/left-nav-deploying-ballerina-on-kubernetes-swan-lake.html
_layouts/ballerina-deploying-ballerina-on-kubernetes-left-nav-pages-swanlake.html
learn/getting-started/deploying-ballerina-on-kubernetes.md
learn/guides/running-ballerina-programs-in-the-cloud/code-to-cloud/code-to-cloud-deployment.md

Adding a deploying ballerina service into Kubernetes section in the getting started section.
> Fixes #

Add deploying k8s in getting started section

---

learn/getting-started/installing-ballerina/Installation-options.md
learn/getting-started/installing-ballerina/setting-up-ballerina.md

Remove repititive updating sections

---

_data/usingqueryexpressionstomanipulatedataswanlake.yml
_includes/left-nav-using-query-expressions-to-manipulate-data-swan-lake.html
_layouts/ballerina-using-query-expressions-to-manipulate-data-swanlake.html
learn/getting-started/working-with-data/using-query-expressions-to-manipulate-data.md

Add Getting Started Guide for "Working with Data"

---

learn.md

Add `Working with Data in Ballerina` to Learn pages

---

learn.md
learn/getting-started/deploying-ballerina-on-kubernetes.md
learn/getting-started/working-with-data/using-query-expressions-to-manipulate-data.md

Add the Kubernetes Getting Started guide to learn.
> Fixes #

Add the Kubernetes Getting Started Guide to Learn

---

learn/getting-started/installing-ballerina/setting-up-ballerina.md

Remove the 'Trying Ballerina in the Playground' section from the setup page. 
> Fixes #
#3445

Remove playground section

---

_data/grpcgettingstarteddnavswanlake.yml

Remove sub-links from left menu
> Fixes #

Remove sub-links from left menu

---

learn/getting-started/installing-ballerina/setting-up-ballerina.md

Update the VS Code marketplace docs link.
> Fixes #3452

Update the VS Code Marketplace Docs Link

---

learn/guides/calling-java-code-from-ballerina.md

Fix a couple of links in the calling Java code from Ballerina guide

---

downloads/swan-lake-release-notes/swan-lake-alpha2/RELEASE_NOTE.md

Fix the Swan Lake Alpha5 release note link.
> Fixes #3466

Fix the Swan Lake Alpha5 Release Note Link

---

learn.md

Update the guides on the learn landing page.
> Fixes #

Update the Guides on the Learn Landing Page

---

_layouts/ballerina-hello-world-left-nav-pages-swanlake.html

Remove the merged conflict.
> Fixes #

Remove the Merged Conflict

---

_data/installingballerinanavswanlake.yml

Update the Left Nav 

---

learn/guides/generating-code-documentation.md

Change wording in documentation guide

---

learn/guides/ballerina-shell.md

Update Shell page

---

learn/references/cli-documentation/cli-commands.md

> Remove update commands menu item

Remove extra tr

---

_data/visualstudiocodeextensionnavswanlake.yml
learn/guides/visual-studio-code-extension/debugging.md

$subject.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/3488

Improve debugger guide content and fix left navigation view issues

---

_data/observingprogramsswanlake.yml
learn.md

Fix observability doc redirection issue

---

_data/guidesnavswanlake.yml
learn.md
learn/guides/configuring-ballerina-programs/configure-values-in-kubernetes-environment.md
learn/guides/configuring-ballerina-programs/configuring-a-sample-ballerina-service.md
learn/guides/configuring-ballerina-programs/providing-values-to-configurable-variables.md
learn/guides/testing-ballerina-code/structuring-tests.md

$subject 
Verified the content and the page structure

Improve configurable learn page content

---

learn/guides/configuring-ballerina-programs/providing-values-to-configurable-variables.md

Fix configurable learn page error

---

learn/guides/ballerina-openapi-support.md

Add minor changes to OpenAPI learn page

---

learn.md

Change href in Working with Data in Ballerina

---

_data/deployingballerinaonkubernetesnavswanlake.yml
learn.md
learn/getting-started/deploying-ballerina-on-kubernetes.md

Fix caps issue in deployment getting started page

---

learn.md

Fix the RESTful guide Learn link.
> Fixes #

Fix the RESTful Guide Learn link

---

_data/workingwithdatainballerinaswanlake.yml
learn/getting-started/working-with-data-in-ballerina.md
learn/getting-started/writing-a-restful-api-with-ballerina.md

Refactor Redirect url for `Working with Data in Ballerina`

---

learn/getting-started/writing-a-grpc-service-with-ballerina.md
learn/references/cli-documentation/grpc.md

Fix the issues found in Grammarly
> Fixes #

Fix the issues found in Grammarly

---

_data/visualstudiocodeextensionnavswanlake.yml
learn/guides/visual-studio-code-extension/debugging.md

$subject. 
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/3488

Fix debugger guide navigations

---

learn/guides/ballerina-shell.md

Fix minor issue in shell page

---

learn/guides/generating-code-documentation.md

Replace outdated code block in documentation guide

---

learn/getting-started/writing-a-graphql-api-with-ballerina.md

Update the layout of the GraphQL guide.
> Fixes #

Update the GraphQL Guide Layout

---

learn/guides/generating-code-documentation.md

Remove unnecessary steps from documentation guide

---

learn/guides/generating-code-documentation.md

Add clarification in documentation guide

---

_data/clidocumentationnavswanlake.yml
learn/references/cli-documentation/update-tool.md

Add sub topics in Update Tool left navigation

---

learn/getting-started/writing-a-graphql-api-with-ballerina.md

Update the GraphQL guide permalink.
> Fixes #

Update the GraphQL Guide Permalink

---

learn/getting-started/installing-ballerina/Installation-options.md

Change update tool version

---

learn/guides/ballerina-openapi-support.md

>$Subject 
Resolves issue1, issue2, etc.
> Fixes #

Add minor change to OpenAPI learn page

---

_data/testingcodeswanlake.yml

Fix broken links in Testing guide

Fix broken links in Testing guide

---

_data/clidocumentationnavswanlake.yml

Fix the title

---

learn.md

Update the Learn section descriptions.
> Fixes #

Update the Learn Section Descriptions

---

learn/getting-started/getting-started-with-ballerina.md

Fix code formatting issue

---

learn/getting-started/getting-started-with-ballerina.md

Fix issues in getting started guide

---

learn.md

Fix the RESTful guide description.
> Fixes #

Fix the RESTful Guide Description

---

learn/guides/organizing-ballerina-code.md

Fix broken links and improve content in ballerina package guide

---

learn/guides/testing-ballerina-code/code-coverage-and-reporting.md
learn/guides/testing-ballerina-code/configuring-tests.md
learn/guides/testing-ballerina-code/defining-test-groups.md
learn/guides/testing-ballerina-code/mocking.md
learn/guides/testing-ballerina-code/quick-start-on-testing.md
learn/guides/testing-ballerina-code/structuring-tests.md
learn/guides/testing-ballerina-code/writing-tests.md

Improve and fix Ballerina testing guide content

---

learn/getting-started/writing-a-graphql-api-with-ballerina.md

Add Note About Isolation Warnings in GraphQL Guide

---

learn/guides/testing-ballerina-code/configuring-tests.md
learn/guides/testing-ballerina-code/quick-start-on-testing.md
learn/guides/testing-ballerina-code/writing-tests.md

Add minor fixes for Ballerina test guide

---

learn/getting-started/installing-ballerina/Installation-options.md
learn/getting-started/installing-ballerina/setting-up-ballerina.md

Update Installing Ballerina reference links

---

learn/getting-started/getting-started-with-ballerina.md

Update creating a bal project description

---

learn/guides/generating-code-documentation.md

Add minor improvements to the docerina learn guide

---

learn/slides/language-walkthrough/language-walkthrough.md

Add metadata of the language-walkthrough page

---

learn/guides/configuring-ballerina-programs/configuring-a-sample-ballerina-service.md
learn/guides/configuring-ballerina-programs/providing-values-to-configurable-variables.md

Add minor fixes for configurable variable guide

---

_includes/nav.html

Update the banner for Swan Lake GA.
> Fixes #

Update the Banner for Swan Lake GA

---

learn/guides/ballerina-shell.md

$subject to improve the Ballerina shell learn page.

Fix Ballerina shell learn page doc issues

---

learn/getting-started/writing-a-restful-api-with-ballerina.md

Update the POST API

---

_data/workingwithdatainballerinaswanlake.yml
learn/getting-started/working-with-data-in-ballerina.md

Update working with data in ballerina page.

Update working with data in ballerina page

---

learn/why-ballerina/concurrent.md

Fix doc guidelines deviations in Concurrent Why Ballerina Page

---

learn/guides/managing-dependencies.md

Improve Managing Dependencies guide.

Improve Managing Dependencies guide

---

learn/why-ballerina/graphical.md

Improve why ballerina - graphical page

---

learn/guides/organizing-ballerina-code.md

Fix organizing ballerina code page

---

learn/why-ballerina/data-oriented.md

Improve why ballerina - data oriented page

---

learn/guides/testing-ballerina-code/quick-start-on-testing.md

Fix Testing guide

---

learn/guides/publishing-packages-to-ballerina-central.md

Improve Publishing Packages to BC guide

Improve Publishing Packages to BC guide

---

learn/why-ballerina/reliable-maintainable.md

Fix doc guidelines deviations for Reliable, Maintainable why Ballerina-page

---

learn/getting-started/language-basics.md

Review "Language Basics"

---

learn/guides/managing-dependencies.md

Fix managing dependencies page

---

_data/guidesnavswanlake.yml
_data/learnnavswanlake.yml
_data/testingcodeswanlake.yml
learn.md
learn/guides/testing-ballerina-code/mocking.md
learn/guides/testing-ballerina-code/testing-a-simple-function.md
learn/guides/testing-ballerina-code/writing-tests.md

Change 'Quick Start guide' to 'Testing a Simple Function'

---

security-policy.md

Improve security policy page

---

_data/distinctivelangfeaturesnavswanlake.yml

Fix navigation for distinctive features

---

_data/deployingballerinaonkubernetesnavswanlake.yml
learn/getting-started/deploying-ballerina-on-kubernetes.md

Improve Deploying Ballerina on Kubernetes guide

Improve Deploying Ballerina on Kubernetes guide

---

learn/getting-started/writing-a-restful-api-with-ballerina.md

Update the code and the text

---

_data/restapiguidenavswanlake.yml

Fix the left navigation

---

css/home-page-2020.css

Fix minor adjustment

---

learn/getting-started/deploying-ballerina-on-kubernetes.md
learn/guides/running-ballerina-programs-in-the-cloud/code-to-cloud/code-to-cloud-deployment.md

$Subject.  Resolves #3627 
> Fixes #

Code to cloud related Prerequisites improvements and fix broken links

---

learn/by-example/booleans.html
spec/spec.md

Use actual heading for the spec changelog

---

learn/getting-started/writing-a-graphql-api-with-ballerina.md

Add minor improvements to the `Writing a GraphQL API with Ballerina`

---

_data/restapiguidenavswanlake.yml

FIx left nav bar in `Writing a RESTful API with Ballerina`

FIx left nav bar in `Writing a RESTful API with Ballerina`

---

learn/why-ballerina/flexibly-typed.md

Introduce changes from the final review of flexibly-typed.md

---

learn/why-ballerina/cloud-native.md

Introduce changes from the final review of cloud-native.md

---

learn/getting-started/writing-a-restful-api-with-ballerina.md

Fix code formatting issue in `writing restful api guide`

---

_data/distinctivelangfeaturesnavswanlake.yml
learn/guides/distinctive-language-features/data.md
learn/guides/distinctive-language-features/network-interaction.md

Fix the data and network interactions sections of the distinctive lang features

---

_data/graphapiguidenavswanlake.yml
_data/grpcgettingstarteddnavswanlake.yml
learn/getting-started/writing-a-grpc-service-with-ballerina.md

Update left nav-bar in `Writing a GraphQL API with Ballerina` and `Writing a gRPC Service with Ballerina` pages

---

learn/guides/distinctive-language-features/data.md

Fix invalid escaping

---

community-new.html
events.html
resources.html
tech-talk.html

Update community page header placement  and styles

---

learn/guides/distinctive-language-features/concurrency.md

Fix the concurrency section of distinctive lang features

---

learn/references/cli-documentation/cli-commands.md
learn/references/cli-documentation/grpc.md
learn/references/cli-documentation/update-tool.md

Refactor cli-documentation page

---

learn/guides/publishing-packages-to-ballerina-central.md

$Subject
Resolves #3142
> Fixes #

Add create org link

---

learn/getting-started/deploying-ballerina-on-kubernetes.md

Minor changes regarding tooling in prerequisites

---

learn/getting-started/writing-a-graphql-api-with-ballerina.md
learn/getting-started/writing-a-grpc-service-with-ballerina.md
learn/getting-started/writing-a-restful-api-with-ballerina.md

Update GraphQL, gRPC, and REST API Guides

---

learn/guides/distinctive-language-features/data.md

Update data related description

---

learn/guides/distinctive-language-features/data.md

Fix few descriptions in distinctive language features

---

learn/guides/distinctive-language-features/data.md

Fix few doc mistakes under Table

---

learn/guides/distinctive-language-features/network-interaction.md

Fix few doc issues in network-interaction.md

---

learn/guides/distinctive-language-features/network-interaction.md

Fix issues in `network-interaction.md`

---

learn/guides/ballerina-shell.md

Add SEO keywords to Shell learn page

---

_data/gettingstartedwithballerina.yml
_data/packagereferencesnavswanlake.yml
_includes/left-nav-getting-started-swan-lake.html
_layouts/ballerina-example-page-old.html
_layouts/ballerina-grpc-getting-started-left-nav-pages-swanlake.html
css/ballerina-io-learn-v2.css
css/prism.css
download.html
learn/getting-started/installing-ballerina/setting-up-ballerina.md

> 
> Fixes #3665
> Fixes #3548
> Fixes #3457
> Fixes #3529

Add pre ga bug fixes

---

download.html

Link the Getting Started Guide from the Downloads page.
> Fixes #3658

Link the `Getting Started` Guide from the `Downloads` Page

---

learn/guides/ballerina-openapi-support.md
learn/references/cli-documentation/cli-commands.md

Fix OpenAPI learn page broken link

---

_data/styleguidenavswanlake.yml
learn/references/style-guide/coding-conventions.md
learn/references/style-guide/coding-conventions/annotations-documentation-and-comments.md
learn/references/style-guide/coding-conventions/expressions.md
learn/references/style-guide/coding-conventions/operators-keywords-and-types.md
learn/references/style-guide/coding-conventions/statements.md
learn/references/style-guide/coding-conventions/top-level-definitions.md

Refactor style guide

---

learn/getting-started/writing-a-restful-api-with-ballerina.md

Add missing keywords in `Writing a RESTful API with Ballerina`

Add missing keywords in `Writing a RESTful API with Ballerina` guide

---

index.html

Remove unnecessary spaces around `|`

---

learn/guides/distinctive-language-features/data.md

Fix few doc issues

---

learn/guides/distinctive-language-features/network-interaction.md

Highlight test urls in `network interaction`

---

_data/buildingadataservicenavswanlake.yml
learn/getting-started/building-a-data-service-in-ballerina.md

Improve `Building a Data Service in Ballerina` page content

Improve `Building a Data Service in Ballerina` page content

---

_includes/ballerina-footer.html

Fix the footer

---

learn/guides/testing-ballerina-code/writing-tests.md

Fix back ticks issue within code block

Fix back ticks issue within code block

---

_data/ballerinaopenapisupportswanlake.yml
learn/guides/ballerina-openapi-support.md

Reset the OpenAPI learn page navigation bar

---

_data/distinctivelangfeaturesnavswanlake.yml
learn/guides/distinctive-language-features/advanced-general-purpose-language-features.md

Fix the advanced features section of distinctive lang features

---

_data/workingwithdatainballerinaswanlake.yml
learn/getting-started/working-with-data-in-ballerina.md

Update working-with-data sub headings

---

index.html

Add kafka sample to the Ballerina in Action Section

---

.gitignore
_data/graphapiguidenavswanlake.yml
learn/getting-started/writing-a-graphql-api-with-ballerina.md

Remove Unnecessary Steps from the GraphQL Guide

---

learn/references/cli-documentation/cli-commands.md

Fix backtick issue in the table

---

_data/swanlake-latest/metadata.json

Update metadata.json for 2201.0.0 release

---

learn/why-ballerina/flexibly-typed.md

$title.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/3712.

Fix invalid table tag

---

learn/other/data-and-events-processing/using-language-integrated-queries.md
learn/other/network-communication/HTTP/http-clients/http-clients.md
learn/other/network-communication/gRPC/implementing-grpc-services-and-clients/implementing-grpc-services.md
learn/references/cli-documentation/cli-commands.md
learn/why-ballerina/cloud-native.md

$Subject. 
Resolves #3715
> Fixes #

Change `The below is` to `Below is`

---

_data/organizingcodeswanlake.yml

$subject.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/3718

Fix package guide title inconsistencies

---

_includes/ballerina-head-landing-page.html
_includes/ballerina-head.html
_includes/ballerina-home-head.html

fix prepod sm banner

---

_layouts/ballerina-grpc-getting-started-left-nav-pages-swanlake.html

Fix grpc page  css bug

---

_includes/ballerina-head-landing-page.html
_includes/ballerina-head.html
_includes/ballerina-home-head.html

Add sm banner for live site

---

index.html

This will add the following example to the Ballerina-in-Action section of the homepage.
```ballerina
import ballerina/graphql;
import ballerina/http;
import ballerinax/mysql;
import ballerinax/mysql.driver as _;
configurable string user = ?;
configurable string password = ?;
configurable string host = ?;
configurable int port = ?;
configurable string database = ?;
configurable string apiEndpoint = ?;
public type Album record {
string id;
string title;
string artist;
decimal price;
};
public enum Currency {
USD,
LKR,
EUR,
GBP
}
service / on new graphql:Listener(9000) {
private final mysql:Client dbClient;
private final http:Client httpClient;
private final Currency baseCurrency;
function init() returns error? {
self.dbClient = check new (host, user, password, database, port); …
```

Add GraphQL Example to Ballerina-In-Action Section

---

_data/distinctivelangfeaturesnavswanlake.yml
_data/langbasicsnavswanlake.yml
learn/guides/distinctive-language-features/concurrency.md

Fix left navigation emphasis

---

index.html

Remove added kafka sample

---

index.html

Reverts ballerina-platform/ballerina-dev-website#3701

Revert "Add kafka sample to the Ballerina in Action Section"

---

_data/organizingcodeswanlake.yml

$subject. The new restructured navigation view is shown below.

Restructure left navigation for organizing code guide

---

downloads/swan-lake-release-notes/swan-lake-2201.0.0/RELEASE_NOTE.md

Update release notes for Update Tool

---

learn/references/package-references.md

> Rearrange titles in package references

Rearrange titles in package references

---

_data/distinctivelangfeaturesnavswanlake.yml
learn/guides/distinctive-language-features/advanced-general-purpose-language-features.md

Fix spread operator title and navigation

---

download.html

Update the Downloads page for the Swan Lake GA.
> Fixes #

Update the Downloads page for the Swan Lake GA  

---

_layouts/ballerina-example-page-old.html
_layouts/ballerina-example-page.html
css/ballerina-io-bbe.css
index.html

Fix bbe nav

---

index.html

Add a new line after config variable to improve readability

---

index.html

Fix formatting of sql sample

---

spec/spec.md

Fix the spec release date and platform spec versions

---

index.html

Rename samples to format the titles

---

learn/getting-started/deploying-ballerina-on-kubernetes.md

$Subject as the code snippet  contains ballerina code.
> Fixes #

Add syntax highlighting to deploying ballerina guide

---

index.html

Horizontal scroll

---

learn/guides/configuring-ballerina-programs/providing-values-to-configurable-variables.md

Merge cells in configurable module info table

---

_data/organizingcodeswanlake.yml

Reverts ballerina-platform/ballerina-dev-website#3750

Revert "Restructure left navigation for organizing code guide"

---

learn/references/package-references.md

Reverts ballerina-platform/ballerina-dev-website#3762

Revert "Rearrange titles in package references"

---

index.html

Fix slight indentation in gRPC sample in home

---

index.html

Fix a typo and remove a comment

---

index.html

Reverts ballerina-platform/ballerina-dev-website#3770

Revert "Fix a typo and remove a comment"

---

css/home-page-2020.css
index.html

Fix ballerina in action style

---

index.html

Fix syntax for sql sample

---

learn/references/cli-documentation/cli-commands.md

Update reference links for core commands

Update reference links

---

learn/guides/testing-ballerina-code/configuring-tests.md

> Improve titles in configuring tests page

Improve titles in configuring tests page

---

index.html

Change the order of gRPC remote services

---

_layouts/ballerina-example-page-old.html
_layouts/ballerina-example-page.html

Add bbe nav fixes

---

downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-preview7/RELEASE_NOTE.md

Fix broken links for the SL GA release.
> Fixes #

Fix Broken Links for the SL GA Release

---

index.html

Fix the gRPC error message and equals operator

---

_includes/ballerina-head-landing-page.html
_includes/ballerina-head.html
_includes/ballerina-home-head.html

Sm banner test

---

index.html

Fix the indentation of gRPC

---

_includes/ballerina-head-landing-page.html
_includes/ballerina-head.html
_includes/ballerina-home-head.html

Reverts ballerina-platform/ballerina-dev-website#3787

Revert "Sm banner test"

---

learn/guides/visual-studio-code-extension/debugging.md

Fix breadcrumbs issue in debugger guide

---

_includes/ballerina-footer.html

Update the `Subscribe to Newsletter` Footer Button.
> Fixes #

Update the `Subscribe to Newsletter` Footer Button

---

index.html

Addressed a few code review comments

Address review comments

---

learn/guides/configuring-ballerina-programs/quick-start-on-configurable-variables.md
learn/guides/running-ballerina-programs-in-the-cloud/code-to-cloud/code-to-cloud-deployment.md

Fix broken links post SL GA release.
> Fixes #

Fix Broken Links Post SL GA Release

---

downloads/swan-lake-release-notes/swan-lake-2201.0.0/RELEASE_NOTE.md

Update the `RELEASE_NOTE.md` on Migrating from SL Beta releases.
> Fixes #

Update the `RELEASE_NOTE.md` on Migrating from SL Beta Releases

---

index.html

Apply Suggestions from the Code Review

---

learn/getting-started/writing-a-graphql-api-with-ballerina.md

This is to avoid duplicated intro entries in https://ballerina.io/learn/writing-a-graphql-api-with-ballerina/

Remove duplicated intro lines

---

index.html

Fix newsletter button issue

---

index.html

Add code improvements from suggestions to kafka sample

---

_includes/nav.html

Update `nav.html` to fix a conflict merge.
> Fixes #

Update `nav.html` to Fix a Conflict Merge

---

learn/guides/debugging-ballerina-programs.md

$subject.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/3814

Fix debugger guide introduction

---

index.html

Fix-event-section-bug

---

.github/scripts/publish_homebrew.py
.github/workflows/publish_homebrew.yml

Automate publishing new release to homebrew
> Fixes #3843

Restore homebrew workflow

---

.github/workflows/bal_in_action.yml
src/ballerina-in-action/bbe-generator.py

To build and validate the Ballerina in Action examples in the website. 
> Fixes #
#3837

Build Ballerina in Action Examples

---

1.2/learn/installing-ballerina/index.html
download.html
learn/getting-started/installing-ballerina/Installation-options.md

Add the Homebrew installation option.
> Fixes #1929

Add the Homebrew installation option

---

download.html
index.html
learn.md

Add IDs to all headings.
> Fixes #3855

Add IDs to All Headings

---

1.2/learn/installing-ballerina/index.html

Fix the ZIP file link of 1.2.
> Fixes #3289

Fix the ZIP File Link of 1.2

---

community-new.html
tech-talk.html

> Remove Upcoming Tech Talk section from Community page and Tech Talk page

Remove upcoming tech talk section

---

community-new.html

Update the newsletter subscription title.
> Fixes #

Update the Newsletter Subscription Title

---

index.html

Upcoming section remove

---

index.html
learn/guides/ballerina-openapi-support.md

Change header levels in OpenAPI learn page 

---

learn/guides/distinctive-language-features/data.md

Fix escaping

---

_includes/ballerina-footer.html
community-new.html

Fix the `Report issues` footer link.
> Fixes #3921

Fix the `Report issues` Footer Link

---

_data/swanlake-latest/metadata.json

>Update swan-lake latest version from `2201.0.0` to `2201.0.1`
> Fixes #

Update swan-lake latest version 

---

_data/swanlake_release_notes_versions.json

> Update release notes data manually.
> Fixes #

Update release notes data

---

_data/releasenotes.yml
_includes/nav.html
download.html
downloads/1.2.x-release-notes/1.2.25.md
downloads/release-notes.md
downloads/swan-lake-release-notes.md
downloads/swan-lake-release-notes/swan-lake-2201.0.0/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.0.1/RELEASE_NOTE.md

Do the updates for the 2201.0.1 release.
> Fixes #

Do the Updates for the 2201.0.1 Release

---

downloads/1.2.x-release-notes/1.2.24.md
downloads/1.2.x-release-notes/1.2.25.md
downloads/release-notes.md
downloads/swan-lake-release-notes.md
js/redirections.js

Fix the build error in the pre-prod site.
> Fixes #

Fix the Build Error in the Pre-Prod Site

---

downloads/swan-lake-release-notes/swan-lake-2201.0.1/RELEASE_NOTE.md

Do minor fixes in the 2201.0.1 (Swan Lake) release note.
> Fixes #

Do Minor Fixes in the 2201.0.1 (Swan Lake) Release Note

---

community-new.html
events.md
index.html

Fix sentence case on the Community page.
> Fixes #

Fix Sentence Case on the Community Page

---

community-new.html

> Updated the Newsletter Section and add a link as view all newsletters to go to Ballerina Newsletter page
> Fixes #

Update newsletter section

---

community-new.html
community/newsletter.md
js/redirections.js

Add the Slack and newsletter redirections.
> Fixes #

Add the Slack and Newsletter Redirections

---

_data/grpcgettingstarteddnavswanlake.yml
learn/getting-started/writing-a-grpc-service-with-ballerina.md

Review the gRPC Getting Started guide.
> Fixes #

Review the gRPC Getting Started Guide

---

css/home-page-2020.css

> Fix alignment issues of Icons, Titles & More Info links in Why Ballerina section.
>#3588

Fix alignment issues in Why Ballerina section

---

downloads/swan-lake-release-notes/swan-lake-2201.0.1/RELEASE_NOTE.md

Update the 2201.0.1 release note links.
> Fixes #

Update the 2201.0.1 Release Note Links

---

js/ballerina-leftnav.js

> Fix clicking reference link doesn't activate the heading in nav-bar
> Fixes #3563

Fix clicking reference link doesn't activate the heading in nav-bar

---

spec/lang/master/index.html
spec/lang/master/spec.xml

Dev to master sync on the 9th of March 2022.
> Fixes #

Dev to Master Sync on the 9th of March 2022

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.25.md
downloads/1.2.x-release-notes/1.2.26md

Add the 1.2.26 release note.
> Fixes #

Add the 1.2.26 Release Note

---

downloads/1.2.x-release-notes/1.2.25.md

Fix the master branch build.
> Fixes #

Fix the Master Branch Build

---

.github/scripts/sync_master_with_dev.py
.github/workflows/sync_master_into_dev.yml

Sync master branch with dev

---

_data/stable-latest/metadata.json

Update metadata.json for 1.2.26 release

---

_data/stable-latest/metadata.json

Update 1.2.27 metadata

---

learn/get-started/write-a-grpc-service-with-ballerina.md

Improve the gRPC Getting Started guide.
> Fixes #

Improve the gRPC Getting Started Guide

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.26.md
downloads/1.2.x-release-notes/1.2.27.md

Add the 1.2.27 release note.
> Fixes #

Add the 1.2.27 Release Note

---

downloads/1.2.x-release-notes/1.2.27.md

Update the 1.2.27 release note.
> Fixes #

Update the 1.2.27 Release Note

---

_data/releasenotes.yml
_data/stable-latest/metadata.json
downloads/1.2.x-release-notes/1.2.26.md
downloads/1.2.x-release-notes/1.2.27.md

Sync the 1.2.27 release updates to master.
> Fixes #

Sync the 1.2.27 Release Updates to Master

---

_data/swanlake-latest/metadata.json

Update latest version

---

_data/releasenotes.yml

Update the active link of the 2201.0.2 release note.
> Fixes #

Update the Active Link of the 2201.0.2 Release Note

---

_data/releasenotes.yml
downloads/swan-lake-release-notes/swan-lake-2201.0.0/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.0.1/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.0.2/RELEASE_NOTE.md

Fix the Release Notes Link in Archived Versions

---

.github/scripts/sync_dev_with_master.py
.github/workflows/sync_dev_with_master.yml

Create automate sync PR

---

.github/workflows/sync_dev_with_master.yml

Fix file name

---

resources.html

Update more sentence case occurrences on the Community page.
> Fixes #

Update More Sentence Case Occurrences on the Community Page

---

community-new.html
community/events.html
index.html

Add new events 

---

learn/guides/test-ballerina-code/code-coverage-and-reporting.md
learn/guides/test-ballerina-code/execute-tests.md
learn/guides/test-ballerina-code/mocking.md
learn/guides/test-ballerina-code/structure-tests.md

Fix `Test Ballerina Code` pages redirections.
> Fixes #

Fix `Test Ballerina Code` Pages Redirections

---

learn/guides/manage-dependencies.md
learn/guides/publish-packages-to-ballerina-central.md
learn/references/package-references.md

> Fix packages documentation
> Fixes #3067

Fix packages documentation

---

learn/guides/test-ballerina-code/execute-tests.md

Fix the recursive redirection on the `Execute Tests` page.
> Fixes #

Fix the recursive redirection in `Execute Tests` page

---

_data/observingprogramsswanlake.yml
learn/guides/observe-ballerina-programs.md

Review the Observability Learn page.
> Fixes #3988 #3989 #3994

Review the Observability Learn page

---

index.html
js/ballerina-common.js

> Create Hyperlinks for the Ballerina in action Samples
> Fixes #4138

Create Hyperlinks for the Ballerina in action Samples

---

_data/releasenotes.yml
downloads/1.2.x-release-notes/1.2.1.md
downloads/1.2.x-release-notes/1.2.13.md
downloads/1.2.x-release-notes/1.2.16.md
downloads/1.2.x-release-notes/1.2.17.md
downloads/1.2.x-release-notes/1.2.18.md
downloads/1.2.x-release-notes/1.2.19.md
downloads/1.2.x-release-notes/1.2.2.md
downloads/1.2.x-release-notes/1.2.20.md
downloads/1.2.x-release-notes/1.2.21.md
downloads/1.2.x-release-notes/1.2.22.md
downloads/1.2.x-release-notes/1.2.23.md
downloads/1.2.x-release-notes/1.2.24.md
downloads/1.2.x-release-notes/1.2.25.md
downloads/1.2.x-release-notes/1.2.26.md
downloads/1.2.x-release-notes/1.2.27.md
downloads/1.2.x-release-notes/1.2.28.md
downloads/1.2.x-release-notes/1.2.3.md
downloads/1.2.x-release-notes/1.2.4.md
downloads/1.2.x-release-notes/1.2.5.md
downloads/1.2.x-release-notes/1.2.6.md

Add the 1.2.28 Release Note

---

_data/ballerinaopenapisupportswanlake.yml
js/redirections.js
learn/guides/ballerina-openapi-support.md

Improve the structure of the OpenAPI guide.
> Fixes #4134

Improve the Structure of the OpenAPI Guide

---

spec/lang/2019R1/index.html
spec/lang/2019R1/style/ballerina-language-specification.css
spec/lang/2019R1/style/ballerina-language-specification.js
spec/lang/2019R2/index.html
spec/lang/2019R2/style/ballerina-language-specification.css
spec/lang/2019R2/style/ballerina-language-specification.js

Fix the styles of old spec versions.
> Fixes #

Fix the Styles of the Old Spec Versions

---

.github/workflows/update_ballerina_by_example_patch.yml

> Include master branch for generation

Include master branch for generation

---

learn/get-started/install-ballerina/set-up-ballerina.md

Link the Get started guide from installation page.
> Fixes #

Link the `Get started` Guide from Installation Page

---

learn.md

Update the `Install Ballerina` URL in `learn.md`.
> Fixes #

Update the `Install Ballerina` URL in `learn.md`

---

Dockerfile

Fix dev build failure

---

Dockerfile
learn.md

Update the Jekyll version in the `Dockerfile`
> Fixes #

Update the Jekyll version in the `Dockerfile`

---

.github/ISSUE_TEMPLATE/type_bug.md
.github/ISSUE_TEMPLATE/type_improvement.md
.github/ISSUE_TEMPLATE/type_new_feature.md
.github/ISSUE_TEMPLATE/type_task.md

Update the area section on dev issue templates.
> Fixes #

Update the Area Section on Dev Issue Templates

---

_data/stable-latest/metadata.json

Update 1.2.28 metadata

---

.github/workflows/update_ballerina_by_example_patch.yml

> Switch BBE generation from patch

Switch BBE generation from patch

---

robots.txt

Add domain verification

---

.github/workflows/add_link_checker.yml

Exclude localhost URLs in the link checker.
> Fixes #

Exclude Localhost URLs in the Link Checker

---

_config.yml

> Update site url in `_config.yml`.
> Fixes #3809

Update site url

---

community/newsletter-new.html
community/newsletter.md

Newsletter landing page update

---

.github/workflows/update_ballerina_by_example_patch.yml

> Switch dist repo into patch branch

Switch dist repo into patch branch

---

.github/workflows/update_ballerina_by_example_patch.yml

Fix path issue

---

.github/pull_request_template.md

Fix a typo in the PR template.
> Fixes #

Fix a Typo in the PR Template

---

learn/get-started/get-started-with-ballerina.md

Update the `Learn more` section of the `Get started` guide.
> Fixes #

Update the `Learn more` Section of the `Get started` Guide

---

_data/swanlake-latest/metadata.json

Update metadata.json for 2201.0.3

---

downloads/1.2.x-release-notes/1.2.0.md

Fix headings of 1.2.0 release note.
> Fixes #4251

Fix Headings of 1.2.0 Release Note

---

_includes/algolia-open-source.html

Update Algolia API Key.
> Fixes #

Update Algolia API Key

---

learn/get-started/deploy-ballerina-on-kubernetes.md

Improve the deployment `Get Started` guide intro.
> Fixes #

Improve the Deployment `Get Started` Guide Intro

---

.github/workflows/sw_publish_github_release.yml

Reverts ballerina-platform/ballerina-dev-website#4263

Revert "Fix the Prod Sync Release Note Generation Issue"

---

.github/workflows/sw_publish_github_release.yml

Add workflow dispatch

---

.github/workflows/sw_publish_github_release.yml

Add directory listing

---

.github/workflows/sw_publish_github_release.yml

Add extra header in curl command

---

.github/workflows/sw_publish_github_release.yml

Update workflow triggering events

---

_config.yml

Update `config.yml` to Exclude 1.1 & 1.0
> Fixes #

 Update `config.yml` to Exclude 1.1 & 1.0

---

_config.yml

Remove 1.1 from excluding

---

_config.yml

Update configs to include 1.0

---

downloads/swan-lake-release-notes/swan-lake-2201.0.3/RELEASE_NOTE.md

Rename the 2201.0.3 release note folder.
> Fixes #

Rename the 2201.0.3 Release Note Folder

---

downloads/swan-lake-release-notes/swan-lake-2201.0.3/RELEASE_NOTE.md

Correct the 2201.0.3 redirections
> Fixes #

Correct the 2201.0.3 Redirections

---

_data/releasenotes.yml

Correct release notes left nav highlighting
> Fixes #

Correct Release Notes Left Nav Highlighting

---

downloads/swan-lake-release-notes/swan-lake-2201.0.2/RELEASE_NOTE.md

Fix the 2201.0.2 release note front matter.
> Fixes #

Fix the 2201.0.2 Release Note Front Matter

---

index.html

To add an separate id to .proto file code snippet to detect it in content review.

Add id to proto file

---

_data/ballerinagraphqlsupportswanlake.yml
_data/clidocumentationnavswanlake.yml
_includes/left-nav-graphql-support-swan-lake.html
_layouts/ballerina-graphql-support-left-nav-pages-swanlake.html
learn.md
learn/guides/ballerina-graphql-support.md
learn/guides/ballerina-openapi-support.md
learn/references/cli-documentation/graphql.md

Add the GraphQL Learn content.
> Fixes #

Add the GraphQL Learn Content

---

_data/ballerinaasyncapisupportswanlake.yml
_data/clidocumentationnavswanlake.yml
_includes/left-nav-asyncapi-support-swan-lake.html
_layouts/ballerina-asyncapi-support-left-nav-pages-swanlake.html
learn.md
learn/guides/ballerina-asyncapi-support.md
learn/guides/ballerina-graphql-support.md
learn/references/cli-documentation/asyncapi.md
learn/references/cli-documentation/graphql.md

Add the AsyncAPI Tool Learn content.
> Fixes #

Add the AsyncAPI Tool Learn Content

---

_data/learnleftnav.yml
_includes/learn-left-nav.html
_layouts/ballerina-learn-left-nav.html
learn.md

Add  a left nav to Learn and rearrange the sections.
> Fixes #

Add  a Left Nav to Learn and Rearrange the Sections

---

_includes/ballerina-footer.html
_includes/nav.html
community/newsletter-new.html
community/newsletter/2020-1.md
community/newsletter/2020-2.md
community/newsletter/2020-3.md
community/newsletter/2020-4.md
community/newsletter/2020-5.md
community/newsletter/2021-1.md
community/newsletter/2021-2.md
community/newsletter/2021-3.md
community/newsletter/2021-4.md
community/newsletter/2021-5.md
community/newsletter/2021-6.md
community/newsletter/2021-7.md
community/newsletter/2022-1.md
community/newsletter/2022-2.md
js/redirections.js

Fix master to dev merge conflict.
> Fixes #

Fix Master to Dev Merge Conflict

---

_data/testingcodeswanlake.yml
learn/guides/test-ballerina-code/mocking.md

HTTP spec has changed so Mocking has to reflect the change
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4348

Update testerina mocking guide

---

learn/guides/test-ballerina-code/mocking.md

Correct http payload in mocking md
