- index.html
Reverts ballerina-platform/ballerina-dev-website#4318
> Revert "Add id to proto file"

- learn/get-started/build-a-data-service-in-ballerina.md
- learn/get-started/get-started-with-ballerina.md
- learn/get-started/install-ballerina/Installation-options.md
- learn/get-started/work-with-data-in-ballerina.md
> Fix get started pages

- community-new.html
Fix the `Report issues` link.
> Fixes
> Fix the `Report issues` Link

- learn/guides/ballerina-graphql-support.md
> Update GraphQL tool doc

- _data/swanlake-latest/metadata.json
> Update metadata for 2201.1.0 release

- community-new.html
> In Get Started links in first three items isn't working, with this PR it will fix that issue.
> Fix bug on community page

- _data/releasenotes.yml
- downloads/swan-lake-release-notes/swan-lake-2201.0.1/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.0.3/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
Add the 2201.1.0 release note to the release branch.
> Fixes #
> Add the 2201.1.0 Release Note to the Release Branch

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
> Remove GraphQL interface support entry from release note

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
> Add ProjectAPI improvement to release note

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
> Fix the multiplicative expr change description

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
> Add config map name example to release note

- learn/guides/graphql-client-tool.md
- learn/references/cli-documentation/graphql.md
> Update GraphQL client tool docs
> Update GraphQL client tool docs

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
> Add reason for the breaking change of faas modules

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
$subject related to debugger + open API bug fixes.
> Fix invalid links in 2201.1.0 release notes

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
> Add FaaS breaking change reasoning

- .github/workflows/update_ballerina_by_example_on_demand.yml
> Fix update bbe on demand for latest distribution

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
> Fix LS release note

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
> Remove Ballerinax Modules from the Release Note

- _data/distinctivelangfeaturesnavswanlake.yml
> Fix a typo

- learn/references/cli-documentation/graphql.md
Fix a typo in GraphQL CLI docs
> Fixes #
> Fix a Typo in GraphQL CLI Docs

- .github/workflows/generate_ballerina_by_example_on_demand.yml
> BBE generation on demand workflow added

- .github/workflows/automate_issue_labels.yml
> Automate adding labels in issues

- _data/workingwithdatainballerinaswanlake.yml
- learn.md
- learn/get-started/work-with-data-using-queries-in-ballerina.md
Rename `Work with data in Ballerina` Get Started guide.
> Fixes #4388
> Rename `Work with data in Ballerina` Get Started Guide

- _data/releasenotes.yml
- downloads/swan-lake-release-notes/swan-lake-2201.0.3/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.0.4/RELEASE_NOTE.md
Add the 2201.0.4 release note.
> Fixes #4399
> Add the 2201.0.4 Release Note

- _data/swanlake-latest/metadata.json
> Update metadata.json for 2201.0.4

- _data/ballerinagraphqlsupportswanlake.yml
- learn/guides/graphql-client-tool.md
- learn/references/cli-documentation/graphql.md
> Improve GraphQL client tool guide intro
> Improve GraphQL client tool guide

- _data/swanlake-latest/metadata.json
> Change release date for update 1 release

- _data/ballerinaasyncapisupportswanlake.yml
- learn/guides/asyncapi-tool.md
> Improve AsyncAPI tool learn docs
> Improve AsyncAPI tool learn docs

- _data/restapiguidenavswanlake.yml
- learn/get-started/write-a-restful-api-with-ballerina.md
Improve the RESTful Get started guide.
> Fixes #4386
> Improve the RESTful Get Started Guide

- index.html
> Fixes #https://github.com/ballerina-platform/ballerina-dev-website/issues/4490
> Update kafka sample

- index.html
> Update BIA with HTTP status code constants

- _data/swanlake_release_notes_versions.json
- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
Fix the 2201.1.0 release note and archived versions.
> Fixes #
> Fix the 2201.1.0 Release Note and Archived Versions

- downloads/swan-lake-release-notes/swan-lake-2201.0.4/RELEASE_NOTE.md
Update release notes common link
> Fixes #
> Update Release Notes Common Link

- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
- learn/guides/graphql-client-tool.md
- spec/lang/draft/index.html
- spec/lang/master/spec.xml
Fix broken links post 2201.1.0.
> Fixes #
> Fix Broken Links Post 2201.1.0

- community/newsletter/2022-4.md
> Create 2022-4.md Newsletter

- community/newsletter-new.html
> Update `newsletter-new.html` for 2022-4 Newslertter

- .github/workflows/automate_issue_labels.yml
$title
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4165
> Add a workflow to automate issue labeling

- .github/workflows/automate_issue_labels.yml
> Fix workflow issue

- spec/lang/draft/v2022R2/index.html
- spec/lang/draft/v2022R2/spec.xml
- spec/lang/draft/v2022R2/style/ballerina-language-specification.css
- spec/lang/draft/v2022R2/style/ballerina-language-specification.js
> Add missing draft

- .github/scripts/sync_master_with_dev.py
> Fix the issue in sending PR

- .github/workflows/automate_issue_labels.yml
> Add check for commented labels

- _data/stable-latest/metadata.json
> Update metadata.json for 1.2.30 release

- downloads/1.2.x-release-notes/1.2.29.md
Update the issues addressed by the 1.2.29 release in its release note.
> Fixes #
> Update the Issues Addressed by 1.2.29

- README.md
Add the fix of the event machine build error.
> Fixes #
> Add the Fix of the Event Machine Build Error

- license-of-site.md
Update site license titles to sentence case.
> Fixes #4540
> Update Site License Titles to Sentence Case

- _data/installingballerinanavswanlake.yml
- learn/get-started/install-ballerina/Installation-options.md
Add `Build from source` in `Installation options`.
> Fixes #4476
> Add `Build from source` in `Installation options`

- SECURITY.md
$subject related to https://github.com/wso2-enterprise/internal-support-ballerina/issues/78
>  Add Security Policy File

- SECURITY.md
> Update SECURITY.md titles to sentence case to be consistent with the other components of the Ballerina documentation.
> Update security policy file

- js/hyperlink-creator.js
- learn/by-example/css/ballerina-io-bbe-new.css
> Hyperlink rendering fixes for BBE pages

- .github/scripts/bbe/markdownConverter.js
- learn/by-example/css/ballerina-io-bbe-new.css
> Fenced code block feature added

- .github/scripts/bbe/markdownConverter.js
- learn/by-example/css/ballerina-io-bbe-new.css
> Markdown list rendering feature update

- .github/scripts/bbe/markdownConverter.js
> Code rendering feature for lists

- _data/platformspecificationsswanlake.yml
- spec/spec.md
> Add stdlib spec to left nav

- spec/spec.md
> Change table for stdlib specs

- spec/spec.md
> Change edition name

- _data/swanlake_release_notes_versions.json
> Update release note version

- downloads/swan-lake-release-notes/swan-lake-2201.0.5/RELEASE_NOTE.md
> Update `2201.0.5` release note

- learn/guides/organize-ballerina-code/package-references.md
> Add include field to package-references

- _data/releasenotes.yml
- _data/swanlake_release_notes_versions.json
- downloads/swan-lake-release-notes/2201.0.5/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.0.5/RELEASE_NOTE.md
Fix master to dev sync conflict.
> Fixes #
> Fix master to dev sync conflict

- _data/swanlake-latest/metadata.json
> Update metadata.json for 2201.1.1 release

- _data/swanlake_release_notes_versions.json
- downloads/swan-lake-release-notes/swan-lake-2201.1.1/RELEASE_NOTE.md
Fix release note left nav.
> Fixes #
> Fix release note left nav

- _data/stable-latest/metadata.json
> Update metadata.json for 1.2.31 release

- learn/guides/asyncapi-tool.md
> Improve AsyncAPI tool docs
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4484
> Improve AsyncAPI tool doc

- .github/workflows/sw_update_release__note_versions.yml
> Change branch to trigger workflow

- components/home-page/intro/Intro.js
- next.config.js
- pages/cookie-policy.js
- pages/downloads/1.2.x-release-notes/[...slug].js
- pages/downloads/stable-release-notes/[slug].js
- pages/downloads/swan-lake-release-notes/[...slug].js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/learn/platform-specifications.js
- pages/license-of-site.js
- pages/privacy-policy.js
- pages/security-policy.js
- pages/terms-of-service.js
- pages/trademark-usage-policy.js
- pages/why-ballerina/[...slug].js
> Fix broken links in home page & page toc.
> Fix broken links in home page and page toc.

- components/learn/use-cases/UseCases.js
> Fix typos in Learn landing page
> Fixes #4725
> Fix typos in Learn landing page

- privacy-policy.md
- terms-of-service.md
- trademark-usage-policy.md
Change `WSO2.Inc.` to `WSO2.LLC.` in B.io.
> Fixes #4706
> Change `WSO2.Inc.` to `WSO2.LLC.` in B.io

- _data/workingwithdatainballerinaswanlake.yml
- learn/get-started/work-with-data-using-queries-in-ballerina.md
Restructure the queries get started guide.
> Fixes #
> Restructure the Queries Get Started Guide

- _data/buildingadataservicenavswanlake.yml
- learn/get-started/build-a-data-service-in-ballerina.md
Restructure the data service get started guide.
> Fixes #
> Restructure the Data Service Get Started Guide

- components/community/get-involved/GetInvolved.module.css
- pages/downloads/index.js
- styles/Downloads.module.css
> Fix styling issues in Community and Downloads pages
> Fixes #4752, #4753, #4754, #4755
> Fix styling issues in Community and Downloads pages

- styles/globals.css
> Increase line height in Ballerina in action code snippets
> Fixes #4730
> Increase line height in Ballerina in action code snippets

- .github/workflows/update_stdlib_specs.yml
> Add workflow to update stdlib specs

- components/common/left-nav/LeftNav.js
- components/common/left-nav/LeftNav.module.css
- pages/learn/get-started/[...slug].js
- swan-lake/learn-the-language/language-basics.md
> Update styles in left nav & fix incorrect highlighting in page toc
> Fixes #4771 & #4750
> Update styles in left nav & fix incorrect highlighting in page toc

- pages/downloads/index.js
- styles/Downloads.module.css
> Fix the flickering in downloads page

- .github/workflows/update_stdlib_specs.yml
- spec/spec.md
> Add all stdlibs in the standard library specifications page table

- .github/workflows/update_stdlib_specs.yml
> Change base branch for workflow

- layouts/Layout404.js
- styles/globals.css
> Fix style issues in 404 page
> Fixes #4782
> Fix style issues in 404 page

- styles/globals.css
> Fix table width
> Fixes #4786
> Fix table width

- _includes/ballerina-example-head.html
- _includes/ballerina-head-landing-page.html
- _includes/ballerina-head-nl.html
- _includes/ballerina-head.html
- _includes/ballerina-home-head.html
> Include CookiePro script

- _includes/ballerina-footer.html
- _includes/bbe-footer.html
- css/ballerina-io.css
- js/ballerina-common.js
> Remove existing cookie policy popup
> Remove existing cookie policy popup

- pages/downloads/0.9.x-release-notes/[...slug].js
- pages/downloads/1.0.x-release-notes/[...slug].js
- pages/downloads/1.1.x-release-notes/[...slug].js
- public/spec/lang/master/index.html
- public/spec/lang/master/spec.xml
> Update the content to match the prod site

- next.config.js
- pages/downloads/archived.js
> Remove links to 0.990.5 & 0.990.7 release notes & update github path

- components/learn/intro/Intro.js
> Update description for specs

- public/js/ballerina-common.js
- public/spec/lang/2019R1/style/ballerina-language-specification.js
- public/spec/lang/2019R2/style/ballerina-language-specification.js
- public/spec/lang/2019R3/style/ballerina-language-specification.js
- public/spec/lang/2020R1/style/ballerina-language-specification.js
- public/spec/lang/2021R1/style/ballerina-language-specification.js
> Remove frontmatter from spec/lang htmls

- components/community/get-involved/GetInvolved.js
- swan-lake/learn-the-platform/configure-observe/configure-ballerina-programs/provide-values-to-configurable-variables.md
- utils/learn-lm.json
> Remove links pointing to the live site

- components/community/get-involved/GetInvolved.js
- swan-lake/learn-the-platform/configure-observe/configure-ballerina-programs/provide-values-to-configurable-variables.md
- swan-lake/why-ballerina/data-oriented.md
- utils/learn-lm.json
> Add backticks to headings

- components/community/get-involved/GetInvolved.js
- components/home-page/bal-action/BalAction.js
- swan-lake/learn-the-platform/configure-observe/configure-ballerina-programs/provide-values-to-configurable-variables.md
- swan-lake/why-ballerina/data-oriented.md
- utils/learn-lm.json
> Add links to home page examples
> Fixes #4797
> Add links to home page examples

- swan-lake/get-started/install-ballerina/set-up-ballerina.md
> Fix broken link

- components/home-page/videos/Videos.js
- components/home-page/videos/Videos.module.css
> Add featured videos

- components/home-page/videos/Videos.js
- components/home-page/videos/Videos.module.css
- components/learn/language/Language.module.css
> Fix font-weight inconsistency in Learn landing page

- components/common/footer/Footer.js
- components/community/get-involved/GetInvolved.js
- components/home-page/bal-action/BalAction.js
- components/learn/language/Language.module.css
- components/learn/platform/Platform.js
- styles/globals.css
- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-use-cases/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-use-cases/write-a-graphql-api-with-ballerina.md
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/featured-use-cases/write-a-restful-api-with-ballerina.md
> Apply the old color scheme to code snippets in home page examples

- components/common/footer/Footer.js
- components/learn/language/Language.module.css
> Open community channels in different tabs

- components/common/footer/Footer.js
- components/learn/language/Language.module.css
> Open external links in new tabs

- components/common/footer/Footer.js
- components/community/get-involved/GetInvolved.js
- components/learn/language/Language.module.css
- styles/globals.css
> Fix modals overlapping with the secondary navigation bar in community page
> Fixes #4839
> Fix modals overlapping with the secondary navigation bar in community page

- components/common/footer/Footer.js
- components/community/get-involved/GetInvolved.js
- components/learn/language/Language.module.css
- styles/globals.css
> Switch the colors of the buttons

- components/common/footer/Footer.js
- pages/spec/http/index.js
- pages/spec/jwt/index.js
- pages/spec/os/index.js
- styles/globals.css
> Fix build errors

- pages/learn/by-example/index.js
Update `font-weight` of BBE landing page for `Next.js` website to improve contrast.
> Update `font-weight` of BBE landing page for `Next.js` website

- learn/guides/publish-packages-to-ballerina-central.md
- learn/references/cli-documentation/cli-commands.md
This PR 
- Updates package learn guide with semver tool introduction
- Update cli command reference guide with semver tool description
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4495
> Update learn guides with semver tool content

- components/common/pg-toc/Toc.js
- pages/downloads/index.js
- pages/learn/ballerina-specifications.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/why-ballerina/[...slug].js
- styles/globals.css
- swan-lake/get-started/install-ballerina/set-up-ballerina.md
> $subject
> Fixes #4865, #4873
> Add intro sections to Learn pages & a version separator to Downloads page

- pages/learn/ballerina-specifications.js
- styles/globals.css
> Fix styling issues in the Note section

- styles/globals.css
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/why-ballerina/cloud-native.md
> Add correct styles to bullet points

- swan-lake/why-ballerina/cloud-native.md
> Capitalize Github Actions

- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/why-ballerina/cloud-native.md
> Highlight proto code snippet

- components/common/pg-toc/Toc.js
- pages/cookie-policy.js
- pages/learn/ballerina-specifications.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/license-of-site.js
- pages/privacy-policy.js
- pages/security-policy.js
- pages/terms-of-service.js
- pages/trademark-usage-policy.js
- pages/why-ballerina/[...slug].js
- styles/globals.css
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/why-ballerina/cloud-native.md
> Open the Learn pages edit option in a new tab

- components/common/footer/Footer.js
- components/common/newsletter-subscription/NewsletterSubscription.module.css
- components/common/pg-toc/Toc.js
- pages/cookie-policy.js
- pages/learn/ballerina-specifications.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/license-of-site.js
- pages/privacy-policy.js
- pages/security-policy.js
- pages/terms-of-service.js
- pages/trademark-usage-policy.js
- pages/why-ballerina/[...slug].js
- styles/globals.css
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/why-ballerina/cloud-native.md
> $subject
> Fixes #4891, #4897, #4899, #4899, #4900, #4905, #4906
> Fix broken links & code highlighting issues

- components/common/footer/Footer.js
- components/common/newsletter-subscription/NewsletterSubscription.module.css
- components/common/pg-toc/Toc.js
- pages/cookie-policy.js
- pages/learn/ballerina-specifications.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/license-of-site.js
- pages/privacy-policy.js
- pages/security-policy.js
- pages/terms-of-service.js
- pages/trademark-usage-policy.js
- pages/why-ballerina/[...slug].js
- styles/globals.css
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/learn-the-platform/java-interoperability/java-interoperability-guide/java-interoperability.md
- swan-lake/why-ballerina/cloud-native.md
> Fix image aspect ratio

- components/common/footer/Footer.js
- components/common/newsletter-subscription/NewsletterSubscription.module.css
- components/common/pg-toc/Toc.js
- pages/cookie-policy.js
- pages/learn/ballerina-specifications.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/license-of-site.js
- pages/privacy-policy.js
- pages/security-policy.js
- pages/terms-of-service.js
- pages/trademark-usage-policy.js
- pages/why-ballerina/[...slug].js
- styles/globals.css
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/learn-the-platform/java-interoperability/java-interoperability-guide/java-interoperability.md
- swan-lake/why-ballerina/cloud-native.md
- swan-lake/why-ballerina/reliable-maintainable.md
> Fix capitalization issues in text

- pages/downloads/0.9.x-release-notes/[...slug].js
- pages/downloads/1.0.x-release-notes/[...slug].js
- pages/downloads/1.1.x-release-notes/[...slug].js
- pages/downloads/1.2.x-release-notes/[...slug].js
- pages/downloads/stable-release-notes/[slug].js
- pages/downloads/swan-lake-release-notes/[...slug].js
- pages/learn/ballerina-specifications.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/spec/http/index.js
- pages/spec/jwt/index.js
- pages/spec/os/index.js
- pages/why-ballerina/[...slug].js
- styles/globals.css
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
> Add background color to code snippets

- styles/globals.css
> Fix alignment of blockquotes

- learn/guides/organize-ballerina-code/organize-ballerina-code.md
- learn/guides/organize-ballerina-code/package-references.md
Review the `Package references` left nav.
> Fixes #
> Review the `Package references` left nav

- components/learn/platform/Platform.js
- styles/globals.css
- utils/learn-lm.json
> Increase font size of L4 headings

- components/learn/platform/Platform.js
- utils/learn-lm.json
> Change section title

- components/learn/platform/Platform.js
- utils/learn-lm.json
> Add punctuation to learn landing page descriptions

- swan-lake/learn-the-platform/java-interoperability/call-java-code-from-ballerina.md
> Remove extra space in front of commentsin code snippets

- components/learn/use-cases/UseCases.js
- swan-lake/learn-the-platform/java-interoperability/call-java-code-from-ballerina.md
- swan-lake/learn-the-platform/test-document-the-code/generate-code-documentation.md
> Match links with page titles

- .github/workflows/update_stdlib_specs.yml
> Add update stdlib specs workflow

- .github/workflows/update_stdlib_specs.yml
> Fix update stdlib specs worflow

- components/learn/language/Language.js
- components/learn/language/Language.module.css
> Change the button text to View slides

- components/common/left-nav/LeftNav.js
- components/common/redirect-message/RedirectMessage.js
- components/common/top-nav/TopNav.js
- components/home-page/bal-action/BalAction.js
- components/learn/intro/Intro.module.css
- components/learn/new/New.js
- layouts/LayoutDocs.js
- pages/404.js
- pages/downloads/0.9.x-release-notes/[...slug].js
- pages/downloads/1.0.x-release-notes/[...slug].js
- pages/downloads/1.1.x-release-notes/[...slug].js
- pages/downloads/1.2.x-release-notes/[...slug].js
- pages/downloads/archived.js
- pages/downloads/index.js
- pages/downloads/swan-lake-release-notes/[...slug].js
- pages/learn/ballerina-specifications.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/index.js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/why-ballerina/[...slug].js
- styles/globals.css
- utils/archived-lm.json
> $subject
> Fixes #4894, #4927, #4886, #4953, #4950
> Fix spacing issues, add BBE redirect and new archive page

- robots.txt
> Allow crawling the dev site

- spec/spec.md
Update the sections and the intro of spec page.
> Fixes #4941
> Update the sections and the intro of spec page

- CNAME
> Update the CNAME with pre-prod url

- package-lock.json
- package.json
- pages/learn/get-started/[...slug].js
Reverts ballerina-platform/ballerina-dev-website#5019
> Revert "Pl test"

- cookie-policy.md
Fix the typo in the cookie policy.
> Fixes #
> Fix the typo in the cookie policy

- components/common/pg-toc/Toc.js
- pages/cookie-policy.js
- pages/downloads/0.9.x-release-notes/[...slug].js
- pages/downloads/1.0.x-release-notes/[...slug].js
- pages/downloads/1.1.x-release-notes/[...slug].js
- pages/downloads/1.2.x-release-notes/[...slug].js
- pages/downloads/swan-lake-release-notes/[...slug].js
- pages/learn/ballerina-specifications.js
- pages/learn/by-example/index.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/index.js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/license-of-site.js
- pages/privacy-policy.js
- pages/security-policy.js
- pages/terms-of-service.js
- pages/trademark-usage-policy.js
- pages/why-ballerina/[...slug].js
- styles/globals.css
Added custom `Page Toc` for `ballerina-release` pages.
> Added custom `Page Toc` for `ballerina-release` pages

- cookie-policy.md
Fix typos in the cookie policy.
> Fixes #
> Fix typos in the cookie policy

- components/common/left-nav/LeftNav.js
- components/common/top-nav/TopNav.js
- components/learn/language/Language.js
- layouts/LayoutHome.js
- pages/community/index.js
- pages/downloads/archived.js
- pages/learn/use-cases.js
- utils/archived-lm.json
> $subject
> Fixes #5027, #5026, #4790, #4758
> Move Api Docs link to left nav and add meta tags to pages

- swan-lake/get-started/install-ballerina/installation-options.md
Update the `Build from source` page link.
> Fixes #4881
> Update the `Build from source` page link

- components/common/top-nav/TopNav.js
- layouts/LayoutDownloads.js
- layouts/LayoutHome.js
- pages/community/ballerina-newsletter.js
- pages/community/ballerina-tech-talk.js
- pages/community/events.js
- pages/community/index.js
- pages/community/resources.js
- pages/downloads/archived.js
> Add meta data to improve SEO

- learn/guides/distinctive-language-features/network-interaction.md
$title
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/37237
> Add resource access action learn section

- components/community/get-involved/GetInvolved.js
Update the active proposals description.
> Fixes #
> Update the active proposals description

- components/common/search/Search.js
> Point to Algolia pre-prod index

- .github/workflows/generatemd.yml
> Add generatemd.yml file

- learn/guides/test-ballerina-code/configure-tests.md
> Correct Configure tests md file

- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
$subject
Fixes: https://github.com/ballerina-platform/ballerina-dev-website/issues/4880
> Make improvements to building a data service guide

- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/learn-the-platform/ballerina-central/publish-packages-to-ballerina-central.md
Improve the Ballerina Central learn page.
> Fixes #4866
> Improve the Ballerina Central learn page

- .github/workflows/node.js.yml
- components/common/pg-toc/Toc.js
- styles/globals.css
- swan-lake/learn-the-language/distinctive-language-features/advanced-general-purpose-language-features.md
- utils/rl.json
> Remove special characters in page toc & fix style issues

- README.md
- components/common/footer/Footer.js
- components/common/footer/Footer.module.css
- public/img/rss.svg
> Update the README content

- components/common/footer/Footer.js
- components/common/footer/Footer.module.css
- public/img/rss.svg
> Add the Subscribe via RSS button to the B.io footer

- _data/distinctivelangfeaturesnavswanlake.yml
- swan-lake/learn-the-language/distinctive-language-features/advanced-general-purpose-language-features.md
- swan-lake/learn-the-language/language-basics.md
$title.
- Addresses point 1 of https://github.com/ballerina-platform/ballerina-dev-website/issues/4822
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4936 (except the last point - see https://github.com/ballerina-platform/ballerina-dev-website/issues/4936#issuecomment-1207763281)
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4937 (except for point 1 - see https://github.com/ballerina-platform/ballerina-dev-website/issues/4937#issuecomment-1207765103)
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4942
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4956
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/4957
- Fixes …
> Address review suggestions for the language guide

- swan-lake/learn-the-language/language-basics.md
Improve the `Language basics` page.
> Fixes #4935
> Improve the `Language basics` page

- components/community/events/past-events/PastEvents.module.css
- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-use-cases/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-use-cases/write-a-graphql-api-with-ballerina.md
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/featured-use-cases/write-a-restful-api-with-ballerina.md
> Sync with prod

- components/community/events/past-events/PastEvents.module.css
- styles/globals.css
- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-use-cases/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-use-cases/write-a-graphql-api-with-ballerina.md
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/featured-use-cases/write-a-restful-api-with-ballerina.md
> Fix search box getting hidden in mobile view

- components/common/footer/Footer.js
- components/common/left-nav/LeftNav.js
- components/common/left-nav/LeftNavYaml.js
- components/common/newsletter-subscription/NewsletterSubscription.js
- components/common/pg-toc/Toc.js
- components/common/prev-next/PrevNext.js
- components/common/redirect-message/RedirectMessage.js
- components/common/search/Search.js
- components/common/search/search-box/SearchBox.js
- components/common/search/search-hits/SearchHits.js
- components/common/top-nav/TopNav.js
- components/common/upcoming-events/UpcomingEvents.js
- components/community/events/past-events/PastEvents.module.css
- styles/globals.css
- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-use-cases/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-use-cases/write-a-graphql-api-with-ballerina.md
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/featured-use-cases/write-a-restful-api-with-ballerina.md
> Add license header for common components

- .github/workflows/node.js.yml
- pages/learn/by-example/index.js
- styles/globals.css
Add links to sections of BBE landing page.
> Add links to sections of BBE landing page

- components/common/meta/Meta.js
- components/home-page/videos/Videos.module.css
- layouts/Layout404.js
- layouts/LayoutCommunity.js
- layouts/LayoutDocs.js
- layouts/LayoutDownloads.js
- layouts/LayoutHome.js
- layouts/LayoutLearn.js
- layouts/LayoutOther.js
- layouts/LayoutRN.js
- layouts/LayoutSpec.js
- next-sitemap.config.js
- utils/CNAME
- utils/robots.txt
> Update meta data for prod deployment

- components/home-page/videos/Videos.module.css
> Fix play button position in  safari

- components/home-page/videos/Videos.module.css
- next-sitemap.config.js
- utils/CNAME
- utils/robots.txt
> Create new CNAME & robots.txt file for prod

- .github/workflows/ballerina_by_example_on_demand_update.yml
Create `Next.js` BBE generation on demand workflow.
> Create `Next.js` BBE generation on demand workflow

- components/community/slack/Slack.js
- pages/community/index.js
> Fix Slack Registration

- policy/license-of-site.md
pdate sentence case in site license titles.
> Fixes #
> Update sentence case in site license titles

- pages/learn/by-example/index.js
Update `next/link` in BBE landing page.
> Update `next/link` in BBE landing page

- policy/cookie-policy.md
Update the cookie policy with the cookie list.
> Fixes #4951
> Update the cookie policy with the cookie list

- .github/workflows/node.js.yml
> Change branches in node.js.yml workflow

- package-lock.json
- package.json
- pages/spec/lang/draft/index.js
- styles/globals.css
> Fix rendering issues in spec/lang/drafts landing page

- .github/workflows/node.js.yml
Revoke removing directories in `node.js.yml`.
> Revoke removing directories in `node.js.yml`

- .github/scripts/bbe/convertMarkdown.js
Update BBE generation workflow to support `image tags`.
> Update BBE generation workflow to support `image tags`

- .github/workflows/ballerina_by_example_on_demand_update.yml
Update default branch in BBE on demand generation workflow.
> Update default branch in BBE on demand generation workflow

- .github/workflows/ballerina_by_example_on_demand_update.yml
Update code checkout branch in BBE generation workflow.
> Update code checkout branch in BBE generation workflow

- downloads/swan-lake-release-notes/swan-lake-alpha1/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-alpha2/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-beta6/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
- swan-lake/featured-use-cases/work-with-data-using-queries-in-ballerina.md
- swan-lake/learn-the-platform/java-interoperability/java-interoperability-guide/ballerina-ffi.md
- swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md
Fix broken links after master sync of new site.
> Fixes #
> Fix broken links after master sync of new site

- downloads/1.2.x-release-notes/1.2.13.md
- downloads/swan-lake-release-notes/swan-lake-beta3/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
- swan-lake/learn-the-platform/ballerina-tooling/graphql-client-tool.md
Fix more broken links on the new site master branch.
> Fixes #
> Fix more broken links on master

- components/common/redirect-message/RedirectMessage.js
- components/common/search/Search.js
- pages/_document.js
- pages/learn/by-example/index.js
- pages/learn/index.js
- pages/spec/lang/draft/index.js
- styles/globals.css
> Point Search to prod index

- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/learn-the-platform/ballerina-tooling/graphql-client-tool.md
Fix two more broken links.
> Fixes #
> Fix two more broken links

- downloads/swan-lake-release-notes/swan-lake-alpha3/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-alpha4/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-alpha5/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-beta2/RELEASE_NOTE.md
Fix all the update tool broken links.
> Fixes #
> Fix all the update tool broken links

- swan-lake/learn-the-platform/ballerina-tooling/graphql-client-tool.md
> Test graphql.md

- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-use-cases/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-use-cases/write-a-graphql-api-with-ballerina.md
- swan-lake/get-started/get-started-with-ballerina.md
- swan-lake/learn-the-platform/ballerina-tooling/asyncapi-tool.md
Fix more broken links on the new live site.
> Fixes #
> Fix more broken links on the new live site

- components/common/left-nav/LeftNavYaml.js
> Fix broken links in BBE landing page

- .github/scripts/bbe/convertMarkdown.js
> Add html to bbes

- .github/scripts/bbe/convertMarkdown.js
Reverts ballerina-platform/ballerina-dev-website#5259
> Revert "Add html to bbes"

- downloads/1.2.x-release-notes/1.2.10.md
- downloads/1.2.x-release-notes/1.2.11.md
- downloads/1.2.x-release-notes/1.2.8.md
- downloads/1.2.x-release-notes/1.2.9.md
- downloads/RELEASE_NOTE.md
- downloads/stable-release-notes/1.2.10/RELEASE_NOTE.md
- downloads/stable-release-notes/1.2.11/RELEASE_NOTE.md
- downloads/stable-release-notes/1.2.12/RELEASE_NOTE.md
- downloads/stable-release-notes/1.2.13/RELEASE_NOTE.md
- downloads/stable-release-notes/1.2.8/RELEASE_NOTE.md
- downloads/stable-release-notes/1.2.9/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/2201.1.0/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview5/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview7/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-preview8/RELEASE_NOTE.md
> Fix broken links in release notes

- layouts/Layout404.js
- layouts/LayoutCommunity.js
- layouts/LayoutDocs.js
- layouts/LayoutDownloads.js
- layouts/LayoutHome.js
- layouts/LayoutLearn.js
- layouts/LayoutOther.js
- layouts/LayoutRN.js
- layouts/LayoutSpec.js
> Include CookiePro for layouts
> Include CookiePro for layouts

- components/common/left-nav/LeftNavYaml.js
- pages/learn/by-example/[bbe].js
- pages/learn/by-example/index.js
Update BBE navigation panel.
- Added for BBE mobile view.
- Expanded navigation panel for BBE landing page.
> Update BBE navigation panel

- swan-lake/learn-the-language/distinctive-language-features/concurrency.md
> Add rollback statement learn page section

- .github/scripts/sync_master_with_dev.py
> Handle no commits scenario in sync PR

- .github/scripts/bbe/convertMarkdown.js
Fix new line rendering for BBE out files.
Fixes #5277
> Fix new line rendering for BBE out files

- .github/workflows/ballerina_by_example_on_demand_update.yml
Fix the dist repo branch checkout in on demand BBE action.
> Fixes #
> Fix the dist repo branch checkout in on demand BBE action

- components/learn/language/Language.js
- swan-lake/learn-the-language/language-walkthrough.md
> Add headings on the language walkthrough page

- .github/workflows/ballerina_by_example_on_demand_update.yml
Fix the BBE workflow master sync during checkout.
> Fixes #
> Fix the BBE workflow master sync during checkout

- components/home-page/bal-action/BalAction.js
> Remove html encodings from Ballerina examples

- .github/workflows/generatemd.yml
Update the active proposals workflow.
> Fixes #5081 and #5205
> Update the active proposals workflow

- styles/globals.css
> Fix rendering blockquotes in BBEs

- styles/globals.css
> Fix style issues in BBE lists

- pages/learn/get-started/[...slug].js
- swan-lake/get-started/install-ballerina/installation-options.md
> Add missing zip file urls

- components/home-page/bal-action/BalAction.js
> Remove html encoding from home page samples

- components/common/footer/Footer.js
- components/community/discord/Discord.js
> Update discord url

- components/home-page/bal-action/BalAction.js
> Update the code in BIA samples

- pages/_document.js
> Remove noindex meta tags

- components/common/left-nav/LeftNav.js
- layouts/Layout404.js
- layouts/LayoutCommunity.js
- layouts/LayoutDocs.js
- layouts/LayoutDownloads.js
- layouts/LayoutHome.js
- layouts/LayoutLearn.js
- layouts/LayoutOther.js
- layouts/LayoutRN.js
- layouts/LayoutSpec.js
> Add viewport meta tag and fix build warnings

- layouts/Layout404.js
- layouts/LayoutCommunity.js
- layouts/LayoutDocs.js
- layouts/LayoutDownloads.js
- layouts/LayoutHome.js
- layouts/LayoutLearn.js
- layouts/LayoutOther.js
- layouts/LayoutRN.js
- layouts/LayoutSpec.js
> Remove unused cookie-pro scripts

- components/home-page/bal-action/action-bbe/consuming-services.md
- components/home-page/bal-action/action-bbe/graphql-api.md
- components/home-page/bal-action/action-bbe/grpc-api-proto.md
- components/home-page/bal-action/action-bbe/grpc-api.md
- components/home-page/bal-action/action-bbe/kafka-consumer-producer.md
- components/home-page/bal-action/action-bbe/restful-api.md
- components/home-page/bal-action/action-bbe/working-with-data.md
- components/home-page/bal-action/action-bbe/working-with-databases.md
> Include action bbes in md files

- swan-lake/learn-the-language/language-basics.md
> Update the lang library section

- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-use-cases/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
Improve the K8S deployment get started guide.
> Fixes #4814
> Improve the K8S deployment get started guide

- community/newsletter/2022-7.md
- community/proposals/active-proposals.md
Add the Aug 2022 newsletter to master.
> Fixes #
> Add the Aug 2022 newsletter to master

- community/newsletter/2022-7.md
- layouts/Layout404.js
- layouts/LayoutCommunity.js
- layouts/LayoutDocs.js
- layouts/LayoutDownloads.js
- layouts/LayoutHome.js
- layouts/LayoutLearn.js
- layouts/LayoutOther.js
- layouts/LayoutRN.js
- layouts/LayoutSpec.js
- pages/_document.js
> Fix issues in the newsletter & add missing GA scripts

- styles/globals.css
> Remove extra space in spec contents

- downloads/swan-lake-release-notes/swan-lake-2201.2.0/RELEASE_NOTE.md
> Improve terms used in the release note for isolated feature

- components/common/top-nav/TopNav.js
- components/common/top-nav/TopNav.module.css
> Add hackathon banner

- _data/swanlake-latest/metadata.json
- _data/swanlake_release_notes_versions.json
> Update metadata for 2201.2.0 release

- _data/events.json
> Add missing past events

- utils/archived-lm.json
> Add missing archived version to the left nav

- components/downloads/packs/Packs.js
- components/downloads/packs/Packs.module.css
- pages/downloads/index.js
> Point pre-prod and dev environments to distribution-dev environment

- components/downloads/packs/Packs.js
- components/downloads/packs/Packs.module.css
- layouts/Layout404.js
- layouts/LayoutCommunity.js
- layouts/LayoutDocs.js
- layouts/LayoutDownloads.js
- layouts/LayoutHome.js
- layouts/LayoutLearn.js
- layouts/LayoutOther.js
- layouts/LayoutRN.js
- layouts/LayoutSpec.js
- pages/_document.js
- pages/downloads/index.js
> Update Google Tag Manager scripts

- public/spec/lang/master/index.html
- public/spec/lang/master/spec.xml
> Resolve conflicts in spec/lang

- downloads/swan-lake-release-notes/swan-lake-2201.2.0/RELEASE_NOTE.md
> Update the spec version

- styles/globals.css
> Fix image rendering issue in grpc tutorial

- downloads/swan-lake-release-notes/swan-lake-2201.1.2/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
> Add swan-lake-2201.1.2 release note

- components/community/discord/Discord.js
- components/community/discord/Discord.module.css
> Update discord member count

- components/community/discord/Discord.module.css
> Fix styling issues in Discord member count

- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
$subject
Fixes: https://github.com/ballerina-platform/ballerina-dev-website/issues/5524
> Change content type in CURL request in Build a data service

- _data/stable-latest/metadata.json
> Update metadata.json for 1.2.32 release

- components/common/top-nav/TopNav.js
> Update hackathon banner

- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
Update instructions on MySQL driver import.
> Fixes #5479
> Update instructions on MySQL driver import

- components/home-page/videos/Videos.module.css
> Fix jumble of play button in home page videos
Firefox
Chrome
Safari 
> Fixes #5099
> Fix jumbled play button in home page video 

- .github/workflows/prod_sync_gh-pages.yml
- components/common/redirect-message/RedirectMessage.js
- components/common/top-nav/TopNav.js
> Add redirects to BBE urls with .html and remove hackathon banner

- .github/workflows/prod_sync_gh-pages.yml
> Automate prod site update

- .github/scripts/bbe/convertMarkdown.js
- styles/globals.css
> $subject
> Fixes #5351 & #5560
> Indent elements inside lists & add tooltips to BBE buttons

- components/common/left-nav/LeftNav.js
- pages/why-ballerina/[...slug].js
- utils/learn-lm.json
> Add Why-ballerina pages to Learn left-nav

- _data/swanlake-latest/metadata.json
- _data/swanlake_release_notes_versions.json
> Update metadata for release 2201.2.1

- swan-lake/learn-the-platform/ballerina-tooling/graphql-client-tool.md
> Update learn pages content

- pages/downloads/index.js
- styles/Downloads.module.css
> Add VSCode button

- utils/archived-lm.json
> Add 2201.2.0 to archived versions left-nav

- components/common/top-nav/TopNav.js
> Increase the height in mobile nav

- .github/scripts/bbe/convertMarkdown.js
> Hide Edit on Github button if the url returns 404

- swan-lake/learn-the-platform/test-document-the-code/debug-ballerina-programs.md
> Learn update for the debugger run in terminal feature

- downloads/swan-lake-release-notes/swan-lake-2201.2.0/RELEASE_NOTE.md
> Remove the empty "Breaking Changes" section

- downloads/swan-lake-release-notes/swan-lake-2201.2.0/RELEASE_NOTE.md
> Introduce a separate "Backward Incompatible Changes" section

- components/common/highlight-syntax/HighlightSyntax.js
- components/common/main-content/MainContent.js
- pages/learn/ballerina-specifications.js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/policies/[slug].js
- pages/why-ballerina/[...slug].js
> Improve Shiki loading time

- swan-lake/learn-the-platform/ballerina-tooling/strand-dump-tool.md
> Edit strand dump guide for update 3 changes

- _data/swanlake-latest/metadata.json
- _data/swanlake_release_notes_versions.json
- utils/archived-lm.json
- utils/rl.json
> Update metadata.json for 2201.2.2 release

- downloads/swan-lake-release-notes/swan-lake-2201.2.2/RELEASE_NOTE.md
> Add swan-lake-2201.2.2 release note

- swan-lake/featured-use-cases/write-a-restful-api-with-ballerina.md
Reverts ballerina-platform/ballerina-dev-website#5686
> Revert "Add content type header to the curl request for data binding"

- downloads/swan-lake-release-notes/swan-lake-2201.2.2/RELEASE_NOTE.md
> Add language server 2201.2.2 release note

- swan-lake/featured-use-cases/write-a-restful-api-with-ballerina.md
> Add content type header to the curl request for data binding

- swan-lake/featured-use-cases/write-a-restful-api-with-ballerina.md
> Escape special characters in the JSON payload of the curl cmd

- swan-lake/why-ballerina/cloud-native.md
> Remove untainted annotation usage

- swan-lake/featured-use-cases/write-a-graphql-api-with-ballerina.md
> This PR removes additional curly brace appeared in a code block and updates tree diagram appeared in the write-a-graphql-api-with-ballerina.md file
> Minor changes to graphql featured use-case

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
> Update output for learn pages

- swan-lake/learn-the-language/distinctive-language-features/data.md
> Fix issues in `Data.md`

- swan-lake/learn-the-platform/java-interoperability/java-interoperability-guide/ballerina-ffi.md
- resolves a few missing imports in code snippets 
- fixes some code highlighting issues
- addresses a few code formatting issues
> Update ballerina FFI guide

- swan-lake/learn-the-platform/ballerina-tooling/ballerina-shell.md
> Update Shell output texts

- swan-lake/why-ballerina/flexibly-typed.md
> Fix why pages

- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
> Fix annotation changes in grpc service

- swan-lake/learn-the-platform/test-document-the-code/generate-code-documentation.md
> Make minor change to output text in documentation guide

- swan-lake/learn-the-language/distinctive-language-features/network-interaction.md
Update `network interaction.md`.
> Update `network interaction.md`.

- swan-lake/learn-the-language/distinctive-language-features/data.md
Update table,stream and xml content in `data.md` File
> Update table,stream and xml content in `data.md` File

- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
> Fix issues with building a data service use case example

- swan-lake/learn-the-platform/ballerina-tooling/asyncapi-tool.md
> Add minor code changes to the asyncapi tool doc

- utils/archived-lm.json
> Add 2201.2.2 to versions list

- swan-lake/learn-the-platform/configure-observe/observe-ballerina-programs.md
> Fix observability page issues

- .github/scripts/bbe/convertMarkdown.js
> Fix alignment of buttons in expression-oriented style BBE

- swan-lake/why-ballerina/concurrent.md
$title
Fixes #5703
Fixes #4769
> Remove strand annotation from `concurrent.md`

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
- utils/rl.json
Add the 2201.2.3 release note.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/5734
> Add the 2201.2.3 release note

- _data/ballerinagraphqlsupportswanlake.yml
- swan-lake/learn-the-platform/ballerina-tooling/graphql-client-tool.md
$title
> Fixes #
https://github.com/ballerina-platform/graphql-tools/issues/110
> Update GraphQL learn pages with IDL support

- downloads/swan-lake-release-notes/swan-lake-2201.2.1/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.2.2/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
Fix the troubleshooting links in release notes.
> Fixes #5785
> Fix the troubleshooting links in release notes

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
>  Update release note with OpenAPI changes that included in this PR https://github.com/ballerina-platform/ballerina-release/pull/2174
> Sync the release note with OpenAPI changes 

- _data/stable-latest/metadata.json
> Update metadata.json for 1.2.34 release

- downloads/1.2.x-release-notes/1.2.34.md
- utils/archived-lm.json
- utils/rl.json
Create the 1.2.34 release note.
> Fixes #
> Create the 1.2.34 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
> Include publishing this release part
> Include publishing this release part

- swan-lake/learn-the-platform/source-code-dependencies/manage-dependencies.md
> Update manage-dependencies learn page

- _data/ballerinagraphqlsupportswanlake.yml
- swan-lake/learn-the-platform/ballerina-tooling/graphql-client-tool.md
Reverts ballerina-platform/ballerina-dev-website#5755
> Revert "Update GraphQL learn pages with IDL support"

- components/home-page/bal-action/BalAction.js
- components/home-page/events/Events.js
- components/home-page/videos/Videos.js
- components/home-page/why-bal/WhyBal.js
- components/learn/language/Language.js
- components/learn/new/New.js
- components/learn/platform/Platform.js
- components/learn/use-cases/UseCases.js
- pages/index.js
- pages/learn/index.js
> Add the Pilcrow Sign to the Topics on the Home Page & Learn landing page

- swan-lake/learn-the-platform/source-code-dependencies/manage-dependencies.md
> Improve manage dependencies documentation
> Improve manage dependencies documentation

- downloads/swan-lake-release-notes/swan-lake-2201.3.0/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Create the 2201.3.0 release note.
> Fixes #
> Create the 2201.3.0 release note

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Create the 2201.4.0 release note.
> Fixes #
> Create the 2201.4.0 release note

- downloads/swan-lake-release-notes/swan-lake-2201.3.0/RELEASE_NOTE.md
> Update outer join change log

- .github/workflows/pre-prod_sync.yml
> Add an input parameter to select the source branch

- .github/scripts/bbe/convertMarkdown.js
> Stop creating Playgroud links in n BBEs

- swan-lake/learn-the-platform/ballerina-tooling/strand-dump-tool.md
> Add details to get strand dump during `bal test`

- next.config.js
- utils/rearrangeFiles.sh
> Fix broken links in Native support section

- components/learn/platform/Platform.js
- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Change title to sentence case

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Fix issue with frontmatter and remove repeating intro

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Add suggestions from review comments

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Change the image size using HTML

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Format the docker file

- downloads/swan-lake-release-notes/swan-lake-2201.3.0/RELEASE_NOTE.md
Review the 2201.3.0 release note.
> Fixes #
> Review the 2201.3.0 release note

- .github/workflows/pre_release_homepage_sample_build.yml
- components/home-page/bal-action/generate-bal-script.py
> Check home page samples along with new releases

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Update native support guide with review comments

- .github/scripts/bbe/convertMarkdown.js
- styles/globals.css
> Fix styling issues in BBE Related links

- .github/scripts/bbe/convertMarkdown.js
> Enable playground button in BBEs

- _data/swanlake-latest/metadata.json
- _data/swanlake_release_notes_versions.json
> Update metadata for 2201.3.0 release

- components/home-page/bal-action/action-bbe/consuming-services.md
- components/home-page/bal-action/action-bbe/graphql-api.md
- components/home-page/bal-action/action-bbe/grpc-api.md
- components/home-page/bal-action/action-bbe/working-with-data.md
- components/home-page/bal-action/action-bbe/working-with-databases.md
> Update home page samples

- utils/rl.json
> Add missing releases to release note navigation

- public/spec/lang/2022R3/index.html
- public/spec/lang/2022R3/spec.xml
- public/spec/lang/2022R3/style/ballerina-language-specification.css
- public/spec/lang/2022R3/style/ballerina-language-specification.js
> Add 2022R3 specs

- .github/scripts/bbe/convertMarkdown.js
> Switch off playground links in BBEs

- public/spec/lang/2022R4/index.html
- public/spec/lang/2022R4/style/ballerina-language-specification.css
- public/spec/lang/2022R4/style/ballerina-language-specification.js
> Add 2022R4 lang specs

- spec/spec.md
Update the 2022R4 lang spec.
> Fixes #6032
> Update the 2022R4 lang spec

- spec/spec.md
Update the 2022R4 version.
> Fixes #
> Update the 2022R4 version

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Update native support guide with Apple M1 support

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/graphql.md
>$subject
Fixes: [#3737](https://github.com/ballerina-platform/ballerina-standard-library/issues/3737)
> Update CLI Documentation with GraphQL Schema Generation Command

- components/learn/platform/Platform.js
- downloads/swan-lake-release-notes/swan-lake-2201.1.0/RELEASE_NOTE.md
- next.config.js
- swan-lake/featured-use-cases/write-a-graphql-api-with-ballerina.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- swan-lake/learn-the-platform/ballerina-tooling/graphql-tool.md
- utils/learn-lm.json
>$subject
Fixes: [#3818](https://github.com/ballerina-platform/ballerina-standard-library/issues/3818)
> Update the GraphQL Tool Guide with SDL Schema Generation

- downloads/swan-lake-release-notes/swan-lake-2201.2.4 /RELEASE_NOTE.md
> Update dev tooling release notes for 2201.2.4

- downloads/swan-lake-release-notes/swan-lake-2201.2.4 /RELEASE_NOTE.md
> Add code to cloud bug fixes to 2201.2.4 release note

- _data/swanlake_release_notes_versions.json
- utils/archived-lm.json
> Update release notes versions

- downloads/swan-lake-release-notes/swan-lake-2201.2.4 /RELEASE_NOTE.md
Fix formatting issues of the 2201.2.4 release note.
> Fixes #
> Fix formatting issues of the 2201.2.4 release note

- downloads/swan-lake-release-notes/swan-lake-2201.3.1/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Create the 2201.3.1 release note.
> Fixes #
> Create the 2201.3.1 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.4/RELEASE_NOTE.md
- utils/rl.json
Fix 2201.2.4 issues.
> Fixes #
> Fix 2201.2.4 issues

- pages/downloads/archived.js
> Remove PGP content from archived page

- components/common/search/Search.js
> Remove extra line

- components/home-page/bal-action/action-bbe/working-with-databases.md
> Remove unnecessary check keyword usage

- components/home-page/bal-action/action-bbe/working-with-databases.md
Add the missing backticks.
> Fixes #
> Add the missing backticks

- downloads/swan-lake-release-notes/swan-lake-2201.3.1/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Add 2201.3.1 release note to the release branch.
> Fixes #
> Add 2201.3.1 release note to the release branch

- downloads/swan-lake-release-notes/swan-lake-2201.3.1/RELEASE_NOTE.md
> Remove ftp change from the release note

- downloads/swan-lake-release-notes/swan-lake-2201.3.1/RELEASE_NOTE.md
Update the issue links in the 2201.3.1 release note.
> Fixes #
> Update the issue links in the 2201.3.1 release note

- downloads/swan-lake-release-notes/swan-lake-2201.2.4/RELEASE_NOTE.md
Update 2201.2.4 release note with Dev Tools improvements.
> Fixes #
> Update 2201.2.4 release note with Dev Tools improvements

- .github/workflows/pre_release_homepage_sample_build.yml
> Update the secret in actions

- .github/workflows/pre_release_homepage_sample_build.yml
> Update sample check

- _data/swanlake-latest/metadata.json
- _data/swanlake_release_notes_versions.json
> Update metadata for 2201.3.1 release

- styles/globals.css
Fix the `Archived versions` page styles.
> Fixes #6091
> Fix the `Archived versions` page styles

- components/common/main-content/MainContent.js
- pages/community/active-proposals.js
- pages/downloads/1.2.x-release-notes/[...slug].js
- pages/downloads/swan-lake-release-notes/[...slug].js
- pages/learn/featured-use-cases/[...slug].js
- pages/learn/get-started/[...slug].js
- pages/learn/learn-the-language/[...slug].js
- pages/learn/learn-the-platform/[...slug].js
- pages/spec/[slug].js
- pages/why-ballerina/[...slug].js
- utils/highlighter.js
> Fix build failure

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Add the 2201.3.2 release note.
> Fixes #
> Add the 2201.3.2 release note

- downloads/swan-lake-release-notes/swan-lake-2201.3.0/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-alpha2/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-alpha3/RELEASE_NOTE.md
> $Subject
Related to https://github.com/wso2-enterprise/internal-support-ballerina/issues/238
> Update 2201.3.0 release note Backward-incompatible changes

- .github/scripts/bbe/convertMarkdown.js
> Switch off playground links

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
> Add language updates bug fixes to 2201.3.2 release notes

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
> Update release note 2201.3.2 with OpenAPI Changes 

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
> Add build tools release notes

- downloads/swan-lake-release-notes/swan-lake-2201.3.0/RELEASE_NOTE.md
> $Subject
Related to https://github.com/wso2-enterprise/internal-support-ballerina/issues/238
> Add steps to resolve the UUID related error to release notes

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Add the 2201.3.2 release note to the release branch.
> Fixes #
> Add the 2201.3.2 release note to the release branch

- _data/swanlake-latest/metadata.json
- _data/swanlake_release_notes_versions.json
> Update metadata for 2201.3.2 release

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
> Update release-note to include component-model-generator bug fixes

- .github/scripts/bbe/convertMarkdown.js
> Switch on playground link

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
> Update release-note for 2201.3.2

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
Update Project Design View bug fixes link.
> Fixes #
> Update `Project Design View` bug fixes link

- downloads/swan-lake-release-notes/swan-lake-2201.3.2/RELEASE_NOTE.md
Update formatting of the 2201.3.2 release note.
> Fixes #
> Update formatting of the 2201.3.2 release note

- components/learn/platform/Platform.js
Fix ampersands and sentence case.
> Fixes #
> Fix ampersands and sentence case

- downloads/swan-lake-release-notes/swan-lake-2201.0.4/RELEASE_NOTE.md
> Add oauth2 package API changes

- downloads/swan-lake-release-notes/swan-lake-2201.0.4/RELEASE_NOTE.md
> Add oauth2 package API changes to 2201.4.0-release-note

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Add GraphQL Changes to 2201.4.0 Release Note

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Add new feature in NATS module to 2201.4.0 Release Note

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Update release note with constraint package updates

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Add runtime release note for `2201.4.0`

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Update the link of std lib bug fixes

- package-lock.json
- package.json
> Upgrade shiki version

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Add LS release note

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Add build tools changes to the release note
> Add build tools changes to the release note

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Update 2201.4.0 release note with OpenAPI changes

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Update the native support guide with the changes in master

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Update release notes with tuple member annotation

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> This PR includes the release-notes for the changes made to the below areas,
> - CLI changes (bal folmat command refactorings)
> - JSON to Record Converter tool changes (generating non-conflicting record names)
> Update release-notes to include tooling changes

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Fix tuple member annotations description

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Expand the guide for native test

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Update release note with annotations on fields of anonymous records

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Add c2c release notes to 2201.4.0 release notes

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Add IO release notes to 2201.4.0 release notes

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Add persist package and tool to the release note

- next-sitemap.config.js
> Fix page indexing issues

- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
> Refactor LS relaese note

- components/learn/platform/Platform.js
- downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
- downloads/vs-code-release-notes/3.3.0.md
- swan-lake/featured-use-cases/build-a-data-service-in-ballerina.md
- swan-lake/featured-use-cases/deploy-ballerina-on-kubernetes.md
- swan-lake/featured-use-cases/work-with-data-using-queries-in-ballerina.md
- swan-lake/featured-use-cases/write-a-graphql-api-with-ballerina.md
- swan-lake/featured-use-cases/write-a-grpc-service-with-ballerina.md
- swan-lake/featured-use-cases/write-a-restful-api-with-ballerina.md
- swan-lake/get-started/get-started-with-ballerina.md
- swan-lake/get-started/install-ballerina/set-up-ballerina.md
- swan-lake/learn-the-platform/ballerina-tooling/asyncapi-tool.md
- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
- swan-lake/why-ballerina/graphical.md
- utils/learn-lm.json
Update VS Code marketplace references.
> Fixes #
> Update VS Code marketplace references

- pages/_document.js
> Update meta tags

- _data/stable-latest/metadata.json
> Update metadata.json for 1.2.35 release

- _data/stable-latest/metadata.json
> Update metadata.json for `1.2.36` release

- downloads/1.2.x-release-notes/1.2.35.md
- downloads/1.2.x-release-notes/1.2.36.md
- utils/archived-lm.json
- utils/rl.json
> Add the 1.2.36 release note

- swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md
> Add Azure functions CosmosDB trigger changes

- next.config.js
> $subject
> Fixes https://github.com/wso2-enterprise/internal-support-ballerina/issues/159 & https://github.com/wso2-enterprise/internal-support-ballerina/issues/271
> Add content security policies to avoid clickjacking

- components/integrations/code/Code.js
- components/integrations/code/Code.module.css
- components/integrations/code/integration-bbe/github-copilot.md
- components/integrations/code/integration-bbe/network-data.md
- pages/integrations/index.js
- styles/globals.css
> Add sample md files

- _data/swanlake-latest/metadata.json
> Update  2201.4.0 metadata json

- _data/swanlake_release_notes_versions.json
Add 3.2 to archived versions.
> Fixes #
> Add 3.2 to archived versions

- swan-lake/references/style-guide/coding-conventions.md
- swan-lake/references/style-guide/coding-conventions/annotations-documentation-and-comments.md
- swan-lake/references/style-guide/coding-conventions/expressions.md
- swan-lake/references/style-guide/coding-conventions/operators-keywords-and-types.md
> Fix code best practices in style guide

- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/define-data-driven-tests.md
- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/define-test-groups.md
- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/mocking.md
- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/test-a-simple-function.md
- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/test-services-and-clients.md
> Fixes issues in test guide and updates output to match changes in SL update 4
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/6358
> Fix issues in test guide

- components/integration/use-cases/UseCases.js
> Fix link texts

- components/integration/use-cases/UseCases.js
I updated the text on the website to match the document.
> Sync Solve any integration descriptions to match with the doc

- components/integration/code/Code.js
- components/integration/code/Code.module.css
> Fix ipaas image rendering size

- components/integration/code/Code.module.css
> Fix image alignments

- pages/_document.js
- pages/learn/by-example/index.js
- pages/learn/index.js
- pages/usecases/integration/index.js
> Update url path for sm banner
> Fixes #
> Update url path for sm banner

- swan-lake/learn-the-platform/source-code-dependencies/manage-dependencies.md
- swan-lake/learn-the-platform/source-code-dependencies/package-references.md
> Improve docs for platform dependencies
> Improve docs for platform dependencies

- downloads/swan-lake-release-notes/swan-lake-2201.3.4/RELEASE_NOTE.md
- utils/rl.json
> Add 2201.3.4 release note

- utils/archived-lm.json
- utils/rl.json
Add 2201.3.4 to left navs.
> Fixes #
> Add 2201.3.4 to left navs

- components/common/footer/Footer.js
- components/common/footer/Footer.module.css
> Add copyright message

- components/integration/use-cases/UseCases.js
- components/integration/use-cases/UseCases.module.css
> Fix text alignment issues in Use Cases

- components/integration/code/Code.js
- components/integration/code/Code.module.css
- components/integration/code/integration-bbe/12-factor-apps-for-integration-problems.md
- components/integration/code/integration-bbe/connect-with-anything.md
- components/integration/code/integration-bbe/graphql-ballerina-is-graphql.md
- components/integration/code/integration-bbe/http-ballerina-is-http.md
- components/integration/code/integration-bbe/json-ballerina-is-json.md
- components/integration/code/integration-bbe/open-source-zero-lock-in.md
> Add new samples

- components/integration/code/Code.js
- layouts/LayoutCommunity.js
> Highlight active link in TopNav

- components/integration/replace-zapier/code/Code.js
- components/integration/replace-zapier/code/Code.module.css
- components/integration/replace-zapier/code/zapier-bbe/better-security.md
- components/integration/replace-zapier/code/zapier-bbe/community-driven-development.md
- components/integration/replace-zapier/code/zapier-bbe/connect-with-anything.md
- components/integration/replace-zapier/code/zapier-bbe/diagram-when-you-need.md
- components/integration/replace-zapier/code/zapier-bbe/free-and-opensource.md
- components/integration/replace-zapier/code/zapier-bbe/git-based-workflow.md
- components/integration/replace-zapier/code/zapier-bbe/greater-scalability-flexibility-and-customization.md
- components/integration/replace-zapier/intro/Intro.js
- components/integration/replace-zapier/intro/Intro.module.css
- components/integration/replace-zapier/use-cases/UseCases.js
- components/integration/replace-zapier/use-cases/UseCases.module.css
- pages/usecases/integration/replace-zapier/index.js
> Add replace-zapier page

- components/integration/replace-zapier/use-cases/UseCases.js
- components/integration/replace-zapier/use-cases/UseCases.module.css
> Update zapier page content

- components/common/main-content/MainContent.js
- styles/globals.css
> Fix table rendering in mobile view

- components/integration/replace-zapier/code/Code.js
- components/integration/replace-zapier/code/Code.module.css
- components/integration/replace-zapier/code/zapier-bbe/better-security.md
- components/integration/replace-zapier/code/zapier-bbe/community-driven-development.md
- components/integration/replace-zapier/code/zapier-bbe/connect-with-anything.md
- components/integration/replace-zapier/code/zapier-bbe/diagram-when-you-need.md
- components/integration/replace-zapier/code/zapier-bbe/free-and-opensource.md
- components/integration/replace-zapier/code/zapier-bbe/git-based-workflow.md
- components/integration/replace-zapier/code/zapier-bbe/greater-scalability-flexibility-and-customization.md
- components/integration/replace-zapier/intro/Intro.js
- components/integration/replace-zapier/intro/Intro.module.css
- components/integration/replace-zapier/use-cases/UseCases.js
- components/integration/replace-zapier/use-cases/UseCases.module.css
- pages/usecases/integration/replace-zapier/index.js
> Recreate Zapier content

- downloads/swan-lake-release-notes/swan-lake-2201.4.1/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Add release note for 2201.4.1 patch release
> Add 2201.4.1 release note

- components/integration/replace-zapier/code/zapier-bbe/better-security.md
- components/integration/replace-zapier/code/zapier-bbe/connect-with-anything.md
- components/integration/replace-zapier/code/zapier-bbe/greater-scalability-flexibility-and-customization.md
> Fix display issues in code samples

- components/ai/code/Code.js
- components/ai/code/ai-bbe/bring-text-alive-with-openai-chats.md
- components/ai/code/ai-bbe/connectors-for-openai-apis.md
- components/ai/code/ai-bbe/create-images-with-dall-e.md
- components/ai/code/ai-bbe/fine-tune-models-with-your-own-data.md
- components/ai/code/ai-bbe/transcribe-speech-or-music-with-whisper.md
- components/ai/code/ai-bbe/why-is-ballerina-the-way-you-should-write-ai-applications.md
- components/ai/use-cases/UseCases.js
- components/common/top-nav/TopNav.js
- styles/globals.css
> Update content and styles

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Add GraphQL Changes to 2201.5.0 Release Note

- components/ai/code/Code.js
- components/ai/code/ai-bbe/bring-text-alive-with-openai-chats.md
- components/ai/code/ai-bbe/create-ai-powered-apis.md
- components/ai/code/ai-bbe/create-images-with-dall-e.md
- components/ai/code/ai-bbe/fine-tune-models-with-your-own-data.md
- components/ai/code/ai-bbe/libraries-for-ai-operations.md
- components/ai/code/ai-bbe/music1.md
- components/ai/code/ai-bbe/why-is-ballerina-the-way-you-should-write-ai-applications.md
- components/ai/code/ai-bbe/write-robust-api-powered-ai-applications.md
- components/ai/intro/Intro.js
> Fix text issues

- components/ai/code/ai-bbe/why-is-ballerina-the-way-you-should-write-ai-applications.md
> Fix line breaks in code samples

- components/ai/code/ai-bbe/create-ai-powered-apis.md
- components/ai/code/ai-bbe/dalle1.md
- components/ai/code/ai-bbe/dalle3.md
- components/ai/code/ai-bbe/fine-tune-models-with-your-own-data.md
- components/ai/code/ai-bbe/libraries-for-ai-operations.md
- components/ai/code/ai-bbe/music1.md
- components/ai/code/ai-bbe/music2.md
- components/ai/code/ai-bbe/openai1.md
- components/ai/code/ai-bbe/openai2.md
- components/ai/code/ai-bbe/write-robust-api-powered-ai-applications.md
> Fix sample codes

- components/ai/code/ai-bbe/create-ai-powered-apis.md
- components/ai/code/ai-bbe/dalle1.md
- components/ai/code/ai-bbe/dalle2.md
- components/ai/code/ai-bbe/fine-tune-models-with-your-own-data.md
- components/ai/code/ai-bbe/openai1.md
> Fix sample width

- components/ai/code/ai-bbe/why-is-ballerina-the-way-you-should-write-ai-applications.md
> Fix code width

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Add breaking change for `2201.5.0` update

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Add a few language breaking changes for Update 5

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
> Update help text with deprecate command details

- components/ai/code/Code.js
- components/ai/code/Code.module.css
- styles/globals.css
> Update styles in AI page

- components/ai/code/ai-bbe/why-is-ballerina-the-way-you-should-write-ai-applications.md
- components/ai/intro/Intro.js
> Update conetent in AI page

- components/ai/intro/Intro.js
- pages/usecases/ai/index.js
> Update styles and content

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
Add release note for Ballerina regular expressions
Fixes #6581
> Add release note for Ballerina regular expressions

- components/home-page/bal-action/BalAction.js
> Switch to integration-samples repo
> Switch to integration-samples repo

- _data/stable-latest/metadata.json
- downloads/1.2.x-release-notes/1.2.37.md
- utils/archived-lm.json
- utils/rl.json
> Update `metadata.json` and release note for release 1.2.37

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Update 2201.5.0 release note with OpenAPI changes

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Add isolated change to the release note

- .github/workflows/add_link_checker.yml
> Include npm link checker

- .github/workflows/add_link_checker.yml
> Separate the steps

- components/common/upcoming-events/UpcomingEvents.js
> Show recent events first in upcoming events

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Update 2201.5.0 release notes with bindgen tool improvements

- _data/release_notes_versions.json
- _data/stable-latest/metadata.json
> Remove `vsix` link for 1.2.37

- _data/events.json
> Fix events order

- .github/workflows/add_link_checker.yml
> Improve link checker

- swan-lake/learn-the-language/language-basics.md
- swan-lake/learn-the-platform/source-code-dependencies/style-guide/top-level-definitions.md
- swan-lake/learn-the-platform/test-document-the-code/generate-code-documentation.md
Reverts ballerina-platform/ballerina-dev-website#6647
> Revert "Fix syntax highlighting issues"

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
Update the release note with persist V3 changes
> Update the release note with persist V3 changes

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Update Test framework release note
> Update Test framework release note

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Add c2c release note changes for 2201.5.0

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Update dev tooling release notes

- _data/swanlake-latest/metadata.json
- downloads/swan-lake-release-notes/swan-lake-2201.4.1/RELEASE_NOTE.md
> Update release note and `metadata.json` for `2201.4.1 release`

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Update release note with http changes

- _data/swanlake_release_notes_versions.json
> Update `swanlake_release_notes_versions.json` for `2201.4.1` release

- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/mocking.md
> Add note about object mocking

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Add NATS and RabbitMQ Changes to 2201.5.0 Release Note

- swan-lake/learn-the-language/language-basics.md
- swan-lake/learn-the-platform/source-code-dependencies/style-guide/top-level-definitions.md
> Fix syntax highlighting issues

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Add test framework improvement as a breaking change
> Add test framework improvement as a breaking change

- swan-lake/learn-the-platform/ballerina-central/publish-packages-to-ballerina-central.md
- swan-lake/learn-the-platform/source-code-dependencies/package-references.md
> $subject
* Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/6669
> Add private package details

- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/mocking.md
- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/test-services-and-clients.md
$subject
> Fixes [distribution-issue](https://github.com/ballerina-platform/ballerina-distribution/issues/4262)
> Replace regex stdlib usages with regexp langlib

- next.config.js
> Update content security policy

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
> Update Release Note with GraphQL Changes

- swan-lake/learn-the-language/distinctive-language-features/advanced-general-purpose-language-features.md
> Fix compilation error in regexp lang guide

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
Rename Update 5 RN folder.
> Fixes #
> Rename Update 5 RN folder

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
> Add runtime breaking change

- components/downloads/packs/Packs.js
- pages/downloads/archived.js
- swan-lake/get-started/install-ballerina/set-up-ballerina.md
> Add ARM64 button

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> This is removed since the issue is fixed with update 5 by providing a separate installer.
> Related issue which is fixed: https://github.com/ballerina-platform/ballerina-lang/issues/39003
> Remove known issue with MAC Apple processor

- downloads/swan-lake-release-notes/swan-lake-2201.5.0 /RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
Review Update 5 breaking changes.
> Fixes #
> Review Update 5 breaking changes

- _data/stable-latest/metadata.json
- downloads/1.2.x-release-notes/1.2.38.md
- utils/archived-lm.json
- utils/rl.json
> Update release note and metadata.json for `1.2.38`

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
> Fix syntax issue in bindgen tool release note
> Fixes #6714
> Fix syntax issue in bindgen tool release note

- .github/workflows/prod_sync_artifacts_on_demand.yml
> Update runner to run on ubuntu-latests

- _data/release_notes_versions.json
- _data/stable-latest/metadata.json
> Remove vsix from release_notes_versions and metadata.json

- styles/globals.css
Update code snippet styles when indented.
> Fixes #
> Update code snippet styles when indented

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
> Update release note with installer changes

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
Fix code formatting in the Update 5 release note.
> Fixes #
> Fix code formatting in the Update 5 release note

- _data/swanlake_release_notes_versions.json
Add 4.1 to  archived versions.
> Fixes #
> Add 4.1 to  archived versions

- components/downloads/packs/Packs.js
- pages/downloads/archived.js
- pages/learn/get-started/[...slug].js
- swan-lake/get-started/install-ballerina/set-up-ballerina.md
> Add arm64 meta data

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
Improve the Update 5 release note.
> Fixes #
> Improve the Update 5 release note

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
Change the `Update Ballerina` section in the Update 5 release note.
> Fixes #
> Change the `Update Ballerina` section in Update 5 release note

- swan-lake/learn-the-language/distinctive-language-features/advanced-general-purpose-language-features.md
Fix post 2201.5.0 issues.
> Fixes #
> Fix post 2201.5.0 issues

- .github/workflows/sw_prod_sync_artifacts.yml
> Update runner to run on ubuntu-latest

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
Fix formatting issue in Up5 release note.
> Fixes #
> Fix formatting issue in Up5 release note

- downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
Fix indentation in Up5 release note.
> Fixes #
> Fix indentation in Up5 release note

- pages/index.js
> Remove CSP

- swan-lake/learn-the-platform/ballerina-central/publish-packages-to-ballerina-central.md
- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/configure-tests.md
> Add improvements to the test and package guides

- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/execute-tests.md
> Adds documentation support for https://github.com/ballerina-platform/ballerina-lang/issues/27158
> Add testerina coverage exclusion content

- components/ai/code/ai-bbe/dalle1.md
- components/ai/code/ai-bbe/music1.md
- components/ai/code/ai-bbe/music2.md
- components/ai/code/ai-bbe/openai1.md
- components/ai/code/ai-bbe/openai2.md
> Update code snippets

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
Update the update tool page.
> Fixes #6755
> Update the update tool page

- downloads/swan-lake-release-notes/swan-lake-2201.3.4/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.4.1/RELEASE_NOTE.md
Review update tool section in the release notes.
> Fixes #6781
> Review update tool section in release notes

- downloads/swan-lake-release-notes/swan-lake-2201.4.2/RELEASE_NOTE.md
- utils/rl.json
> Add release note and r1.json entry for release 2201.4.2

- downloads/swan-lake-release-notes/swan-lake-2201.3.4/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
- downloads/swan-lake-release-notes/swan-lake-2201.4.1/RELEASE_NOTE.md
Fix the versions in update Ballerina section.
> Fixes #
> Fix the versions in update Ballerina section

- swan-lake/learn-the-platform/source-code-dependencies/package-references.md
> Add missing description in Ballerina.toml

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
Review the Update Tool page.
> Fixes #
> Review the Update Tool page

- pages/learn/get-started/index.js
- utils/rearrangeFiles.sh
> Fix routing issues in get-started page

- _data/swanlake_release_notes_versions.json
- utils/archived-lm.json
> Add 2201.4.2 release information

- next.config.js
- swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/aws-lambda.md
- utils/learn-lm.json
Update the AWS Lambda learn page.
> Fixes #
> Update the AWS Lambda learn page

- swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/aws-lambda.md
Update all hyperlinks of AWS Lambda Learn page.
> Fixes #
> Update all hyperlinks of AWS Lambda Learn page

- package-lock.json
- package.json
> Update Shiki version

- _data/swanlake_release_notes_versions.json
- downloads/swan-lake-release-notes/swan-lake-2201.3.5/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
> Add `2201.3.5` release information

- components/ai/code/Code.js
- components/ai/code/ai-bbe/bring-text-alive-with-openai-chats.md
- components/ai/code/ai-bbe/create-images-with-dall-e.md
- components/ai/code/ai-bbe/dalle4.md
- components/ai/code/ai-bbe/effortlessly-create-impactful-business.md
> Update AI page content

- swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md
Remove incorrect text on Azure Functions Learn page.
> Fixes #
> Remove incorrect text on Azure Functions Learn page

- _data/events.json
> Fix order of events

- components/home-page/intro/Intro.js
- components/learn/intro/Intro.js
Update button labels.
> Fixes #
> Update button labels

- spec/spec.md
> Add YAML and TOML module specs

- swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md
Add the section on Azure Functions native.
> Fixes #
> Add the section on Azure Functions native

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Add GraphQL Changes to 2201.6.0 Release Note

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- swan-lake/learn-the-platform/source-code-dependencies/organize-ballerina-code.md
> Include bal new changes and bal init deprecation

- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/configure-tests.md
> Pass configurable variables for bal test

- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/configure-tests.md
> Pass configurable variable for bal test

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Release notes for bal new and bal init changes

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/graphql.md
- swan-lake/learn-the-platform/ballerina-tooling/graphql-tool.md
Reverts ballerina-platform/ballerina-dev-website#6933
> Revert "Update the GraphQL Tool Guide with Ballerina GraphQL service generation"

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Add architecture model generator changes to release note

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Add some FE breaking changes

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Add runtime changes to the 2201.6.0 release note

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Update release note with update tool changes

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
- pages/downloads/0.9.x-release-notes/[...slug].js
- pages/downloads/1.0.x-release-notes/[...slug].js
- pages/downloads/1.1.x-release-notes/[...slug].js
- pages/downloads/1.2.x-release-notes/[...slug].js
- pages/downloads/swan-lake-release-notes/[...slug].js
> Fix styling issues in tables

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Update with constraint and http package changes

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Add persist changes in release notes

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> $Subject
> Fixes #https://github.com/ballerina-platform/openapi-tools/issues/1365
> [2201.6.0] Update release note with the OpenAPI changes

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
> Update release note with interceptor change

- pages/downloads/index.js
> Fix build error

- components/healthcare/code/healthcare-bbe/ballerina-is-hl7.md
> Update hl7 code

- swan-lake/learn-the-platform/native-support/build-a-native-executable.md
> Update GraalVM learn page

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
> Update the update tool documentation

- components/integration/replace-zapier/code/Code.js
- components/integration/replace-zapier/code/zapier-bbe/better-security.md
- components/integration/replace-zapier/code/zapier-bbe/connect-with-anything.md
- components/integration/replace-zapier/code/zapier-bbe/diagram-when-you-need.md
- components/integration/replace-zapier/code/zapier-bbe/free-and-opensource.md
- components/integration/replace-zapier/code/zapier-bbe/git-based-workflow.md
- components/integration/replace-zapier/code/zapier-bbe/greater-scalability-flexibility-and-customization.md
- components/integration/replace-zapier/code/zapier-bbe/trivial-hosting-in-wso2-choreo-ipaas.md
- components/integration/replace-zapier/use-cases/UseCases.js
> Update zapier page

- components/learn/platform/Platform.js
- components/learn/use-cases/UseCases.js
- swan-lake/featured-scenarios/manage-data-persistence-with-bal-persist.md
> Add descriptions for each page link

- swan-lake/learn-the-platform/ballerina-persist/overview.md
- swan-lake/learn-the-platform/ballerina-persist/persist-cli.md
- swan-lake/learn-the-platform/ballerina-persist/persist-client-api.md
- swan-lake/learn-the-platform/ballerina-persist/persist-model.md
- swan-lake/learn-the-platform/ballerina-persist/supported-data-stores.md
> Fix the yaml rendering issue

- _data/release_notes_versions.json
Pull changes sent to master to Up6 branch.
> Fixes #
> Pull changes sent to master to Up6 branch

- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
> Add a minor fix for command output

- components/integration/replace-camel/code/camel-bbe/connect-with-anything.md
- components/integration/replace-camel/code/camel-bbe/for-integrations.md
- components/integration/replace-camel/code/camel-bbe/replace-dsl.md
- pages/usecases/integration/replace-camel/index.js
> Add review changes to camel page

- pages/usecases/eda/index.js
> Update sm banner

- _data/swanlake-latest/metadata.json
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
Add Up6 artifacts to master.
> Fixes #
> Add Up6 artifacts to master

- downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Add the Up6 release note to master.
> Fixes #
> Add the Up6 release note to master

- _data/swanlake_release_notes_versions.json
> Update archived versions

- swan-lake/featured-scenarios/manage-data-persistence-with-bal-persist.md
- swan-lake/learn-the-platform/ballerina-persist/bal-persist-overview.md
- swan-lake/learn-the-platform/ballerina-persist/persist-cli-tool.md
- swan-lake/learn-the-platform/ballerina-persist/persist-model.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
Fix up 6 broken links.
> Fixes #
> Fix up 6 broken links

- swan-lake/learn-the-platform/ballerina-persist/persist-client-api.md
Add the BBE link to the `Persist Client API` page.
> Fixes #
> Add the BBE link to the `Persist Client API` page

- pages/usecases/integration/replace-apollo-graphql/index.js
> Fix build issue on Apollo page

- components/common/top-nav/TopNav.js
- components/microservices/code/Code.js
- pages/usecases/microservices/index.js
> Update top-nav and styles

- components/integration/replace-mulesoft/use-cases/UseCases.js
> Update use cases

- components/eda/code/eda-bbe/email.md
- components/eda/code/eda-bbe/passing-around-messages.md
- pages/usecases/eda/index.js
> Fix EDA page issues

- components/microservices/code/microservices-bbe/designed-for-failure.md
- components/microservices/code/microservices-bbe/devops-agility.md
- pages/usecases/microservices/index.js
> Fix microservices page issues

- components/eda/code/eda-bbe/email.md
- components/eda/code/eda-bbe/file.md
- components/eda/code/eda-bbe/passing-around-messages.md
- components/eda/code/eda-bbe/websocket.md
> Replace links to the code

- components/integration/replace-apollo-graphql/code/Code.js
- components/integration/replace-apollo-graphql/code/Code.module.css
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/code-first-ballerina.md
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/code-first-graphql.md
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/similarities-default-values-ballerina.md
> Make Code-first Section in Replace Apollo GraphQL Page Draggable

- components/eda/code/Code.js
- components/eda/code/eda-bbe/webhook_with_websub.md
> Update websub subscriber code link

- components/microservices/code/Code.js
> Fix the alternating background colors of the blades

- pages/usecases/microservices/index.js
Fixes the title in the main page.
> Fix titles in few places

- components/integration/replace-apollo-graphql/code/Code.js
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/clean-and-simple-code.md
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/cli-tool.md
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/subscription-support.md
> Fix issues in usecases

- swan-lake/learn-the-platform/ballerina-central/publish-packages-to-ballerina-central.md
> Remove proxy content

- swan-lake/learn-the-platform/ballerina-central/publish-packages-to-ballerina-central.md
Reverts ballerina-platform/ballerina-dev-website#7111
> Revert "Remove proxy content"

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Create theUpdate 7 release note.
> Fixes #
> Create the Update 7 release note

- components/integration/replace-java/code/Code.js
- components/integration/replace-java/code/java-bbe/expressive-query.md
- components/integration/replace-java/code/java-bbe/flexible-typing.md
- components/integration/replace-java/code/java-bbe/table-type-ballerina.md
- components/integration/replace-java/code/java-bbe/type-annotation-n-inference-ballerina.md
- components/integration/replace-java/code/java-bbe/type-annotation-n-inference-java.md
- components/integration/replace-java/code/java-bbe/union-types.md
- pages/usecases/integration/replace-java/index.js
> [Java DOP comparison] Rephrase descriptions and fix compilation failure

- _data/events.json
- components/community/tech-talk/past-tech-talks/PastTechTalks.js
Update the 7th June 2023 Tech Talk link.
> Fixes #
> Update the 7th June 2023 Tech Talk link

- components/integration/replace-boomi/code/boomi-bbe/greater-scalability-flexibility-and-customization.md
> Fix issue in page content for ballerina vs. boomi

- swan-lake/learn-the-platform/ballerina-central/publish-packages-to-ballerina-central.md
> Related to https://github.com/ballerina-platform/ballerina-lang/issues/40649
> Fix proxy port

- components/learn/platform/Platform.js
- swan-lake/featured-scenarios/manage-data-persistence-with-bal-persist.md
- swan-lake/learn-the-platform/ballerina-persist/bal-persist-overview.md
- swan-lake/learn-the-platform/ballerina-persist/persist-cli-tool.md
- swan-lake/learn-the-platform/ballerina-persist/persist-client-api.md
- swan-lake/learn-the-platform/ballerina-persist/persist-model.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md
- utils/learn-lm.json
> Change the titles of persist feature based on the review

- pages/usecases/integration/replace-apollo-graphql/index.js
> Fix a typo in replace apollo page

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
Merge 2201.7.0 release note to the release branch.
> Fixes #
> Merge 2201.7.0 release note to the release branch

- downloads/swan-lake-release-notes/swan-lake-2201.5.1/RELEASE_NOTE.md
- utils/archived-lm.json
- utils/rl.json
> Add 2201.5.1 release note

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> Update release note for group by/collect

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> [2201.7.0] - Update release note with persist MSSQL support

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
- swan-lake/learn-the-platform/source-code-dependencies/package-references.md
> Modify based on suggestion on CLI improvements

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
- swan-lake/learn-the-platform/source-code-dependencies/package-references.md
> [2201.7.0] - Modify based on suggestion

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> [2201.7.0] Update the Release Note with GraphQL Improvements

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> [2201.7.0] - Add isolated FP change

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> [2201.7.0] - Change LS release note

- downloads/swan-lake-release-notes/swan-lake-2201.5.1/RELEASE_NOTE.md
> [2201.5.1]Update release note with OpenAPI changes

- swan-lake/learn-the-platform/source-code-dependencies/package-references.md
> [2201.7.0]- Add Graalvm compatibility property changes to package references

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> [2201.7.0] - Update RELEASE_NOTE with http changes

- swan-lake/learn-the-platform/test-document-the-code/generate-code-documentation.md
$title.
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/7151
> Add record documentation example

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> Add runtime changes to the 2201.7.0 release note

- pages/usecases/vs-code-home-page/index.js
Update Ballerina VS Code extension SM banner.
> Fixes #
> Update Ballerina VS Code extension SM banner

- components/integration/replace-apollo-graphql/code/Code.js
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/connect-with-anything.md
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/subscription-support.md
> Update the apollo graphql page with examples

- components/integration/replace-apollo-graphql/code/Code.js
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/better-security.md
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/cli-tool.md
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/connect-with-anything.md
- components/integration/replace-apollo-graphql/code/apollo-graphql-bbe/simplifying-graphql-api-development.md
- pages/usecases/integration/replace-apollo-graphql/index.js
> Fix replace Apollo page issues

- swan-lake/learn-the-platform/test-document-the-code/test-ballerina-code/execute-tests.md
> Add missing content

- downloads/verification-notes/release-artfiacts-verification.md
Adding a template Markdown file to include details of `Ballerina` release artifacts and `cosign` signature verification.
> Add release verification notes

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> Updated released note with some changes
> [2201.7.0] Update release note with few OpenAPI changes

- swan-lake/featured-scenarios/work-with-data-using-queries-in-ballerina.md
> [2201.7.0] - Refactor group by content

- swan-lake/learn-the-language/distinctive-language-features/data.md
> Update the description of Stream type

- components/integration/replace-springboot/code/springboot-bbe/configurability-toml.md
- pages/usecases/integration/replace-springboot/index.js
> $subject
> Part of [#4454](https://github.com/ballerina-platform/ballerina-standard-library/issues/4454)
> Incorporate review suggestions

- downloads/verification-notes/release-artfiacts-verification.md
Update template Markdown file which includes details of Ballerina release artifacts and cosign signature verification.
Fixes #7211
> Update release verification

- downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md
> Update release-note with the official GraalVM support

- _data/release_notes_versions.json
- _data/stable-latest/metadata.json
- downloads/1.2.x-release-notes/1.2.40.md
- swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/update-tool.md
- utils/archived-lm.json
- utils/rl.json
> Add release note for 1.2.40 release

- _data/swanlake_release_notes_versions.json
> Update metadata for 2201.5.1 release

- utils/archived-lm.json
- utils/rl.json
> Update utils with 1.2.40

- downloads/verification-notes/release-artfiacts-verification.md
Include placeholder for `branch` in Verification via `Cosign CLI` section to get updated automatically.
> Update verification section to include placeholder

- pages/downloads/release-artfiacts-verification.js
> Add branch to liquid content

- swan-lake/featured-scenarios/manage-data-persistence-with-bal-persist.md
> Change the field names in persist quick start guide  to camelcase

- swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md
> [2201.7.0] - Add AZF Update 7 GraalVM related changes

- downloads/verification-notes/release-artfiacts-verification.md
> Change formatting of verification notes

- components/integration/code/integration-bbe/json-ballerina-is-json.md
- components/integration/data-oriented-programming/code/Code.js
- components/integration/data-oriented-programming/code/java-bbe/data-immutability.md
- components/integration/data-oriented-programming/code/java-bbe/expressive-query.md
- components/integration/data-oriented-programming/code/java-bbe/flexible-typing-ballerina.md
- components/integration/data-oriented-programming/code/java-bbe/flexible-typing.md
- components/integration/data-oriented-programming/code/java-bbe/json-support.md
- components/integration/data-oriented-programming/code/java-bbe/optional-types.md
- components/integration/data-oriented-programming/code/java-bbe/pattern-matching.md
- components/integration/data-oriented-programming/code/java-bbe/record-type.md
- components/integration/data-oriented-programming/code/java-bbe/stream-type.md
- components/integration/data-oriented-programming/code/java-bbe/table-type.md
- components/integration/data-oriented-programming/code/java-bbe/type-constraints.md
- components/integration/data-oriented-programming/code/java-bbe/union-types.md
- components/integration/data-oriented-programming/code/java-bbe/xml-support-java.md
- components/integration/data-oriented-programming/code/java-bbe/xml-support.md
> [DOP] Update sample URLs in the integration-samples repo
