learn/how-to-extend-ballerina.md
> This PR removes the old content in the "How to extend Ballerina" page and adds new content in its place.
>
> Related PR: ballerinax/hello#18
=> Update how to extend b7a page

downloads/archived.md, downloads/release-notes.md, learn/tools-ides/intellij-plugin.md, learn/tools-ides/vscode-plugin.md, spec.md, v0-991/learn.md, v0-991/learn/ballerina-streaming-reference.md, v0-991/learn/cli-commands.md, v0-991/learn/faq.md, v0-991/learn/getting-started.md, v0-991/learn/how-to-deploy-and-run-ballerina-programs.md, v0-991/learn/how-to-document-ballerina-code.md, v0-991/learn/how-to-extend-ballerina.md, v0-991/learn/how-to-observe-ballerina-code.md, v0-991/learn/how-to-publish-modules.md, v0-991/learn/how-to-structure-ballerina-code.md, v0-991/learn/how-to-test-ballerina-code.md, v0-991/learn/how-to-write-secure-ballerina-code.md, v0-991/learn/intellij-plugin-doc.md, v0-991/learn/quick-tour.md, v0-991/learn/set-up-ballerina-sdk.md, v0-991/learn/style-guide.md, v0-991/learn/tools-ides.md
=> Fix permalink issues

_includes/ballerina-head-landing-page.html, _layouts/ballerina-landing-page.html, downloads/archived.md
(cherry picked from commit ee82c1431c102fac1b61851556712147371157b3)
> Fixes #
=> Update archived page

learn/how-to-write-secure-ballerina-code.md
This PR fixes a bug in Ballerina code examples of the security doc.
=> Fix a bug in security doc

learn/how-to-write-secure-ballerina-code.md
This PR fixes the TOC of https://ballerina.io/learn/how-to-write-secure-ballerina-code/ page
=> Fix TOC of security doc

_includes/ballerina-head-landing-page.html, _includes/ballerina-head.html, downloads/archived.md, js/download/archived_download.js
> Fixing the release note and archive pages
> Fixes #
=> Fixed the conflict in archived and release notes JS

spec/lang/2019R3/experimental.html
=> Update lang.stream URL

learn/how-to-structure-ballerina-code.md
> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/19857
=> Update commands in how to structure

css/ballerina-io-learn.css, css/ballerina-io.css, css/home-page.css, img/main-play-green-btn.svg, index.html
=> Add playground btn to website

img/main-play-green-btn.svg
=> Add a solid play icon for playground link

community.md, learn.md
This is to review and do a few improvements to the Learn page[1].
[1] https://ballerina.io/learn/
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/47
=> Review the Learn Page

learn/by-example/all-bbes.json, learn/by-example/rabbitmq-consumer-with-client-acknowledgement.html, learn/by-example/rabbitmq-consumer-with-data-binding.html, learn/by-example/rabbitmq-consumer-with-qos-settings.html, learn/by-example/rabbitmq-consumer.html, learn/by-example/rabbitmq-producer.html
> Added RabbitMQ BBEs
> Fixes #
=> Added RabbitMQ BBEs

learn/by-example/built-bbes.json
> updated built BBE list
> Fixes #
=> updated built BBE list

_includes/ballerina-head-landing-page.html
> Removed extra archived script
> Fixes #33
=> Removed extra archived script

learn/by-example/awslambda-deployment.html, learn/by-example/docker-deployment.html, learn/by-example/kubernetes-deployment.html, learn/by-example/openshift-deployment.html
> Edit on Github links updated
> Fixes #
=> Edit on Github links updated

sitemap.xml
> Sitemap for the new site to fix the broken search results
> Fixes #
=> Sitemap for the new site

learn/by-example/table-queries-join-with-filtering.html, learn/by-example/table-queries-join.html, learn/by-example/table-queries-select-with-few-output-fields.html, learn/by-example/table-queries-select-with-filtering.html, learn/by-example/table-queries-select-with-group-by.html, learn/by-example/table-queries-select-with-order-by.html
> Adding Table Query BBEs
> Fixes #
=> Adding Table Query BBEs

learn/by-example/table-queries-join-with-filtering.html, learn/by-example/table-queries-join.html, learn/by-example/table-queries-select-with-few-output-fields.html, learn/by-example/table-queries-select-with-filtering.html, learn/by-example/table-queries-select-with-group-by.html, learn/by-example/table-queries-select-with-order-by.html
=> removed extra header

learn.md
=> Change the description of the language specification box

learn/events.md
=> Update events page

community.md
Change the Text "Standard libraries" to "Standard Library"
> Fixes #https://github.com/ballerina-platform/ballerina-dev-website/issues/127
=> Improve the Content of the Community Page

learn/how-to-use-openapi-tools.md
=> Rename ballerinna to ballerina

learn/style-guide.md, learn/style-guide/README.md, learn/style-guide/definitions.md, learn/style-guide/expressions.md, learn/style-guide/statements.md
Resolves issue [#20352](https://github.com/ballerina-platform/ballerina-lang/issues/20352)
=> Fix incorrect code snippets

learn/how-to-test-ballerina-code.md
$title
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/153
=> Remove function mocks section

learn.md
=> Redirection added

learn.md
=> Extra line break character added after meta

js/ballerina-common.js
=> updated the dropdown destination URL

v1-1/learn/api-docs/index.html, v1-1/learn/ballerina-streaming-reference.md, v1-1/learn/cli-commands.md, v1-1/learn/events.md, v1-1/learn/faq.md, v1-1/learn/how-to-deploy-and-run-ballerina-programs.md, v1-1/learn/how-to-document-ballerina-code.md, v1-1/learn/how-to-extend-ballerina.md, v1-1/learn/how-to-generate-code-for-protocol-buffers.md, v1-1/learn/how-to-observe-ballerina-code.md, v1-1/learn/how-to-publish-modules.md, v1-1/learn/how-to-structure-ballerina-code.md, v1-1/learn/how-to-test-ballerina-code.md, v1-1/learn/how-to-use-openapi-tools.md, v1-1/learn/how-to-write-secure-ballerina-code.md, v1-1/learn/installing-ballerina.md, v1-1/learn/quick-tour.md, v1-1/learn/set-up-ballerina-sdk.md, v1-1/learn/style-guide.md, v1-1/learn/style-guide/definitions.md, v1-1/learn/style-guide/expressions.md, v1-1/learn/tools-ides.md, v1-1/learn/tools-ides/intellij-plugin.md, v1-1/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md, v1-1/learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md, v1-1/learn/tools-ides/vscode-plugin.md, v1-1/learn/tools-ides/vscode-plugin/documentation-viewer.md, v1-1/learn/tools-ides/vscode-plugin/graphical-editor.md, v1-1/learn/tools-ides/vscode-plugin/language-intelligence.md, v1-1/learn/tools-ides/vscode-plugin/run-and-debug.md
This will fix the page mapping issue with ballerina.io version 1.1.0.
> Fixes https://github.com/ballerina-platform/ballerina-platform.github.io/issues/94
=> Fix page mapping issue with bio v1.1

learn.md, learn/how-to-keep-ballerina-up-to-date.md
This feature will be released with Ballerina 1.1.0 version
=> How to guide on Ballerina update tool

learn/how-to-keep-ballerina-up-to-date.md
=> Improve content

v1-1/learn.md
=> Update heading tag

v1-1/learn.md
Reverts ballerina-platform/ballerina-dev-website#172 as it served the test purpose we send it for :D
=> Revert "Update heading tag"

v1-1/learn.md
=> Include how to update link

v1-1/learn.md, v1-1/learn/how-to-keep-ballerina-up-to-date.md
> Move how to update article to v1-1 directory
=> Move how to update article to v1-1 directory

css/ballerina-io.css
> When we navigate to learn page the navigation bar is become sloppy between
768px to 991px screen range.
> Fixes #
I override the Navbar collapse point.
You can check this [picture](https://drive.google.com/file/d/1wQEyodlKv99412UOMHbFhkkGHo6HlzYE/view?usp=sharing).
=> Sloppy nav bar fixed,

learn/how-to-deploy-and-run-ballerina-programs.md, v0-991/learn/how-to-deploy-and-run-ballerina-programs.md, v1-0/learn/how-to-deploy-and-run-ballerina-programs.md, v1-1/learn/how-to-deploy-and-run-ballerina-programs.md
We need to add the import ballerina/log; to the configuration given under the "Docker-Based Deployment" section in [1] & [2].
[1] https://ballerina.io/v0-991/learn/how-to-deploy-and-run-ballerina-programs/
[2] https://ballerina.io/v1-0/learn/how-to-deploy-and-run-ballerina-programs/
Fixes #196
=> Add the import/log to Docker-based Deployment

learn/how-to-deploy-and-run-ballerina-programs.md, v0-991/learn/how-to-deploy-and-run-ballerina-programs.md, v1-0/learn/how-to-deploy-and-run-ballerina-programs.md, v1-1/learn/how-to-deploy-and-run-ballerina-programs.md
This is to fix formatting issues in the Docker-based deployment configuration in the "How to Run and Deploy Ballerina Programs" guide.
> Fixes #
=> Fix Formatting of the Docker-Based Deployment Config

learn/quick-tour.md, v1-0/learn/quick-tour.md, v1-1/learn/quick-tour.md
We need to add the @tainted annotation in the HTTP Client configuration in the Quick Tour[1].
[1] https://ballerina.io/learn/quick-tour/
> Fixes #197
=> Add the @tainted Annotation in the Quick Tour

downloads.html
=> updated released date

downloads.html
=> updated the notice

code-of-conduct.md
This adds the Code of Conduct to the B.io and updates it based on the latest version 2.0 as per [1].
[1] https://www.contributor-covenant.org/version/2/0/code_of_conduct
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/129
=> Add the Code of Conduct

code-of-conduct.md
This is to fix the below problem in how the tables are being rendered in [1].
[1] https://ballerina.io/code-of-conduct/
> Fixes #221
=> Fix the Formatting of the Tables in the Code of Conduct

downloads.html
=> Adding 1.1.2 release-updated pack sizes

v1-2/learn/how-to-test-ballerina-code.md
To update the 'how-to-test-ballerina-code' page
=> Add Function mocking documentation

v1-2/learn/how-to-use-openapi-tools.md, v1-2/learn/style-guide.md, v1-2/learn/style-guide/README.md, v1-2/learn/style-guide/definitions.md, v1-2/learn/style-guide/operators_keywords_and_types.md, v1-2/learn/style-guide/statements.md
This will add fixes to the issues in how-to guide for openapi and Style guide
=> Fix how to guide for OpenAPI and Style guide

v1-2/learn/how-to-generate-code-for-protocol-buffers.md
Update how-to guide of protocol buffers to Ballerina generation tool
=> Update how to guide of protocol buffers

v1-2/learn/how-to-document-ballerina-code.md
=> Fix how to guide

v1-2/learn/how-to-test-ballerina-code.md
> Remove unsupported Service Skeleton doc
=> Remove unsupported Service Skeleton doc

v1-2/learn/how-to-deploy-and-run-ballerina-programs.md
> Document was out of date with source code resource being missing. Updated the sample in kubernetes section. 
> Fixes #
=> Update deploy and run BBG for 1.2 release

v1-2/learn/how-to-deploy-and-run-ballerina-programs.md
=> Fix markdown tables in deploy and run BBG

v1-2/learn/how-to-deploy-and-run-ballerina-programs.md
=> Fix tables in deploy and run bbg

v1-2/learn/how-to-write-secure-ballerina-code.md
- Updated the code segments to read ballerina.home from the config, instead of system variable (${ballerina.home})
- Added scope section to JWT example to match the correct behavior described in the text
- Updated variable names to correct case, to avoid errors when pasted into the editor.
- Fixed errors in example code segments
> Fixes #
=> Update secure code guide with 1.2 changes

v1-2/learn/by-example/http-1.1-to-2.0-protocol-switch.html, v1-2/learn/by-example/http-2.0-server-push.html
=> Fix broken BBE links

v1-2/learn/api-docs/ballerina/http/index.html
This will fix broken BBE in http api doc
=> Fix apidocs broken bbe for http

downloads.html
=> Release date updated

v1-2/learn/api-docs/ballerina/test/annotations.html, v1-2/learn/api-docs/ballerina/test/index.html
> Add missing parts in test api doc
=> Add missing parts in test api doc

why/the-network-in-the-language.md
=> Update VSCode URL

why/from-code-to-cloud.md, why/sequence-diagrams-for-programming.md
=> Update why pages

downloads.html
=> updated the dist upgrade command

downloads.html
=> updated the released date

_layouts/ballerina-layer-page.html, why/from-code-to-cloud.md, why/sequence-diagrams-for-programming.md, why/the-network-in-the-language.md
Update layout
- Added new layer page template
=> Update WHY page layout

_includes/ballerina-example-head.html, _includes/ballerina-head-landing-page.html, _includes/ballerina-head.html, _includes/ballerina-home-head.html
> Updated the template files to include the meta keywords
> Fixes #
=> Added SEO tags

.github/workflows/update_release_note_versions_json.yml
=> Add workflow to auto gen release_note_versions JSON

_data/metadata.json
=> Update version in the json file

_data/metadata.json
> Please note that this PR is sent to test a github workflow
=> Update version of metadata json file

_data/metadata.json
> This is PR is a PR created to test a github workflow.
=> Update version of release-note-versions json file

learn.md, learn/cli-commands.md
=> replaced old versioned URLS

index.html
=> Updated the BBE link

0.991/learn.md, 1.0/learn.md, 1.1/learn.md
> Added redirections to old /learn pages
> Fixes #
=> Added redirections to old /learn pages

_includes/nav.html
> updated the version drop down
> Fixes #
=> updated the version drop down

downloads/release-notes/1.2.2/RELEASE_NOTE.md
=> Add release note for 1.2.2

downloads/release-notes/1.2.2/RELEASE_NOTE.md
=> Fix formatting issues

1.1/learn/installing-ballerina.md
=> Update redirect from in 1.1

1.0/learn/ballerina-streaming-reference.md, 1.0/learn/cli-commands.md, 1.0/learn/faq.md, 1.0/learn/how-to-deploy-and-run-ballerina-programs.md, 1.0/learn/how-to-document-ballerina-code.md, 1.0/learn/how-to-extend-ballerina.md, 1.0/learn/how-to-generate-code-for-protocol-buffers.md, 1.0/learn/how-to-observe-ballerina-code.md, 1.0/learn/how-to-publish-modules.md, 1.0/learn/how-to-structure-ballerina-code.md, 1.0/learn/how-to-test-ballerina-code.md, 1.0/learn/how-to-use-openapi-tools.md, 1.0/learn/how-to-write-secure-ballerina-code.md, 1.0/learn/installing-ballerina.md, 1.0/learn/quick-tour.md, 1.0/learn/set-up-ballerina-sdk.md, 1.0/learn/style-guide.md, js/ballerina-common.js
> Added redirections to 1.0 learn pages
> Fixes #
=> Added redirections to 1.0 learn pages

learn/tools-ides/vscode-plugin.md
=> Fixing the VScode URL

learn/by-example/index.html
=> Added the redirect_to from v1-2 URL

learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md, learn/tools-ides/vscode-plugin/documentation-viewer.md, learn/tools-ides/vscode-plugin/graphical-editor.md, learn/tools-ides/vscode-plugin/language-intelligence.md, learn/tools-ides/vscode-plugin/run-all-tests.md, learn/tools-ides/vscode-plugin/run-and-debug.md
=> Removed the redirection loop

index.html
=> Update why Ballerina URLs

.github/workflows/add_new_release_note.yml, .github/workflows/update_api_docs.yml, .github/workflows/update_ballerina_by_example.yml, .github/workflows/update_release_note_versions_json.yml
=> Refactor workflows a bit

learn/tools-ides/intellij-plugin.md, learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md, learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md, learn/tools-ides/vscode-plugin.md, learn/tools-ides/vscode-plugin/documentation-viewer.md, learn/tools-ides/vscode-plugin/graphical-editor.md, learn/tools-ides/vscode-plugin/language-intelligence.md, learn/tools-ides/vscode-plugin/run-all-tests.md, learn/tools-ides/vscode-plugin/run-and-debug.md
> Updated redirections from v1-2/
> Fixes #
=> Updated redirections to fix old versioned mapping

sitemap.xml
=> updated sitemap

learn/style-guide/annotations_documentation_and_comments.md, learn/style-guide/definitions.md, learn/style-guide/expressions.md, learn/style-guide/operators_keywords_and_types.md, learn/style-guide/statements.md
> Fixed the redirection rules for style-guide
> Fixes #
=> Fixed the redirection rules

_data/learnnav.yml, _includes/left-nav.html, _layouts/ballerina-left-nav-pages.html, css/ballerina-io-learn-v2.css, img/down-arrow-learn.svg, img/up-arrow-learn.svg, learn/cli-guide.md, learn/learning-the-basics.md, learn/managing-ballerina/keeping-ballerina-up-to-date.md, learn/quick-tour.md, learn/setting-up-ballerina-tools.md, learn/setting-up-ballerina.md, learn/standard-library.md, learn/style-guide.md, learn/working-with-ballerina-services/deploying-ballerina-services.md, learn/working-with-ballerina-services/developing-ballerina-services-using-openapi-documentation.md, learn/working-with-ballerina-services/generating-ballerina-code-for-protocol-buffer-definitions.md, learn/working-with-ballerina-services/observing-ballerina-services.md, learn/writing-ballerina-code.md, learn/writing-ballerina-code/publishing-modules-to-ballerina-central.md, learn/writing-ballerina-code/running-ballerina-code.md, learn/writing-ballerina-code/structuring-ballerina-code.md, learn/writing-ballerina-code/testing-ballerina-code.md, learn/writing-ballerina-code/using-ballerina-tools.md, learn/writing-ballerina-code/writing-secure-code.md
New learn section with navigation
=> Add new learn section

_includes/nav-breadcrumbs.html
Fix breadcrumbs for Jekyll pages
=> Fix breadcrumbs

_includes/ballerina-example-head.html, _includes/ballerina-head-landing-page.html, _includes/ballerina-head.html, _includes/ballerina-home-head.html
> Updated the null check for page level meta tags
> Fixes #
=> Updated page specific meta tags section

_data/learnnav.yml, _layouts/ballerina-learn-landing-page.html, learn.md
=> Edit the new learn page structure

.github/workflows/add_new_release_note.yml, .github/workflows/update_api_docs.yml, .github/workflows/update_ballerina_by_example.yml, .github/workflows/update_release_note_versions_json.yml
=> Refactor workflows

.github/workflows/add_new_release_note.yml, .github/workflows/update_api_docs.yml, .github/workflows/update_ballerina_by_example.yml, .github/workflows/update_release_note_versions_json.yml
=> Change the trigger the event `push`

_data/learnnav.yml, learn.md
Address the feedback given on the new Learn page.
> Fixes #
=> Address the Feedback Given on the New Learn Page

_layouts/ballerina-learn-landing-page.html, _layouts/ballerina-left-nav-pages.html, js/ballerina-leftnav.js
=> Update learn page layout

learn.md
=> Fix learn page links

js/lunr.js, js/site-search.js, search.html
> Integrating Lunr search with ballerina.io
> Fixes #
=> Adding search module to the website

learn.md
Change the main sections of the Learn page.
> Fixes #
=> Change the Main Sections of the Learn Page

_layouts/ballerina-layer-page.html, _layouts/ballerina-learn-landing-page.html, css/ballerina-io-docs.css, css/ballerina-io.css, why-ballerina/from-code-to-cloud.md, why-ballerina/the-network-in-the-language.md
=> Update WHY page links

_data/learnnav.yml, learn.md
Update the sections of the Learn page.
> Fixes #
=> Update the Sections of the Learn Page

code-of-conduct.md, downloads.html, events.md, index.html, license-of-site.md, privacy-policy.md, security.md, terms-of-service.md, why-ballerina/from-code-to-cloud.md, why-ballerina/network-aware-type-system.md, why-ballerina/sequence-diagrams-for-programming.md, why-ballerina/the-network-in-the-language.md
=> Update More Info link

why-ballerina/from-code-to-cloud.md, why-ballerina/network-aware-type-system.md, why-ballerina/sequence-diagrams-for-programming.md, why-ballerina/the-network-in-the-language.md
=> Fix breadcrumbs on WHY pages

css/home-page.css, index.html
=> Fix home page links

events.md
=> Update QCon Dates

_data/latest/metadata.json
=> Update metadata.json for 1.2.3 release

events.md
=> Update with Oracle Meetup

.github/workflows/publish_intellij_plugin.yml
=> Include checkout action for ballerina-dev-website

.github/workflows/homebrew_publish.yml, .github/workflows/prod_sync.yml, .github/workflows/publish_intellij_plugin.yml, .github/workflows/publish_vscode_plugin.yml, .github/workflows/update_api_docs.yml, .github/workflows/update_ballerina_by_example.yml, downloads/RELEASE_NOTE.md
=> Fix issues workflows

.github/workflows/update_api_docs.yml
=> Fix indentation issue

0.990/learn/by-example/http-1.1-to-2.0-protocol-switch.html, 0.990/learn/by-example/http-2.0-server-push.html, 0.991/learn/by-example/http-1.1-to-2.0-protocol-switch.html, 0.991/learn/by-example/http-2.0-server-push.html, 1.0/learn/by-example/http-1.1-to-2.0-protocol-switch.html, 1.0/learn/by-example/http-2.0-server-push.html, 1.1/learn/by-example/http-1.1-to-2.0-protocol-switch.html, 1.1/learn/by-example/http-2.0-server-push.html, learn/by-example/http-1.1-to-2.0-protocol-switch.html, learn/by-example/http-2.0-server-push.html
This will fix the 404 in BBEs where there is a dot in the file name ( in the last path of the URI)
=> Fix url issue in BBE

_data/learnnav.yml, learn/by-example/index.html, learn/how-to-call-java-code-from-ballerina.md
=> Update doc  URL

_includes/ballerina-example-head.html, _includes/ballerina-head-landing-page.html, _includes/ballerina-head.html, _includes/ballerina-home-head.html
=> Point download URL to S3

.github/workflows/prod_sync_artifacts.yml
=> Add workflow to syn from dev to prod

_includes/nav.html, css/ballerina-io.css
=> Update version dropdown

.github/workflows/prod_sync_artifacts.yml
=> Change the secret names

.github/workflows/prod_sync_artifacts.yml
=> Change the trigger

js/ballerina-common.js
> Enabled enter key for the search form submit
> Fixes #
=> Enabled enter key for the search

_includes/nav.html
=> Fixed versions number

.github/workflows/update_api_docs.yml, .github/workflows/update_ballerina_by_example.yml
> This updates both api-doc and bbe workflows.
=> Update workflows to get resource from distribution

js/ballerina-common.js
=> Version drop down selected value fixed

.github/scripts/search_index_generator.js
> Search index generator script added
> Fixes #
=> Search index generator script added

1.0/learn/installing-ballerina.md, 1.1/learn/installing-ballerina.md, learn/installing-ballerina.md
Fix the alignment issue in the topics in the Installing Ballerina page[1].
[1] https://ballerina.io/learn/installing-ballerina/
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/527
=> Fix the Alignment Issue of Topics in the Installing Ballerina Page

.github/scripts/search_index_generator.js, .github/workflows/index_search.yml
=> Add new workflow to index search

_data/latest/metadata.json
Please note that this is a test commit and will be reverted soon.
This was merged to test the workflows before actual the release.
This will trigger below workflows.
- add_new_release_note
- update_api_docs
- update_release_note_versions_json
- update_ballerina_by_example
- index_search
=> [Test] Change the pack size

_data/latest/metadata.json
Reverts ballerina-platform/ballerina-dev-website#545
=> Revert "[Test] Change the pack size"

.github/workflows/index_search.yml
=> Fix the checkout action version

.github/workflows/update_api_docs.yml, _data/release_notes_versions.json
> $subject. Along with that a fixed an issue in workflow.
=> Fix download vsix issue

_data/release_notes_versions.json
=> Fix download issue for vsix files

.github/scripts/search_index_generator.js
> - Added a mechanism to skip folders and files from indexing for the site search
- Construct the final JS format for the search index file
> Fixes #
=> Added nofollow directories

_config.yml
=> Add the prod dist server

_config.yml
> We will omitting this commit when we sync with the production repo.
=> Add the dev dist server

_data/latest/metadata.json
=> Update metadata.json for 1.2.4 release

downloads/release-notes/1.2.4/RELEASE_NOTE.md
> Updates the release note for the 1.2.4 release.
=> Update release note for 1.2.4

downloads/release-notes/1.2.4/RELEASE_NOTE.md
> Updates the release note for 1.2.4
=> Replace the template strings for version in the release note

js/site-search.js
=> removed extra slash in the search result

.github/scripts/search_index_generator.js
> Skipping 404 page, jekyll folders, and the spec follder
> Fixes #
=> Updated the nofollow list

.github/workflows/index_search.yml
=> Fix the build failure in index_search workflow

.github/workflows/prod_sync_artifacts.yml, .github/workflows/publish_intellij_plugin.yml
=> Fix the issue in publishing idea plugin

0.991/learn/getting-started.md, 1.0/learn/installing-ballerina.md, 1.1/learn/installing-ballerina.md, _data/learnnav.yml, downloads.html, learn/installing-ballerina.md
Fix issues in the Installing Ballerina & Downloads pages.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/528 & https://github.com/ballerina-platform/ballerina-dev-website/issues/540
=> Fix Issues in the Installing Ballerina & Downloads Pages

learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md
=> Add redirect from

_config.yml
=> Fix the dev-url

events.md
=> Update Cloud DC meetup slides

.github/scripts/sanitize_rn.py, .github/workflows/publish_github_release.yml, community.md, events.md, hbs/archived_list.hbs
=> Prod sync from dev

community.md, js/ballerina-common.js
=> Email subscription form added-UI fix pending

js/ballerina-common.js
=> Updated the campaign

_config.yml
> Removing versioned folders from the build and keeping the existing copy in _site
> Fixes #
=> Removed versioned folders from site build

_config.yml
=> Updated exclude list

_config.yml
=> Updated keep_files

_config.yml
=> Merged shafreens config changes

_config.yml
=> Change the url from http to https

_config.yml
=> Fix dist url in dev site

community.md
=> Update anchor tag

community/newsletter.md, community/newsletter/issue-1.md
=> Update newsletter pages

.github/workflows/prod_sync.yml
> This will always make sure changes in prod-sync always get the priority.
=> Change pull command to auto resolve conflicts

community/newsletter.md, community/newsletter/2020-1.md
=> added newsletter archives

community/newsletter.md
=> Reorder form in newsletter homepage

.github/workflows/prod_sync.yml, _includes/ballerina-head-nl.html, _layouts/ballerina-newsletter.html, community.md, community/newsletter.md, community/newsletter/2020-1.md, learn/how-to-use-openapi-tools.md
=> Prod sync with dev

0.990/index.html, 0.991/index.html, 1.0/index.html, 1.1/index.html
> Added redirection rules to the root of the version folder
> Fixes #
=> Added redirections to the versioned folders

404.html, js/ballerina-common.js
> To fix previous API docs and BBE redirections in the versioned folders
> Fixes #
=> Added the bulk redirection method

_includes/ballerina-head.html, community/newsletter/2020-1.md, community/slack.md, js/ballerina-common.js, why-ballerina/network-aware-type-system.md
> Lambda based Slack service added
> Fixed a broken link in the newsletter
> Removed old Slack service resources
> Fixes #
=> Added New Slack service

community.md
Add the newsletter to the "Community" page TOC.
> Fixes #
=> Add the Newsletter to the Community Page TOC

why-ballerina/network-aware-type-system.md
> Mapped /why-ballerina URLs to fix broken links
> Fixes #
=> Mapped /why-ballerina URLs

index.html
=> Update link to batteries included page

spec.md
=> Fix spec proposals link

0.991/learn/installing-ballerina/index.html, spec/lang/2019R1/index.html, spec/lang/2019R2/index.html, spec/lang/2019R3/experimental.html, spec/lang/2019R3/index.html, spec/lang/2020R1/index.html
> Fixed broken link for installing-ballerina
> Fixes #
=> Fixed broken link + favicon icon

0.991/learn/getting-started/index.html, 1.0/learn/installing-ballerina/index.html, 1.1/learn/installing-ballerina.md, learn/installing-ballerina.md
Improving the "Installing Ballerina page.
> Fixes #591 and #542.
=> Improving the "Installing Ballerina Page

learn/installing-ballerina.md
Fix Some Minor issues in the revamped Installing Ballerina page
> Fixes #
=> Fix Some Minor Issues in the Revamped Installing Ballerina Page

spec/draft/index.md, spec/live/index.md
> I am working on automating publishing spec changes to the site. This includes folder structure required for that.
=> Initial folder structure for coming spec changes

learn/installing-ballerina.md
Improve installing instructions in [1].
[1] https://dev.ballerina.io/learn/installing-ballerina/
> Fixes #
=> Improve Installing Instructions

spec/draft/latest/index.md
=> Add a location for draft/latest spec

spec/draft/index.html, spec/draft/index.md
=> Add page for listing draft specs

spec/draft/style/ballerina-language-specification.css, spec/draft/style/ballerina-language-specification.js
=> Fix the styling issue

learn/installing-ballerina.md
Address feedback provided on the "Installing Ballerina" page [1].
[1] https://ballerina.io/learn/installing-ballerina/
> Fixes #
=> Address Feedback on the "Installing Ballerina" Page

community.md
=> Updates text

learn/installing-ballerina.md
Fix a Minor Typo in the "Installing Ballerina" page[1].
[1] https://ballerina.io/learn/installing-ballerina/
> Fixes #
=> Fix a Minor Typo in the "Installing Ballerina" Page

spec/lang/master/index.md
=> Add new location for live spec

downloads.html
=> Fix download buttons

downloads.html
Address the feedback received for the new "Donwloads" page layout[1].
[1] http://dev.ballerina.io/downloads/
> Fixes #
=> Address the Feedback Received for the New "Donwloads" Page Layout

spec.md
Update the spec page in Bio[1] with the latest changes done for the Ballerina Swan Lake release.
> Fixes #
=> Update the Spec Page in Bio with the Latest Changes

spec.md
Add styling to the Note in the Spec page[1].
[1] https://dev.ballerina.io/spec/
> Fixes #
=> Add Styling to the Note in the Spec page

1.1/learn/installing-ballerina.md, learn/installing-ballerina.md
Add the ZIP Archive Download to [1].
[1] https://ballerina.io/learn/installing-ballerina/#installing-via-the-ballerina-language-zip-file
> Fixes #
=> Add the ZIP Archive Download to the "Installing Ballerina" Page

learn/installing-ballerina.md
Add code to get the download count of the zip archive
> Fixes #
=> Add Code to Get the Download Count of the ZIP Archive

.github/scripts/search_index_generator.js
=> Included spec landing page in the search

_includes/nav.html
=> add Swan Lake to the drop down

.github/scripts/homebrew_publish.py, .github/workflows/homebrew_publish.yml
> Fix the sync issue with the remote upstream Homebrew/homebrew-core repo
> Fix the missing quotation of the ballerina.rb file
=> Fix sync issue with Homebrew/homebrew-core

downloads.html
Fix the new Downloads page of the Swan Lake release,
> Fixes #
=> Fix the New Downloads Page of the Swan Lake Release

downloads.html
=> Fix layout

_data/swanlake-latest/metadata.json
=> Add metadata location for swan-lake

_data/stable-latest/metadata.json
=> Update values of the metadata json

swan-lake/learn/tools-ides/setting-up-visual-studio-code.md
Update the VS Code guide for the Swan Lake release.
> Fixes #
=> Update the VS Code Guide for the Swan Lake Release

_data/learnnavswanlake.yml, _includes/left-nav-swanlake.html, _layouts/ballerina-left-nav-pages-swanlake.html, swan-lake/learn/installing-ballerina.md
Updated the new layout for swan lake release
=> Update learn navigation for swan lake

downloads/swan-lake-release-notes.md, js/release_notes/swan_lake_all_release_notes.js
Add the Release Note page for the Swan Lake release.
> Fixes #
=> Add Release Note Page for the Swan Lake Release

.github/workflows/update_api_docs.yml, .github/workflows/update_ballerina_by_example.yml
=> Fix the path issue in workflows

downloads.html, downloads/swan-lake-archived.md, js/download/swan_lake_archived_download.js
Add the Swan Lake release note to the Downloads page.
> Fixes #
=> Add the Swan Lake Release Note to the Downloads Page

downloads/swan-lake-release-notes/swan-lake/RELEASE_NOTE.html
Add the release note folder for Swan Lake release.
> Fixes #
=> Add the Release Note Folder for the Swan Lake Relase

downloads/release-notes.md, downloads/swan-lake-release-notes.md
Fix the Swan Lake release note JSON file.
> Fixes #
=> Fix the Swan Lake Release Note JSON File

learn/calling-java-code-from-ballerina.md
Update the `Calling Java Code from Ballerina` documentation page with the latest changes to the Bindgen tool.
=> Update the How To doc of the Bindgen tool

js/release_notes/all_release_notes.js, js/release_notes/swan_lake_all_release_notes.js
=> Fix the issue in release-notes page

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
Improve the Swan Lake release note.
> Fixes #
=> Improve the Swan Lake Release Note

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
> Update release note with log-api improvements.
=> Update release note with log-api improvements

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
Update the code snippets in the Swan Lake release note.
> Fixes #
=> Update the Code Snippets in the Swan Lake Release Note

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
=> Add raw templates and dependently-typed function signatures

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
Fix some issues in the bindgen section of the release note.
=> Minor improvements to the release note

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
=> Add Testerina Function Mocking and Object Mocking details

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
=> Update 'never' type section in the RELEASE_NOTE.md

swan-lake/learn/writing-secure-ballerina-code.md
Update secure ballerina code doc for Swan Lake release.
=> Update secure ballerina code doc

swan-lake/learn/keeping-ballerina-up-to-date.md
> Update the update tool learn page
=> Update the update tool learn page

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
=> Add SQL module description

downloads.html
> Include how to use update tool to get swan lake preview1
=> Include how to use update tool to get swan lake preview1

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
> Update testerina release note
=> Update testerina release note

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
Fix minor issues in the Swan Lake release note.
> Fixes #
=> Fix Minor Issues in the Swan Lake Release Note

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
=> Update type inclusion release note

downloads.html
=> Add line break

downloads.html, js/redirections.js
=> Added rpm file paths

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
> Update object mocking release note
=> Update object mocking release note

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
> Fixes issues in the release note
=> Fix issues in the release note

downloads.html
Update minor fixes in the Downloads page.
> Fixes #
=> Update Minor Fixes in the Downloads Page

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
As authored offline by @hasithaa @pubudu91 @KRVPerera and @MaryamZi
=> Update the release note for language changes

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
=> Add minor modifications for developer tools notes

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
=> Use italics for old vs new syntax

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
=> Change language in code snippet

_data/stable-latest/metadata.json, _data/swanlake-latest/metadata.json
=> Update the download page data

.github/workflows/prod_sync_artifacts.yml, .github/workflows/publish_github_release.yml
=> Update workflows to work with swanlake

_data/swanlake-latest/metadata.json
=> Add the new metadata.json file

_data/swanlake_release_notes_versions.json
=> Update with new release data

_data/swanlake-latest/metadata.json, _data/swanlake_release_notes_versions.json
=> Fix the date issue in relese note

downloads.html
Fix the markup issues and footer in the downloads page
=> Fix the markup issues and footer

swan-lake/learn/by-example/hello-world-client.html
=> Change hello world client bbe in swan lake

swan-lake/learn/installing-ballerina.md
Fix the installation instructions of the ZIP file for Swan Lake release.
> Fixes #
=> Fix the Installation Instructions of the ZIP File for the Swan Lake Release

swan-lake/learn/by-example/hello-world-service.html
note $subject
This has been updated by 
https://github.com/ballerina-platform/ballerina-distribution/commit/6965d667fced12465da602301db20d4b4acef25f
And then PR: https://github.com/ballerina-platform/ballerina-distribution/pull/619
=> Fix hello_world_service.bal

why-ballerina/the-network-in-the-language.md
=> Update network in the language page code snippet

swan-lake/learn/by-example/hello-world-service.html
=> Fix Hello world service BBE

learn/by-example/hello-world-client.html, learn/by-example/hello-world-service.html
note $subject
This PR is to reflect :
commit:
https://github.com/ballerina-platform/ballerina-lang/commit/01803ca983c0275ff6b1760e3217cbbf2c33a666
PR:
https://github.com/ballerina-platform/ballerina-lang/pull/24385
=> generate v1.2.x BBE hello-world-[cs] for anjanas changes

_data/swanlake-latest/metadata.json
Add the ZIP Archive in the metadata JSON file for Swan Lake.
> Fixes #
=> Add the ZIP Archive in the Metadata JSON File for Swan Lake

learn/installing-ballerina.md, swan-lake/learn/installing-ballerina.md
Change the ZIP installation instructions for Swan Lake.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/901
=> Change the ZIP installation instructions for Swan Lake

.github/workflows/index_search.yml, .github/workflows/sw_add_new_release_note.yml, .github/workflows/sw_publish_github_release.yml, .github/workflows/sw_update_api_docs.yml, .github/workflows/sw_update_ballerina_by_example.yml, .github/workflows/sw_update_release__note_versions.yml, downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
> With the swan lake release we had to change the site a lot. This PR fixes the workflows which were impacted with those changes.
=> Fix all the workflows to match new changes

search.html
=> Removed version drop down from the search page

.github/scripts/publish_json.py, .github/workflows/sw_update_release__note_versions.yml, .github/workflows/update_api_docs.yml
=> Move publish_json.py to dev repo

_data/swanlake-latest/metadata.json
> This is just test commit. This PR will be reverted after the test.
=> Test new workflows

.github/workflows/sw_update_ballerina_by_example.yml
=> Fix the path issue in BBE swan lake workflow

_data/swanlake-latest/metadata.json
Reverts ballerina-platform/ballerina-dev-website#912
=> Revert "Test new workflows"

.github/workflows/add_new_release_note.yml, .github/workflows/index_search.yml, .github/workflows/prod_sync.yml, .github/workflows/sw_add_new_release_note.yml, .github/workflows/sw_update_release__note_versions.yml, .github/workflows/update_release_note_versions_json.yml
=> Change workflow names to match new behaviour

_includes/nav.html, css/bbe-home-page.css, js/api-doc-template.js
With this , We can do customizations on the BBE homepage.
=> Add BBE home page css

_config.yml
=> 0.991 directory removed from the website build

learn/api-docs/ballerina/http/records/CorsConfig.html, security.md, spec/spec.md
Remove inappropriate words from Bio.
> Fixes #
=> Remove Inappropriate Words from Bio

_data/stable-latest/metadata.json
=> Update metadata.json for 1.2.5 release

_data/stable-latest/metadata.json
Reverts ballerina-platform/ballerina-dev-website#936
=> Revert "Update metadata.json for 1.2.5 release"

.github/workflows/add_new_release_note.yml, .github/workflows/index_search.yml, .github/workflows/update_release_note_versions_json.yml
=> Fix the authentication problem in workflows

_data/stable-latest/metadata.json
> $subject. Reverted the previous one in order to re-trigger the updated workflows.
=> Update the metadata.json for 1.2.5

_data/stable-latest/metadata.json
Reverts ballerina-platform/ballerina-dev-website#942
=> Revert "Update the metadata.json for 1.2.5"

.github/workflows/add_new_release_note.yml, .github/workflows/index_search.yml, .github/workflows/update_release_note_versions_json.yml
=> Fix the autherization issue in workflows

_data/stable-latest/metadata.json
This PR is sent to re-trigger the workflows as it fails previously.
=> Update the metadata.json for 1.2.5 

downloads/release-notes/1.2.5/RELEASE_NOTE.md
=> Update release notes for 1.2.5 release

_data/stable-latest/metadata.json
=> Update metadata.json file for 1.2.5 release

.github/workflows/sw_add_new_release_note.yml, .github/workflows/sw_update_release__note_versions.yml
=> Fix authentication issue when pushing changes

_data/stable-latest/metadata.json
=> Add the missing entries in the metadata.json file

.github/workflows/update_release_note_versions_json.yml, _data/release_notes_versions.json
=> Fix the workflow to use the correct python script

downloads/release-notes/1.2.5/RELEASE_NOTE.md
=> Fix a typo in release note

downloads/release-notes/1.2.5/RELEASE_NOTE.md
=> Add missing line break from release note

_data/stable-latest/metadata.json, downloads/release-notes/1.2.5/RELEASE_NOTE.md
=> Fix incorrect version in metadata.json

community.md, community/newsletter.md, community/newsletter/2020-2.md, events.md
=> Dev Prod Sync

learn/by-example/object-assignability.html, swan-lake/learn/by-example/object-assignability.html
Add bullets to the description of the Object Assignability BBE.
> Fixes #
=> Add Bullets to the Description of the Object Assignability BBE

downloads.html
=> Added a new class for tracking

swan-lake/learn/by-example/object-assignability.html
Update the last bullet point in the Object Assignability BBE.
> Fixes #
=> Update the Object Assignability BBE

learn/installing-ballerina.md, swan-lake/learn/installing-ballerina.md
=> Added GTM tracking class

.github/workflows/prod_sync_artifacts.yml, .github/workflows/sw_prod_sync_artifacts.yml
> It seems the latest amzon aws/cli has introduced some issues when running in github workflows. I have fixed this by using an older version.
=> Fix the error in aws/cli of github workflows

.github/workflows/publish_intellij_plugin.yml
=> Update workflow publishing Intellij Plugin to use oracle jdk 8

.github/scripts/publish_homebrew.py
> Add contact information in the PR message body sent to the https://github.com/Homebrew/homebrew-core
> Fixes #
=> Add contact info in the PR message

_data/stable-latest/metadata.json
=> Update metadata.json for 1.2.6

.github/workflows/publish_intellij_plugin.yml
=> Fix alignment issue in work flow to publish intellij plugin

downloads.html, downloads/release-notes/1.2.6/RELEASE_NOTE.md
=> Update release note for 1.2.6

.github/workflows/update_release_note_versions_json.yml, _data/release_notes_versions.json
> Along with that I have updated the missing release note json also.
=> Fix the path issue in workflow

_data/release_notes_versions.json, downloads/release-notes/1.2.6/RELEASE_NOTE.md
=> Fix header in release note and date in release note page

downloads/release-notes/1.2.5/RELEASE_NOTE.md, downloads/release-notes/1.2.6/RELEASE_NOTE.md
=> Fix the pull command in release notes

_data/release_notes_versions.json, downloads/release-notes/1.2.5/RELEASE_NOTE.md, downloads/release-notes/1.2.6/RELEASE_NOTE.md
=> [Prod Sync] Fix pull command in 1.2.5 and 1.2.6 release notes

hbs/archived_list.hbs
=> added the new tracking class

.github/workflows/publish_vscode_plugin.yml
=> Fix the path issue

css/ballerina-io-bbe.css
=> Update BBE list style

js/ballerina-common.js
=> Fixed the version dropdown behavior on the browser back button

css/bbe-page.css
=> Fix page width

_data/learnnavswanlake.yml
=> Fix indenation swanlake yml

swan-lake/learn/executing-tests.md, swan-lake/learn/mocking.md, swan-lake/learn/testing-quick-start.md, swan-lake/learn/writing-tests.md
> Fix redirection issues in testing docs
=> Fix redirection issues in testing docs

learn/deployment/awslambda.md
=> Add AWS Lambda user guide page

_data/learnnavswanlake.yml, swan-lake/learn/mocking.md, swan-lake/learn/testing-quick-start.md, swan-lake/learn/writing-tests.md
> Fix font style issues in testing docs
=> Fix font style issues in testing docs

swan-lake/learn/writing-tests.md
> Fix font issues in testing docs
=> Fix font issues in testing docs

learn/api-docs/ballerina/index.html
=> Add module description for awslambda and azure functions

1.0/learn/by-example/index.html
Fix breadcrumbs in the BBE index page in 1.0
> Fixes #
=> Fix Breadcrumbs in the BBE Index Page in 1.0

_data/learnnav.yml
Add the Azure Guide to the learn navigation structure.
> Fixes #
=> Add the Azure Guide to the Learn Navigation Structure

swan-lake/learn/mocking.md, swan-lake/learn/testing-quick-start.md
Improve code blocks in testing guide
=> Improve code blocks in testing guide

swan-lake/learn/testing-quick-start.md
> Improve testing quick start guide
=> Improve testing quick start guide

swan-lake/learn/mocking.md
Improve mocking code snippets for better readability
=> Improve mocking code snippets for better readability

swan-lake/learn/mocking.md
> Improve mocking code snippets
=> Improve mocking code snippets

swan-lake/learn/mocking.md
> Format lengthy lines in the mocking code snippets
=> Format lengthy lines in the mocking code snippets

_data/learnnavswanlake.yml, js/redirections.js, swan-lake/learn/testing-ballerina-code/executing-tests.md, swan-lake/learn/testing-ballerina-code/mocking.md, swan-lake/learn/testing-ballerina-code/testing-quick-start.md, swan-lake/learn/testing-ballerina-code/writing-tests.md
=> Add redirections for the new Testing guides

_data/swanlake_release_notes_versions.json
=> Update relase notes version

downloads.html
> Fixes the release version to slp2
=> Fix release version

downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
> This PR adds the initial draft of the release note.
=> Add release note for slp2

.github/scripts/sanitize_rn.py, .github/workflows/publish_github_release.yml, .github/workflows/sw_publish_github_release.yml
=> Fix publish release github workflow

js/redirections.js
Add redirections for the Streaming Guide.
> Fixes #
=> Add Redirections for the Streaming Guide

downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
=> Add a missing import

swan-lake/learn/testing-ballerina-code/mocking.md, swan-lake/learn/testing-ballerina-code/testing-quick-start.md
> Update mocking syntax for swan lake preview2
=> Update mocking syntax for swan lake preview2

downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
Review the slp2 release note.
> Fixes #
=> Review the Swan Lake Preview 2 Release Note

downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
Address the review comments of the slp2 release note.
> Fixes #
=> Address the Review Comments of the SLP2 Release Note

downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
=> Minor updates to JSON changes

.github/workflows/sw_update_release__note_versions.yml
=> Fix the typo in the workflow

_data/swanlake-latest/metadata.json, downloads/swan-lake-release-notes/swan-lake-preview2/RELEASE_NOTE.md
=> Update metadata.json for slp2

learn/deployment/docker.md, swan-lake/learn/deployment/docker.md, swan-lake/learn/testing-ballerina-code/mocking.md, swan-lake/learn/tools-ides/setting-up-intellij-idea.md, swan-lake/learn/tools-ides/setting-up-intellij-idea/using-intellij-plugin-features.md, why-ballerina/from-code-to-cloud.md, why-ballerina/the-network-in-the-language.md
Fix slp2 broken links.
> Fixes #
=> Fix Swan lake Preview 2 Release Broken Links

downloads.html
=> Fix typo in downloads page

_plugins/_capitalize_all.rb, downloads.html
=> Automate manual bits in download page

.github/scripts/sanitize_rn.py
=> Fix the issue in sanitizing the string in publish github workflow

learn/keeping-ballerina-up-to-date.md, swan-lake/learn/keeping-ballerina-up-to-date.md
Update the `dist pull` command description in the "Pull a specific distribution" section[1].
[1] https://ballerina.io/learn/keeping-ballerina-up-to-date/#pull-a-specific-distribution
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1108
=> Update the `dist pull` Command Description

css/ballerina-io.css
=> Remove line numbers from H2s

learn/by-example/azure-functions-deployment.html
Update the Azure Deployment BBE for 1.2.x.
> Fixes #
=> Update the Azure Deployment BBE for 1.2.x

_data/learnnavswanlake.yml, js/redirections.js, learn/deployment/aws-lambda.md, learn/deployment/azure-functions.md, swan-lake/learn/deployment/aws-lambda.md, swan-lake/learn/deployment/azure-functions.md
Add the Azure Guide to the Swan Lake release.
> Fixes #
=> Add the Azure Guide to the Swan Lake Release

swan-lake/learn/testing-ballerina-code/executing-tests.md
> Improve examples on executing tests.
>
=> Improve examples on executing tests

_data/stable-latest/metadata.json
=> Update metadata.json for 1.2.7 release

downloads/release-notes/1.2.7/RELEASE_NOTE.md
Add the 1.2.7 Release Note to Dev Site.
> Fixes #
=> Add the 1.2.7 Release Note to Dev Site

learn/by-example/azure-functions-deployment.html
Fix the broken link in the Azure Functions BBE.
> Fixes #
=> Fix the Broken Link in the Azure Functions BBE

.github/workflows/publish_intellij_plugin.yml
=> Fix java home issue in Intellij plugin publish workflow

robots.txt
Allow the link checker to crawl the dev site links.
> Fixes #
=> Allow the Link Checker to Crawl the Dev Site Links

swan-lake/learn/testing-ballerina-code/writing-tests.md
Correct function name to assertNotExactEquals
=> Correct function name to assertNotExactEquals

learn/calling-java-code-from-ballerina.md, swan-lake/learn/calling-java-code-from-ballerina.md
Fix the inconsistencies when marking ballerina commands in code snippets.
> Fixes #1120
=> Fix the Inconsistencies When Marking Ballerina Commands

_data/learnnav.yml, learn.md
Fixes link to Testing Ballerina code in 1.2.x
> Fixes #
=> Fix learn.md link for Testing Ballerina code

_data/swanlake-latest/metadata.json
=> Update metadata.json for slp3 release

downloads.html
=> Update version in downloads page

swan-lake/learn/testing-ballerina-code/writing-tests.md
> Add new annotation doc to the testing guide
=> Add new annotation doc to the testing guide

downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
Add the slp3 release note content.
> Fixes #
=> Add the slp3 Release Note Content

downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
> Update test framework release notes code snippets
=> Update test framework release notes code snippets

downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
> Add new integration features such as sort and inner query expression to release notes.
=> Add sort clause and inner query expressions to release note

downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
> Update testerina code snippet in release notes
=> Update testerina code snippet in release notes

css/bbe-page.css
=> Remove BBE copy button

downloads/swan-lake-release-notes/swan-lake-preview3/RELEASE_NOTE.md
=> Fix typo in slp3 release note

1.0/learn/by-example/kubernetes-deployment.html, 1.1/learn/by-example/kubernetes-deployment.html
Fix the resources links in the K8S BBEs in v1.1 & v1.0.
> Fixes #
=> Fix the Resources Links in the K8S BBE in v1.1 & v1.0

robots.txt
Revert the crawlers in dev.
> Fixes #
=> Revert the Crawlers in Dev

1.1/learn.md, js/redirections.js, learn.md, swan-lake/learn.md
Redirect FAQ and By-Guide broken links.
> Fixes #
=> Redirect FAQ and By-Guide Broken Links

robots.txt
Allow the link checker in the dev site.
> Fixes #
=> Allow the Link Checker in the Dev Site

js/redirections.js
Add redirections for the JDBC big dataset BBE.
> Fixes #
=> Add Redirections for the JDBC Big Dataset BBE

robots.txt
> Prod version of the robots txt file. (allow all )
> Fixes #
=> Prod version of the robots

robots.txt
> Dev version of robots txt
> Fixes #
=> Dev version of robots

swan-lake/learn/by-example/raw-template.html
=> Fix raw template BBE

.github/scripts/publish_homebrew.py, .github/workflows/publish_homebrew.yml
=> Add license info and Manuel workflow dispatch event for Homebrew publishing

.github/workflows/publish_vscode_plugin.yml
=> Disable VS Code plugin by changing the branch name

_data/stable-latest/metadata.json
=> Update metadata.json for Ballerina-1.2.8

1.0/learn/how-to-observe-ballerina-code/index.html, 1.1/learn/how-to-observe-ballerina-code.md, learn/calling-java-code-from-ballerina.md, learn/deployment/azure-functions.md, learn/observing-ballerina-code.md, swan-lake/learn/calling-java-code-from-ballerina.md, swan-lake/learn/deployment/azure-functions.md, swan-lake/learn/observing-ballerina-code.md
Fix consistency issues of the second iteration.
> Fixes #
=> Fix Consistency Issues of the Second Iteration

downloads/release-notes/1.2.8/RELEASE_NOTE.md
=> Add release-notes for Ballerina-1.2.8

_layouts/ballerina-newsletter.html
=> Update table layout style

downloads/RELEASE_NOTE.md, downloads/release-notes/1.2.7/RELEASE_NOTE.md, downloads/release-notes/1.2.8/RELEASE_NOTE.md
Add the 1.2.8 Release Note.
> Fixes #
=> Add the 1.2.8 Release Note

community/newsletter/2020-3.md
=> Remove broken links

.github/workflows/publish_vscode_plugin.yml
$subject by reverting the PR https://github.com/ballerina-platform/ballerina-dev-website/pull/1220
=> Enable VS Code plugin by changing the branch name

1.0/learn/how-to-structure-ballerina-code/index.html, 1.0/learn/intellij-plugin/index.html, 1.0/learn/intellij-plugin/using-intellij-plugin-features/index.html, 1.0/learn/intellij-plugin/using-the-intellij-plugin/index.html, 1.0/learn/vscode-plugin/graphical-editor/index.html, 1.0/learn/vscode-plugin/index.html, 1.0/learn/vscode-plugin/run-and-debug/index.html, 1.1/learn/how-to-structure-ballerina-code.md, 1.1/learn/tools-ides/intellij-plugin.md, 1.1/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md, 1.1/learn/tools-ides/intellij-plugin/using-the-intellij-plugin.md, 1.1/learn/tools-ides/vscode-plugin.md, 1.1/learn/tools-ides/vscode-plugin/graphical-editor.md, 1.1/learn/tools-ides/vscode-plugin/run-and-debug.md, learn/deployment/kubernetes.md, learn/structuring-ballerina-code.md, learn/tools-ides/setting-up-intellij-idea.md, learn/tools-ides/setting-up-intellij-idea/using-intellij-plugin-features.md, learn/tools-ides/setting-up-intellij-idea/using-the-intellij-plugin.md, learn/tools-ides/setting-up-visual-studio-code.md, learn/tools-ides/setting-up-visual-studio-code/graphical-editor.md, learn/tools-ides/setting-up-visual-studio-code/run-and-debug.md, swan-lake/learn/deployment/kubernetes.md, swan-lake/learn/structuring-ballerina-code.md, swan-lake/learn/tools-ides/setting-up-intellij-idea.md, swan-lake/learn/tools-ides/setting-up-intellij-idea/using-intellij-plugin-features.md, swan-lake/learn/tools-ides/setting-up-intellij-idea/using-the-intellij-plugin.md, swan-lake/learn/tools-ides/setting-up-visual-studio-code.md, swan-lake/learn/tools-ides/setting-up-visual-studio-code/graphical-editor.md, swan-lake/learn/tools-ides/setting-up-visual-studio-code/run-and-debug.md
Fix more consistency issues.
> Fixes #
=> Fix More Consistency Issues 

js/site-search.js, search.html
=> Added loading message

css/ballerina-io.css
=> Fix release-notes titles

1.0/learn/how-to-deploy-and-run-ballerina-programs/index.html, 1.0/learn/how-to-generate-code-for-protocol-buffers/index.html, 1.0/learn/how-to-structure-ballerina-code/index.html, 1.0/learn/how-to-use-openapi-tools/index.html, 1.0/learn/intellij-plugin/index.html, 1.0/learn/intellij-plugin/using-intellij-plugin-features/index.html, 1.0/learn/vscode-plugin/graphical-editor/index.html, 1.0/learn/vscode-plugin/index.html, 1.0/learn/vscode-plugin/run-and-debug/index.html, 1.1/learn/how-to-generate-code-for-protocol-buffers.md, 1.1/learn/how-to-use-openapi-tools.md, 1.1/learn/tools-ides/intellij-plugin/using-intellij-plugin-features.md, js/redirections.js, learn/generating-ballerina-code-for-protocol-buffer-definitions.md, learn/using-the-openapi-tools.md, swan-lake/learn/generating-ballerina-code-for-protocol-buffer-definitions.md
Fix the issues in the TOCs added to the Learn pages.
> Fixes #
=> Fix the Issues in the TOCs Added to the Learn Pages

1.0/learn/how-to-use-openapi-tools/index.html, 1.0/learn/installing-ballerina/index.html, 1.0/learn/vscode-plugin/index.html, 1.1/learn/how-to-deploy-and-run-ballerina-programs.md, 1.1/learn/installing-ballerina.md, learn/calling-java-code-from-ballerina.md, learn/installing-ballerina.md, swan-lake/learn/calling-java-code-from-ballerina.md, swan-lake/learn/installing-ballerina.md
Fix more TOC issues in Learn pages.
> Fixes #
=> Fix More TOC Issues in Learn Pages

downloads/swan-lake-release-notes/swan-lake-preview1/RELEASE_NOTE.md
Add H7 title styles of the Release Note.
> Fixes #
=> Add H7 Title Styles of the Release Note

swan-lake/learn/testing-ballerina-code/mocking.md
Fix issues in sample code in the mocking test guide
=> Fix issues in sample code in the mocking test guide

learn/testing-ballerina-code/writing-tests.md
=> Fix errors in the writing tests website page

_layouts/ballerina-no-git-inner-page.html, js/site-search.js, learn/by-example/index.html, search.html
> Added a new layout for the pages without a git edit link
> Fixes #
=> Removed Github image broken link & added search status

css/bbe-page.css
Enable the copy button CSS in BBEs.
> Fixes #
=> Enable the copy button CSS in BBEs

js/download/swan_lake_archived_download.js
> Added Swan Lake releases to the archived releases list.
> Fixes #
=> Added Swan Lake releases to the archived releases list

learn/calling-java-code-from-ballerina.md
=> Document BalEnv async interop use case

learn/calling-java-code-from-ballerina.md
=> Changing class annotation becase it has become a keyword.

swan-lake/learn/writing-secure-ballerina-code.md
This PR updates the https://ballerina.io/swan-lake/learn/writing-secure-ballerina-code doc with latest updates.
=> Update secure ballerina doc

js/download/swan_lake_archived_download.js
=> Reverted the change -  Swan Lake releases to the archived releases list

downloads/archived.md, downloads/swan-lake-archived.md, js/download/swan_lake_archived_download.js
=> Added a seperate page for Swan Lake archived releases

downloads.html, downloads/all-swan-lake-release-notes.md
Create all release notes files for both Stable and Swan Lake versions.
> Fixes #
=> Create All Release Notes Files for Both Stable and Swan Lake Versions

downloads.html
Update the release notes link for Swan Lake in the "downloads.html" file.
> Fixes #
=> Update the Release Notes Link for Swan Lake

downloads/all-swan-lake-release-notes.md
Change the Release Notes page layout.
> Fixes #
=> Change the Release Notes Page Layout

events.md
=> Fixed markup

_includes/ballerina-head-landing-page.html, _includes/ballerina-head-nl.html, js/download/swan_lake_archived_download.js
=> Fix for the Swan Lake releases notes in the archived page

learn/documenting-ballerina-code.md
> Since Docerina doesn't support services, the current learn page has wrong information at the end. This PR fixes the issue with a custom function and a class definition.
=> Fix docerina learn page

learn/using-the-openapi-tools.md
=> Update openAPI learn page

learn/writing-secure-ballerina-code.md, swan-lake/learn/writing-secure-ballerina-code.md
=> Migrate code to use updated lib functions

_data/swanlake-latest/metadata.json
=> Update metadata JSON for slp4

js/redirections.js
Add redirections to BBEs changed in SLP4.
> Fixes #
=> Add Redirections to BBEs Changed in SLP4

.github/workflows/sw_update_ballerina_by_example.yml
=> And generate playground link parameter

downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
Fix the release note layout.
> Fixes #
=> Fix the Release Note Layout

.github/workflows/sw_update_ballerina_by_example.yml
=> Add manual trigger for bbe generation

downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
Address the review comments of the SLP4 release note in [1].
[1] https://github.com/ballerina-platform/ballerina-dev-website/pull/1299
> Fixes #
=> Address the Review Comments of the SLP4 Release Note

.github/workflows/sw_update_ballerina_by_example.yml
$subject as it is fixed by https://github.com/ballerina-platform/ballerina-release/pull/49
=> Remove rename command

downloads/release-notes.md, downloads/swan-lake-release-notes.md
=> Fix release notes

downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
=> Fix table line breaks

swan-lake/learn/api-docs/ballerina/cache/index.html
=> Update index file of cache api-doc for swan-lake  

downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md, swan-lake/learn/by-example/index.html
Fix more issues after SLP4 release.
> Fixes #
=> Fix More Issues After SLP4 Release

swan-lake/learn/api-docs/ballerina/cache/index.html
=> Change object keywords to class in the index file

swan-lake/learn/testing-ballerina-code/writing-tests.md, swan-lake/learn/using-the-cli-tools.md
Fix Learn page issues after SLP4.
> Fixes #
=> Fix Learn Page Issues After SLP4

js/redirections.js, swan-lake/learn/by-example/object-type.html
Fix the redirections of Object BBEs.
> Fixes #
=> Fix the Redirections of Object BBEs

swan-lake/learn/by-example/object-assignability.html, swan-lake/learn/by-example/object-constructor-expression.html, swan-lake/learn/by-example/object-type.html
Update the output of the "Object Types" BBE.
> Fixes #
=> Update the Output of the "Object Types" BBE

_config.yml
Skip old versions in the "config.yml" file.
> Fixes #
=> Skip Old Versions in the "Config.yml" File

downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
Add a note on formatter to the slp4 release note.
=> Add a note on formatter to the slp4 release note

_data/swanlake-latest/metadata.json
=> Update release date for slp4

.github/workflows/sw_prod_sync_artifacts.yml
=> Add manual trigger for prod sync

swan-lake/learn/api-docs/ballerina/java.jdbc/index.html, swan-lake/learn/api-docs/ballerina/mysql/index.html, swan-lake/learn/by-example/different-payload-types.html, swan-lake/learn/by-example/header-based-routing.html, swan-lake/learn/by-example/http-1-1-to-2-0-protocol-switch.html, swan-lake/learn/by-example/http-100-continue.html, swan-lake/learn/by-example/query-path-matrix-param.html, swan-lake/learn/by-example/websocket-chat-application.html
=> Fix broken links

downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
=> Update lang.array:sort() example in the Swan Lake Release Note

learn/api-docs/ballerina/java.jdbc/index.html, learn/by-example/jdbc-client-batch-update.html, learn/by-example/jdbc-client-call-procedures.html, learn/by-example/jdbc-client-crud-operations.html, learn/by-example/jdbc2-complex-type-queries.html, learn/by-example/jdbc2-execute-operation.html, learn/by-example/jdbc2-init-options.html, learn/by-example/jdbc2-query-operation.html, learn/by-example/mysql-complex-type-queries.html, learn/by-example/mysql-execute-operation.html, learn/by-example/mysql-init-options.html, learn/by-example/mysql-query-operation.html, learn/running-ballerina-code.md, swan-lake/learn/api-docs/ballerina/java.jdbc/index.html, swan-lake/learn/api-docs/ballerina/mysql/index.html, swan-lake/learn/by-example/jdbc-batch-execute-operation.html, swan-lake/learn/by-example/jdbc-complex-type-queries.html, swan-lake/learn/by-example/jdbc-execute-operation.html, swan-lake/learn/by-example/jdbc-init-options.html, swan-lake/learn/by-example/jdbc-parameterized-query.html, swan-lake/learn/by-example/jdbc-query-operation.html, swan-lake/learn/by-example/mysql-batch-execute-operation.html, swan-lake/learn/by-example/mysql-call-stored-procedures.html, swan-lake/learn/by-example/mysql-complex-type-queries.html, swan-lake/learn/by-example/mysql-execute-operation.html, swan-lake/learn/by-example/mysql-init-options.html, swan-lake/learn/by-example/mysql-parameterized-query.html, swan-lake/learn/by-example/mysql-query-operation.html
Fix the driver path in MySQL & JDBC BBEs.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/200
=> Fix the Driver Path in MySQL & JDBC BBEs

events.md
=> Add Open Source Summit Japan

learn/testing-ballerina-code/writing-tests.md, swan-lake/learn/testing-ballerina-code/writing-tests.md
Fix the issues in the Writing Tests page[1] in Swan Lake.
[1] https://ballerina.io/swan-lake/learn/testing-ballerina-code/writing-tests/
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1369
=> Fix the Issues in the Writing Tests Page in Swan Lake

downloads/swan-lake-release-notes/swan-lake-preview4/RELEASE_NOTE.md
=> Add a note on predeclared module prefixes to the slp4 release note

learn/using-the-openapi-tools.md, swan-lake/learn/using-the-openapi-tools.md
Swap the Open API Learn page versions.
> Fixes #
=> Swap the Open API Learn Page Versions

1.0/learn/how-to-structure-ballerina-code/index.html, 1.1/learn/how-to-structure-ballerina-code/index.html, learn/structuring-ballerina-code.md, swan-lake/learn/structuring-ballerina-code.md
Fix a typo in the "Structuring Ballerina Code" learn page.
> Fixes #
=> Fix a Typo in the "Structuring Ballerina Code" Learn Page

_layouts/ballerina-inner-page.html, css/ballerina-io.css, learn/quick-tour.md, swan-lake/learn/quick-tour.md
=> Add toc to quick tour

_layouts/ballerina-release-notes.html, downloads/release-notes.md, downloads/swan-lake-release-notes.md
=> Remove TOC from release notes

swan-lake/learn/testing-ballerina-code/mocking.md
=> Update Object Mocking Http example in Testing-Ballerina-Code page

downloads.html
Update the Downloads page for SLP5.
> Fixes #
=> Update the Downloads page for SLP5

downloads/swan-lake-release-notes/swan-lake-preview5/RELEASE_NOTE.md
Add the SLP5 release note.
> Fixes #
=> Add the SLP5 Release Note

downloads/release-notes/1.2.9/RELEASE_NOTE.md
Add the 1.2.9 release note.
> Fixes #
=> Add the 1.2.9 Release  Note

404.html, _layouts/ballerina-inner-page.html, css/bbe-home-page.css, learn/quick-tour.md, page-not-available.html, swan-lake/learn/quick-tour.md
=> Fix toc issues

learn/quick-tour.md, swan-lake/learn/quick-tour.md
=> Fix git stars

js/redirections.js
Add redirections for the Observability BBEs for Swan Lake.
> Fixes #
=> Add Redirections for the Observability BBEs for Swan Lake

downloads.html
Update the titles of the "Downloads" page.
> Fixes #
=> Update the titles of the "Downloads" Page

swan-lake/learn/by-example/all-bbes.json
> $subject of http-client-data-binding
=> Update incorrect BBE url

downloads.html
Update the "Downloads" page for SLP5.
> Fixes #
=> Update the "Downloads" Page for SLP5

learn/calling-java-code-from-ballerina.md
Doc Issue: #1420 
Related Issue: https://github.com/ballerina-platform/ballerina-lang/issues/26219
=> Remove the Maven Resolver section from learn page

downloads/swan-lake-release-notes/swan-lake-preview5/RELEASE_NOTE.md
=> Update release note saying websub module is not working with SLP5

downloads/swan-lake-release-notes/swan-lake-preview5/RELEASE_NOTE.md
Say that Socket module needs to be built in offline mode.
=> Add a known issue to release note

js/redirections.js
Since it is being added in SLP5 need to add redirections for the "HTTP Client Data Binding" BBE for previous version in Bio.
> Fixes #
=> Add redirections for the "HTTP Client Data Binding" BBE

code-of-conduct.md, community.md, community/slack.md, license-of-site.md, privacy-policy.md, security.md, terms-of-service.md
Add TOCs to the docs of the footer links.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1446
=> Add TOCs to the Docs of the Footer Links

learn/api-docs/ballerina/docker/annotations.html, learn/api-docs/ballerina/docker/index.html, learn/api-docs/ballerina/docker/records/DockerConfiguration.html, learn/api-docs/ballerina/docker/records/ExposeConfig.html, learn/api-docs/ballerina/docker/records/FileConfig.html, learn/api-docs/ballerina/docker/records/FileConfigs.html
Replace the Docker module in 1.2 to fix the broken link[1].
[1] https://github.com/ballerina-platform/ballerina-lang/issues/25417
> Fixes #
=> Replace the Docker Module in 1.2 to Fix the Broken Link

events.md
=> Remove toc

1.0/page-not-available.html, swan-lake/page-not-available.html
Fix the TOCs in the Page Not Available error pages.
> Fixes #
=> Fix the TOCs in the Page Not Available error pages

events.md
=> Update Open Source Summit Japan event

.github/workflows/add_link_checker.yml
Add the link checker.
> Fixes #
=> Add the Link Checker

.github/scripts/publish_homebrew.py
=> Fix preceding white-space issue in publish_homebrew.py

community.md
=> Remove back to top link from community page

downloads/release-notes/1.2.10/RELEASE_NOTE.md
Add the 1.2.10 release note.
> Fixes #
=> Add the 1.2.10 Release Note

css/home-page-2020.css, home.html
=> Add new home page

1.0/learn/how-to-document-ballerina-code/index.html, 1.1/learn/how-to-document-ballerina-code/index.html, learn/documenting-ballerina-code.md, swan-lake/learn/documenting-ballerina-code.md
Improve the Tip in the "Documenting Ballerina Code" Learn page.
> Fixes #
=> Improve the Tip in the "Documenting Ballerina Code" Learn Page

swan-lake/learn/quick-tour.md
Fix the titles of the Swan Lake Quick Tour.
> Fixes #
=> Fix the Titles of the Swan Lake Quick Tour

swan-lake/learn/testing-ballerina-code/mocking.md
Update mocking portion of the testing-ballerina-code learn page
> Fixes #
=> Update testing-ballerina-code for swan-lake

swan-lake/learn/testing-ballerina-code/writing-tests.md
Add test assertion diff examples
=> Add test assertion diff examples

_config.yml
Change the dist server link from HTTP to HTTPS.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1497
=> Change the Dist Server Link from HTTP to HTTPS

_data/learnnavswanlake.yml, swan-lake/learn.md
Add the User Guide link for Swan Lake.
> Fixes #
=> Add the User Guide Link for Swan Lake

learn/testing-ballerina-code/executing-tests.md
Update commands for Testing-Ballerina-Code
=> Update testing-ballerina-code for 1.2.x

swan-lake/learn/installing-ballerina.md, swan-lake/learn/quick-tour.md
Fix issues in getting started guides.
> Fixes #
=> Fix issues in getting started guides

downloads/swan-lake-release-notes/swan-lake-preview6/RELEASE_NOTE.md
Add details of package to release note.
=> Add packages to slp7 release notes

community.md
=> Add standard library repo to community page

_data/stable-latest/metadata.json
=> Update metadata for 1.2.11 release

downloads/release-notes/1.2.11/RELEASE_NOTE.md
Add the 1.2.11 release note.
> Fixes #
=> Add the 1.2.11 Release Note

_data/stable-latest/metadata.json
=> Revert "Update metadata for 1.2.11 release"

_includes/ballerina-footer.html
=> Hide cookie policy

_data/swanlake-latest/metadata.json
=> Update metadata for SLP7

downloads/swan-lake-archived.md, downloads/swan-lake-release-notes/swan-lake-preview6/RELEASE_NOTE.md, downloads/swan-lake-release-notes/swan-lake-preview7/RELEASE_NOTE.md
Fix the SLP7 release note.
> Fixes #
=> Fix the SLP7 Release Note

1.0/learn/vscode-plugin/index.html, 1.1/learn/vscode-plugin/index.html, learn/tools-ides/setting-up-visual-studio-code.md, swan-lake/learn/tools-ides/setting-up-visual-studio-code.md
Update VSCode docs.
> Fixes #1542
=> Update VSCode Docs

swan-lake/learn/documenting-ballerina-code.md
> Refactor documentation learn page to reflect ProjectAPI changes
=> Refactor documentation learn page

learn/keeping-ballerina-up-to-date.md, swan-lake/learn/keeping-ballerina-up-to-date.md
Remove the minor releases frequency from docs.
> Fixes #1562
=> Remove the Minor Releases Frequency from Docs

_config.yml
Revert the "config.yml" file changes.
> Fixes #
=> Revert the "config.yml" File Changes

swan-lake/learn/testing-ballerina-code/mocking.md, swan-lake/learn/testing-ballerina-code/testing-quick-start.md
=> Update testing-ballerina-code for swan-lake spl8

events.md
=> Remove upcoming events section

events.md
Comment out the "Upcoming Events" from the Events page.
> Fixes #
=> Comment Out the "Upcoming Events" from the Events Page

learn/calling-java-code-from-ballerina.md, swan-lake/learn/calling-java-code-from-ballerina.md, swan-lake/learn/structuring-ballerina-code/structuring-ballerina-code.md
=> Fix .bal word highlighting in the docs

_data/swanlake-latest/metadata.json
=> Update metadata for slp8 release

downloads/swan-lake-release-notes/swan-lake-preview8/RELEASE_NOTE.md
Fix issues of the SLP8 release note.
> Fixes #
=> Fix Issues of the SLP8 Release Note

swan-lake/learn/testing-ballerina-code/executing-tests.md
=> Fix executing tests learn page

swan-lake/learn/by-example/graphql-resources-with-record-values.html, swan-lake/learn/by-example/graphql-resources-with-scalar-values.html
Fix the .out files of the GraphQL BBEs.
> Fixes #
=> Fix the .out Files of the GraphQL BBEs

swan-lake/learn/by-example/graphql-resources-with-record-values.html, swan-lake/learn/by-example/graphql-resources-with-scalar-values.html
Fix the comments in the .out files of the GraphQL BBEs.
> Fixes #
=> Fix the Comments in the .out Files of the GraphQL BBEs

.github/workflows/publish_homebrew.yml
=> Disable auto triggering homebrew workflow

downloads/release-notes/1.2.12/RELEASE_NOTE.md
Add the 1.2.12 release note.
> Fixes #
=> Add the 1.2.12 Release Note

_data/stable-latest/metadata.json
=> Update metadata for 1.2.12 release

swan-lake/learn/quick-tour.md
Update the Swan Lake Quick Tour on HTTP service related changes.
> Fixes #
=> Update the Swan Lake Quick Tour on HTTP Service Related Changes

learn/api-docs/ballerina/awslambda/annotations.html, learn/api-docs/ballerina/awslambda/functions.html, learn/api-docs/ballerina/awslambda/index.html, learn/api-docs/ballerina/awslambda/objects/Context.html, learn/api-docs/ballerina/awslambda/records/APIGatewayProxyRequest.html, learn/api-docs/ballerina/awslambda/records/DynamoDBEvent.html, learn/api-docs/ballerina/awslambda/records/DynamoDBRecord.html, learn/api-docs/ballerina/awslambda/records/DynamoDBStreamRecord.html, learn/api-docs/ballerina/awslambda/records/NameValue.html, learn/api-docs/ballerina/awslambda/records/S3Bucket.html, learn/api-docs/ballerina/awslambda/records/S3Element.html, learn/api-docs/ballerina/awslambda/records/S3Event.html, learn/api-docs/ballerina/awslambda/records/S3Identity.html, learn/api-docs/ballerina/awslambda/records/S3Object.html, learn/api-docs/ballerina/awslambda/records/S3Record.html, learn/api-docs/ballerina/awslambda/records/SESAction.html, learn/api-docs/ballerina/awslambda/records/SESCommonHeaders.html, learn/api-docs/ballerina/awslambda/records/SESElement.html, learn/api-docs/ballerina/awslambda/records/SESEvent.html, learn/api-docs/ballerina/awslambda/records/SESMail.html, learn/api-docs/ballerina/awslambda/records/SESReceipt.html, learn/api-docs/ballerina/awslambda/records/SESRecord.html, learn/api-docs/ballerina/awslambda/records/SESVerdict.html, learn/api-docs/ballerina/awslambda/records/SQSEvent.html, learn/api-docs/ballerina/awslambda/records/SQSRecord.html, learn/api-docs/ballerina/index.html
Add deployment modules to the index page of 1.2.12 API docs.
> Fixes #
=> Add Deployment Modules to the Index Page of 1.2.12 API Docs

swan-lake/learn/structuring-ballerina-code/structuring-ballerina-code.md, swan-lake/learn/structuring-ballerina-code/working-with-ballerina-modules.md
=> Fix issues in ballerina package related learn pages

learn/calling-java-code-from-ballerina.md, swan-lake/learn/deployment/docker.md
Do a few minor edits in learn pages.
> Fixes #
=> Do a Few Minor Edits in Learn Pages

swan-lake/learn/deployment/docker.md
=> Update service syntax

js/redirections.js
Redirect secured service with OAuth BBE for Swan Lake.
> Fixes #
=> Redirect Secured Service with OAuth BBE for Swan Lake

js/redirections.js
$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/1073
=> Redirect access control BBE pages for Swan Lake

js/redirections.js
$subject related to https://github.com/ballerina-platform/ballerina-dev-website/pull/1652
=> Fix commas for redirections

_data/stable-latest/metadata.json
=> Update metadata for 1.2.13 release

downloads/release-notes/1.2.13/RELEASE_NOTE.md
Add the 1.2.13 release note.
> Fixes #
=> Add the 1.2.13 Release Note

.github/workflows/add_link_checker.yml, 1.1/learn/api-docs/ballerinax/awslambda.html, learn/coding-conventions/top-level-definitions.md, swan-lake/learn/coding-conventions/top-level-definitions.md
Fix links of the link checker report.
> Fixes #
=> Fix Links of the Link Checker Report

1.0/page-not-available.html, 1.1/page-not-available.html, page-not-available.html, swan-lake/page-not-available.html
Update the "Page Not Available" message.
> Fixes #
=> Update the "Page Not Available" Message

swan-lake/learn/documenting-ballerina-code.md
> Update ballerina command to bal in documentation learn page
=> Update ballerina command to bal in documentation learn page

swan-lake/learn/by-example/aws-lambda-deployment.html, swan-lake/learn/by-example/c2c-deployment.html, swan-lake/learn/by-example/docker-deployment.html, why-ballerina/network-aware-type-system.md, why-ballerina/the-network-in-the-language.md
Update the `bal` command in "Why Ballerina" pages.
> Fixes #
=> Update the `bal` Command in "Why Ballerina" Pages

swan-lake/learn/testing-ballerina-code/executing-tests.md, swan-lake/learn/testing-ballerina-code/mocking.md, swan-lake/learn/testing-ballerina-code/testing-quick-start.md, swan-lake/learn/testing-ballerina-code/writing-tests.md
Update testerina learn page with new annotation changes
> Fixes #
=> Update Testerina Writing tests

swan-lake/learn/installing-ballerina.md, swan-lake/learn/keeping-ballerina-up-to-date.md
=> Update ballerina to bal command change in the learn page

swan-lake/learn/testing-ballerina-code/writing-tests.md
=> Change Testerina configuration details

swan-lake/learn/observing-ballerina-code.md
> Update Ballerina Observability to the new configuration model
=> Update Ballerina Observability to the new configuration model

js/redirections.js
$subject related to https://github.com/ballerina-platform/ballerina-distribution/pull/1182
=> Update redirection of access control BBEs

swan-lake/learn/security/authentication-and-authorization.md
This PR updates the `authentication and authorization` learn page for Swan Lake, which is under security category.
This page was newly added by https://github.com/ballerina-platform/ballerina-dev-website/pull/1699
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/584
=> Update authn/authz learn page for SwanLake alpha

swan-lake/learn/deployment/code-to-cloud/code-to-cloud-samples.md
=> Rename module to package

swan-lake/learn/observing-ballerina-code.md
Add additional content for setting up prometheus
Rename `ballerina` to `bal` in a missed place
=> Update setting up prometheus

_data/learnnavswanlake.yml, swan-lake/learn/publishing-modules-to-ballerina-central.md, swan-lake/learn/running-ballerina-code.md, swan-lake/learn/using-the-cli-tools.md
$subject
Update `running ballerina code` and `publishing-modules-to-ballerina-central` learn pages
=> Update learn pages

swan-lake/learn/security/authentication-and-authorization.md
=> Update authn/authz learn page

swan-lake/learn/by-example/anydata-type.html
Fix the next previous links of the Anydata type BBE.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/1721
=> Fix the next previous links of the Anydata Type BBE

swan-lake/learn/running-ballerina-code.md
=> Fix typo in running-ballerina-code.md

swan-lake/learn/by-example/anydata-type.html
Update the Anydata Type BBE.
> Fixes #
=> Update the Anydata Type BBE

swan-lake/learn/structuring-ballerina-code/working-with-ballerina-modules.md
=> Update working with modules learn page

swan-lake/learn/coding-conventions.md, swan-lake/learn/coding-conventions/top-level-definitions.md
=> Update formatting of code samples in the coding convention related learn pages

swan-lake/learn/security/writing-secure-ballerina-code.md
=> Update how to write secure code learn page

swan-lake/learn/quick-tour.md
=> Update quick tour with new service syntax

_data/swanlake-latest/metadata.json
=> Update to alpha release

swan-lake/learn/by-example/csv-io.html, swan-lake/learn/by-example/json-io.html
=> Fix ballerina->bal in I/O BBEs

download.html, downloads/swan-lake-release-notes/swan-lake-alpha/RELEASE_NOTE.md
Add Swan Lake Alpha release note.
> Fixes #
=> Add Swan Lake Alpha Release Note

swan-lake/learn/deployment/code-to-cloud/code-to-cloud-samples.md
=> Fix service syntax

downloads/swan-lake-release-notes/swan-lake-alpha1/RELEASE_NOTE.md
Fix more issues in the SL Alpha release note.
> Fixes #
=> Fix More Issues in the SL Alpha Release Note

downloads/swan-lake-release-notes/swan-lake-alpha1/RELEASE_NOTE.md
Fix more issues in the Swan Lake Alpha1 release note.
> Fixes #
=> Fix More Issues in the Swan Lake Alpha1 Release Note

download.html, downloads/swan-lake-release-notes/swan-lake-alpha1/RELEASE_NOTE.md
Update the `bal dist pull` command for Swan Lake Alpha1.
> Fixes #
=> Update the `bal dist pull` Command for Swan Lake Alpha1

downloads/swan-lake-release-notes/swan-lake-alpha1/RELEASE_NOTE.md
Fix the topics in the TOC of the SLAlpha1 release note.
> Fixes #
=> Fix the Topics in the TOC of the SLAlpha1 Release Note

swan-lake/learn.md
Add the "Language Guide" to Swan Lake Learn.
> Fixes #
=> Add the "Language Guide" to Swan Lake Learn

swan-lake/learn.md
Open all links of Swan Lake Learn in new tabs.
> Fixes #
=> Open all Links of Swan Lake "Learn" in New Tabs

swan-lake/learn/using-the-cli-tools.md
Update ballerina to bal in CLI tools learn page
> Fixes #
=> Update using-the-cli-tools learn page

swan-lake/learn/generating-ballerina-code-for-protocol-buffer-definitions.md
> Update `Generating Ballerina Code for Protocol Buffer Definitions` learn page with minor content changes.
> Fixes #
=> Update content in generating-ballerina-code-for-protocol-buffer-definitions.md

README.md
=> Added 'bundle install' step to readme

swan-lake/learn/calling-java-code-from-ballerina.md
> Update Interoperability doc to explain how to use Ballerina Complex Types in Java
> Fixes #27017
=> Update Interoperability doc to explain how to use Ballerina complex types in Java

swan-lake/learn/network-communication/http/communication-resiliency.md, swan-lake/learn/network-communication/http/data-binding.md, swan-lake/learn/network-communication/http/data-streaming.md, swan-lake/learn/network-communication/http/http.md, swan-lake/learn/network-communication/http/multipart-message-handling.md, swan-lake/learn/network-communication/http/secure-communication.md
Restrcuture the HTTP Guide.
> Fixes #
=> Restrcuture the HTTP Guide

swan-lake/learn/by-example/kafka-authentication-sasl-plain-consumer.html, swan-lake/learn/by-example/kafka-authentication-sasl-plain-producer.html, swan-lake/learn/by-example/kafka-consumer-client.html, swan-lake/learn/by-example/kafka-consumer-group-service.html, swan-lake/learn/by-example/kafka-consumer-service.html, swan-lake/learn/by-example/kafka-producer-transactional.html, swan-lake/learn/by-example/kafka-producer.html, swan-lake/learn/by-example/mysql-batch-execute-operation.html, swan-lake/learn/by-example/mysql-call-stored-procedures.html, swan-lake/learn/by-example/mysql-complex-type-queries.html, swan-lake/learn/by-example/mysql-execute-operation.html, swan-lake/learn/by-example/mysql-init-options.html, swan-lake/learn/by-example/mysql-parameterized-query.html, swan-lake/learn/by-example/mysql-query-operation.html, swan-lake/learn/by-example/nats-basic-client.html, swan-lake/learn/by-example/nats-streaming-client.html, swan-lake/learn/by-example/nats-streaming-durable-subscriptions.html, swan-lake/learn/by-example/nats-streaming-queue-group.html, swan-lake/learn/by-example/nats-streaming-start-position.html, swan-lake/learn/by-example/rabbitmq-consumer-with-client-acknowledgement.html, swan-lake/learn/by-example/rabbitmq-consumer.html, swan-lake/learn/by-example/rabbitmq-producer.html, swan-lake/learn/by-example/rabbitmq-transaction-consumer.html, swan-lake/learn/by-example/rabbitmq-transaction-producer.html
> Fixes links to ballerinax modules
=> Fix ballerinax links

download.html
Update the "Downloads" page to prioritise Swan Lake.
> Fixes #
=> Update the "Downloads" Page to Prioritise Swan Lake

download.html
Update the "Downloads" page for Swan Lake.
> Fixes #
=> Update the "Downloads" Page for Swan Lake

swan-lake/learn/network-communication/grpc/grpc.md
Resize the "admin RPC service" image.
> Fixes #
=> Resize the "Admin RPC Service" Image

spec/lang/draft/style/ballerina-language-specification.js, spec/lang/draft/v2020-06-18/style/ballerina-language-specification.js, spec/lang/draft/v2020-09-16/style/ballerina-language-specification.js, spec/lang/draft/v2020-09-22/style/ballerina-language-specification.js, spec/lang/draft/v2020-12-17/style/ballerina-language-specification.js, spec/lang/master/style/ballerina-language-specification.js
> Fixed the mixed content security issue
> Fixes #1490
=> Fixed the mixed content security issue

1.0/page-not-available.html, 1.1/page-not-available.html, page-not-available.html, swan-lake/page-not-available.html
Add the slash redirection to the "Page not Available" pages.
> Fixes #
=> Add the Slash Redirection to the "Page not Available" Pages

_data/learnnavswanlake.yml, swan-lake/learn/processing-data-events/using-language-integrated-queries.md
Add the "Language Integrated Queries" to the Swan Lake "User Guide".
> Fixes #
=> Add the "Language Integrated Queries" to the Swan Lake "User Guide"

why-ballerina/network-aware-type-system.md
=> Update Why Ballerina - Type System Content for Swan Lake Alpha 1

why-ballerina/the-network-in-the-language.md
=> Update Why Ballerina - Network Content for Swan Lake Alpha 1

why-ballerina/sequence-diagrams-for-programming.md
=> Update Why Ballerina - Sequence Diagram Content for Swan Lake Alpha 1

swan-lake/learn/network-communication/grpc/grpc.md, swan-lake/learn/network-communication/grpc/implementing-grpc-services-and-clients.md, swan-lake/learn/network-communication/grpc/performing-grpc-streaming.md, swan-lake/learn/processing-data-events/using-language-integrated-queries.md
Update More Changes in the new Learn Pages below.
- Language Integrated Queries
- HTML
- gRPC
> Fixes #
=> Update More Changes in the New Learn Pages

swan-lake/learn/processing-data-events/using-language-integrated-queries.md
Fix the sample code in the "Language Integrated Query" Learn page.
> Fixes #
=> Fix the Sample Code in the "Language Integrated Query" Learn Page

download.html
Fix the "Downloads" page for Swan Lake Alpha2.
> Fixes #
=> Fix the "Downloads" Page for Swan Lake Alpha2

404.html
=> Hide version picker

hbs/archived_list.hbs
=> added an ID for each download section

_layouts/ballerina-landing-page.html
=> Add slp6 to the archives

download.html, learn/by-example/c2c-deployment.html, learn/calling-java-code-from-ballerina.md, learn/deployment/code-to-cloud/code-to-cloud-samples.md, learn/deployment/code-to-cloud/code-to-cloud.md, learn/network-communication/grpc/implementing-grpc-services-and-clients.md, learn/network-communication/grpc/performing-grpc-streaming.md, learn/structuring-ballerina-code/structuring-ballerina-code.md
Rename "BALO" to "BALA" in Swan Lake.
> Fixes #
=> Rename "BALO" to "BALA" in Swan Lake

learn/by-example/index.html, learn/calling-java-code-from-ballerina.md, why-ballerina/batteries-included.md, why-ballerina/from-code-to-cloud.md, why-ballerina/network-aware-type-system.md, why-ballerina/sequence-diagrams-for-programming.md, why-ballerina/the-network-in-the-language.md
Update the links in "Why Ballerina" pages.
> Fixes #
=> Update the Links in "Why Ballerina" Pages

why-ballerina/from-code-to-cloud.md
- Update code to cloud info in Why Ballerina
=> Update code to cloud info

js/ballerina-common.js
=> Fixed the dropdown for Safari

.github/workflows/add_link_checker.yml
Update the Link Checker to skip HTTPS.
> Fixes #
=> Update the Link Checker to Skip HTTPS

.github/workflows/add_spell_checker.yml, learn/keeping-ballerina-up-to-date.md
Update the Swan Lake Update Tool page.
> Fixes #
=> Update the Swan Lake Update Tool Page

why-ballerina/the-network-in-the-language.md
=> Update IAM section of network-in-the-language

.github/workflows/sw_update_api_docs.yml, .github/workflows/sw_update_ballerina_by_example.yml, .github/workflows/update_api_docs.yml, .github/workflows/update_ballerina_by_example.yml
Update the release workflows for Swan Lake.
> Fixes #
=> Update the Release Workflows for Swan Lake

1.2/learn.md, 1.2/learn/by-example/kubernetes-deployment.html, downloads/archived.md, downloads/release-notes.md, learn/network-communication/http/multipart-message-handling.md, why-ballerina/from-code-to-cloud.md, why-ballerina/the-network-in-the-language.md
Fix more broken links.
> Fixes #
=> Fix More Broken Links

.github/workflows/add_link_checker.yml
Update link checker to add 1.2.
> Fixes #
=> Update Link Checker to Add 1.2

_data/swanlake-latest/metadata.json
=> Update metadata.json with slalpha2 release

Gemfile.lock
=> Updated the lock file

1.2/learn.md
=> Fixed the build issue

learn-2.md, learn.md
Update the descriptions of the Swan Lake Learn page.
> Fixes #
=> Update the Descriptions of the Swan Lake Learn Page

swan-lake/learn/api-docs/ballerina/index.html
=> Add api doc redirects from /swan-lake/learn

404.html
=> Added swan lake common redirection for learn pages

swan-lake/learn/api-docs/ballerina/index.html
=> Add redirects for /swan-lake/learn API Docs

swan-lake/learn/api-docs/ballerina/index.html
=> Improve redirection 

download.html, downloads/swan-lake-release-notes/swan-lake-alpha2/RELEASE_NOTE.md
Add the Swan Lake Alpha2 Release Note.
> Fixes #
=> Add the Swan Lake Alpha2 Release Note

learn/deployment/code-to-cloud/code-to-cloud-samples.md, learn/deployment/code-to-cloud/code-to-cloud.md
- Simplify sample service code
- https://github.com/ballerina-platform/module-ballerina-c2c/issues/103
=> Simplify sample service code

learn/api-docs/ballerina/java/index.html
=> Fix java api docs redirect

.github/workflows/sw_update_ballerina_by_example.yml
> Fixes the path issue by getting the short version from the metadata.json file
=> Fix distribution path issue in BBE gen workflow

.github/workflows/sw_update_api_docs.yml
=> Fix short version in Swan Lake API doc gen workflow

_data/swanlake-latest/metadata.json
=> Update metadata.json for slalpha2 release

.github/workflows/add_link_checker.yml
Remove SendGrid configuration.
> Fixes #
=> Remove SendGrid Configuration

download.html
Update the Downloads page.
> Fixes #
=> Update the Downloads Page

_data/swanlake-latest/metadata.json, download.html
Add display version in the "metadata.json" file for Swan Lake.
> Fixes #
=> Add Display Version in the "metadata.json" File for Swan Lake

css/ballerina-io-learn-v2.css, css/ballerina-io.css
=> Fix brteadcrumbs

community.md, community/newsletter.md
=> Update newsletter URLs

index.html, learn.md, learn/user-guide/getting-started.md
Update the new Home page.
> Fixes #
=> Update the New Home Page
