downloads/release-artifacts-verification.md
pages/downloads/release-artfiacts-verification.js

Change verification docs

---

swan-lake/learn-the-platform/build-a-graalvm-executable/build-the-executable-in-a-container.md

Fix code formatting issues with GraalVM guide

---

downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md

Update the example for group-by/collect

---

downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md

Add separate sections for aggregation in the Update 7 release note.
> Fixes #

Add separate sections for aggregation in the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md

Address more Up7 release note review comments.
> Fixes #

Address more Up7 release note review comments

---

components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/data-immutability.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/expressive-query.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/flexible-typing.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/optional-types.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/pattern-matching.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/record-type.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/stream-type.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/table-type.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/type-constraints.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/union-types.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/xml-support.md

[DOP] Update sample URLs

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json

Update metadata.json for 2201.7.0 release

---

downloads/swan-lake-release-notes/swan-lake-2201.0.1/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.0.2/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.0.3/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.0.4/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.0.5/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.1.1/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.1.2/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.2.1/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.2.2/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.2.3/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md

Fix the release version inconsistencies.
> Fixes #

Fix the release version inconsistencies

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Create the 2201.8.0 release note.
> Fixes #

Create the 2201.8.0 release note

---

swan-lake/learn-the-language/distinctive-language-features/advanced-general-purpose-language-features.md

Fix minor typo found here: 
https://ballerina.io/learn/distinctive-language-features/advanced-general-purpose-language-features/#object-types
N/A

Fix minor typo

---

downloads/swan-lake-release-notes/swan-lake-2201.6.1/RELEASE_NOTE.md

Add `2201.6.1` release note

---

swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/aws-lambda.md

Address the review comments on the AWS Lambda page in https://github.com/ballerina-platform/ballerina-dev-website/pull/6970.
> Fixes #

Address review comments on AWS Lambda page

---

swan-lake/featured-scenarios/work-with-data-using-queries-in-ballerina.md

Update the aggregation and grouping titles in guides.
> Fixes #

Update the aggregation and grouping titles in guides

---

downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md

Update the aggregation sections
.
> Fixes #

Update the aggregation sections

---

components/common/top-nav/TopNav.js
components/common/top-nav/TopNav.module.css

Add DOP usecases to navbar

---

components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/record-type-ballerina.md
components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/stream-type-ballerina.md
components/integration/data-oriented-programming/code/java-bbe/record-type.md

[DOP] Update samples to avoid scrolling

---

downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md

Update the `JetStreamClient` and `JetStreamListener` hyperlinks.
> Fixes #7017

Update the `JetStreamClient` and `JetStreamListener` hyperlinks

---

swan-lake/why-ballerina/graphical.md

Update the Graphical Why Ballerina page.
> Fixes #

Update the Graphical Why Ballerina page

---

components/b2b/code/b2b-bbe/ballerina-is-edifact.md

> Change the EDIFACT sample to avoid nesting

Change the EDIFACT sample to avoid nesting

---

components/common/top-nav/CustomMenu.js
components/common/top-nav/CustomToggle.js
components/common/top-nav/TopNav.js
components/common/top-nav/TopNav.module.css

Redesign top nav

---

components/common/top-nav/TopNav.js

Fix broken url

---

components/common/top-nav/CustomMenu.js
components/common/top-nav/CustomToggle.js
components/common/top-nav/TopNav.js

Fix build issues

---

pages/usecases/data-oriented-programming/index.js
pages/usecases/integration/ballerina-vs-java-for-data-oriented-programming/index.js

Update DOP banner images

---

downloads/swan-lake-release-notes/swan-lake-2201.7.1/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

[2201.7.1] - Add 2201.7.1 release note

---

components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/data-immutability-java.md

Update class name in DOP sample

---

components/integration/ballerina-vs-java-for-data-oriented-programming/code/java-bbe/table-type-ballerina.md

Fix incorrect table sample in DOP

---

swan-lake/learn-the-platform/source-code-dependencies/manage-dependencies.md

Update https://ballerina.io/learn/manage-dependencies/#update-dependency-versions to depict how versions are updated when there is a distribution version minor change.
> Related to https://github.com/ballerina-platform/ballerina-lang/issues/39850

[WIP] - Mention dependency resolution for new distributions

---

_data/stable-latest/metadata.json

Update metadata.json for `1.2.41` release

---

components/common/top-nav/CustomToggle.js

Add role to Explore button in top nav

---

package-lock.json
package.json

Update react-bootstrap version

---

.github/workflows/pre-prod_sync.yml

Change the OS of deployment node

---

utils/rearrangeFiles.sh

Fix shell script failure

---

swan-lake/learn-the-platform/ballerina-tooling/ballerina-shell.md

$title
https://github.com/ballerina-platform/ballerina-lang/issues/41034

[2201.8.0] Make ballerina shell experimental

---

utils/rearrangeFiles.sh

Update shell script

---

components/eda/code/eda-bbe/webhook_with_websub_hub.md
components/eda/code/eda-bbe/websocket.md

Squeeze in the code

---

components/b2b/code/b2b-bbe/ballerina-is-edifact.md
components/common/top-nav/TopNav.js

Update top nav and fix code length

---

pages/usecases/b2b/index.js

Update b2b sm-banner

---

_data/release_notes_versions.json
_data/stable-latest/metadata.json
downloads/1.2.x-release-notes/1.2.42.md
utils/archived-lm.json
utils/rl.json

Update metadata.json and release note for release `1.2.42`

---

swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md

Address FaaS docs review comments.
> Fixes #

Address FaaS docs review comments

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[2201.8.0] Add list constant feature to release note

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.7.1/RELEASE_NOTE.md
utils/archived-lm.json

$title
Other files are updated in https://github.com/ballerina-platform/ballerina-dev-website/pull/7353

Update release note and `metadata.json` for `2201.7.1` release

---

downloads/swan-lake-release-notes/swan-lake-2201.6.1/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.7.1/RELEASE_NOTE.md

Update tooling bug fixes sections of release note.
> Fixes #

Update tooling bug fixes sections of release notes

---

swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md

Fix the Azure Functions BBE link.
> Fixes #

Fix the Azure Functions BBE link

---

swan-lake/learn-the-platform/run-in-the-cloud/function-as-a-service/azure-functions.md

Update the step to create an Azure subscription.
Update the step to create an Azure subscription.
> Fixes #

Update the step to create an Azure subscription

---

components/common/footer/Footer.js
components/common/top-nav/CustomMenu.js
components/common/top-nav/TopNav.js
styles/globals.css

Fix TopNav dropdown hover and fix warnings

---

components/common/top-nav/TopNav.js
components/community/blog/Blog.js
components/community/blog/Blog.module.css
components/home-page/intro/Intro.module.css
pages/community/index.js

Add blog to community page and update topnav

---

pages/index.js
styles/Home.module.css

Change Events blade order

---

_data/release_notes_versions.json
_data/stable-latest/metadata.json
downloads/1.2.x-release-notes/1.2.43.md
utils/archived-lm.json
utils/rl.json

Update release note and `metadata.json` for `1.2.43` release

---

policy/privacy-policy.md

Add the updated  privacy policy content.
> Fixes #

Add the updated  privacy policy content

---

components/common/top-nav/TopNav.js
components/common/top-nav/TopNav.module.css
styles/globals.css

Update top nav

---

components/common/top-nav/TopNav.js

Add new logo to offCanvas menu

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Add constant byte array literal support release notes

---

components/healthcare/code/healthcare-bbe/ballerina-is-fhir.md
components/healthcare/code/healthcare-bbe/powerful-health-data-mapping.md

Reflect updates to fhir libs

---

swan-lake/learn-the-platform/ballerina-tooling/cli-documentation/cli-commands.md

$subject 
Related to https://github.com/ballerina-platform/ballerina-lang/issues/40264

Add bal tool command details

---

components/home-page/articles/Articles.js

Fix build failures

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Related to https://github.com/ballerina-platform/ballerina-lang/issues/40264

[Update 8] - Bal tool release note

---

components/home-page/articles/Articles.js

Update styles in Articles

---

swan-lake/integration-technology-tools/edi-tool.md
swan-lake/integration-technology-tools/health-tool.md

Fix a few issues in the learn revamp.
> Fixes #

Fix a few issues in the learn revamp

---

package-lock.json

Replace the package lock JSON file.
> Fixes #

Replace the package lock JSON file

---

swan-lake/integration-technology-tools/edi-tool.md

Address the review comments of the EDI tool page.
> Fixes #

Address the review comments of the EDI tool page

---

swan-lake/integration-technology-tools/health-tool.md

Address review comments of the Health tool page.
> Fixes #

Address review comments of the Health tool page

---

components/ai/code/Code.js
components/b2b/code/Code.js
components/data-oriented-programming/code/Code.js
components/eda/code/Code.js
components/healthcare/code/Code.js
components/home-page/articles/Articles.js
components/home-page/articles/Articles.module.css
components/home-page/bal-action/BalAction.js
components/integration/ballerina-vs-apollo-for-graphql/code/Code.js
components/integration/ballerina-vs-java-for-data-oriented-programming/code/Code.js
components/integration/code/Code.js

Add news source and missing images

---

components/home-page/articles/Articles.js
components/home-page/articles/Articles.module.css
pages/index.js

Hide events and update styles

---

swan-lake/integration-technology-tools/edi-tool.md

Add steps in the EDI Tool page.
> Fixes #

Add steps in the EDI Tool page

---

downloads/swan-lake-release-notes/swan-lake-2201.7.2/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add 2201.7.2 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.7.2/RELEASE_NOTE.md

Fix dev tools url

---

components/common/sample-list/SampleList.module.css
next.config.js
package-lock.json
package.json
pages/learn/integration/pre-built-integrations/sample1.js

Add pre-built sample template

---

downloads/swan-lake-release-notes/swan-lake-2201.7.2/RELEASE_NOTE.md

Update OpenAPI release notes

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.7.2/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Sync  release-2201.7.2 with master

---

pages/community/active-proposals.js
pages/downloads/0.9.x-release-notes/[...slug].js
pages/downloads/1.0.x-release-notes/[...slug].js
pages/downloads/1.1.x-release-notes/[...slug].js
pages/downloads/1.2.x-release-notes/[...slug].js
pages/downloads/installation-options.js
pages/downloads/swan-lake-release-notes/[...slug].js
pages/downloads/verify-ballerina-artifacts.js
pages/learn/ballerina-specifications.js
pages/learn/featured-scenarios/[...slug].js
pages/learn/get-started/index.js
pages/learn/learn-the-language/[...slug].js
pages/learn/learn-the-platform/[...slug].js
pages/policies/[slug].js
pages/why-ballerina/[...slug].js

Add edit icon

---

pages/index.js

Hide events blade when there are no upcoming events

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
community/proposals/active-proposals.md
components/eda/code/eda-bbe/email.md
components/eda/code/eda-bbe/grpc.md
components/eda/code/eda-bbe/passing-around-messages.md
components/eda/code/eda-bbe/webhook_with_websub.md
components/eda/code/eda-bbe/webhook_with_websub_hub.md
components/eda/code/eda-bbe/websocket.md
components/home-page/articles/Articles.js
components/home-page/articles/Articles.module.css
components/home-page/why-bal/WhyBal.js
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/clean-and-simple-code.md
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/designer-tool.md
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/diagram-when-you-need.md
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/git-based-workflow.md
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/simplifying-graphql-api-development.md
downloads/swan-lake-release-notes/swan-lake-2201.7.2/RELEASE_NOTE.md
pages/usecases/eda/index.js
public/spec/graphql/spec.md
public/spec/java.jms/spec.md
spec/graphql/spec.md
spec/java.jms/spec.md
utils/archived-lm.json
utils/rl.json

Sync master to sync-revamp

---

pages/downloads/index.js

> Improve download page written content

Improve download page written content

---

swan-lake/integration-tools/health-tool.md

Fix code formatting of health tool example code.
> Fixes #

Fix code formatting of health tool example code

---

pages/downloads/index.js

> Fix download page content issues

Fix download page content issues

---

components/learn/boxes/Boxes.js
next.config.js
swan-lake/integration-tools/grpc-tool.md
utils/learn-lm.json

Fix learn tools

---

components/learn/boxes/Boxes.js

Fix api docs url

---

pages/learn/patterns/[pattern].js
pages/learn/patterns/index.js
styles/globals.css

Update styles in EIP pages

---

components/learn/boxes/Boxes.js
pages/_document.js

Update meta and remove broken links

---

components/common/sample-list/SampleList.js

Update styles in sample list

---

_data/release_notes_versions.json
_data/stable-latest/metadata.json
downloads/1.2.x-release-notes/1.2.44.md
utils/archived-lm.json
utils/rl.json

Add release note and update metadata.json for 1.2.44 release

---

policy/privacy-policy.md

Update the `dpo@wso2.com` email address.
> Fixes #

Update the `dpo@wso2.com` email address

---

pages/downloads/index.js

> Improve learn page reference

Improve learn page reference

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[Update 8] - Add graphql package changes

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

> Related to https://github.com/ballerina-platform/ballerina-lang/issues/41016

[Update 8] - Add custom repository support release note

---

swan-lake/learn-the-platform/build-a-graalvm-executable/build-the-executable-in-a-container.md
swan-lake/learn-the-platform/build-a-graalvm-executable/build-the-executable-locally.md
swan-lake/learn-the-platform/build-a-graalvm-executable/graalvm-executable-overview.md

> $Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4757

[Update 8] - Update GraalVM Learn page with Update 8 changes

---

swan-lake/learn-the-platform/source-code-dependencies/manage-dependencies.md

> Related to https://github.com/ballerina-platform/ballerina-lang/issues/41016

[Update 8] - Add custom repository support

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[Update 8] Add runtime updates to the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

> Fixes #https://github.com/ballerina-platform/openapi-tools/issues/1504

[Update 8] Update release note with OpenAPI tool changes

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[Update 8] - Add std-lib new features to the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[Update 8] Update release note with LS changes

---

pages/learn/patterns/[pattern].js
styles/globals.css

Add back button to EIP pages

---

pages/index.js
styles/Home.module.css

Remove users

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[Update 8] - Add xml map field access changes to release notes

---

community/proposals/active-proposals.md

Update Ballerina active proposals

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.5.2/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add changes related to u5.2 patch

---

components/learn/pattern/Pattern.module.css
pages/learn/enterprise-integration-patterns/index.js
styles/globals.css

Fix style issues in mobile view

---

components/learn/pattern/Pattern.js
components/learn/pattern/Pattern.module.css

Fix alignment issues in EIP patterns

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Add breaking changes related to,
1. https://github.com/ballerina-platform/ballerina-lang/issues/37750
2. https://github.com/ballerina-platform/ballerina-lang/issues/38270
3. https://github.com/ballerina-platform/ballerina-lang/issues/38498
4. https://github.com/ballerina-platform/ballerina-lang/issues/38499
5. https://github.com/ballerina-platform/ballerina-lang/pull/38029

[Update 8] - Add breaking changes details for u8 release note

---

policy/cookie-policy.md
policy/privacy-policy.md

Update missing cookies.
> Fixes #

Update missing cookies

---

policy/cookie-policy.md

Fix cookie tables formatting.
> Fixes #

Fix cookie tables formatting

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

> Add breaking changes related to 
1. https://github.com/ballerina-platform/ballerina-lang/issues/41104
2. https://github.com/ballerina-platform/ballerina-lang/issues/37670
3. https://github.com/ballerina-platform/ballerina-lang/pull/40971

[Update 8] - Add breaking changes for U8

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[Update 8] - Add some breaking changes

---

components/common/main-content/MainContent.js
policy/cookie-policy.md

Fix styles and open external links in new tab

---

pages/learn/enterprise-integration-patterns/Patterns.module.css
pages/learn/enterprise-integration-patterns/[pattern].js
pages/learn/enterprise-integration-patterns/enterprise-integration-patterns/content-filter/content-filter.yml
pages/learn/enterprise-integration-patterns/enterprise-integration-patterns/normalizer/normalizer.yml
pages/learn/enterprise-integration-patterns/enterprise-integration-patterns/scatter-gather/scatter-gather.yml

Convert "ballerina helps" section to markdown.

Fix EIP pages review comments

---

swan-lake/development-tutorials/run-in-the-cloud/aws-lambda.md

$Subject 
Related to https://github.com/ballerina-platform/module-ballerinax-aws.lambda/issues/661
> Fixes #

Add graalvm step to aws lambda

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[Update 8] Add intersection type related changes to the release note

---

components/common/redirect-message/RedirectMessage.js

> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/41341

Add redirection to broken link

---

case-studies/wso2-vs-ballerina.md
components/common/top-nav/CustomMenu.js
components/common/top-nav/TopNav.js
pages/case-studies/[slug].js

Setup case-studies layout

---

components/home-page/users/Users.js

> Include hyperlinks for user logos

Include hyperlinks for user logos

---

components/home-page/users/Users.js

Change url to https

---

components/home-page/users/Users.js

Update Choreo url

---

components/home-page/users/Users.js

Update wso2 url

---

components/home-page/articles/Articles.js

Fix permalink icon

---

pages/learn/integration/pre-built-integrations/google-drive-to-onedrive-integration.js
pages/learn/integration/pre-built-integrations/google-sheets-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/hubspot-contacts-to-google-contacts-integration.js
pages/learn/integration/pre-built-integrations/kafka-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/newsapi-to-email-integration.js
pages/learn/integration/pre-built-integrations/shopify-to-outlook-integration.js

Update sample descriptions

---

case-studies/wso2-vs-ballerina.md
pages/case-studies/[slug].js

Update case-studies layout

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

[Update 8] - Add crypto module breaking changes

---

swan-lake/development-tutorials/build-a-graalvm-executable/build-the-executable-locally.md

> $Subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/7774

Add ARM installer information in GraalVM guide

---

swan-lake/development-tutorials/run-in-the-cloud/azure-functions.md

Change azure functions to java 17

---

pages/learn/integration/pre-built-integrations/ftp-edi-message-to-salesforce-opportunity.js

Format code in the FTP-EDI sample

---

pages/learn/integration/pre-built-integrations/index.js

Update tags for pre-built samples

---

case-studies/wso2-vs-ballerina.md
pages/case-studies/[slug].js
styles/globals.css

Update quote styles

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Add the 2201.8.0 release note to the release branch.
> Fixes #

Add the 2201.8.0 release note to the release branch

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Add the 2201.8.0 release note to the release note branch.
> Fixes #

Add the 2201.8.0 release note to release note branch

---

case-studies/wso2.md

Update the WSO2 testimonial section.
> Fixes #

Update WSO2 testimonial section

---

components/common/sample-list/SampleList.js
components/common/top-nav/TopNav.module.css
components/learn/boxes/Boxes.js
next.config.js
pages/learn/integration/integration-tutorials/[slug].js
pages/learn/integration/integration-tutorials/index.js
swan-lake/integration-tutorials/write-a-restful-api-with-ballerina.md

Add integration-tutorials structure

---

pages/learn/integration/pre-built-integrations/ftp-edi-message-to-salesforce-opportunity.js
pages/learn/integration/pre-built-integrations/github-to-email-integration.js
pages/learn/integration/pre-built-integrations/gmail-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/google-drive-to-onedrive-integration.js
pages/learn/integration/pre-built-integrations/google-sheets-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/hubspot-contacts-to-google-contacts-integration.js
pages/learn/integration/pre-built-integrations/index.js
pages/learn/integration/pre-built-integrations/kafka-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/mysql-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/news-api-to-email-integration.js
pages/learn/integration/pre-built-integrations/salesforce-to-twilio-integration.js
pages/learn/integration/pre-built-integrations/shopify-to-outlook-integration.js

Review prebuilt integration samples text.
> Fixes #

Review prebuilt integration samples text

---

downloads/swan-lake-release-notes/swan-lake-2201.5.3/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add 2201.5.3 release information

---

pages/learn/integration/pre-built-integrations/ftp-edi-message-to-salesforce-opportunity.js
pages/learn/integration/pre-built-integrations/github-to-email-integration.js
pages/learn/integration/pre-built-integrations/gmail-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/google-drive-to-onedrive-integration.js
pages/learn/integration/pre-built-integrations/google-sheets-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/hubspot-contacts-to-google-contacts-integration.js
pages/learn/integration/pre-built-integrations/kafka-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/mysql-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/news-api-to-email-integration.js
pages/learn/integration/pre-built-integrations/salesforce-to-twilio-integration.js
pages/learn/integration/pre-built-integrations/shopify-to-outlook-integration.js

Update alt texts for the images in pre-built examples

---

styles/globals.css

Reduce the font size of quotes

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Fix formatting issues of the 2201.8.0 release note.
> Fixes #

Fix formatting issues of the 2201.8.0 release note

---

pages/learn/integration/integration-tutorials/[slug].js

Revert "Remove integration tutorial slug"

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

> Related to https://github.com/ballerina-platform/ballerina-lang/issues/41016

Modify the custom repository related release note

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Add log and persist changes to the release notes

---

pages/learn/integration/integration-tutorials/index.js
swan-lake/integration-tutorials/service-orchestration.md

Add the service orchestration tutorial

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Fix review suggestions of the 2201.8.0 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Add GraphQL dataloader example

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Address the Update 8 release note review comments added in https://github.com/ballerina-platform/ballerina-dev-website/pull/7801.
> Fixes #

Address the Update 8 release note comments

---

.github/workflows/pre_release_homepage_sample_build.yml

Update pre-release homepage samples for Java 17

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json

Update metadata.json for 2201.8.0 release

---

.github/scripts/bbe/convertMarkdown.js

> Fixes #
Fix bbe gen issues when `ordered list items` exceed 9 items.

Fix BBE generation script

---

.github/scripts/bbe/convertMarkdown.js

Fix bbe generation lists

---

swan-lake/integration-tutorials/service-orchestration.md

Add the link to the GH project

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Address up8 rn comments.
> Fixes #

Address up8 rn comments

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Clear more issues in the Up8 release note.
> Fixes #

Clear more issues in the Up8 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Update the milestone links.
> Fixes #

Update the milestone links

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md
swan-lake/development-tutorials/troubleshoot-the-runtime/strand-dump-tool.md

Fix Up8 release branch issues.
> Fixes #

Fix Up8 release branch issues

---

swan-lake/development-tutorials/build-a-graalvm-executable/build-the-executable-in-a-container.md
swan-lake/development-tutorials/run-in-the-cloud/aws-lambda.md
swan-lake/development-tutorials/run-in-the-cloud/azure-functions.md

Fix broken links on Up8 branch.
> Fixes #

Fix broken links on Up8 branch

---

swan-lake/development-tutorials/java-interoperability/call-java-code-from-ballerina.md

Address interop section restructuring review comments of https://github.com/ballerina-platform/ballerina-dev-website/pull/7706.
> Fixes #

Address interop section restructuring review comments

---

swan-lake/integration-tools/edi-tool.md

Fix code snippets of the EDI tool page.
> Fixes #

Fix code snippets of the EDI tool page

---

swan-lake/integration-tutorials/send-emails-from-a-service.md

Add the "send emails from a service" tutorial

---

swan-lake/development-tutorials/source-code-dependencies/manage-dependencies.md

Restructure the custom repository content.
> Fixes #

Restructure the custom repository content

---

pages/learn/integration/integration-tutorials/index.js

Fix the url of the connecting web apis tutorial

---

downloads/swan-lake-release-notes/swan-lake-2201.8.0/RELEASE_NOTE.md

Move breaking changes section in Update 8 release note.
> Fixes #

Move breaking changes section in Update 8 release note

---

swan-lake/integration-tutorials/content-based-message-routing.md
swan-lake/integration-tutorials/send-emails-from-a-service.md
swan-lake/integration-tutorials/sending-a-message-to-a-service.md
swan-lake/integration-tutorials/service-orchestration.md

Fix minor improvements in integration tutorials

---

pages/learn/integration/integration-tutorials/index.js
swan-lake/integration-tutorials/sending-emails-from-a-service.md

Update sending emails from a service tutorial

---

pages/learn/integration/integration-tutorials/index.js
swan-lake/integration-tutorials/sending-a-message-to-a-service.md
swan-lake/integration-tutorials/service-orchestration.md

Address review suggestions

---

swan-lake/integration-tutorials/content-based-message-routing.md
swan-lake/integration-tutorials/transform-message-formats.md

Improve "content-based message routing" and "transform message formats" tutorials

---

pages/learn/integration/integration-tutorials/[slug].js

Introduce syntax highlighting

---

components/bff/intro/Intro.js

Reverts ballerina-platform/ballerina-dev-website#7835 from the integration-tutorials branch.

Revert "Fix minor issue"

---

components/learn/boxes/Boxes.js
next.config.js

Add back integration-tutorial content

---

pages/learn/integration/integration-tutorials/index.js

Update the description of sending emails from a service tutorial

---

pages/learn/integration/integration-tutorials/[slug].js

Fix intro width

---

pages/learn/integration/integration-tutorials/index.js
swan-lake/integration-tutorials/content-based-message-routing.md

Fix label ordering and resize image

---

swan-lake/integration-tutorials/content-based-message-routing.md
swan-lake/integration-tutorials/sending-a-message-to-a-service.md
swan-lake/integration-tutorials/sending-emails-from-a-service.md
swan-lake/integration-tutorials/service-orchestration.md
swan-lake/integration-tutorials/transforming-message-formats.md

Fix several issues

---

swan-lake/integration-tutorials/sending-emails-from-a-service.md

Change the order of return types

---

pages/learn/integration/integration-tutorials/[slug].js
pages/learn/integration/integration-tutorials/index.js

Fix year in copyright notice

---

pages/learn/integration/integration-tutorials/index.js

Remove commented out entry

---

components/microservices/code/microservices-bbe/ballerina-with-graalvm.md

Add working url for graalVM blade

---

pages/usecases/microservices/index.js

Change SM-banner to Ballerina generic banner in microservices page

---

components/hacktoberfest/rewards/Rewards.js
components/hacktoberfest/rules/Rules.js

Improve written content

---

pages/hacktoberfest/index.js

Fix social media image

---

pages/hacktoberfest/index.js

Fix social media title

---

layouts/LayoutHacktoberfest.js

Fix title text

---

spec/spec.md

Update `ballerina library` word in `spec.md`.
> Fixes #

Update `ballerina library` word in `spec.md`

---

components/common/top-nav/TopNav.js
components/microservices/code/Code.js

Update keys in topNav and fix background colors of blades

---

components/common/footer/Footer.js
components/hacktoberfest/challenges/challenges.js
components/hacktoberfest/rewards/Rewards.js
components/hacktoberfest/rules/Rules.js
layouts/LayoutHacktoberfest.js
pages/hacktoberfest/index.js

Fix navigation & style issues in hacktoberfest page

---

components/hacktoberfest/challenges/challenges.js
components/hacktoberfest/rewards/Rewards.js

Improve text content

---

components/common/footer/Footer.js
components/home-page/articles/Articles.js
components/home-page/intro/Intro.js

Add new articles, update link titles and reduce icon sizes

---

components/home-page/articles/Articles.js

Add new article

---

components/home-page/articles/Articles.js

Include proper url

---

components/bff/code/Code.js

Update React and Asgardeo related gif images for BFF Usecase page

Update React and Asgardeo related gif images for BFF Usecase page

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.8.1/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add changes related to 2201.8.1 release

---

_data/swanlake-latest/metadata.json

Update metadata.json for 2201.8.1

---

_data/events.json
components/common/left-nav/LeftNav.js
components/common/upcoming-events/UpcomingEvents.js
components/community/events/past-events/PastEvents.js
utils/learn-lm.json

Fix typos in events and update learn left nav

---

components/common/top-nav/TopNav.js

Add Hacktoberfest banner

---

components/common/top-nav/TopNav.js

Reverts ballerina-platform/ballerina-dev-website#8006 for further reviewing.

Revert "Add Hacktoberfest banner"

---

components/common/top-nav/TopNav.module.css

Fix style issues in the Hacktoberfest banner

---

downloads/installation-options.md

Fix formatting issue

---

_data/release_notes_versions.json
_data/stable-latest/metadata.json
downloads/1.2.x-release-notes/1.2.45.md
utils/archived-lm.json
utils/rl.json

Add release note and update metadata.json for 1.2.45 release 

---

pages/learn/integration/pre-built-integrations/ftp-edi-message-to-salesforce-opportunity.js
pages/learn/integration/pre-built-integrations/github-to-email-integration.js
pages/learn/integration/pre-built-integrations/gmail-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/google-drive-to-onedrive-integration.js
pages/learn/integration/pre-built-integrations/google-sheets-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/hubspot-contacts-to-google-contacts-integration.js
pages/learn/integration/pre-built-integrations/kafka-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/mysql-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/news-api-to-email-integration.js
pages/learn/integration/pre-built-integrations/salesforce-to-twilio-integration.js
pages/learn/integration/pre-built-integrations/shopify-to-outlook-integration.js

Fix Images are not rendered properly in Firefox- Pre-built example pages

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.8.2/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Update release note and metadata for 2201.8.2

---

components/common/footer/Footer.js

Update linkedin url

---

components/common/top-nav/TopNav.js
components/vs-code-extension/intro/Intro.js
layouts/LayoutLearn.js
pages/learn/vs-code-extension/index.js

Fix the top nav and the docs button as shown below.
> Fixes #

Fix the top nav and docs button

---

_data/events.json
components/common/top-nav/TopNav.js
pages/learn/references/ballerina-specifications.js

Fix mobile nav & banner expiration

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.7.3/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note and metadata for 2201.7.3

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.7.4/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note for 2201.7.4 release

---

components/downloads/packs/Packs.js
pages/downloads/index.js

Add unique ids to installers

---

components/common/main-content/MainContent.js
styles/globals.css

> Add copy code button to sample code in website pages
> Fixes #8028
**1. Full Page of Get Started**
**2. Full Page of Integration - Open Api Tool Page**
**3. Copied one of the code block then its showing copied checkbox only to respective code block. Example 1**
**4. Copied one of the code block then its showing copied checkbox only to respective code block. Example 2**
**5. Checked icon change to Copy icon after 3 seconds**
Let me know in case of any changes. Please review the changes @anupama-pathirage, @ThisaruGuruge, @sm1990

Added copy code button to sample code in website pages #8028

---

styles/globals.css

Update globals.css
> Layout shift on hover
> Fixes #8118

Fixed: Layout shift on hover on button

---

components/home-page/articles/Articles.js
components/home-page/why-bal/WhyBal.module.css
styles/Home.module.css
styles/globals.css

Add the carousal to news section

---

swan-lake/integration-tutorials/transforming-message-formats.md

Remove `fee` in ReservationResponse

---

components/etl/code/Code.js
components/etl/code/Code.module.css

Fix style issues

---

swan-lake/development-tutorials/ballerina-persist/persist-cli-tool.md
swan-lake/development-tutorials/build-and-run/update-tool.md
swan-lake/development-tutorials/run-in-the-cloud/azure-functions.md
swan-lake/development-tutorials/source-code-dependencies/package-references.md
swan-lake/integration-tools/openapi-tool.md
swan-lake/integration-tutorials/content-based-message-routing.md
swan-lake/integration-tutorials/sending-a-message-to-a-service.md
swan-lake/integration-tutorials/sending-emails-from-a-service.md
swan-lake/integration-tutorials/service-orchestration.md
swan-lake/integration-tutorials/transforming-message-formats.md
swan-lake/other/tooling-guide/intellij-idea-plugin/set-up-intellij-idea.md
swan-lake/resources/featured-scenarios/work-with-data-using-queries-in-ballerina.md

Remove bash from code snippets.
> Fixes #8144

Remove bash from code snippets

---

downloads/swan-lake-release-notes/swan-lake-2201.4.0/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.5.0/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.6.0/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.7.0/RELEASE_NOTE.md

Fix the `Breaking changes` section in the release notes.
> Fixes #7911

Fix the `Breaking changes` section in release notes

---

swan-lake/integration-tutorials/content-based-message-routing.md
swan-lake/integration-tutorials/sending-a-message-to-a-service.md
swan-lake/integration-tutorials/sending-emails-from-a-service.md
swan-lake/integration-tutorials/service-orchestration.md
swan-lake/integration-tutorials/transforming-message-formats.md

Improve and fix errors in tutorials

---

_data/articles.json
components/home-page/articles/Articles.js

Refactor the code in Ballerina in the news section

---

swan-lake/integration-tutorials/content-based-message-routing.md
swan-lake/integration-tutorials/sending-a-message-to-a-service.md
swan-lake/integration-tutorials/sending-emails-from-a-service.md
swan-lake/integration-tutorials/transforming-message-formats.md

Add dollar mark in bash code

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.6.2/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note for 2201.6.2 release

---

components/common/top-nav/TopNav.js
components/vs-code-extension/intro/Intro.js

Update styles and remove debug logs

---

_data/release_notes_versions.json
_data/stable-latest/metadata.json
downloads/1.2.x-release-notes/1.2.46.md
utils/archived-lm.json
utils/rl.json

Add release note for 1.2.46 release

---

swan-lake/integration-tutorials/sending-a-message-to-a-service.md

Add generated record type

---

swan-lake/integration-tools/health-tool.md

Fix the code snippet on the health tool page.
> Fixes #

Fix the code snippet on the health tool page

---

swan-lake/integration-tutorials/sending-a-message-to-a-service.md

Make record open in generated code in sending-a-message-to-a-service tutorials

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.6.3/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note for 2201.6.3 release

---

downloads/swan-lake-release-notes/swan-lake-2201.6.3/RELEASE_NOTE.md

Fix incorrect version in update 6 release note

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.5.4/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note for 2201.5.4 release

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.47.md
utils/archived-lm.json
utils/rl.json

Add release note for 1.2.47 release

---

components/salesforce/code/salesforce-bbe/ai.md
components/salesforce/code/salesforce-bbe/b2b.md
components/salesforce/code/salesforce-bbe/datasources.md
components/salesforce/code/salesforce-bbe/notifications.md
components/salesforce/code/salesforce-bbe/productivity.md
components/salesforce/code/salesforce-bbe/realtime.md
components/salesforce/code/salesforce-bbe/servicenow.md
components/salesforce/code/salesforce-bbe/shopify.md

> Shorten the salesforce samples in the use cases page
> Fixes [#8240](https://github.com/ballerina-platform/ballerina-dev-website/issues/8240)

Shorten the salesforce integration samples in usecases page

---

swan-lake/integration-tutorials/content-based-message-routing.md
swan-lake/integration-tutorials/transforming-message-formats.md

Related to the review comments in the following PRs.
- https://github.com/ballerina-platform/ballerina-dev-website/pull/8233
- https://github.com/ballerina-platform/ballerina-dev-website/pull/8233

Address review comments in `Content-based message routing` and `Transforming message formats` tutorials

---

pages/learn/enterprise-integration-patterns/enterprise-integration-patterns/claim-check/claim-check.yml
pages/learn/enterprise-integration-patterns/enterprise-integration-patterns/publish-subscribe-channel/publish-subscribe-channel.yml

Fixed review suggestions for EIP batch 4

Fixed review suggestions for EIP batch 4

---

downloads/1.2.x-release-notes/1.2.x-bug-fixes-template.md
downloads/1.2.x-release-notes/1.2.x-security-fixes-template copy.md
downloads/swan-lake-release-notes/swan-lake-bug-fixes-template/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-security-fixes-template/RELEASE_NOTE.md

Create release notes templates.
> Fixes #

Create release notes templates

---

components/bff/code/bff-bbe/json-support.md

Update Bff samples
Address this comment - https://github.com/ballerina-platform/ballerina-dev-website/pull/8258#discussion_r1394345805

Update Bff samples

---

swan-lake/development-tutorials/source-code-dependencies/style-guide/annotations-documentation-and-comments.md
swan-lake/development-tutorials/source-code-dependencies/style-guide/coding-conventions.md
swan-lake/development-tutorials/source-code-dependencies/style-guide/operators-keywords-and-types.md
swan-lake/development-tutorials/source-code-dependencies/style-guide/statements.md
swan-lake/development-tutorials/source-code-dependencies/style-guide/top-level-definitions.md

Fix style guide issues.
> Fixes #7010

Fix style guide issues

---

swan-lake/integration-tutorials/sending-emails-from-a-service.md
swan-lake/integration-tutorials/service-orchestration.md

Improve `Sending emails` and `Service orchestration` tutorials

---

swan-lake/integration-tutorials/sending-a-message-to-a-service.md
swan-lake/integration-tutorials/transforming-message-formats.md

Update "Send request" section in "Integration Tutorials"

---

downloads/1.2.x-release-notes/1.2.x-security-fixes-template.md

Update the 1.2.x release note templates.
> Fixes #

Update the 1.2.x release note templates

---

downloads/1.2.x-release-notes/1.2.x-bug-fixes-template.md
downloads/1.2.x-release-notes/1.2.x-security-fixes-template.md
downloads/swan-lake-release-notes/swan-lake-bug-fixes-template/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-security-fixes-template/RELEASE_NOTE.md

Update the release note templates.
> Fixes #

Update the release note templates

---

components/salesforce/code/salesforce-bbe/ai.md
components/salesforce/code/salesforce-bbe/b2b.md
components/salesforce/code/salesforce-bbe/datasources.md
components/salesforce/code/salesforce-bbe/notifications.md
components/salesforce/code/salesforce-bbe/productivity.md
components/salesforce/code/salesforce-bbe/realtime.md
components/salesforce/code/salesforce-bbe/servicenow.md
components/salesforce/code/salesforce-bbe/shopify.md

> Related to [https://github.com/ballerina-platform/ballerina-library/issues/5732](https://github.com/ballerina-platform/ballerina-library/issues/5732)

Update descriptions of the integration samples

---

.github/scripts/bbe/convertMarkdown.js

> Replace playground url with VS Code

Replace playground url with VS Code

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.8.3/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add 2201.8.3 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.8.3/RELEASE_NOTE.md

Fix indentation issue in Release note

---

.github/scripts/bbe/convertMarkdown.js

Remove playground button

---

.github/scripts/bbe/convertMarkdown.js

Fix style issue

---

.github/scripts/bbe/convertMarkdown.js

Sync staging into master

---

components/bff/code/Code.js

Fix permalinks in bff page

---

downloads/swan-lake-release-notes/swan-lake-2201.8.4/RELEASE_NOTE.md

[2201.8.4]Update RELEASE_NOTE.md

---

components/home-page/users/Users.js

Update the RAAPID.AI case study on the home page.
> Fixes #

Update RAAPID.AI case study on home page

---

components/healthcare/code/healthcare-bbe/ballerina-is-fhir.md
components/healthcare/code/healthcare-bbe/ballerina-is-hl7.md
components/healthcare/code/healthcare-bbe/connect-to-emrs.md
components/healthcare/code/healthcare-bbe/powerful-health-data-mapping.md

Update sample links to align with dir refactoring

---

swan-lake/integration-tools/health-tool.md

Update the new artifact links of the health tool.
> Fixes #

Update the new artifact links of the health tool

---

case-studies/mosip.md

Fix Mosip case study broken links.
> Fixes #

Fix MOSIP case study broken links

---

_data/articles.json

Add new articles

---

components/salesforce/code/Code.module.css
components/salesforce/code/salesforce-bbe/ai.md
components/salesforce/code/salesforce-bbe/b2b.md
components/salesforce/code/salesforce-bbe/datasources.md
components/salesforce/code/salesforce-bbe/notifications.md
components/salesforce/code/salesforce-bbe/productivity.md
components/salesforce/code/salesforce-bbe/realtime.md
components/salesforce/code/salesforce-bbe/servicenow.md
components/salesforce/code/salesforce-bbe/shopify.md

Sync Sahan salesforce usecases into staging

---

components/common/top-nav/TopNav.js

Add blog to top nav

---

components/etl/code/etl-bbe/data-enrichment-magic.md

Add Usecases etl to staging

---

layouts/LayoutDocs.js
layouts/LayoutLearn.js
pages/learn/by-example/[bbe].js
pages/learn/development-tutorials/[...slug].js
pages/learn/integration-tools/[...slug].js
pages/learn/integration/[...slug].js
pages/learn/references/ballerina-specifications.js
pages/learn/resources/[...slug].js
pages/learn/vs-code-extension/build-executables.js
pages/learn/vs-code-extension/configure-the-extension.js
pages/learn/vs-code-extension/debug-the-code/[...slug].js
pages/learn/vs-code-extension/deploy-with-wso2-choreo.js
pages/learn/vs-code-extension/design-the-application/[...slug].js
pages/learn/vs-code-extension/design-the-services/[...slug].js
pages/learn/vs-code-extension/get-started.js
pages/learn/vs-code-extension/implement-the-code/[...slug].js
pages/learn/vs-code-extension/license.js
pages/learn/vs-code-extension/notebooks.js
pages/learn/vs-code-extension/references/[...slug].js
pages/learn/vs-code-extension/release-notes/[...slug].js
pages/learn/vs-code-extension/run-a-program.js
pages/learn/vs-code-extension/test-the-code.js
pages/learn/vs-code-extension/troubleshoot.js
pages/learn/vs-code-extension/try-the-services/[...slug].js
pages/learn/vs-code-extension/write-the-code/[...slug].js
pages/why-ballerina/[...slug].js

Refactor meta tags to pick the correct sm-banner

---

downloads/verify-ballerina-artifacts.md

Fix verify commands

---

components/salesforce/code/Code.js
components/salesforce/code/salesforce-bbe/ai.md
components/salesforce/code/salesforce-bbe/shopify.md

Sahan salesforce usecases

---

components/learn/integration-tutorials/data.js
swan-lake/integration-tutorials/file-processing.md

Add the file processing tutorial

---

case-studies/avinya-foundation.md

Shorten the Avinya case study title.
> Fixes #

Shorten the Avinya case study title

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.4.3/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add 2201.4.3 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.4.3/RELEASE_NOTE.md

Update RELEASE_NOTE.md with release note fix

---

pages/case-studies/[slug].js
styles/globals.css

Fix style issues in case-studies pages

---

components/common/newsletter-subscription/NewsletterSubscription.js
components/community/events/Events.js
components/community/join-us/JoinUs.js
components/community/join-us/JoinUs.module.css
components/community/resources/Resources.js
pages/community/ballerina-newsletter.js

Update styles remove unnecessary text

---

case-studies/fat-tuesday.md

Add bullet points to the FAT Tuesday case study.
> Fixes #

Add bullet points to the FAT Tuesday case study

---

components/salesforce/code/salesforce-bbe/servicenow.md
components/salesforce/code/salesforce-bbe/shopify.md

Update servicenow and shopify integration codes

---

components/salesforce/code/salesforce-bbe/datasources.md
components/salesforce/code/salesforce-bbe/notifications.md
components/salesforce/code/salesforce-bbe/productivity.md
components/salesforce/code/salesforce-bbe/realtime.md

Updated github links

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.5.5/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note for 2201.5.5

---

components/salesforce/code/salesforce-bbe/ai.md
components/salesforce/code/salesforce-bbe/b2b.md
components/salesforce/code/salesforce-bbe/datasources.md
components/salesforce/code/salesforce-bbe/notifications.md
components/salesforce/code/salesforce-bbe/productivity.md
components/salesforce/code/salesforce-bbe/realtime.md
components/salesforce/code/salesforce-bbe/servicenow.md
components/salesforce/code/salesforce-bbe/shopify.md
pages/learn/integration/pre-built-integrations/google-sheets-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/kafka-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/mysql-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/salesforce-to-twilio-integration.js
pages/usecases/salesforce/index.js

sync Sahan salesforce usecases

---

swan-lake/development-tutorials/build-and-run/cli-commands.md

Update the `bal help` CLI texts.
> Fixes #8536 and #8537

Update the `bal help` CLI texts

---

_data/use-cases.json
components/common/use-cases/UseCases.js
components/common/use-cases/UseCases.module.css
pages/case-studies/index.js
pages/usecases/index.js

Create landing pages for usecases and case studies

---

components/salesforce/code/salesforce-bbe/datasources.md
components/salesforce/code/salesforce-bbe/notifications.md
components/salesforce/code/salesforce-bbe/productivity.md

Update github links of the samples

---

swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/define-test-groups.md

Fix command error in "Execute grouped tests" learn page

---

swan-lake/development-tutorials/source-code-dependencies/package-references.md

Fix links in the `Package references` page.
> Fixes #8548

Fix links in the `Package references` page

---

components/common/main-content/MainContent.js

>$subject
> Fixes #8288
& #8552

Preserve line spacing when copying code snippets

---

swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/write-tests.md

Fix issues on the `Write tests` page.
> Fixes #8553

Fix issues on the `Write tests` page

---

pages/learn/integration/pre-built-integrations/google-sheets-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/kafka-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/mysql-to-salesforce-integration.js
pages/learn/integration/pre-built-integrations/salesforce-to-twilio-integration.js

> Fixes [8572](https://github.com/ballerina-platform/ballerina-dev-website/issues/8572)

Update github links for the broken pre-built-integration code samples

---

components/home-page/bal-action/BalAction.js

Remove playground links

---

downloads/installation-options.md

$title
> Fixes #
https://github.com/ballerina-platform/ballerina-distribution/issues/5108

Update the guide for install via ZIP

---

swan-lake/development-tutorials/source-code-dependencies/package-references.md
swan-lake/development-tutorials/source-code-dependencies/style-guide/statements.md

Fix a few formatting issues in docs.
> Fixes #

Fix a few formatting issues in docs

---

downloads/installation-options.md

Update `bal version` command output

---

components/etl/code/etl-bbe/data-enrichment-magic.md
components/etl/code/etl-bbe/drive-data-interactions-with-models.md
components/etl/code/etl-bbe/eleminating-redundency-for-cleaner-data.md
components/etl/code/etl-bbe/extract-data-from-github.md
components/etl/code/etl-bbe/load-data-to-data-warehouse.md
components/etl/code/etl-bbe/load-from-kafka-topics.md
components/etl/code/etl-bbe/precision-cleaning-with-regex.md
components/etl/code/etl-bbe/refining-data-excellence.md
components/etl/code/etl-bbe/reshaping-data-with-data-mapper.md

$subject
> Fixes #8604
Related PRs - [sample-pr](https://github.com/ballerina-guides/etl-samples/pull/14)

Address review suggestions for the etl use cases page

---

swan-lake/development-tutorials/source-code-dependencies/manage-dependencies.md

add new sample for importing non-default modules

---

swan-lake/development-tutorials/ballerina-central/publish-packages-to-ballerina-central.md

Update Ballerina Central login options.
> Fixes #8598

Update Ballerina Central login options

---

_data/articles.json

Add new news article

---

swan-lake/resources/featured-scenarios/write-a-graphql-api-with-ballerina.md

Fixes: [#8645](https://github.com/ballerina-platform/ballerina-dev-website/issues/8645)

Fix Typo in GraphQL Guide

---

swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/define-data-driven-tests.md

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/42017

Remove quotes in data driven tests

---

swan-lake/development-tutorials/ballerina-central/publish-packages-to-ballerina-central.md

$subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8601

Add documentation for deprecating all versions of a package

---

swan-lake/integration-tools/graphql-tool.md

Fixes: [#6042](https://github.com/ballerina-platform/ballerina-library/issues/6042)
Fixes: [#8642](https://github.com/ballerina-platform/ballerina-dev-website/issues/8642)
Fixes: [#8643](https://github.com/ballerina-platform/ballerina-dev-website/issues/8643)
Fixes: [#8644](https://github.com/ballerina-platform/ballerina-dev-website/issues/8644)

Mark GraphQL Client Generation Feature as Experimental

---

_data/release_notes_versions.json
_data/stable-latest/metadata.json
downloads/1.2.x-release-notes/1.2.49.md
utils/archived-lm.json
utils/rl.json

Add release note and metadata for 1.2.49 release

---

components/common/main-content/MainContent.js
styles/globals.css

Fix spacing in images and code blocks

---

_data/university_sessions.json
components/community/events/past-events/PastEvents.js
components/student-engagement/past-sessions/PastSessions.js
components/student-engagement/past-sessions/PastSessions.module.css

Add past sessions

---

pages/student-engagement-programs/index.js

Update page titles

---

components/community/join-us/JoinUs.js
pages/_document.js
pages/community/index.js

Fix broken links and update text in community page

---

_data/university_sessions.json
components/student-engagement/outline/Outline.js
components/student-engagement/past-sessions/PastSessions.js
components/student-engagement/past-sessions/PastSessions.module.css
pages/community/events.js
pages/community/student-program/index.js

Incorporate review comments

---

swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/test-a-simple-function.md
swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/write-tests.md

> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8715 https://github.com/ballerina-platform/ballerina-dev-website/issues/8722 https://github.com/ballerina-platform/ballerina-dev-website/issues/8723

Fix issues in tests learn pages

---

_data/events.json
components/common/upcoming-events/UpcomingEvents.js
components/community/events/past-events/PastEvents.js

Display multiple presenters in events

---

components/learn/boxes/Boxes.js

Update the Description of GraphQL Tool

---

components/common/top-nav/TopNav.js
components/common/top-nav/TopNav.module.css

Add WSO2Con banner

---

components/common/top-nav/TopNav.module.css

Add onHover styles to the WSO2Con banner

---

components/student-engagement/get-involved/GetInvolved.js
components/student-engagement/get-involved/GetInvolved.module.css

Resize buttons

---

pages/community/student-program/index.js

Fix typo in page title

---

layouts/LayoutCommunity.js
pages/community/index.js
pages/community/newsletter/[...slug].js
pages/community/student-program/index.js

Update page description in student-program page

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.8.5/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.8.6/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Update release note and metadata for release 2201.8.6

---

swan-lake/integration-tools/edi-tool.md

Reverts ballerina-platform/ballerina-dev-website#8696
Reverting the changes since a new version of EDI tool has been released and the doc changes need to be updated in prod asap.

Revert "Update EDI tool documentation"

---

swan-lake/integration-tools/edi-tool.md

> Update the EDI Tool page changes with EDI Tool release 1.0.0
Related to : https://github.com/ballerina-platform/ballerina-dev-website/issues/8804

Update EDI Tool documentation for release v1.0 enhancements

---

case-studies/ballerina-central.md
pages/case-studies/[slug].js
styles/globals.css

Add a disclaimer message to case-study pages

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.50.md
utils/archived-lm.json
utils/rl.json

Add release note for 1.2.50 release

---

components/common/newsletter-subscription/NewsletterSubscription.js
pages/community/newsletter/[...slug].js

Add subscription form

---

swan-lake/development-tutorials/ballerina-persist/bal-persist-overview.md
swan-lake/development-tutorials/ballerina-persist/persist-cli-tool.md

Update the content to match the new changes of the Persist commands

---

swan-lake/development-tutorials/source-code-dependencies/manage-dependencies.md
swan-lake/development-tutorials/source-code-dependencies/package-references.md

$subject
Related issues - https://github.com/ballerina-platform/ballerina-lang/issues/42155

[2201.9.0] Add build tool documentation

---

public/spec/crypto/spec.md
spec/crypto/spec.md

Reverts ballerina-platform/ballerina-dev-website#8839

Revert "[AUTOMATE] Update Ballerina Standard Library (crypto) Specifications"

---

swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/write-tests.md

$subject
Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8701

Fix table style in test assertions

---

policy/privacy-policy.md

Update privacy-policy.md to remove playground reference

---

swan-lake/resources/featured-scenarios/write-a-graphql-api-with-ballerina.md

$Subject
Fixes #8641 
Fixes #8640

Update the GraphQL Learn Page

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add changes to nats and rabbitmq packages

---

pages/community/events.js

Set upcoming events as the default tab

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add Avro package as a new feature in update 9.0.0 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add xml and formatter fix release notes for 2201.9.0

---

swan-lake/integration-tools/edi-tool.md

Fix syntax highlighting and code copying issues

---

components/common/main-content/MainContent.js

Fix copy button moving with horizontal scroll

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Update release note for GraphQL package

---

_data/articles.json
components/common/main-content/MainContent.js

Fix build issues and add new article

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Move cloud improvements into Ballerina library section

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add language server and shell release notes for U9

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add a bug fix to the release note and reorganize the breaking changes section

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add worker changes to U9 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add missing punctuation marks in the U9 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add backward incompatible change to release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add `guidewire.insnow` updates on the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add MongoDB Updates in the Release Note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add `ibm.ibmmq` updates on the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add `GitHub` updates on the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add updates from Lib5 team

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Apply review suggestions

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add record default value improvement to release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Update Twilio/EDI connector release-note for U9

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add changes to salesforce package

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add jsondata and xmldata modules to release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add snowflake connector

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Move redshift updates

---

components/common/use-cases/UseCases.module.css

Fix class names

---

_data/use-cases.json

Add etl page

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Remove duplicate NATS and RabbitMQ entries

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add JSON prettify API to the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Update U9 release note with JMS package

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Add bindgen tool and debugger bug fixes to the update 9 release notes

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Fix several issues in the U9 release note

---

swan-lake/development-tutorials/ballerina-central/publish-packages-to-ballerina-central.md
swan-lake/development-tutorials/source-code-dependencies/package-references.md

$ subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8963

Document missing Ballerina.toml fields

---

components/common/prev-next/PrevNext.js
next.config.js
utils/learn-lm.json

Refactor prev-next component and fix build errors

---

pages/case-studies/index.js
pages/use-cases/index.js

Update meta data

---

swan-lake/development-tutorials/ballerina-persist/supported-data-stores.md

This PR is to update supported data types and to address minor changes for Redis DB in persist documentation.

Update supported data stores in persist

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

[2201.9.0] Update openAPI tool breaking changes

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Update RELEASE_NOTE.md with AI data mapper information

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
utils/archived-lm.json

Update metadata for release 2201.9.0

---

components/ai/intro/Intro.js

Update intro text

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.51.md
utils/archived-lm.json
utils/rl.json

Add release note for `1.2.51` release

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Update TLS group change imporovement to release notes

---

pages/learn/vs-code-extension/build-executables.js
pages/learn/vs-code-extension/configure-the-extension.js
pages/learn/vs-code-extension/debug-the-code/[...slug].js
pages/learn/vs-code-extension/deploy-with-wso2-choreo.js
pages/learn/vs-code-extension/design-the-application/[...slug].js
pages/learn/vs-code-extension/design-the-services/[...slug].js
pages/learn/vs-code-extension/get-started.js
pages/learn/vs-code-extension/implement-the-code/[...slug].js
pages/learn/vs-code-extension/index.js
pages/learn/vs-code-extension/license.js
pages/learn/vs-code-extension/notebooks.js
pages/learn/vs-code-extension/references/[...slug].js
pages/learn/vs-code-extension/release-notes/[...slug].js
pages/learn/vs-code-extension/run-a-program.js
pages/learn/vs-code-extension/test-the-code.js
pages/learn/vs-code-extension/troubleshoot.js
pages/learn/vs-code-extension/try-the-services/[...slug].js
pages/learn/vs-code-extension/write-the-code/[...slug].js

Add prev/next buttons to vs-code extension docs

---

components/common/footer/Footer.js
components/common/footer/Footer.module.css
components/home-page/intro/Intro.js
components/home-page/intro/Intro.module.css
package-lock.json
package.json
pages/_app.js

Update 3rd party logos in the footer

---

downloads/installation-options.md

Update installation-options.md to fix syntax highlighting issue

---

components/common/top-nav/TopNav.js
package-lock.json
package.json

Add dark mode to b.io

---

components/common/top-nav/TopNav.js

Remove commented code

---

_data/university_sessions.json
components/student-engagement/events/Events.js

Fix build errors and update the component

---

_data/events.json

Add new event

---

components/common/footer/Footer.js
layouts/Layout404.js
layouts/LayoutCommunity.js
layouts/LayoutDocs.js
layouts/LayoutDownloads.js
layouts/LayoutHacktoberfest.js
layouts/LayoutHome.js
layouts/LayoutLearn.js
layouts/LayoutOther.js
layouts/LayoutRN.js
layouts/LayoutUseCase.js

Dynamically update the copyright year

---

downloads/swan-lake-release-notes/swan-lake-2201.9.0/RELEASE_NOTE.md

Refine runtime backward-incompatible changes entry

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.1/RELEASE_NOTE.MD
utils/archived-lm.json
utils/rl.json

Add  release note and metadata for release 2201.9.1

---

_data/articles.json
_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.1/RELEASE_NOTE.MD
utils/archived-lm.json
utils/rl.json

Add Release 2201.9.1

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.8.7/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add 2201.8.7 release notes

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.52.md
utils/archived-lm.json
utils/rl.json

Add release note for `1.2.52` release

---

_data/release_notes_versions.json
components/common/sample-list/SampleList.js
components/learn/pattern/Pattern.js

Make icons clickable in EIP page and remove invalid artifacts

---

components/common/sample-list/SampleList.module.css
components/learn/pattern/Pattern.module.css

Add highlight on hover in EIP

---

_data/university_sessions.json

Add UoM session slides

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

Add release note for 2201.9.2 release

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

[2201.9.2] Update release note with LS changes

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

[2201.9.2]Update release note with openapi changes

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

> Add Ballerina packages updates to the 9.2 release note

Add Ballerina packages updates to the 9.2 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

Update 2201.9.2 release notes with CLI fixes

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

Update 2201.9.2 release notes with Bindgen tool fixes

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

Update 2201.9.2 release notes with WSDL tool

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

Update release note for 2201.9.2

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

> $title.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/pull/9126/files#r1670637154

[2201.9.2] Fix WSDL release-note to address review comments.

---

downloads/swan-lake-release-notes/swan-lake-2201.9.2/RELEASE_NOTE.md

> Update the 2201.9.2 release note.

Update the 2201.9.2 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.8.7/RELEASE_NOTE.md

> Update the 2201.8.7 release note

Update the 2201.8.7 release note

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.53.md
utils/archived-lm.json
utils/rl.json

Add release note for 1.2.53 release

---

downloads/1.2.x-release-notes/1.2.53.md

Update 1.2.53 release note

---

components/ai/code/Code.js
components/ai/code/ai-bbe/trivial-hosting-in-wso2-choreo-ipaas.md
components/integration/ballerina-vs-apollo-for-graphql/code/Code.js
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/trivial-hosting-in-wso2-choreo-ipaas.md
components/integration/code/Code.js
components/integration/code/integration-bbe/trivial-hosting-in-wso2-choreo-ipaas.md
pages/_app.js

Update the wording and permalinks in Choreo blades

---

pages/community/student-program/project-mentorship.js

Refactor code

---

components/common/card-grid/CardGrid.js

Add contact email

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.54.md
utils/archived-lm.json
utils/rl.json

Add release note for 1.2.54 release

---

_data/use-cases.json
pages/use-cases/microservices/index.js

Update H1 in microservice page

---

swan-lake/integration-tools/edi-tool.md

This pull request introduces several doc enhancements and fixes to the EDI libgen functionality. Below are the key changes included in this PR:
- **Add Examples for REST Codegen:** Added new examples to the REST code generation documentation. These examples are intended to provide clearer guidance and support for users utilizing our codegen tools, demonstrating practical use cases and enhancing user understanding.
- **Enhance the example `libgen` command:**  Enhance the example `libgen` command by adding the format of -p parameter .
Related: https://github.com/ballerina-platform/ballerina-library/issues/6804, https://github.com/ballerina-platform/ballerina-library/issues/6813

Add improvements on EDI LibGen

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

[2201.10.0] Add release note for http

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Add JWT package changes to the release note

---

_data/university_sessions.json
components/student-engagement/events/Events.js

Hide presenter details for hackathons

---

components/student-engagement/events/Events.js

Add sponsored text

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Add the 2201.10.0 release note for bal run --watch and GraalVM compatibility

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Add Stripe connector to the connector release note

---

downloads/swan-lake-release-notes/swan-lake-2201.9.3/RELEASE_NOTE.md

Add the 2201.9.3 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Add ASB changes to the connector release note

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Add xml related fixed for `2201.10.0` release note

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

[2201.10.0] Add LanguageServer features to release note

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Added features from lib 5 sub team

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

[2201.10.0] Add data.yaml module to the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Add `ldap` and `http` library updates to the 2201.10.0 release note

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.3/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Update metadata and release note for 2201.9.3 release

---

downloads/swan-lake-release-notes/swan-lake-2201.9.3/RELEASE_NOTE.md

Update placeholders with the actual values in the 2201.9.3 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

 Update JWT changes in the U10 release-note

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Add the 2201.10.0 release note for supporting package resources

---

next-sitemap.config.js
utils/rearrangeFiles.sh

Clean up the sitemap

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Add bal persist features in update 10 release notes

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

> Adding the release notes related to the Runtime for Ballerina Swan Lake Update 10.
> Added items under "Improvements" and "New Runtime Java APIs" while removing the "New features" section under "Runtime updates"

Runtime release notes for Ballerina Swan Lake Update 10

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

[2201.10.0] Update release note with OpenAPI changes

---

swan-lake/development-tutorials/source-code-dependencies/package-references.md

> Fixes https://github.com/ballerina-platform/ballerina-lang/issues/42466

Mark a Java dependency as GraalVM compatible

---

downloads/swan-lake-release-notes/swan-lake-2201.10.0/RELEASE_NOTE.md

Remove unwanted sections from release note

---

swan-lake/development-tutorials/ballerina-persist/bal-persist-overview.md
swan-lake/development-tutorials/ballerina-persist/persist-introspection.md

Remove experimental from introspection

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
utils/archived-lm.json
utils/rl.json

Add update 10 metadata

---

_data/university_sessions.json

Add new university session

---

swan-lake/development-tutorials/source-code-dependencies/manage-dependencies.md

Fix double quote in code example

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.8.8/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add update 8.8 release note

---

pages/community/student-program/project-mentorship.js

Update page description

---

swan-lake/development-tutorials/ballerina-central/configure-a-network-proxy.md

- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9328

Add required domains for Ballerina

---

swan-lake/development-tutorials/ballerina-central/configure-a-network-proxy.md

Convert links to code blocks

---

_data/student_projects.json

Add repo details

---

swan-lake/vs-code-extension/design-the-services/http-api-designer.md

> $Subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8973
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9346

Update HTTP API designer learn page

---

components/home-page/users/Users.js

Resize user logo

---

swan-lake/vs-code-extension/design-the-services/http-api-designer.md

Add correct language identifier for the syntax highlighter

---

swan-lake/resources/featured-scenarios/manage-data-persistence-with-bal-persist.md

Add minor changes after review

---

_data/university_sessions.json

Add new university sessions

---

swan-lake/development-tutorials/observability/observe-ballerina-programs.md

- Add minor improvements to Observe Ballerina programs guide
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8896

Add minor improvements to Observe Ballerina programs guide

---

swan-lake/development-tutorials/observability/observe-metrics.md

- Update default value for metricsReporter
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8897

Update default value for metricsReporter

---

swan-lake/development-tutorials/observability/observe-ballerina-programs.md

* Fix the issues mentioned in: https://github.com/ballerina-platform/ballerina-dev-website/issues/8978

Improve guide for observing a Ballerina program

---

components/common/card-grid/CardGrid.js

Remove commented codes

---

swan-lake/development-tutorials/source-code-dependencies/style-guide/annotations-documentation-and-comments.md

Include the best practice for documenting a Ballerina record in the style guide

---

swan-lake/development-tutorials/ballerina-central/publish-packages-to-ballerina-central.md

* $subject
* Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9425

Add description for setting access token via environment variable

---

components/nust/contribute/Contribute.js
components/nust/contribute/Contribute.module.css
components/nust/rewards/Rewards.module.css
components/nust/rules/Rules.module.css
components/student-engagement/outline/Outline.js
components/student-engagement/outline/Outline.module.css
pages/namibia-hackathon/index.js

Update styles and rename components

---

.github/workflows/add_link_checker.yml

Run octopus and catch errors for better logging

---

pages/community/ambassadors.js

Add apply button

---

components/common/footer/Footer.js
components/common/footer/Footer.module.css
components/hacktoberfest-2024/challenges/Challenges.module.css
components/hacktoberfest-2024/challenges/challenges.js

Update button colors

---

components/hacktoberfest-2024/challenges/Challenges.module.css
components/hacktoberfest-2024/challenges/challenges.js
components/hacktoberfest-2024/intro/Intro.js
components/hacktoberfest-2024/intro/Intro.module.css
components/hacktoberfest-2024/rewards/Rewards.module.css
components/hacktoberfest-2024/rules/Rules.js
components/hacktoberfest-2024/rules/Rules.module.css
pages/hacktoberfest/index.js

Update styles and fix sm-banner

---

downloads/swan-lake-release-notes/swan-lake-2201.10.1/RELEASE_NOTE.md

Address Release note suggestions for 2201.10.1 

---

components/learn/boxes/Boxes.js
next.config.js
swan-lake/resources/featured-scenarios/create-your-first-connector-with-ballerina.md
utils/learn-lm.json

$subject. 
Resolves https://github.com/ballerina-platform/ballerina-dev-website/issues/9350

Add "Create your first connector with Ballerina" featured scenario to the learn pages

---

swan-lake/development-tutorials/build-and-run/update-tool.md

> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/8670

Include proxy information for update tool

---

swan-lake/development-tutorials/observability/observe-logs.md

Update elastic search version to latest

---

components/hacktoberfest-2024/challenges/challenges.js
components/hacktoberfest-2024/rewards/Rewards.js

Update swag store and guide links

---

components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/better-security.md
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/cli-tool.md
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/designer-tool.md
components/integration/ballerina-vs-apollo-for-graphql/code/apollo-graphql-bbe/similarities.md

> Fixes :[#8887](https://github.com/ballerina-platform/ballerina-dev-website/issues/8887)

Update GraphQL vs Apollo comparison

---

hacktoberfest/connector-contributor-guide.md

Add contributor guide for hacktoberfest connector projects

---

hacktoberfest/connector-contributor-guide.md

$subject addresses the minor improvements suggested in https://github.com/ballerina-platform/ballerina-dev-website/pull/9502

Add minor improvements to the hacktoberfest contributor guide

---

components/hacktoberfest-2024/challenges/challenges.js
components/hacktoberfest-2024/rules/Rules.js
hacktoberfest/connector-contributor-guide.md

Update credits and rules

---

components/hacktoberfest-2024/challenges/challenges.js

Update text in Discord button

---

swan-lake/development-tutorials/configurability/provide-values-to-configurable-variables.md

Add configurable env variable supported version information

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.4/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add Release 2201.9.4

---

components/healthcare/code/Code.js
components/healthcare/code/healthcare-bbe/ai-pair-programming.md
components/healthcare/code/healthcare-bbe/apis-are-new-dll.md
components/healthcare/code/healthcare-bbe/connect-to-emrs.md
components/healthcare/code/healthcare-bbe/powerful-edi-for-claims.md
components/healthcare/code/healthcare-bbe/powerful-health-data-mapping.md
components/healthcare/code/healthcare-bbe/why-ballerina-for-healthcare-apps.md
components/healthcare/intro/Intro.js

This PR contains the fixes mentioned in [1] and the code segments updated in the 'Powerful health data mapping' section. 
[1] - https://github.com/ballerina-platform/ballerina-dev-website/issues/8742

Add healthcare usecase fixes

---

.github/scripts/spellcheck.py
.github/workflows/spell-check.yml
.spelling

> The GitHub Action is Schedule to run once a week - **Runs every Monday at midnight UTC**
It also sends an email to the code owners with a spellcheck report.
You can ignore specific words if you include them in to `.spelling` file.
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9536

Spell-Checker-Github-Action

---

swan-lake/development-tutorials/run-in-the-cloud/code-to-cloud-deployment.md

- Fix formatting in code to cloud guide

Fix formatting in code to cloud guide

---

.github/scripts/spellcheck.py

The final report includes, the code snippets in the .md files.
eg:-
File: swan-lake/vs-code-extension/get-started.md Misspelled words: sdk:, [multi-root, 1.60.0, [multiple, later., command., workspace**, [ballerina](https://ballerina.io/downloads/)., multi-root, it., <img, ---, intro:, [visual, [ballerina, packages](#open-multiple-ballerina-packages), **vs, line,, workspace., keywords:, extension,, extension., ballerina,, ballerina, corner., ###, instructions,, ., workspace,, [single, editor](https://code.visualstudio.com/download), class="cinlineimage-half"/>, **file, description:, started,, editor,, …

Fix ignore code snippet blocks and inline code during spellcheck

---

components/common/main-content/MainContent.js
swan-lake/resources/featured-scenarios/manage-data-persistence-with-bal-persist.md

Support multi-line commands to be copied

---

components/nust/intro/Intro.js
components/nust/intro/Intro.module.css

Add event ended message

---

.github/workflows/prod_sync_gh-pages.yml

Add missing styles to draft spec

---

components/common/redirect-message/RedirectMessage.js

Add redirect for RegEx BBE

---

.github/scripts/bbe/convertMarkdown.js

Fix style issues in BBEs

---

swan-lake/resources/learn-the-language/concurrency.md

> Add documentation for transaction timeouts
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9571

Add documentation for transaction timeouts

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.5/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

> $subject 
https://github.com/ballerina-platform/ballerina-distribution/issues/5812

Add release note for 2201.9.5

---

utils/robots.txt

Remove old and invalid urls from search indexes

---

_data/release_notes_versions.json

Fix json syntax error for `release_notes_versions`

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.10.3/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release details for 2201.10.3

---

downloads/swan-lake-release-notes/swan-lake-2201.10.3/RELEASE_NOTE.md

Fix release details for 2201.10.3

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.6/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add 2201.9.6 release details

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.6/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release 2201.9.6

---

components/community/contribute/Contribute.js

Reverts ballerina-platform/ballerina-dev-website#9642

Revert "Update Contribute.js"

---

pages/downloads/1.2.x-release-notes/[...slug].js
pages/downloads/swan-lake-release-notes/[...slug].js

Remove invalid template pages

---

swan-lake/development-tutorials/ballerina-central/configure-a-network-proxy.md

- Add environment variable details for proxy configuration
- https://github.com/wso2-enterprise/internal-support-ballerina/issues/813

Add environment variable details for proxy configuration

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

[2201.11.0]Add Http changes to U11 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

[2201.11.0] Incorporate review comments

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.8.9/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add 2201.8.9 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Add release note for u11 changes for data modules

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.56.md
utils/archived-lm.json
utils/rl.json

Create release note for 1.2.56 release

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Add release note for u11 for xml step extension

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Add runtime updates to the 2201.11.0 release note

---

.github/workflows/pre_release_homepage_sample_build.yml
downloads/installation-options/build-ballerina-from-source.md
downloads/installation-options/installation-options.md
swan-lake/development-tutorials/build-a-graalvm-executable/build-the-executable-locally.md
swan-lake/development-tutorials/run-in-the-cloud/azure-functions.md

Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9670

[release-2201.11.0] Add Java 21 changes

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Add LDAP SSL/TLS support in the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

> Update the release note by adding the following tools as newly introduced features.
- WSDL Tool
- XSD Tool

Add tool updates to the 2201.11.0 release note

---

components/learn/boxes/Boxes.js
next.config.js
swan-lake/integration-tools/wsdl-tool.md
swan-lake/integration-tools/xsd-tool.md
utils/learn-lm.json

> Following tools are listed under the integration tools section
- WSDL Tool
- XSD Tool

Add tools details to the integration tools section

---

swan-lake/integration-tools/wsdl-tool.md

Remove unnecessary annotation in CLI commands

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Add crypto new features to release note

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Add external contributors to the release note

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Update release note

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Improve grammar

---

downloads/swan-lake-release-notes/swan-lake-2201.10.4/RELEASE_NOTE.md

Release note 2201.10.4 branch

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Include more contributors

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

> Remove unwanted information for user

Remove unwanted information for user

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Address runtime related suggestions in release note

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Update data modules with samples in release note

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Remove invalid headings and fix syntax highlighting

---

downloads/swan-lake-release-notes/swan-lake-2201.11.0/RELEASE_NOTE.md

Update release note 2201.11.0

---

components/learn/boxes/Boxes.js
next.config.js
swan-lake/development-tutorials/build-and-run/cicd.md
utils/learn-lm.json

- Add page on CICD pipeline configuration
- Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9676

Add page on CICD pipeline configuration

---

components/learn/boxes/Boxes.js
swan-lake/development-tutorials/build-and-run/cicd.md
utils/learn-lm.json

- Make title sentence case in CICD guide

Make title sentence case in CICD guide

---

_data/university_sessions.json

> Add the upcoming session for UoM project groups

Add UoM session

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.57.md
utils/archived-lm.json
utils/rl.json

Add release note for 1.2.57 release

---

downloads/swan-lake-release-notes/swan-lake-2201.12.0/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add update 12 release note

---

downloads/swan-lake-release-notes/swan-lake-2201.12.0/RELEASE_NOTE.md

> Add consolidate-packages tool to U12 release note

Add consolidate-packages tool to U12 release note

---

swan-lake/integration-tools/wsdl-tool.md

Remove unnecessary `sh` tags from docs

---

components/learn/boxes/Boxes.js
swan-lake/integration-tools/consolidate-packages-tool.md

Add fixes related to consolidate tool docs

---

downloads/swan-lake-release-notes/swan-lake-2201.12.0/RELEASE_NOTE.md

Remove the section on scan tool rules from http release note

---

utils/archived-lm.json
utils/rl.json

Add rl and archived-lm entries required for Update 12

---

components/ai/code/ai-bbe/ballerina-ai-agent.md

Update variable name in ai agent code

---

components/ai/code/Code.js

Fix ' character escaping

---

downloads/swan-lake-release-notes/swan-lake-2201.12.0/RELEASE_NOTE.md

Fix release note title and remove empty bug fix milestones

---

components/learn/boxes/Boxes.js
next.config.js
swan-lake/development-tutorials/additional-tools/scan-tool.md
utils/learn-lm.json
utils/rearrangeFiles.sh

Learn landing page
Scan tool page

Include the scan tool learn page

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.12.1/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.12.2/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release notes for 2201.12.1 and 2201.12.2

---

components/learn/boxes/Boxes.js
swan-lake/development-tutorials/additional-tools/scan-tool.md

Fix capitalizations

---

components/home-page/bal-action/BalAction.js

Fix alignment in BIA images

---

downloads/swan-lake-release-notes/swan-lake-2201.12.1/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.12.2/RELEASE_NOTE.md

Update developer tooling release notes for 2201.12.1 and 2201.12.2

---

pages/downloads/index.js

Redirect release note to update 12

---

_data/events.json

Add events to the page

---

swan-lake/development-tutorials/build-and-run/cicd.md

Fix Github action name

---

_data/university_sessions.json

Add RGU university session

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.12.3/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Sync master for 2201.12.3 release

---

_data/events.json

Update event information

---

components/learn/boxes/Boxes.js
swan-lake/development-tutorials/deployment-guide/deployment-guidelines-overview.md
swan-lake/development-tutorials/deployment-guide/virtual-machine-deployment.md
utils/learn-lm.json

> $Subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9799

Add centralized deployment guide

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.10.5/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note for 2201.10.5

---

.github/workflows/pre_release_homepage_sample_build.yml
components/home-page/bal-action/BalAction.js
components/home-page/bal-action/action-bbe/working_with_llms.md

$title.
Addresses part of https://github.com/ballerina-platform/ballerina-library/issues/7869

Add the working with LLMs BIA sample

---

components/ai/code/Code.js
components/ai/code/ai-bbe/blog-analyzer-using-natural-programming.md

Update the AI use case page for natural expressions

---

components/learn/boxes/Boxes.js
next.config.js
swan-lake/resources/featured-scenarios/work-with-llms-using-natural-expressions.md
utils/learn-lm.json

Rename the guide

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.7/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note for release 2201.9.7

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.8.10/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release note for release 2201.8.10

---

components/home-page/bal-action/BalAction.js
components/home-page/bal-action/BalAction.module.css

Fix spacing in BIA tabs

---

_data/use-cases.json
components/integration/code/Code.js
pages/use-cases/ai/index.js

Fix AI page title

---

swan-lake/development-tutorials/additional-tools/consolidate-packages-tool.md

Add missing information about consolidation with local packages

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.12.5/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release notes for 2201.12.5

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.12.6/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release notes for 2201.12.6

---

spec/spec.md

Add websub/websubhub specs to the table

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.12.7/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release notes for 2201.12.7

---

components/learn/boxes/Boxes.js
next.config.js
swan-lake/resources/featured-scenarios/build-a-change-data-capture-service-in-ballerina.md
utils/learn-lm.json

Add cdc guide in featured scenario

---

_data/university_sessions.json

> Add missing view slides button

Add missing view slides button

---

_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.9.8/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

Add release notes for 2201.9.8

---

_data/university_sessions.json

Update IEEE hackathon 2025 entry

Update IEEE hackathon 2025 entry

---

swan-lake/development-tutorials/observability/overview-of-ballerina-observability.md
swan-lake/development-tutorials/observability/supported-observability-tools-and-platforms/datadog.md
utils/learn-lm.json

Fix Datadog naming

---

.github/scripts/bbe/convertMarkdown.js

> $subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9930

Add trailing slashes to urls

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.59.md
utils/archived-lm.json
utils/rl.json

Add release note for 1.2.59

---

components/home-page/bal-action/BalAction.js

Fix copying the natural expr BIA

---

swan-lake/development-tutorials/additional-tools/scan-tool.md
utils/highlighter.js

$ subject
> Fixes https://github.com/ballerina-platform/ballerina-dev-website/issues/9804
Waiting for https://github.com/ballerina-platform/sonar-ballerina/pull/13 to be merged for some changes.

Add sonarqube docs for `bal scan`

---

_data/university_sessions.json

> Add innovate with ballerina workshop 2

Add innovate with ballerina workshop 2

---

_data/swanlake-latest/metadata.json
_data/swanlake_release_notes_versions.json
downloads/swan-lake-release-notes/swan-lake-2201.12.9/RELEASE_NOTE.md
utils/archived-lm.json
utils/rl.json

> Add release notes for 2201.12.9´

Add release notes for 2201.12.9

---

downloads/swan-lake-release-notes/swan-lake-2201.12.8/RELEASE_NOTE.md
downloads/swan-lake-release-notes/swan-lake-2201.12.9/RELEASE_NOTE.md

Fix release numbers

---

swan-lake/development-tutorials/test-document-the-code/test-ballerina-code/code-coverage-and-reporting.md

> Include min-coverage information

Include min-coverage information

---

components/ai/code/ai-bbe/natural_programming_compile_time_code_generation.md

Fix formatting in natural programming documentation

---

_data/events.json

Rearrange event details for StaffPlus New York 2025

---

_data/release_notes_versions.json
downloads/1.2.x-release-notes/1.2.61.md
utils/archived-lm.json
utils/rl.json

Add release note for 1.2.61

---

swan-lake/development-tutorials/observability/supported-observability-tools-and-platforms/new-relic.md

Update New Relic user guide

---

components/hacktoberfest-2025/challenges/Challenges.module.css
components/hacktoberfest-2025/challenges/challenges.js
components/hacktoberfest-2025/rewards/Rewards.js

Add contribution message

---

downloads/swan-lake-release-notes/swan-lake-2201.12.10/RELEASE_NOTE.md

Added section for Developer tool updates and OpenAPI tool bug fixes.
> $Subject

Update release notes with OpenAPI tool updates

---

components/hacktoberfest-2025/challenges/challenges.js

Update Discord link to new channel URL
